<?php

/**
 * Implements hook_menu().
 */
function agrocalc_menu()
{
    $items['agro-calculator'] = array(
        'title' => t('Agro Calculator'),
        'description' => t('Agro Calculator'),
        'page callback' => 'drupal_get_form',
        'page arguments' => ['agrocalc_form'],
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_theme().
 */
function agrocalc_theme() {
    return array(
        'protection_program' => array(
            'variables' => array('program' => NULL),
            'template' => 'templates/protection-program',
        ),
    );
}

function agrocalc_form($from, &$form_state)
{
    $form = [
        '#prefix' => '<div id="agrocalc-form-wrapper">',
        '#suffix' => '</div>',
        '#attributes' => ['class' => ['agrocalc-form']],
        'field' => [
            '#type' => 'fieldset',
            '#title' => t('Culture') . '<i> ' . t('and field parameters') . '</i>' . '<img class="help1 hidden-xs" data-onscreen="true" data-animate="true" data-a-delay=".5s" data-a-effect="slide-down" src="/' . drupal_get_path('module', 'agrocalc') . '/images/help/1.png" alt="Помощь" />',
            '#prefix' => '<div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">',
        ],
        'problem' => [
            '#type' => 'fieldset',
            '#title' => t('Problems') . '<i>, ' . t('at field') . '</i>' . '<img class="help2 hidden-xs" data-onscreen="true" data-animate="true" data-a-delay=".5s" src="/' . drupal_get_path('module', 'agrocalc') . '/images/help/2.png"  alt="Помощь"/>'
        ],
        'addon' => ['#type' => 'fieldset', '#title' => t('Additional')],
        'actions' => [
            '#type' => 'container',
            '#attributes' => array('class' => array('form-actions')),
            'help' => [
                '#markup' => '<img class="help3 hidden-xs" data-onscreen="true" data-animate="true" data-a-delay=".5s" data-a-effect="slide-right" src="/' . drupal_get_path('module', 'agrocalc') . '/images/help/3.png" alt="Помощь"/>'
                ]
        ],
        '#attached' => [
            'js' => [
                drupal_get_path('module', 'agrocalc') . '/js/agrocalc.js',
                drupal_get_path('module', 'ext_product') . '/js/accounting.js'
            ],
        ]
    ];
    // ion range slider library
    if (module_exists('libraries') && libraries_detect('ionrange')) {
        $form['#attached']['libraries_load'][] = array('ionrange');
    }

    // onscreen slider library
    if (module_exists('libraries') && libraries_detect('onscreen')) {
        $form['#attached']['libraries_load'][] = array('onscreen');
    }

    // дефолтные переменные
    $culture_id = empty($form_state['input']['culture']) ? '' : $form_state['input']['culture'];
    $phase_id = empty($form_state['input']['phase']) ? '' : $form_state['input']['phase'];
    $area = empty($form_state['input']['area']) ? '' : $form_state['input']['area'];
    $seed = empty($form_state['input']['seed']) ? '' : $form_state['input']['seed'];
    if ($area && !$seed) {
        $seed = 100;
        $form_state['input']['seed'] = $seed;
        $form_state['values']['seed'] = $seed;
    }
    if (isset($form_state['triggering_element']) && $form_state['triggering_element']['#name'] == 'culture') {
        unset($form_state['input']['weeds']); unset($form_state['values']['weeds']);
        unset($form_state['input']['pests']); unset($form_state['values']['pests']);
        unset($form_state['input']['disease']); unset($form_state['values']['disease']);
    }
    $weed_ids = empty($form_state['values']['weeds']) ? '' : $form_state['values']['weeds'];
    $pest_ids = empty($form_state['values']['pests']) ? '' : $form_state['values']['pests'];
    $disease_ids = empty($form_state['values']['diseases']) ? '' : $form_state['values']['diseases'];
    $desic = empty($form_state['values']['desic']) ? '' : $form_state['values']['desic'];
    $fert = empty($form_state['values']['fert']) ? '' : $form_state['values']['fert'];


    // список Культур, для которых составлена ПЗ -----------------------------------------------------------------------
    $query = db_select('node', 'n');
    $query->condition('n.type', 'main_cultures');
    $query->condition('n.status', 1);
    $query->distinct();
    $query->innerJoin('field_data_field_pp_cultures', 'fc', 'fc.field_pp_cultures_target_id = n.nid');
    $query->condition('fc.bundle', 'protection_program');
    $query->fields('n', array('nid', 'title'));
    $query->orderby('n.title', 'ASC');

    $results = $query->execute()->fetchAllKeyed();

    $options = ['' => t('Choose option')] + $results;
    $form['field']['culture'] = array(
        '#type' => 'select',
        '#title' => t('Culture'),
        '#options' => $options,
        '#default_value' => $culture_id,
        '#ajax' => array(
            'callback' => 'agrocalc_form_refresh',
            'wrapper' => 'agrocalc-form-wrapper',
        ),
    );

    // список Фаз, для которых составлена ПЗ ---------------------------------------------------------------------------
    if ($culture_id) {
        $query = db_select('taxonomy_term_data', 't');
        $query->condition('t.vid', 20);
        $query->fields('t', array('tid', 'name'));
        $query->orderBy('t.weight', 'ASC');

        $culture_wr = entity_metadata_wrapper('node', $culture_id);
        if (isset($culture_wr->field_growth_stages_set) && $culture_wr->field_growth_stages_set->value()) {
            $set_tid = $culture_wr->field_growth_stages_set->tid->value();
            $query->innerJoin('field_data_field_mc_periods', 'fp', 'fp.field_mc_periods_tid = t.tid');
            $query->condition('fp.entity_id', $set_tid);
            $query->condition('fp.bundle', 'growth_stages_sets');
        }
        $results = $query->execute()->fetchAllKeyed();
    }
    $options = ['all' => t('All phases')] + $results;
    $form['field']['phase'] = array(
        '#type' => 'select',
        '#title' => t('Culture phase'),
        '#options' => $options,
        '#disabled' => $culture_id ? false : true,
        '#default_value' => $phase_id,
    );

    // Площадь посева --------------------------------------------------------------------------------------------------
    $form['field']['area'] = array(
        '#type' => 'textfield',
        '#title' => t('Area, ha'),
        '#disabled' => $culture_id ? false : true,
        '#default_value' => $area,
    );

    // Норма высева ----------------------------------------------------------------------------------------------------
    $form['field']['seed'] = array(
        '#type' => 'textfield',
        '#title' => t('Seeding rate, kg/ha'),
        '#disabled' => $culture_id ? false : true,
        '#default_value' => $seed,
    );

    // список всех Сорняков --------------------------------------------------------------------------------------------
    $query = db_select('node', 'n');
    $query->condition('n.type', 'weed');
    $query->condition('n.status', 1);
    $query->fields('n', array('nid', 'title'));
    $query->orderBy('n.title', 'ASC');
    $results = $query->execute()->fetchAllKeyed();

    $options = $results;
    $form['problem']['weeds'] = array(
        '#type' => 'select',
        '#title' => t('Weeds'),
        '#options' => $options,
        '#chosen' => true,
        '#multiple' => true,
        '#default_value' => $weed_ids,
        '#disabled' => $culture_id ? false : true,
    );

    // список Вредителей по Культуре -----------------------------------------------------------------------------------
    $query = db_select('node', 'n');
    $query->condition('n.status', 1);
    $query->distinct();
    $query->innerJoin('field_data_field_hobject_cultures', 'fc', 'fc.entity_id = n.nid');
    $query->condition('fc.bundle', 'pest');
    $query->condition('fc.field_hobject_cultures_target_id', $culture_id);
    $query->fields('n', array('nid', 'title'));
    $query->orderBy('n.title', 'ASC');
    $results = $query->execute()->fetchAllKeyed();

    $options = $results;
    $form['problem']['pests'] = array(
        '#type' => 'select',
        '#title' => t('Pests'),
        '#options' => $options,
        '#chosen' => true,
        '#multiple' => true,
        '#default_value' => $pest_ids,
        '#disabled' => $culture_id ? false : true,
    );

    // список Болезней по Культуре -------------------------------------------------------------------------------------
    $query = db_select('node', 'n');
    $query->condition('n.status', 1);
    $query->distinct();
    $query->innerJoin('field_data_field_hobject_cultures', 'fc', 'fc.entity_id = n.nid');
    $query->condition('fc.bundle', 'disease');
    $query->condition('fc.field_hobject_cultures_target_id', $culture_id);
    $query->fields('n', array('nid', 'title'));
    $query->orderBy('n.title', 'ASC');
    $results = $query->execute()->fetchAllKeyed();

    $options = $results;
    $form['problem']['diseases'] = array(
        '#type' => 'select',
        '#title' => t('Diseases'),
        '#options' => $options,
        '#chosen' => true,
        '#multiple' => true,
        '#default_value' => $disease_ids,
        '#disabled' => $culture_id ? false : true,
    );

    // Дополнительные опции --------------------------------------------------------------------------------------------
    $form['addon']['desic'] = array(
        '#type' => 'checkbox',
        '#title' => t('Add desiccants'),
        '#disabled' => $culture_id ? false : true,
        '#default_value' => $desic,
    );
    $form['addon']['fert'] = array(
        '#type' => 'checkbox',
        '#title' => t('Add fertilizers'),
        '#disabled' => $culture_id ? false : true,
        '#default_value' => $fert,
    );

    // Кнопка  ---------------------------------------------------------------------------------------------------------
    $form['actions']['calc'] = array(
        '#type' => 'button',
        '#value' => t('Calculate'),
        '#name' => 'calc',
        '#attributes' => [
            'class' => ['pull-right', 'btn-success', 'btn-wide', 'do-not-print'],
            'onclick' => ["yaCounter11541151.reachGoal('send_agrocalc'); return true;"],
        ],
        '#disabled' => $culture_id ? false : true,
        '#suffix' => '</div>',
        '#ajax' => array(
            'callback' => 'agrocalc_form_refresh',
            'wrapper' => 'agrocalc-form-wrapper',
        ),
    );

    /**
     * $parameters['culture_id'] - список культур из программы или явно заданная культура
     * $parameters['phase_id'] - фильтр по фазе культуры
     * $parameters['weeds_arr'], $parameters['pests_arr'], $parameters['diseases_arr'] - фильтр по вредным объектам
     * $parameters['desiccants'] - добавить десиканты
     * $parameters['fertilizers'] - добавить удобрения
     */
    if ($culture_id && (!isset($form_state['triggering_element']) || $form_state['triggering_element']['#name'] != 'culture')) {
        $program = _reglaments_get_protection_system2([
            'culture_id' => $culture_id,
            'phase_id' => $phase_id,
            'area' => $area,
            'seeding' => $seed,
            'weeds_arr' => $weed_ids,
            'pests_arr' => $pest_ids,
            'diseases_arr' => $disease_ids,
            'desiccants' => $desic,
            'fertilizers' => $fert,
        ]);

        if (!empty($form_state['values']['states'])) {
            $program = _set_program_states($program, $form_state['values']['states']);
        }
        $form_state['storage']['program'] = $program;

        $form['program']    = ['#markup' => theme('protection_program', ['program' => $program])];

        $form['request'] = [
            '#type' => 'fieldset',
            '#prefix' => '<div id="request" class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 do-not-print">',
        ];
        $form['request']['intro'] = [
            '#markup' => '<div class="col-sm-12"><h3>'. t('Get detailed calculation'). '</h3><p class="font-small">' . t('Choose your region, fill phone or E-Mail fields.<br />Our representative will make individual program for you and send it to E-Mail or contact you by phone.') . '</p></div>',
        ];

        $query = db_select('taxonomy_term_data', 't');
        $query->condition('t.vid', 29); // словарь 'regions'
        $query->innerJoin('taxonomy_term_hierarchy', 'h', 'h.tid = t.tid');
        $query->condition('h.parent', 0);
        $query->fields('t', array('tid', 'name'));
        $regions = $query->execute()->fetchAllKeyed();

        $form['request']['region'] = [
            '#type' => 'select',
            '#title' => t('Region') . '<img class="help8 hidden-xs" data-onscreen="true" data-animate="true" data-a-delay=".5s" src="/' . drupal_get_path('module', 'agrocalc') . '/images/help/8.png" alt="Помощь" />',
            '#options' => $regions,
        ];
        $form['request']['phone'] = [
            '#type' => 'textfield',
            '#title' => t('Phone'),
        ];
        $form['request']['name'] = [
            '#type' => 'textfield',
            '#title' => t('Name'),
        ];
        $form['request']['email'] = [
            '#type' => 'textfield',
            '#title' => t('E-Mail'),
        ];
        $form['actions1'] = [
            '#type' => 'container',
            '#attributes' => ['class' => ['form-actions']],
            '#suffix' => '</div>',
        ];
        $form['actions1']['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Get'),
            '#name' => 'send',
            '#attributes' => ['class' => ['btn-info', 'btn-wide']],
            '#prefix' => '<div class="form-submit-wrapper">',
            '#suffix' => '</div>',
        );
        $form['actions1']['fz152_agreement'] = [
            '#name' => 'fz152-agreement',
            '#type' => 'item',
            '#markup' => t('Pressing "Get" means you agreed with !url.', array('!url' => l(t('Terms of use'), 'info/privacy-policy'), ['attributes' => ['target' => '_blank', 'rel' =>'nofollow']])),
        ];
    }


    return $form;
}

function agrocalc_form_refresh($form, $form_state)
{
    return $form;
}

function agrocalc_form_validate($form, &$form_state)
{
    // сохранить состояние переключателей
    if (isset($form_state['input'])) {
        $states = [];
        foreach ($form_state['input'] as $key => $value) {
            if ($value && strpos($key, 'switch_') === 0 && $key != 'switch_all') {
                $keys = explode('_', $key);
                $states['categories'][$keys[1]]['stages'][$keys[2]][$keys[3]][$keys[4]]['state'] = $value;
                $states['categories'][$keys[1]]['cnt'] = (empty($states['categories'][$keys[1]]['cnt']) ? 0 : $states['categories'][$keys[1]]['cnt']) + 1;
            }
            if (strpos($key, 'range_') === 0) {
                $keys = explode('_', $key);
                $states['categories'][$keys[1]]['stages'][$keys[2]][$keys[3]][$keys[4]]['preparations']['items'][$keys[5]]['rate']['default'] = $value;
            }
        }
        if ($states) $form_state['values']['states'] = $states;
    }

    if ($form_state['triggering_element']['#name'] == 'calc' && !$form_state['values']['area']) {
        form_set_error('area', t('Set area of field'));
    }

    if ($form_state['submitted']) {
        if (empty($form_state['values']['region'])) {
            form_set_error('name', t('Set your region') );
        } else {
            $query = db_select('taxonomy_term_data', 't');
            $query->condition('t.tid', $form_state['values']['region']); // словарь 'regions'
            $query->fields('t', array('name'));
            if ($region = $query->execute()->fetchField()) $form_state['values']['region'] = $region;
        }
        if (!valid_email_address($form_state['values']['email']) && empty($form_state['values']['phone'])) form_set_error('email', t('Set one of fields: ') . t('E-Mail') . ' или ' . t('Phone') . '.' );
        if (empty($form_state['values']['name'])) form_set_error('name', t('Set your name') );
    }
}

function agrocalc_form_submit($form, &$form_state)
{
    $program = $form_state['storage']['program'];
    if (!empty($form_state['values']['states'])) {
        $program = _set_program_states($program, $form_state['values']['states']);
    }

    // отправка письма менеджеру и представителю
    $message = 'Добрый день!<br /><br />';
    $message .= 'На в разделе Калькулятор сайте kccc.ru была отправлена заявка на детальный расчёт.<br />';
    $message .= '<br />';
    $message .= '<b>Данные пользователя</b><br />';
    $message .= 'Регион: ' . $form_state['values']['region'] . '<br />';
    $message .= 'Имя: ' . $form_state['values']['name'] . '<br />';
    $message .= empty($form_state['values']['phone'])    ? '' : 'Телефон: ' . $form_state['values']['phone'] . '<br />';
    $message .= empty($form_state['values']['email'])    ? '' : 'E-Mail: ' . $form_state['values']['email'] . '<br />';
    $message .= '<br />';

    $message .= '<b>Поле</b><br />';
    $message .= 'Культура: ' . $program['header']['title'] . '<br />';
    $message .= 'Фаза: ' . (empty($program['phase'])  ? 'не указана' : $program['phase']) . '<br />';
    $message .= empty($program['area'])     ? '' : 'Площадь посева: ' . $program['area'] . ' га' . '<br />';
    $message .= empty($program['seed'])     ? '' : 'Норма высева: ' . $program['seed'] . ' кг/га' . '<br />';
    $message .= '<br />';

    $message .= '<b>Препараты</b><br />';

    $missed_hobjects = [];
    $total = 0;
    foreach ($program['categories'] as $key_cat => $cat) {
        if (isset($cat['cnt'])) $program['categories'][$key_cat]['cnt'] = $cat['cnt'];
        if (isset($cat['hobjects'])) $missed_hobjects = array_merge($missed_hobjects, explode(', ', $cat['hobjects']));
        foreach ($cat['stages'] as $key_stage => $stage) {
            foreach ($stage as $key_set => $set) {
                foreach ($set as $key_reg => $regl) {
                    if (isset($regl['state']) && $regl['state'] == 'on') {
                        $mix = count($regl['preparations']['items']) > 1;
                        if ($mix) $message .= '<i>Баковая смесь</i><br />';
                        foreach ($regl['preparations']['items'] as $pid => $item) {
                            $message .= $item['title'] . '<br />';
                            if (isset($item['rate']['default'])) {
                                $message .= '<span style="color: #999;">' . $item['rate']['default'] . ' ' . $item['units'] . ', ' . $item['rate']['default'] * $form_state['values']['area'] . ' ' . $item['unit'] . ' на сумму ' . number_format($item['rate']['default'] * $item['price'] * $form_state['values']['area'], 0, ',', ' ') . ' руб.</span><br />';
                                $total += $item['rate']['default'] * $item['price'];
                            }
                        }
                        if (!empty($regl['hobjects'])) $message .= '<span style="color: #999;">Вредные объекты: ' . $regl['hobjects'] . '</span><br />';
                        $message .= '<br />';
                    }
                }
            }
        }
    }
    $message .= '<br />';
    $message .= 'Итого: ' . number_format($total * $form_state['values']['area'], 0, ',', ' ') . ' руб.<br /><br />';

    if ($missed_hobjects) {
        $message .= 'Для следующих вредных объектов решения не подобраны:<br />';
        foreach($missed_hobjects as $hobjects) {
            $message .= '&nbsp;&nbsp;- ' . $hobjects . ';<br />';
        }
    }

//    $email = 'mega_comp@mail.ru' . (valid_email_address($form_state['values']['email']) ? ', ' . $form_state['values']['email'] : '');
    $email = 'support@kccc.ru' . (valid_email_address($program['email']) ? ', ' . $program['email'] : '');
    drupal_mail('system', 'mail', $email, language_default(), array(
        'context' => array(
            'subject' => 'Новая заявка на сайте в разделе Калькулятор',
            'message' => $message,
        ),
    ));

    drupal_set_message('Заявка на детальный расчёт отправлена. В ближайшее время представитель свяжется с Вами.');
    $form_state['rebuild'] = true;
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function agrocalc_preprocess_page(&$vars) {
    // установить для страницы параметры шапки
    if ($_GET['q'] == 'agro-calculator') {
        $image = '/' . drupal_get_path('module', 'agrocalc') . '/images/header_image.jpg';

        $vars['header'] = array(
            'image' => $image,
            'category_title' => '',
            'title' => t('Agro Calculator'),
            'subtitle' => t('Here we will help to make protection program for your main culture and calculate preliminary cost of necessary preparations. You need to enter the parameters of your field, then identify the problems that are present in the field and press the "Calculate" button. The proposed protection program you can also adjust by sliding switches.'),
            'print' => true,
        );
        $vars['wrapper_off'] = true;
    }
}
