<?php

/**
 * Implements hook_uninstall().
 */
function commerce_cart_form_checkout_pane_uninstall() {
  variable_del('commerce_cart_form_checkout_pane_view');
  variable_del('commerce_cart_form_checkout_pane_header');
  variable_del('commerce_cart_form_checkout_pane_footer');
}

/**
 * Implements hook_update_N().
 */
function commerce_cart_form_checkout_update_7101() {
  variable_set('commerce_cart_form_checkout_pane_view', variable_get('commerce_cart_form_contents_pane_view'));
  variable_del('commerce_cart_form_content_pane_view');
}

