<?

function webform_ex_form_alter(&$form, &$form_state, $form_id)
{
    if (strpos($form_id, 'webform_client_form_') === 0) {
        if (isset($form['actions']['next'])) $form['actions']['next']['#attributes']['class'][] = 'btn-primary';
        if (isset($form['actions']['next'])) $form['actions']['next']['#attributes']['class'][] = 'btn-wide';
    }
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function webform_ex_preprocess_page(&$vars)
{
    // todo сделать более точное определение того, что это страница завершения опроса
    if (arg(0) == 'node') {
        if ((isset($vars['node']) && $vars['node']->type == 'webform') || in_array(arg(2), ['done', 'submissions'])) {
            $hi_path = 'public://images/header_images/survey/header_image.jpg';
            $vars['header']['category_title'] = l(t('Surveys'), 'survey');
            $vars['header']['image'] = file_create_url($hi_path);
            $vars['header']['print'] = true;
        }
        if ((isset($vars['node']) && $vars['node']->type == 'webform')) {
            $vars['header']['subtitle'] = t('Survey');
        }
    }
}

/**
 * Pre-processes variables for the "node" theme hook.
 */
function webform_ex_preprocess_node(&$vars)
{
    if($vars['view_mode'] == 'teaser' && $vars['type'] == 'webform') {
        global $user;
        $vars['wf_passed_by_user'] = $user->uid && webform_get_submission_count($vars['node']->nid, $user->uid);

        if (!empty($vars['content']['field_textfield_1'])) $vars['time'] = $vars['content']['field_textfield_1'][0]['#markup'];
    }
}