<?php

define('CAT_HERB_TID',    1);
define('CAT_FUNG_TID',    2);
define('CAT_INSECT_TID',  3);
define('CAT_DESIC_TID',   5);
define('CAT_SEED_TID',    4);
define('CAT_FERT_TID',    6);

/**
 * Implements hook_menu().
 */
function sec_catalog_menu()
{
  $items['katalog'] = [
    'title' => 'Каталог',
    'page callback' => 'sec_catalog_page',
    'access arguments' => ['access content'],
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  ];

  return $items;
}

function sec_catalog_preprocess_page(&$vars)
{
  if (arg(0) == 'katalog') {
    // вывод Заголовка в виде баннера
    $vars['is_title_as_banner'] = true;
    $img_url = 'public://images/page-banners/katalog.jpg';
    $img_url = $vars['is_mobile'] ? image_style_url('banner_mobile', $img_url) : file_create_url($img_url);
    $vars['title_background'] = $img_url;

    // Заголовок
    $title = 'Каталог продукции';
    if (arg(1)) {
      if ($category_id = sec_catalog_get_category_id_by_name(arg(1))) {
        $category_wr = entity_metadata_wrapper('taxonomy_term', $category_id);
        $title = $category_wr->label();
        $icon_num = $category_wr->field_icon->value();
        $vars['title_prefix'] = [
          '#markup' => '<div class="page-title-logo"><i class="icon icon-' . $icon_num . '"></i></div>'
        ];
      }
    }
    $vars['title'] = $title;

    drupal_add_js(drupal_get_path('module', 'sec_catalog') . '/js/sec_catalog.js');
    drupal_add_css(drupal_get_path('module', 'sec_catalog') . '/css/sec_catalog.css');
  }
}

function sec_catalog_page()
{
  $content = '';

  // форма фильтров
  $form = drupal_get_form('sec_catalog_filters_form');

  // список Препаратов
  if ($catalog = sec_catalog_get_products_by_category()) {
    $content .= '<div class="row">';
    foreach ($catalog as $category) {
      // название категории
//      $content .= '<div class="col-xs-12"><div class="category">' . $category['label'] . '<div class="underline"></div></div></div>';
      foreach ($category['products'] as $product_info) {
        $content .= '<div class="col-xs-12 col-md-6">';
        $content .=   theme('card_product_h', $product_info);
        $content .= '</div>';
      }
    }
    $content .= '</div>';
  } else {
    $content .= 'Препаратов не найдено, попробуйте изменить фильтры.';
  }

  return  '<div id="catalog" class="catalog view">' .
            '<div class="catalog-filters">' .
              drupal_render($form) .
            '</div>' .
            '<div class="catalog-content">' .
              $content .
            '</div>' .
          '</div>';
}

function sec_catalog_filters_form($form, $form_state)
{
  $form['filters'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['row']],
  ];

  $filters_set = sec_catalog_get_filters_set();

  $cat_options = ['all' => 'Все'];
  foreach ($filters_set['categories']['options'] as $id => $label) {
    $cat_options[$id] = $label;
  }

  $form['filters']['category'] = [
    '#type' => 'select',
    '#title' => 'Категория',
    '#options' => $cat_options,
    '#default_value' => $filters_set['categories']['current_id'] ?? null,
    '#prefix' => '<div class="col-xs-12 col-md-6 col-lg-3">',
    '#suffix' => '</div>',
    '#ajax' => [
      'wrapper' => 'catalog',
      'callback' => 'sec_catalog_filters_form_ajax',
    ],
  ];

  $cmp_options = ['all' => 'Все'];
  foreach ($filters_set['components']['options'] as $id => $label) {
    $cmp_options[$id] = $label;
  }
  $form['filters']['component'] = [
    '#type' => 'select',
    '#title' => 'Действующее вещество',
    '#options' => $cmp_options,
    '#default_value' => $filters_set['components']['current_id'] ?? null,
    '#prefix' => '<div class="col-xs-12 col-md-6 col-lg-3">',
    '#suffix' => '</div>',
    '#ajax' => [
      'wrapper' => '',
      'callback' => 'sec_catalog_filters_form_ajax',
    ],
  ];

  return $form;
}

function sec_catalog_filters_form_ajax($form, $form_state)
{
  $title = 'Каталог препаратов';
  $title_logo = '';

  // отправить новое содержимое страницы
  $commands[] = ajax_command_replace('#catalog', sec_catalog_page());

  // определить новый URL, которому соответствует содержимое страницы
  // URL будет установлен в адресную строку браузера через history.pushState
  $url = '/katalog';
  $query = [];
  if (is_numeric($form_state['values']['category'])) {
    $category_wr = entity_metadata_wrapper('taxonomy_term', $form_state['values']['category']);
    $title = $category_wr->label();
    if ($icon_num = $category_wr->field_icon->value()) {
      $title_logo = '<div class="page-title-logo"><i class="icon icon-' . $icon_num . '"></i></div>';
    }
    $url .= '/' . strtolower(transliteration_get($title));
  }
  if (is_numeric($form_state['values']['component'])) {
    $query['component'] = $form_state['values']['component'];
  }
  if ($query) $url .= '?' . drupal_http_build_query($query);

  $setting['history']['url'] = $GLOBALS['base_url'] . $url;
  $commands[] = ajax_command_settings($setting);

  // изменить Заголовок страницы
  $commands[] = ajax_command_invoke('#page-title', 'html', [$title_logo . '<h1 class="title">' . $title . '</h1>']);

  return ['#type' => 'ajax', '#commands' => $commands];
}

/**
 * Вернуть массив возможных значений фильтров Каталога и выбранные значения
 *
 * @return array
 */
function sec_catalog_get_filters_set()
{
  $key = drupal_hash_base64($_GET['q']);
  $filters = &drupal_static(__FUNCTION__ . $key);
  if (!isset($filters)) {

    $filters = [
      'categories' => ['current_id' => NULL, 'options' => []],
      'components' => ['current_id' => NULL, 'options' => []],
    ];

    // Категории
    $categories = sec_catalog_get_categories();
    foreach ($categories as $cat) {
      $filters['categories']['options'][$cat['id']] = $cat['label'];
    }
    if ($_GET['q'] == 'system/ajax' && isset($_POST["category"]) && is_numeric($_POST["category"])) {
      $filters['categories']['current_id'] = $_POST["category"];
    }
    elseif (arg(0) == 'katalog' && arg(1)) {
      if ($curr_cat_id = sec_catalog_get_category_id_by_name(arg(1))) {
        $filters['categories']['current_id'] = $curr_cat_id;
      }
    }

    // Действующие вещества
    $components = sec_catalog_get_components('product');
    foreach ($components as $cmp) {
      $filters['components']['options'][$cmp['id']] = $cmp['label'];
    }
    if ($_GET['q'] == 'system/ajax' && isset($_POST["component"]) && is_numeric($_POST["component"])) {
      $filters['components']['current_id'] = $_POST["component"];
    }
    elseif (isset($_GET['component']) && is_numeric($_GET['component'])) {
      $filters['components']['current_id'] = $_GET['component'];
    }
  }

  return $filters;
}

function sec_catalog_get_products_by_category()
{
  $catalog = [];

  $filters_set = sec_catalog_get_filters_set();

  $dbr = db_select('node', 'n');
  $dbr->condition('n.type', 'preparation');
  if ($filters_set['categories']['current_id']) {
    $dbr->innerJoin('field_data_field_prep_category', 'fpc', 'fpc.entity_id = n.nid');
    $dbr->condition('fpc.field_prep_category_tid', $filters_set['categories']['current_id']);
  }
  if ($filters_set['components']['current_id']) {
    $dbr->innerJoin('field_data_field_prep_components', 'fpcoms', 'fpcoms.entity_id = n.nid');
    $dbr->innerJoin('field_data_field_component', 'fpcom', 'fpcom.entity_id = fpcoms.field_prep_components_value');
    $dbr->condition('fpcom.field_component_tid', $filters_set['components']['current_id']);
  }

  //  $dbr->condition('n.type', 'novelty'); // условие вывода в блок
  $dbr->addField('n', 'nid');
  if ($nodes = $dbr->execute()->fetchCol()) {

    foreach($nodes as $nid) {
      $product_info = sec_catalog_get_product_info($nid);
      if (empty($catalog[$product_info['category']['id']])) {
        $catalog[$product_info['category']['id']] = [
          'label' => $product_info['category']['label'],
          'products' => [],
        ];
      }
      $catalog[$product_info['category']['id']]['products'][] = $product_info;
    }
  }

  return $catalog;
}

/**
 * Вернуть массив препаратов с флагом Новинка
 */
function sec_catalog_get_new_products()
{
  $products = [];

  $dbr = db_select('node', 'n');
  $dbr->condition('n.type', 'preparation');
  $dbr->innerJoin('field_data_field_prep_novelty', 'fpn', 'fpn.entity_id = n.nid');
  $dbr->condition('fpn.field_prep_novelty_value', 1);
  $dbr->addField('n', 'nid');
  $dbr->orderRandom();
  if ($nodes = $dbr->execute()->fetchCol()) {

    foreach($nodes as $nid) {
      $products[] = sec_catalog_get_product_info($nid);
    }
  }

  return $products;
}

/**
 * Вернуть массив с рекомендуемыми препаратами
 * todo, пока выводит случайные 6
 */
function sec_catalog_get_recommended_products()
{
  $products = [];

  $dbr = db_select('node', 'n');
  $dbr->condition('n.type', 'preparation');
  $dbr->addField('n', 'nid');
  $dbr->range(0, 5);
  $dbr->orderRandom();
  if ($nodes = $dbr->execute()->fetchCol()) {

    foreach($nodes as $nid) {
      $products[] = sec_catalog_get_product_info($nid);
    }
  }

  return $products;
}

/**
 * Вернуть массив с информацией о препарате
 */
function sec_catalog_get_product_info($node)
{
  $key = $node->nid ?? $node;
  $product = &drupal_static(__FUNCTION__ . serialize($key));

  if (empty($product)) {
    $product = [];
    $node_wr = entity_metadata_wrapper('node', $node);
    if ($node_wr->value()) {
      $product['id'] = $node_wr->getIdentifier();
      $product['title'] = trim($node_wr->label());
      $product['novelty'] = $node_wr->field_prep_novelty->value();
      $trademark = $node_wr->field_prep_trademark->value() ? '<span class="tm">®</span>' : '';
      // наименование для вывода (с формуляцией, например)
      $product['label'] = preg_replace('/^(.*?)((?:\sПро)|(?:\sЭкстра)|(?:\sУльтра)|(?:\s22)|(?:\sФорте)|)$/', '$1' . $trademark . '$2', $product['title']);
      $image_uri = 'public://images/default/no_image.png';
      if ($node_wr->field_image->value()) {
        $image_uri = $node_wr->field_image->file->value()->uri;
      }
      $product['image'] = [
        'teaser' => image_style_url('card_product', $image_uri),
        'full' => file_create_url($image_uri),
      ];

      // категория
      $product['category'] = [
        'id' => $node_wr->field_prep_category->getIdentifier(),
        'label' => $node_wr->field_prep_category->label(),
        'icon_num' => $node_wr->field_prep_category->field_icon->value(),
      ];

      // единицы измерения
      $unit_short = '';
      if ($node_wr->field_prep_tare->value()) {
        $unit_short = $node_wr->field_prep_tare->field_measure_unit->value();
      }
      $unit_apply = $product['category'] == CAT_SEED_TID ? 'т' : 'га';
      $product['units'] = [
        'short' => $unit_short,
        'apply' => $unit_apply,
      ];

      $list = $list2 = [];
      foreach ($node_wr->field_prep_components->getIterator() as $component_wr) {
        $name = $component_wr->field_component->label();
        $conc = $component_wr->field_concentration->value();
        $list[] = [
          'label' => $name,
          'concentration' => $conc,
        ];
        $conc_formatted = str_replace(',00', '', number_format($conc, '2', ',', ''));
        $wrap = strlen($name) > 70;
        $list2[] = '<span class="' . ($wrap ? '' : 'nowrap') . '">' . $name . ',&nbsp;' . $conc_formatted . '&nbsp;г/' . $unit_short . '</span>';
      }
      $product['components'] = [
        'list' => $list,
        'formatted' => implode(' + ', $list2),
      ];

      $product['formulation'] = [
        'short' => $node_wr->field_prep_formulation->value() ? $node_wr->field_prep_formulation->field_acronym->value() : '',
        'full' => $node_wr->field_prep_formulation->label(),
      ];
      $product['path'] = drupal_get_path_alias('node/' . $node_wr->getIdentifier());

      $product['summary'] = $node_wr->field_prep_summary->value();

      $product['advantages'] = [];
      foreach ($node_wr->field_prep_advantages->getIterator() as $adv_wr) {
        $product['advantages'][] = [
          'icon_num' => $adv_wr->field_icon->value(),
          'text' => $adv_wr->field_text->value(),
        ];
      }

      $product['specs'] = [];
      $product['specs'][] = [
        'icon_num' => $node_wr->field_prep_category->field_icon->value(),
        'text' => $node_wr->field_prep_category->label(),
      ];
      $product['specs'][] = [
        'icon_num' => '058',
        'text' => $node_wr->field_prep_tare->label(),
      ];
      if ($product['components']['formatted']) {
        $product['specs'][] = [
          'icon_num' => '052',
          'text' => $product['components']['formatted'],
        ];
      }
      $product['specs'][] = [
        'icon_num' => '053',
        'text' => $node_wr->field_prep_formulation->label(),
      ];

      $product['how_it_works_banner'] = $node_wr->field_prep_how_it_works->value() ? $node_wr->field_prep_how_it_works_banner->file->url->value() : '';
      $product['how_it_works'] = [];
      foreach ($node_wr->field_prep_how_it_works->getIterator() as $how_wr) {
        $product['how_it_works'][] = [
          'icon_num' => $how_wr->field_icon->value(),
          'text' => $how_wr->field_textarea->value(),
        ];
      }

      $product['instructions'] = [];
      foreach ($node_wr->field_prep_instructions->getIterator() as $instr_wr) {
        $product['instructions'][] = [
          'title' => $instr_wr->field_prep_instruction_title->label(),
          'icon_num' => $instr_wr->field_prep_instruction_title->field_icon->value(),
          'text' => $instr_wr->field_textarea->value->value(),
        ];
      }

    }
  }

  return $product;
}

/**
 * Вернуть массив данных Регламентов препарата
 */
function sec_catalog_get_product_reglaments_info($product_id)
{
  $regs = [];

  $product_wr = entity_metadata_wrapper('node', $product_id);
  $product_info = sec_catalog_get_product_info($product_id);

  // данные
  foreach ($product_wr->field_prep_reglaments->getIterator() as $regl_wr) {
    $icon_num = '';
    $cultures = [];
    foreach ($regl_wr->field_cultures->getIterator() as $culture_wr) {
      $cultures[$culture_wr->getIdentifier()] = $culture_wr->label();
      // определить иконку регламента из класса культуры
      if (!$icon_num) $icon_num = sec_catalog_get_culture_class_icon($culture_wr->getIdentifier());
    }
    $cultures_note = $regl_wr->field_cultures_note->value();

    // иконка для "некультурных" регламентов
    if (!$icon_num) {
      $icon_num = $product_info['category']['icon_num'];
    }


    $weed_groups = [];
    foreach ($regl_wr->field_reg_weed_groups->getIterator() as $weed_group_wr) {
      $lifes = [];
      foreach ($weed_group_wr->field_reg_weed_lifes->getIterator() as $weed_life_wr) $lifes[$weed_life_wr->value()] = $weed_life_wr->label();
      $classes = [];
      foreach ($weed_group_wr->field_reg_weed_classes->getIterator() as $weed_class_wr) $classes[$weed_class_wr->getIdentifier()] = $weed_class_wr->label();

      $weed_groups[] = [
        'lifes' => $lifes,
        'classes' => $classes,
      ];
    }

    $pest_classes = [];
    foreach ($regl_wr->field_reg_pest_classes->getIterator() as $pest_class_wr) $pest_classes[$pest_class_wr->getIdentifier()] = $pest_class_wr->label();

    $hobjects = [];
    foreach ($regl_wr->field_hobjects->getIterator() as $hobject_wr) {
      $hobjects[$hobject_wr->getIdentifier()] = [
        'type' => $hobject_wr->type->value(),
        'name' => $hobject_wr->label(),
      ];
    }
    $hobjects_note = $regl_wr->field_hobjects_note->value();

    $prep_spends = [];
    foreach ($regl_wr->field_reg_prep_spends->getIterator() as $prep_spend_wr) {
      $prep_spends[] = $prep_spend_wr->value();
    }

    $mix_spend = $regl_wr->field_reg_mix_spend->value();
    $ratio = $regl_wr->field_reg_ratio->value();
    $wait = $regl_wr->field_reg_wait->value();


    // форматирование
    if ($cultures) {
      $cultures_f = implode(', ', array_values($cultures));
      if ($cultures_note) $cultures_f .= ' (' . $cultures_note . ')';
    } else {
      $cultures_f = $cultures_note;
    }
    $cultures_f = drupal_ucfirst(drupal_strtolower($cultures_f));

    $hobjects_arr = [];
    if ($weed_groups) {
      foreach ($weed_groups as $wg) {
        $hobjects_arr[] = ($wg['lifes'] ? implode(', ', $wg['lifes']) . ' ' : '') . implode(', ', $wg['classes']);
      }
    }
    if ($pest_classes) {
      $hobjects_arr[] = implode(', ', $pest_classes);
    }
    if ($hobjects) {
      foreach ($hobjects as $hi => $ho) {
        $hobjects_arr[] = l($ho['name'], drupal_get_path_alias('node/' . $hi));
      }
    }
    if ($hobjects_arr) {
      $hobjects_f = implode(', ', array_values($hobjects_arr));
      if ($hobjects_note) $hobjects_f .= ' (' . $hobjects_note . ')';
    } else {
      $hobjects_f = $hobjects_note;
    }
    $hobjects_f = drupal_ucfirst(drupal_strtolower($hobjects_f));

    $prep_spends_f = '';
    foreach ($prep_spends as $ps) {
      $ps['from'] = number_format($ps['from'], 2, ',', '');
      $ps['to']   = number_format($ps['to'], 2, ',', '');
      $ps['from'] = rtrim(str_replace(',00', '', $ps['from']), '0');
      $ps['to']   = rtrim(str_replace(',00', '', $ps['to']), '0');
      $psj = $ps['from'] == $ps['to'] ? $ps['to'] : $ps['from'] . '-' . $ps['to'];
      $prep_spends_f .= $prep_spends_f ? ' + ' . $psj : $psj;
    }
    $prep_spends_f .= ' ' . $product_info['units']['short'] . '/' . $product_info['units']['apply'];

    $mix_spend_f = $mix_spend['from'] == $mix_spend['to'] ? $mix_spend['to'] : ($mix_spend['from'] . '-' . $mix_spend['to']);

    $regs[$regl_wr->getIdentifier()] = [
      'icon_num' => $icon_num,
      'cultures' => [
        'list' => $cultures,
        'note' => $cultures_note,
        'formatted' => $cultures_f,
      ],
      'hobjects' => [
        'weed_groups' => $weed_groups,
        'pest_classes' => $pest_classes,
        'list' => $hobjects,
        'note' => $hobjects_note,
        'formatted' => $hobjects_f,
      ],
      'prep_spends' => [
        'list' => $prep_spends,
        'formatted' => $prep_spends_f,
      ],
      'mix_spend' => [
        'raw' => $mix_spend,
        'formatted' => $mix_spend_f . ' л/' . $product_info['units']['apply'],
      ],
      'wait' => [
        'raw' => $wait,
        'formatted' => is_numeric($wait) ? format_plural($wait, '@count day', '@count days') : $wait,
      ],
      'ratio' => [
        'raw' => $ratio,
        'formatted' => ($ratio['from'] == $ratio['to'] ? $ratio['to'] : $ratio['from'] . '-' . $ratio['to']),
      ],
      'description' => $regl_wr->field_reg_description->value(),
    ];
  }

  return $regs;
}

/**
 * Вернуть массив с Категориями
 */
function sec_catalog_get_categories()
{
  $categories = [];
  if ($terms = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('preparation_categories')->vid, 0, null, true)) {
    foreach($terms as $term) {
      $categories[$term->tid] = [
        'id' => $term->tid,
        'label' => $term->name,
        'icon_num' => $term->field_icon["und"][0]["value"],
        'path' => sec_catalog_taxonomy_term_uri($term)['path'],
      ];
    }
  }

  return $categories;
}

/**
 * Вернуть массив ДВ с учётом заданной фильтрации
 * @param $filter
 *  all - все из справочника
 *  product - из продукции
 *
 * @return array
 */
function sec_catalog_get_components($filter = 'all')
{
  $components = [];

  $dbr = db_select('taxonomy_term_data', 't');
  $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('preparation_components')->vid);
  if ($filter == 'product') {
    $dbr->innerJoin('field_data_field_component', 'fpcom', 'fpcom.field_component_tid = t.tid');
  }
  $dbr->orderBy('t.name');
  $dbr->addField('t', 'tid');
  if ($tids = $dbr->execute()->fetchCol()) {
    if ($terms = taxonomy_term_load_multiple($tids)) {
      foreach($terms as $term) {
        $components[$term->tid] = [
          'id' => $term->tid,
          'label' => $term->name,
          'path' => drupal_get_path_alias('taxonomy/term/' . $term->tid),
        ];
      }
    }
  }

  return $components;
}

/**
 * Вернуть id термина категории по имени
 * @param $name - оригинальный или translit
 *
 * @return $tid категории
 */
function sec_catalog_get_category_id_by_name($name)
{
  $vid = taxonomy_vocabulary_machine_name_load('preparation_categories')->vid;
  $terms = taxonomy_get_tree($vid);

  $name = strtolower($name);
  foreach ($terms as $term) {
    if ($name == strtolower($term->name) || $name == strtolower(transliteration_get($term->name))) return $term->tid;
  }

  return false;
}

function sec_catalog_entity_info_alter(&$entity_info)
{
  // изменить функцию формирования пути для Таксономии
  // чтобы ссылка вела не на стандартную страницу вывода терминов,
  // а на кастомную
  $entity_info['taxonomy_term']['uri callback'] = 'sec_catalog_taxonomy_term_uri';
}
function sec_catalog_taxonomy_term_uri($term)
{
  switch ($term->vocabulary_machine_name) {
    // для словаря Категорий изменить путь на свою страницу Каталога
    case 'preparation_categories':
      return array(
        'path' => 'katalog/' . strtolower(transliteration_get($term->name)),
      );
  }

  // default taxonomy term uri
  return taxonomy_term_uri($term);
}

/**
 * Вернуть иконку класса для заданной культуры.
 * Проверяет всю иерархию классов снизу вверх и возвращает первую
 */
function sec_catalog_get_culture_class_icon($culture_id)
{
  $icon_num = '';
  $culture_wr = entity_metadata_wrapper('node', $culture_id);
  if ($culture_wr->field_classificator_flora->value()) {
    if ($parents = taxonomy_get_parents_all($culture_wr->field_classificator_flora->getIdentifier())) {
      foreach ($parents as $parent) {
        if (!empty($parent->field_icon["und"][0]["value"])) {
          $icon_num = $parent->field_icon["und"][0]["value"];
          break;
        }
      }
    }
  }

  return $icon_num;
}

