<?php
function representatives_menu() {
    $items['info/representatives'] = array(
        'title' => 'Representatives',
        'description' => 'Company representatives',
        'page callback' => 'representatives_main_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['source/representatives'] = array(
        'page callback' => '_representatives_source',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}


function representatives_theme() {
    return array(
        'representatives_page' => array(
            'variables' => array('representatives' => NULL),
            'template' => 'templates/page',
        ),
    );
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function representatives_preprocess_page(&$vars) {
    // установить для страницы параметры шапки
    if ($_GET['q'] == 'info/representatives') {
        $image = url('/' . drupal_get_path('module', 'representatives') . '/images/header_image.jpg', array('absolute' => true));

        $vars['header'] = array(
            'image' => $image,
            'category_title' => '',
            'title' => t('Representatives'),
            'subtitle' => t('ООО Trade House "Kirovo-Chepetsk Chemical Company"'),
            'print' => true,
        );
    }
}

// главная страница
function representatives_main_page()
{
    $module_path = drupal_get_path('module', 'representatives');
    drupal_add_js($module_path . '/js/representatives.js');
    drupal_add_css($module_path . '/css/representatives.css');


    $html = 'Список пуст';

    if ($representatives = representatives_get_representatives_list()) {
        $html = theme('representatives_page', array('representatives' => $representatives));
    }

    return $html;
};

function representatives_get_representatives_list()
{
    $module_path = drupal_get_path('module', 'representatives');
    $no_photo = '/sites/default/files/default_images/no_photo.png';

    $representatives['head'][] = array(
        'icon_l_path' => $module_path . '/images/icons/light/',
        'icon_d_path' => $module_path . '/images/icons/dark/',
        'region_path' => $module_path. '/images/map/',
        'office' => 'Директор',
        'surname' => 'Потапов', 'name' => 'Денис', 'name2' => 'Викторович',
        'phones' => array(''),
        'emails' => array(''),
        'photo' => '/' . $module_path . '/images/photos/potapov.png',
    );
    $representatives['head2']['sales_head'] = array(
        'office' => 'Руководитель отдела продаж',
        'surname' => 'Рудяк', 'name' => 'Дмитрий', 'name2' => 'Вячеславович',
        'phones' => array('+7 (912) 726-36-23', '+7 (83361) 9-28-73'),
        'emails' => array('td.sale5@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/rudyak.png',
    );
    $representatives['head2'][] = array(
        'office' => 'Старший менеджер по региональному развитию',
        'surname' => 'Князев', 'name' => 'Алексей', 'name2' => 'Юрьевич',
        'phones' => array('+7 (83361) 9-28-70'),
        'emails' => array('td.sale2@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/knyazev.png',
        'regions' => array(
            71675 => "Архангельская область",
            71653 => "Кабардино-Балкарская Республика",
            71685 => "Калининградская область",
            71686 => "Калужская область",
            71655 => "Карачаево-Черкесская Республика",
            71669 => "Краснодарский край",
            71696 => "Москва и Московская область",
            71698 => "Нижегородская область",
            71699 => "Новгородская область",
            71704 => "Пензенская область",
            71706 => "Псковская область",
            71647 => "Республика Адыгея",
            71651 => "Республика Дагестан",
            71652 => "Республика Ингушетия",
            71654 => "Республика Калмыкия",
            71730 => "Республика Крым",
            71658 => "Республика Марий Эл",
            71661 => "Республика Северная Осетия - Алания",
            71707 => "Ростовская область",
            71708 => "Рязанская область",
            71693 => "Санкт-Петербург и область",
            71713 => "Смоленская область",
            71672 => "Ставропольский край",
            71715 => "Тверская область",
            71717 => "Тульская область",
            71666 => "Чеченская Республика",
            71667 => "Чувашская Республика",
        ),
    );
    $representatives['head2'][] = array(
        'office' => 'Старший менеджер по региональному развитию',
        'surname' => 'Устюжанин', 'name' => 'Данила', 'name2' => 'Игоревич',
        'phones' => array('+7 (83361) 5-40-60'),
        'emails' => array('td.sale1@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/ustyuzhanin.png',
        'regions' => array(
            71677 => "Белгородская область",
            71678 => "Брянская область",
            71682 => "Воронежская область",
            71692 => "Курская область",
            71694 => "Липецкая область",
            71703 => "Орловская область",
            71659 => "Республика Мордовия",
            71714 => "Тамбовская область",
        ),
    );
    $representatives['head2'][] = array(
        'office' => 'Старший менеджер по региональному развитию',
        'surname' => 'Казаков', 'name' => 'Артем', 'name2' => 'Сергеевич',
        'phones' => array('+7 (922) 927-99-33'),
        'emails' => array('td.sale7@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kazakov.png',
        'regions' => array(
            71691 => "Курганская область",
            71701 => "Омская область",
            71702 => "Оренбургская область",
            71648 => "Республика Башкортостан",
            71712 => "Свердловская область",
            71718 => "Тюменская область",
            71720 => "Челябинская область",
            71727 => "Ханты-Мансийский АО - Югра",
            71729 => "Ямало-Ненецкий АО",
        ),
    );
    $representatives['head2'][] = array(
        'office' => 'Старший менеджер по региональному развитию',
        'surname' => 'Якимов', 'name' => 'Евгений', 'name2' => 'Леонидович',
        'phones' => array('8 (83361) 9-28-70', '+7 922 925-88-84'),
        'emails' => array('td.sale11@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/yakimov.png',
        'regions' => array(
          71668 => "Алтайский край",
          71674 => "Амурская область",
          71725 => "Еврейская АО",
          71721 => "Забайкальский край",
          71684 => "Иркутская область",
          71687 => "Камчатский край",
          71688 => "Кемеровская область",
          71670 => "Красноярский край",
          71695 => "Магаданская область",
          71700 => "Новосибирская область",
          71671 => "Приморский край",
          71650 => "Республика Алтай",
          71649 => "Республика Бурятия",
          71663 => "Республика Тыва",
          71665 => "Республика Хакасия",
          71660 => "Республика Саха (Якутия)",
          71711 => "Сахалинская область",
          71716 => "Томская область",
          71673 => "Хабаровский край",
          71728 => "Чукотский АО",
        ),
    );

    $representatives['altai'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Маринина', 'name' => 'Лариса', 'name2' => 'Валентиновна',
        'phones' => array('+7 (922) 927-70-60'),
        'emails' => array('altai@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/altai.png',
        'regions' => array(
            71668 => "Алтайский край",
        ),
    );
    $representatives['altai'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Хаустов', 'name' => 'Сергей', 'name2' => 'Витальевич',
        'phones' => array('+7 (922) 927-68-80'),
        'emails' => array('sergey.haustov@kccc.ru'),
        'photo' => $no_photo,
        'regions' => array(
            71668 => "Алтайский край",
        ),
    );
    $representatives['amur'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Дорошенко', 'name' => 'Елена', 'name2' => 'Юрьевна',
        'phones' => array('+7 (922) 900-74-40'),
        'emails' => array('amur.region@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/amur.png',
        'regions' => array(
            71674 => "Амурская область",
        ),
    );
    $representatives['belgorod'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Левшин', 'name' => 'Петр', 'name2' => 'Иванович',
        'phones' => array('+7 (922) 927-80-90'),
        'emails' => array('belgorod@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/belgorod.png',
        'regions' => array(
            71677 => "Белгородская область",
        ),
    );
    $representatives['vladimir'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (83361) 2-23-49', '+7 (912) 825-47-45'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71679 => "Владимирская область",
        ),
    );
    $representatives['ivanovo'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (83361) 2-23-49', '+7 (912) 825-47-45'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71683 => "Ивановская область",
        ),
    );
    $representatives['kaliningrad'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Райнова', 'name' => 'Ирина', 'name2' => 'Васильевна',
        'phones' => array('+7 (922) 966-64-34'),
        'emails' => array('kaliningrad@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kaliningrad.png',
        'regions' => array(
            71685 => "Калининградская область",
        ),
    );
    $representatives['kirov'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (83361) 2-23-49', '+7 (912) 825-47-45'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71689 => "Кировская область",
        ),
    );
    $representatives['kostroma'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (83361) 2-23-49', '+7 (912) 825-47-45'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71690 => "Костромская область",
        ),
    );
    $representatives['krasnodar'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => '', 'name' => '', 'name2' => '',
        'phones' => array('+7 (922) 900-74-41'),
        'emails' => array('krasnodar@kccc.ru'),
        'photo' => '',
        'regions' => array(
            71669 => "Краснодарский край",
        ),
    );
//    $representatives['krasnodar'][] = array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => 'Мельников', 'name' => 'Сергей', 'name2' => 'Николаевич',
//        'phones' => array('+7 (922) 966 60 12'),
//        'emails' => array('krasnodar.reg@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/melnikov.png',
//        'regions' => array(
//            71669 => "Краснодарский край",
//        ),
//    );
    $representatives['kursk'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => '', 'name' => '', 'name2' => '',
        'phones' => array(''),
        'emails' => array('kursk@kccc.ru'),
        'photo' => '',
        'regions' => array(
            71692 => "Курская область",
      ),
    );
//    $representatives['lipetsk'][] = array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => 'Зеленский', 'name' => 'Денис', 'name2' => 'Александрович',
//        'phones' => array(''),
//        'emails' => array('lipetsk@kccc.ru'),
//        'photo' => '',
//        'regions' => array(
//            71694 => "Липецкая область",
//        )
//    );
    $representatives['lipetsk'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Плешков', 'name' => 'Владимир', 'name2' => 'Геннадьевич',
        'phones' => array('+7 (922) 908-41-44'),
        'emails' => array('lipetsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/pleshkov.png',
        'regions' => array(
            71694 => "Липецкая область",
        )
    );

//    $representatives['novosibirsk'][] =  array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => 'Точилкин', 'name' => 'Николай', 'name2' => 'Михайлович',
//        'phones' => array('+7 (922) 900-74-64'),
//        'emails' => array('novosibirsk@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/novosibirsk.png',
//        'regions' => array(
//    71700 => "Новосибирская область",
//),
//    );
//    $representatives['nnovgorod'][] =  array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => 'Рубизов', 'name' => 'Михаил', 'name2' => 'Александрович',
//        'phones' => array('+7 (922) 966-60-12'),
//        'emails' => array('n.novgorod@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/nnovgorod.png',
//        'regions' => array(
//            71698 => "Нижегородская область",
//        ),
//    );
    $representatives['omsk'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Усатов', 'name' => 'Валерий', 'name2' => 'Васильевич',
        'phones' => array('+7 (922) 900-74-73'),
        'emails' => array('omsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/omsk.png',
        'regions' => array(
            71701 => "Омская область",
        ),
    );
    $representatives['orenburg'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Попов', 'name' => 'Виктор', 'name2' => 'Михайлович',
        'phones' => array('+7 (922) 966-65-00'),
        'emails' => array('orenburg@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/orenburg.png',
        'regions' => array(
            71702 => "Оренбургская область",
        ),
    );
    $representatives['perm'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (83361) 2-23-49', '+7 (912) 825-47-45'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71705 => "Пермский край",
        ),
    );
    $representatives['bashkortostan'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Тураев', 'name' => 'Радик', 'name2' => 'Галиевич',
        'phones' => array('+7 (922) 900-74-77'),
        'emails' => array('bashkortostan@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/bashkortostan.png',
        'regions' => array(
            71648 => "Республика Башкортостан",
        ),
    );
    $representatives['mordoviya'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Агеев', 'name' => 'Сергей', 'name2' => 'Евгеньевич',
        'phones' => array('+7 (922) 900-75-85'),
        'emails' => array('mordoviya@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/mordoviya.png',
        'regions' => array(
            71659 => "Республика Мордовия",
        ),
    );
//    $representatives['tatarstan'][] = array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => '', 'name' => '', 'name2' => '',
//        'phones' => array(''),
//        'emails' => array('tatarstan@kccc.ru'),
//        'photo' => '',
//        'regions' => array(

//),
//    );
//    $representatives['chuvashiya'][] = array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => '', 'name' => '', 'name2' => '',
//        'phones' => array(''),
//        'emails' => array('chuvashiya@kccc.ru'),
//        'photo' => '',
//        'regions' => array(

//),
//    );
    $representatives['rostov'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => '', 'name' => '', 'name2' => '',
        'phones' => array('+7 (922) 966-59-77'),
        'emails' => array('rostov@kccc.ru'),
        'photo' => '',
        'regions' => array(
            71707 => "Ростовская область",
        ),
    );
    $representatives['stavropol'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => '', 'name' => '', 'name2' => '',
        'phones' => array('+7 (922) 966-60-16'),
        'emails' => array('stavropol@kccc.ru'),
        'photo' => '',
        'regions' => array(
            71672 => "Ставропольский край",
        ),
    );
    $representatives['tambov'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Сироткин', 'name' => 'Евгений', 'name2' => 'Николаевич',
        'phones' => array('+7 (922) 966-59-88'),
        'emails' => array('tambov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/tambov.png',
        'regions' => array(
            71714 => "Тамбовская область",
        ),
    );
    $representatives['tyumen'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Знаменщиков', 'name' => 'Василий', 'name2' => 'Александрович',
        'phones' => array('+7 (922) 966-60-04'),
        'emails' => array('tyumen@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/tyumen.png',
        'regions' => array(
            71718 => "Тюменская область",
        ),
    );
    $representatives['udmurtia'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Микряшов', 'name' => 'Владислав', 'name2' => 'Вячеславович',
        'phones' => array('+7 (912) 332-99-69'),
        'emails' => array('udmurtia@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/udmurtia.png',
        'regions' => array(
            71664 => "Удмуртская Республика",
        ),
    );
    $representatives['chelyabinsk'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Шалаев', 'name' => 'Андрей', 'name2' => 'Сергеевич',
        'phones' => array('+7 (902) 602-56-00'),
        'emails' => array('chelyabinsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/chelyabinsk.png',
        'regions' => array(
            71720 => "Челябинская область",
        ),
    );
//    $representatives['chelyabinsk'][] = array(
//        'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => 'Коновалов', 'name' => 'Вячеслав', 'name2' => 'Юрьевич',
//        'phones' => array('+7 (922) 966-65-00'),
//        'emails' => array('chelyabinsk@kccc.ru'),
//        'photo' => '',
//        'regions' => array(

//),
//    );
    $representatives['yaroslavl'][] = array(
        'role' =>  'rep',
        'office' => 'Представитель',
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (83361) 2-23-49', '+7 (912) 825-47-45'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71722 => "Ярославская область",
        ),
    );

    return $representatives;
}


/**
 * callback function
 * источник данных о представителях (исп. в приложении)
 */
function _representatives_source() {
    $results = representatives_get_representatives_list();
    drupal_json_output(['representatives' => $results]);
    drupal_exit();
}

function key_to_region ($key) {
    $region = array(
        'head' => 'ООО Торговый Дом "Кирово-Чепецкая Химическая Компания"',
        'altai' => 'Алтайский край',
        'amur' => 'Амурская область',
        'bashkortostan' => 'Республика Башкортостан',
        'belgorod' => 'Белгородская область',
        'vladimir' => 'Владимирская область',
        'voronezh' => 'Воронежская область',
        'volgograd' => 'Волгоградская область',
        'ivanovo' => 'Ивановская область',
        'kaliningrad' => 'Калининградская область',
        'kirov' => 'Кировская область',
        'kostroma' => 'Костромская область',
        'krasnodar' => 'Краснодарский край',
        'kursk' => 'Курская область',
        'lipetsk' => 'Липецкая область',
        'mordoviya' => 'Республика Мордовия',
        'novosibirsk' => 'Новосибирская область',
        'nnovgorod' => 'Нижегородская область',
        'omsk' => 'Омская область',
        'orenburg' => 'Оренбургская область',
        'orel' => 'Орловская область',
        'perm' => 'Пермский край',
        'rostov' => 'Ростовская область',
        'samara' => 'Самарская область',
        'saratov' => 'Саратовская область',
        'stavropol' => 'Ставропольский край',
        'tatarstan' => 'Республика Татарстан',
        'tambov' => 'Тамбовская область',
        'tyumen' => 'Тюменская область',
        'udmurtia' => 'Республика Удмуртия',
        'ulyanovsk' => 'Ульяновская область',
        'chelyabinsk' => 'Челябинская область',
        'chuvashiya' => 'Чувашская Республика',
        'yaroslavl' => 'Ярославская область',
    );

    return isset($region[$key]) ? $region[$key] : '';
}