<?php
function representatives_menu() {
    $items['info/representatives'] = array(
        'title' => 'Representatives',
        'description' => 'Company representatives',
        'page callback' => 'representatives_main_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['source/representatives'] = array(
        'page callback' => '_representatives_source',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    $items['source/experts'] = array(
        'page callback' => '_experts_source',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}


function representatives_theme() {
    return array(
        'representatives_page' => array(
            'variables' => array('representatives' => NULL),
            'template' => 'templates/page',
        ),
    );
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function representatives_preprocess_page(&$vars) {
    // установить для страницы параметры шапки
    if ($_GET['q'] == 'info/representatives') {
        $image_url = '/' . drupal_get_path('module', 'representatives') . '/images/header_image.jpg';

        $vars['header'] = array(
            'image' => $image_url,
            'category_title' => '',
            'title' => t('Representatives'),
            'subtitle' => t('Our representatives will help you to select and buy products of ООО Trade House "Kirovo-Chepetsk Chemical Company"'),
            'print' => true,
        );
    }
}

// главная страница
function representatives_main_page()
{
    $module_path = drupal_get_path('module', 'representatives');
    drupal_add_js($module_path . '/js/representatives.js');
    drupal_add_css($module_path . '/css/representatives.css');

    $html = '';

    $representatives_form = drupal_get_form('representatives_form');
    $html .= drupal_render($representatives_form);


    return $html;
};

function representatives_form($from, &$form_state)
{
    $form = [
        '#prefix' => '<div id="representatives-form-wrapper">',
        '#suffix' => '</div>',
        '#attributes' => ['class' => ['representatives-form']],
        'selector' => ['#type' => 'fieldset', '#title' => t('Search for area manager<i> by region</i>')],
        'list' => ['#type' => 'fieldset', '#title' => t('The list<i> of area managers</i>')],
    ];

    $query = db_select('taxonomy_term_data', 't');
    $query->condition('t.vid', 29); // словарь 'regions'
    $query->innerJoin('taxonomy_term_hierarchy', 'h', 'h.tid = t.tid');
    $query->condition('h.parent', 0);
    $query->fields('t', array('tid', 'name'));
    $regions = $query->execute()->fetchAllKeyed();

    $options = ['' => t('Choose option')] + $regions;
    $form['selector']['region'] = [
        '#type' => 'select',
        '#title' => t('Region'),
        '#options' => $options,
        '#wrapper_attributes' => ['class' => ['col-md-6']],
        '#prefix' => '<div class="row">',
        '#ajax' => array(
            'callback' => 'representatives_form_refresh',
            'wrapper' => 'representatives-form-wrapper',
        ),
    ];

    $contact = '';
    if (!empty($form_state['values']['region']) && $rep = _get_representative($form_state['values']['region'])) {
        $contact = theme('contact_card', ['contact' => array_shift($rep['region']), 'options' => ['class' => 'col-md-6']]);
    }
    $form['selector']['contact'] = [
        '#markup' => $contact,
        '#suffix' => '</div>',
    ];


    $form['list']['content'] = [
        '#markup' => theme('representatives_page', array('representatives' => representatives_get_representatives_list())),
    ];

    return $form;
}

function representatives_form_refresh($form, $form_state)
{
    return $form;
}


function representatives_get_representatives_list()
{
    $module_path = drupal_get_path('module', 'representatives');
    $no_photo = '/sites/default/files/default_images/no_photo.png';

    $representatives['head'][] = array(
        'icon_l_path' => $module_path . '/images/icons/light/',
        'icon_d_path' => $module_path . '/images/icons/dark/',
        'region_path' => $module_path. '/images/map/',
        'office' => t('Director'),
        'surname' => 'Потапов', 'name' => 'Денис', 'name2' => 'Викторович',
        'phones' => array(''),
        'emails' => array(''),
        'photo' => '/' . $module_path . '/images/photos/potapov.png',
    );
    $representatives['head2']['sales_head'] = array(
        'office' => t('Head of sales department'),
        'access' => true,
        'surname' => 'Рудяк', 'name' => 'Дмитрий', 'name2' => 'Вячеславович',
        'phones' => array('+7 (8332) 76-15-31, доб. 1187', '+7 (912) 726-36-23'),
        'emails' => array('td.sale5@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/rudyak.png',
    );
    $representatives['head2'][] = array(
        'office' => t('Regional development senior manager'),
        'access' => true,
        'surname' => 'Князев', 'name' => 'Алексей', 'name2' => 'Юрьевич',
        'phones' => array('+7 (8332) 76-15-31, доб. 1223', '+7 (922) 936-10-14'),
        'emails' => array('td.sale2@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/knyazev.png',
        'regions' => array(
            71676 => "Астраханская область",
            71680 => "Волгоградская область",
            71653 => "Кабардино-Балкарская Республика",
            71685 => "Калининградская область",
            71655 => "Карачаево-Черкесская Республика",
            71669 => "Краснодарский край",
            71647 => "Республика Адыгея",
            71651 => "Республика Дагестан",
            71652 => "Республика Ингушетия",
            71654 => "Республика Калмыкия",
            71730 => "Республика Крым",
            71661 => "Республика Северная Осетия - Алания",
            71707 => "Ростовская область",
            71672 => "Ставропольский край",
            71666 => "Чеченская Республика",
        ),
    );
//    $representatives['head2'][] = array(
//        'office' => t('Regional development senior manager'),
//        'access' => true,
//        'surname' => 'Устюжанин', 'name' => 'Данила', 'name2' => 'Игоревич',
//        'phones' => array('+7 (8332) 76-15-31, доб. 1154'),
//        'emails' => array('td.sale1@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/ustyuzhanin.png',
//        'regions' => array(
//            71677 => "Белгородская область",
//            71678 => "Брянская область",
//            71694 => "Липецкая область",
//            71703 => "Орловская область",
//            71659 => "Республика Мордовия",
//        ),
//    );
//    $representatives['head2'][] = array(
//        'office' => 'Старший менеджер по региональному развитию',
//        'access' => true,
//        'surname' => 'Казаков', 'name' => 'Артем', 'name2' => 'Сергеевич',
//        'phones' => array('+7 (8332) 76-15-31, доб. 1190', '+7 (922) 927-99-33'),
//        'emails' => array('td.sale7@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/kazakov.png',
//        'regions' => array(
//            71691 => "Курганская область",
//            71701 => "Омская область",
//            71702 => "Оренбургская область",
//            71648 => "Республика Башкортостан",
//            71712 => "Свердловская область",
//            71718 => "Тюменская область",
//            71727 => "Ханты-Мансийский АО - Югра",
//            71720 => "Челябинская область",
//            71728 => "Чукотский АО",
//            71729 => "Ямало-Ненецкий АО",
//        ),
//    );
    $representatives['head2'][] = array(
        'office' => t('Regional development senior manager'),
        'access' => true,
        'surname' => 'Якимов', 'name' => 'Евгений', 'name2' => 'Леонидович',
        'phones' => array('+7 (8332) 76-15-31, доб. 1189', '+7 922 925-88-84'),
        'emails' => array('td.sale11@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/yakimov.png',
        'regions' => array(
          71668 => "Алтайский край",
          71674 => "Амурская область",
          71725 => "Еврейская АО",
          71721 => "Забайкальский край",
          71684 => "Иркутская область",
          71687 => "Камчатский край",
          71670 => "Красноярский край",
          71695 => "Магаданская область",
          71697 => "Мурманская область",
          71700 => "Новосибирская область",
          71671 => "Приморский край",
          71650 => "Республика Алтай",
          71649 => "Республика Бурятия",
          71663 => "Республика Тыва",
          71665 => "Республика Хакасия",
          71660 => "Республика Саха (Якутия)",
          71711 => "Сахалинская область",
          71731 => "Севастополь",
          71673 => "Хабаровский край",
        ),
    );
//    $representatives['head2'][] = array(
//        'office' => 'Территориальный менеджер',
//        'access' => false,
//        'surname' => 'Соколов', 'name' => '', 'name2' => '',
//        'phones' => array('+7 (8332) 76-15-31, доб. ', '+7 922 '),
//        'emails' => array('td.sale@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/bobrov.png',
//        'regions' => array(
//            71675 => "Архангельская область",
//            71681 => "Вологодская область",
//            71693 => "Санкт-Петербург и область",
//            71696 => "Москва и Московская область",
//            71698 => "Нижегородская область",
//            71699 => "Новгородская область",
//            71706 => "Псковская область",
//            71658 => "Республика Марий Эл",
//            71715 => "Тверская область",
//            71717 => "Тульская область",
//            71667 => "Чувашская Республика",
//        ),
//    );
    $representatives['head2'][] = array(
        'office' => t('Area manager'),
        'access' => true,
        'surname' => 'Бобров', 'name' => 'Антон', 'name2' => 'Викторович',
        'phones' => array('+7 (8332) 76-15-32, доб. 1225', '+7 922 900-08-35'),
        'emails' => array('td.sale19@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/bobrov.png',
        'regions' => array(
            71682 => "Воронежская область",
            71692 => "Курская область",
        ),
    );
    $representatives['head2'][] = array(
        'office' => t('Area manager'),
        'access' => true,
        'surname' => 'Скодило', 'name' => 'Андрей', 'name2' => 'Алексеевич',
        'phones' => array('+7 (8332) 76-15-32, доб. 1215', '+7 922 938-65-50'),
        'emails' => array('td.sale21@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/skodilo.png',
        'regions' => array(
            71714 => "Тамбовская область",
            71704 => "Пензенская область",
        ),
    );
    $representatives['head2'][] = array(
        'office' => t('Area manager'),
        'access' => true,
        'surname' => 'Ухарский', 'name' => 'Евгений', 'name2' => 'Андреевич',
        'phones' => array('+7 (8332) 76-15-32, доб. 1219'),
        'emails' => array('td.sale12@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/uharskiy.png',
        'regions' => array(
            71688 => "Кемеровская область",
            71708 => "Рязанская область",
            71713 => "Смоленская область",
            71716 => "Томская область",
            71686 => "Калужская область",
        ),
    );

    $representatives['altai'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Маринина', 'name' => 'Лариса', 'name2' => 'Валентиновна',
        'phones' => array('+7 (922) 927-70-60'),
        'emails' => array('altai@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/altai.png',
        'regions' => array(
            71668 => "Алтайский край",
        ),
    );
    $representatives['altai'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Хаустов', 'name' => 'Сергей', 'name2' => 'Витальевич',
        'phones' => array('+7 (922) 927-68-80'),
        'emails' => array('sergey.haustov@kccc.ru'),
        'photo' => $no_photo,
        'regions' => array(
            71668 => "Алтайский край",
        ),
    );
//    $representatives['amur'][] = array(
//        // 'role' =>  'rep',
//        'office' => 'Представитель',
//        'access' => false,
//        'surname' => 'Дорошенко', 'name' => 'Елена', 'name2' => 'Юрьевна',
//        'phones' => array('+7 (922) 900-74-40'),
//        'emails' => array('amur.region@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/amur.png',
//        'regions' => array(
//            71674 => "Амурская область",
//        ),
//    );
    $representatives['belgorod'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Левшин', 'name' => 'Петр', 'name2' => 'Иванович',
        'phones' => array('+7 (922) 927-80-90'),
        'emails' => array('belgorod@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/belgorod.png',
        'regions' => array(
            71677 => "Белгородская область",
        ),
    );
    $representatives['vladimir'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (912) 825-47-45', '8 (83361) 2-23-49'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71679 => "Владимирская область",
        ),
    );
//    $representatives['voronezh'][] = array(
//        // 'role' =>  'rep',
//        'office' => 'Представитель',
//        'access' => false,
//        'surname' => 'Копейкин', 'name' => 'Роман', 'name2' => 'Александрович',
//        'phones' => array('+7 (922) 900-02-01'),
//        'emails' => array('voronezh1@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/kopeykin.png',
//        'regions' => array(
//            71682 => "Воронежская область",
//        ),
//    );
    $representatives['ivanovo'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (912) 825-47-45', '8 (83361) 2-23-49'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71683 => "Ивановская область",
        ),
    );
    $representatives['kaliningrad'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => '', 'name' => '', 'name2' => '',
        'phones' => array('+7 (922) 936-10-14'),
        'emails' => array('kaliningrad@kccc.ru'),
        'photo' => $no_photo,
        'regions' => array(
            71685 => "Калининградская область",
        ),
    );
    $representatives['kirov'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => true,
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (912) 825-47-45', '8 (83361) 2-23-49'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71689 => "Кировская область",
            71722 => "Ярославская область",
            71683 => "Ивановская область",
            71679 => "Владимирская область",
            71690 => "Костромская область",
            71705 => "Пермский край",
        ),
    );
    $representatives['kostroma'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (912) 825-47-45', '8 (83361) 2-23-49'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71690 => "Костромская область",
        ),
    );
    $representatives['krasnoyarsk'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Савенко', 'name' => 'Алексей', 'name2' => 'Михайлович',
        'phones' => array('+7 (922) 969-47-05'),
        'emails' => array('krasnoyarsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/savenko.png',
        'regions' => array(
            71670 => "Красноярский край",
        ),
    );
    $representatives['krasnodar'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Домницкая', 'name' => 'Виктория', 'name2' => 'Николаевна',
        'phones' => array('+7 (922) 900-05-73'),
        'emails' => array(),
        'photo' => '/' . $module_path . '/images/photos/domnitskaya.png',
        'regions' => array(
            71669 => "Краснодарский край",
        ),
    );
//    $representatives['kursk'][] = array(
//        // 'role' =>  'rep',
//        'office' => 'Представитель',
//        'access' => false,
//        'surname' => 'Журавлев', 'name' => 'Дмитрий', 'name2' => 'Валерьевич',
//        'phones' => array('+7 (922) 900-74-64'),
//        'emails' => array('kursk@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/zhuravlev.png',
//        'regions' => array(
//            71692 => "Курская область",
//      ),
//    );
    $representatives['lipetsk'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Плешков', 'name' => 'Владимир', 'name2' => 'Геннадьевич',
        'phones' => array('+7 (922) 908-41-44'),
        'emails' => array('lipetsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/pleshkov.png',
        'regions' => array(
            71694 => "Липецкая область",
        )
    );
    $representatives['novosibirsk'][] =  array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'surname' => '', 'name' => '', 'name2' => '',
        'phones' => array('+7 (922) 900-74-64'),
        'emails' => array('novosibirsk@kccc.ru'),
        'photo' => $no_photo,
        'regions' => array(
            71700 => "Новосибирская область",
        ),
    );
//    $representatives['nnovgorod'][] =  array(
//        // 'role' =>  'rep',
//        'office' => 'Представитель',
//        'surname' => '', 'name' => '', 'name2' => '',
//        'phones' => array('+7 (922) 966-60-12'),
//        'emails' => array('n.novgorod@kccc.ru'),
//        'photo' => $no_photo,
//        'regions' => array(
//            71698 => "Нижегородская область",
//        ),
//    );
    $representatives['omsk'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Усатов', 'name' => 'Валерий', 'name2' => 'Васильевич',
        'phones' => array('+7 (922) 900-74-73'),
        'emails' => array('omsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/omsk.png',
        'regions' => array(
            71701 => "Омская область",
        ),
    );
    $representatives['orenburg'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Попов', 'name' => 'Виктор', 'name2' => 'Михайлович',
        'phones' => array('+7 (922) 966-65-00'),
        'emails' => array('orenburg@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/orenburg.png',
        'regions' => array(
            71702 => "Оренбургская область",
        ),
    );
    $representatives['orenburg'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Неверов', 'name' => 'Владимир', 'name2' => 'Николаевич',
        'phones' => array('+7 (922) 909-20-33'),
        'emails' => array('orenburg2@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/neverov.png',
        'regions' => array(
            71702 => "Оренбургская область",
        ),
    );
    $representatives['orenburg'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Токарев', 'name' => 'Виктор', 'name2' => 'Анатольевич',
        'expert' => '+7 (922) 555-08-96',
        'phones' => array('+7 (922) 966-05-52'),
        'emails' => array('orenburg3@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/tokarev.png',
        'regions' => array(
            71702 => "Оренбургская область",
        ),
    );
    $representatives['penza'][] = array(
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Юдин', 'name' => 'Сергей', 'name2' => 'Васильевич',
        'phones' => array('+7 (922) 900-01-22'),
        'emails' => array('penza1@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/yudin.png',
        'regions' => array(
            71704 => "Пензенская область",
        ),
    );
    $representatives['penza'][] = array(
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Кобозев', 'name' => 'Сергей', 'name2' => 'Валерьевич',
        'phones' => array('+7 (922) 900-07-73'),
        'emails' => array('penza2@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kobozev.png',
        'regions' => array(
            71704 => "Пензенская область",
        ),
    );
    $representatives['perm'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (912) 825-47-45', '8 (83361) 2-23-49'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71705 => "Пермский край",
        ),
    );
    $representatives['bashkortostan'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Тураев', 'name' => 'Радик', 'name2' => 'Галиевич',
        'phones' => array('+7 (922) 900-74-77'),
        'emails' => array('bashkortostan@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/bashkortostan.png',
        'regions' => array(
            71648 => "Республика Башкортостан",
        ),
    );
    $representatives['mordoviya'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Агеев', 'name' => 'Сергей', 'name2' => 'Евгеньевич',
        'phones' => array('+7 (922) 900-75-85'),
        'emails' => array('mordoviya@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/mordoviya.png',
        'regions' => array(
            71659 => "Республика Мордовия",
        ),
    );

    $representatives['rostov'][] = array(
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Швец', 'name' => 'Олег', 'name2' => 'Викторович',
        'phones' => array('+7 (922) 900-14-43', '+7 (909) 435-82-89'),
        'emails' => array('rostov2@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/shvets.png',
        'regions' => array(
            71707 => "Ростовская область",
        ),
    );
    $representatives['stavropol'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Русанов', 'name' => 'Алексей', 'name2' => 'Владимирович',
        'phones' => array('+7 (918) 742-67-28', '+7 (922) 966-59-77'),
        'emails' => array('stavropol@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/rusanov.png',
        'regions' => array(
            71672 => "Ставропольский край",
        ),
    );
    $representatives['tambov'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'expert' => '+7 (902) 730-80-22',
        'surname' => 'Сироткин', 'name' => 'Евгений', 'name2' => 'Николаевич',
        'phones' => array('+7 (922) 966-59-88'),
        'emails' => array('tambov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/sirotkin.png',
        'regions' => array(
            71714 => "Тамбовская область",
        ),
    );
    $representatives['tyumen'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Знаменщиков', 'name' => 'Василий', 'name2' => 'Александрович',
        'phones' => array('+7 (922) 966-60-04'),
        'emails' => array('tyumen@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/tyumen.png',
        'regions' => array(
            71718 => "Тюменская область",
        ),
    );
    $representatives['tyumen'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Пиленков', 'name' => 'Михаил', 'name2' => 'Владимирович',
        'phones' => array(),
        'emails' => array('tyumen1@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/pilenkov.png',
        'regions' => array(
            71718 => "Тюменская область",
        ),
    );
    $representatives['tyumen'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Основин', 'name' => 'Александр', 'name2' => 'Анатольевич',
        'phones' => array(),
        'emails' => array('tyumen2@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/osnovin.png',
        'regions' => array(
            71718 => "Тюменская область",
        ),
    );
    $representatives['udmurtia'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => true,
        'surname' => 'Микряшов', 'name' => 'Владислав', 'name2' => 'Вячеславович',
        'phones' => array('+7 (912) 332-99-69'),
        'emails' => array('udmurtia@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/udmurtia.png',
        'regions' => array(
            71664 => "Удмуртская Республика",
        ),
    );
    $representatives['chelyabinsk'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Коновалов', 'name' => 'Вячеслав', 'name2' => 'Юрьевич',
        'phones' => array('+7 (922) 747-26-41'),
        'emails' => array('chelyabinsk@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/konovalov.png',
        'regions' => array(
            71720 => "Челябинская область",
        ),
    );
    $representatives['chelyabinsk'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Антонов', 'name' => 'Александр', 'name2' => 'Викторович',
        'phones' => array('+7 (922) 747-26-40'),
        'emails' => array('chelyabinsk1@kccc.ru'),
        'photo' => $no_photo,
        'regions' => array(
            71720 => "Челябинская область",
        ),
    );
    $representatives['yaroslavl'][] = array(
        // 'role' =>  'rep',
        'office' => t('Representative'),
        'access' => false,
        'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
        'phones' => array('+7 (912) 825-47-45', '8 (83361) 2-23-49'),
        'emails' => array('kirov@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/kirov.png',
        'regions' => array(
            71722 => "Ярославская область",
        ),
    );

    if ($GLOBALS['language']->language != 'ru') {
        foreach ($representatives as $key_r => $region) {
            foreach ($region as $key_rp => $rep) {
                if (isset($rep['surname'])) $representatives[$key_r][$key_rp]['surname'] = translit($rep['surname']);
                if (isset($rep['name'])) $representatives[$key_r][$key_rp]['name'] = translit($rep['name']);
                if (isset($rep['name2'])) $representatives[$key_r][$key_rp]['name2'] = translit($rep['name2']);
                if (isset($rep['name2'])) $representatives[$key_r][$key_rp]['name2'] = translit($rep['name2']);
                if (isset($rep['phones'])) {
                    foreach($rep['phones'] as $key => $phone) {
                        $representatives[$key_r][$key_rp]['phones'][$key] = str_replace('доб.', 'add', $phone);
                    }
                }
            }
        }
    }

    return $representatives;
}


/**
 * callback function
 * источник данных о представителях (исп. в приложении)
 */
function _representatives_source($region_id = null)
{
    drupal_json_output(['representatives' => _get_representative($region_id)]);
    drupal_exit();
}

/**
 * используется в корзине
 * @return array|mixed
 */
function _get_representative($tid)
{
    $reps = representatives_get_representatives_list();
    if ($tid) {
        $representatives = [];
        foreach ($reps as $region => $reg) {
            foreach ($reg as $rep) {
                if (isset($rep['regions'][$tid]) && !empty($rep['access'])) {
                    $representatives['region'][] = $rep;
                }
            }
        }
        if (empty($representatives)) {
            $representatives['region'][] = $reps['head2']['sales_head'];
        }
        return $representatives;
    }
    return $reps;
}

/**
 * callback function
 * источник данных об экспертах (исп. в приложении)
 */
function _experts_source($region_id = null)
{
    drupal_json_output(['representatives' => _get_experts($region_id)]);
    drupal_exit();
}

function _get_experts($tid)
{
    $reps = representatives_get_representatives_list();

    $representatives = [];
    foreach ($reps as $region => $reg) {
        foreach ($reg as $rep) {
            if (!empty($rep['expert'])) {
                if (empty($tid) || isset($rep['regions'][$tid])) {
                    unset($rep['regions']);
                    $rep['office'] = 'Научный консультант';
                    $representatives['expert'][] = $rep;
                }
            }
        }
    }
    if (empty($representatives)) {
        $representatives['expert'][] = $reps['tambov'][0];
    }
    return $representatives;

}

//function key_to_region ($key) {
//    $region = array(
//        'head' => 'ООО Торговый Дом "Кирово-Чепецкая Химическая Компания"',
//        'altai' => 'Алтайский край',
//        'amur' => 'Амурская область',
//        'bashkortostan' => 'Республика Башкортостан',
//        'belgorod' => 'Белгородская область',
//        'vladimir' => 'Владимирская область',
//        'voronezh' => 'Воронежская область',
//        'volgograd' => 'Волгоградская область',
//        'ivanovo' => 'Ивановская область',
//        'kaliningrad' => 'Калининградская область',
//        'kirov' => 'Кировская область',
//        'kostroma' => 'Костромская область',
//        'krasnodar' => 'Краснодарский край',
//        'kursk' => 'Курская область',
//        'lipetsk' => 'Липецкая область',
//        'mordoviya' => 'Республика Мордовия',
//        'novosibirsk' => 'Новосибирская область',
//        'nnovgorod' => 'Нижегородская область',
//        'omsk' => 'Омская область',
//        'orenburg' => 'Оренбургская область',
//        'orel' => 'Орловская область',
//        'perm' => 'Пермский край',
//        'rostov' => 'Ростовская область',
//        'samara' => 'Самарская область',
//        'saratov' => 'Саратовская область',
//        'stavropol' => 'Ставропольский край',
//        'tatarstan' => 'Республика Татарстан',
//        'tambov' => 'Тамбовская область',
//        'tyumen' => 'Тюменская область',
//        'udmurtia' => 'Республика Удмуртия',
//        'ulyanovsk' => 'Ульяновская область',
//        'chelyabinsk' => 'Челябинская область',
//        'chuvashiya' => 'Чувашская Республика',
//        'yaroslavl' => 'Ярославская область',
//    );
//
//    return isset($region[$key]) ? $region[$key] : '';
//}