<?php

/* hooks ------------------------------------------------------------------------------------------------ */
function juice_menu()
{
    // // страница настроек блока в админке
    // $items['admin/config/juice'] = array(
    // 'title' => 'Weather block',
    // 'description' => 'Настройки блока погоды',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('juice_settings_form'),
    // 'access arguments' => array('access administration pages'),
    // );

    // подробный прогноз погоды на сайте
    $items['info/agrocast'] = array(
        'title' => t('Agricultural weather forecast'),
        'description' => t('Detailed weather forecast for agrobusiness'),
        'page callback' => 'juice_page_weather',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function juice_preprocess_html(&$vars)
{
    //drupal_add_js(drupal_get_path('module', 'juice') . '/js/juice.js');
}

function juice_page_weather()
{
    drupal_add_js(drupal_get_path('module', 'juice') . '/js/juice.js');
    drupal_add_css(drupal_get_path('module', 'juice') . '/css/juice.css');

    $forecast = juice_get_weather();
    $output = theme('juice_page_weather', array('forecast' => $forecast));

    return $output;
}

function juice_theme()
{
    return array(
        'juice_block_stuff' => array(
            'variables' => array('forecast' => NULL),
            'template' => 'templates/block-weather-stuff',
        ),
        'juice_block_front' => array(
            'variables' => array('forecast' => NULL),
            'template' => 'templates/block-weather-front',
        ),
        'juice_block_front_mini' => array(
            'variables' => array('forecast' => NULL),
            'template' => 'templates/block-weather-front-mini',
        ),
        'juice_block_front_mini2' => array(
            'variables' => array('forecast' => NULL),
            'template' => 'templates/block-weather-front-mini2',
        ),
        'juice_page_weather' => array(
            'variables' => array('forecast' => NULL),
            'template' => 'templates/page-weather',
        ),
    );
}

function juice_block_info()
{
    return array(
        'weather_front' => array(
            'info' => 'Главная | Блок погоды 3х1',
            'cache' => DRUPAL_NO_CACHE,
        ),
        'weather_front_mini' => array(
            'info' => 'Главная | Блок погоды 1х1',
            'cache' => DRUPAL_NO_CACHE,
        ),
        'weather_front_mini2' => array(
            'info' => 'Главная | Блок погоды 1х1 (2)',
            'cache' => DRUPAL_NO_CACHE,
        ),
        'weather_stuff' => array(
            'info' => 'Персонал | Блок погоды для сотрудников',
            'cache' => DRUPAL_NO_CACHE,
        ),
    );
}

function juice_block_view($delta = '')
{
    $block['content'] = array(
        '#forecast' => juice_get_weather(),
        '#attached' => array(
            'js' => array(drupal_get_path('module', 'juice') . '/js/juice.js'),       // подключаем js для блока
            'css' => array(drupal_get_path('module', 'juice') . '/css/juice.css'),       // подключаем css для блока
        ),
    );
    switch ($delta) {
        case 'weather_stuff':
            $block['content']['#theme'] = 'juice_block_stuff';
            break;
        case 'weather_front':
            $block['content']['#theme'] = 'juice_block_front';
            break;
        case 'weather_front_mini':
            $block['content']['#theme'] = 'juice_block_front_mini';
            break;
        case 'weather_front_mini2':
            $block['content']['#theme'] = 'juice_block_front_mini2';
            break;
    }
    return $block;
}

/* functions ------------------------------------------------------------------------------------------------ */

/* форма настроек в админке */
function juice_settings_form($form, $form_state)
{
    $form['juice_city_index'] = array(
        '#type' => 'textfield',
        '#title' => t('City index'),
        '#default_value' => variable_get('juice_city_index', 27198),
        '#maxlength' => 255,
    );
    $form['juice_xml_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Xml file URL'),
        '#default_value' => variable_get('juice_xml_url', "http://export.yandex.ru/weather-ng/forecasts/"),
        '#maxlength' => 255,
        '#description' => t('The XML-file address.'),
    );

    return system_settings_form($form);
}

/* возвращает массив с информацией о погоде из источника xml */
function juice_get_weather() {
    //$cityname = _juice_get_city($_SERVER['REMOTE_ADDR']);
    $cityname = _juice_get_city('94.241.199.191');

    $cities = json_decode(file_get_contents(drupal_get_path('module', 'juice') . '/cities.txt'));
    $weather = array();

    if (isset($cities->$cityname)) {
        $city_id = $cities->$cityname;
    } else {
        $city_id = $cities->{'Москва'};
    }

    // патч для кирова - заменить калужский на кировский
    if ($city_id == 26796) $city_id = 27199;

    $url = variable_get('juice_xml_url', "http://export.yandex.ru/weather-ng/forecasts/") . variable_get('juice_city_index', $city_id) . '.xml';
    libxml_use_internal_errors(true);
    if ($xml = @simplexml_load_file($url, 'SimpleXMLElement', LIBXML_NOWARNING)) {
        $weather = array(
            'city' => (string)$xml['city'],
            'country' => (string)$xml['country'],
            'date' => format_date(REQUEST_TIME, 'custom', 'l, j M Y, G:i'),
            'date_short' => format_date(REQUEST_TIME, 'custom', 'j M Y'),
        );
        $weather['fact'] = array(
            'temp' => (string)$xml->fact->temperature,
            'weather_type' => (string)$xml->fact->weather_type,
            'wind_speed' => (string)$xml->fact->wind_speed,
            'wind_drctn' => (string)$xml->fact->wind_direction,
            'wind_info' => t((string)$xml->fact->wind_direction),
            'humidity' => (string)$xml->fact->humidity,
            'pressure' => (string)$xml->fact->pressure,
            'imagev3' => (string)$xml->fact->{'image-v3'},
            'image' => (string)$xml->fact->image,
        );
        //Погода на 10 дней
        foreach ($xml->day as $day) {
            $result = array(
                'date' => format_date(strtotime($day->attributes()->date), 'custom', 'j M'),
                'weekday_short' => strtolower(format_date(strtotime($day->attributes()->date), 'custom', 'D')),
                'weekday_full' => strtolower(format_date(strtotime($day->attributes()->date), 'custom', 'l')),
                'sunrise' => (string)$day->sunrise,
                'sunset' => (string)$day->sunset,
                'temp_day' => (string)(isset($day->day_part[4]->{'temperature-data'}->avg) ? $day->day_part[4]->{'temperature-data'}->avg : ''),
                'temp_night' => (string)(isset($day->day_part[5]->{'temperature-data'}->avg) ? $day->day_part[5]->{'temperature-data'}->avg : ''),
                'weather_type' => (string)(isset($day->day_part[4]->weather_type) ? $day->day_part[4]->weather_type : ''),
                'wind_speed' => (string)(isset($day->day_part[4]->wind_speed) ? $day->day_part[4]->wind_speed : ''),
                'humidity' => (string)(isset($day->day_part[4]->humidity) ? $day->day_part[4]->humidity : ''),
                'pressure' => (string)(isset($day->day_part[4]->pressure) ? $day->day_part[4]->pressure : ''),
                'imagev3' => (string)(isset($day->day_part[4]->{'image-v3'}) ? $day->day_part[4]->{'image-v3'} : ''),
                'image' => (string)(isset($day->day_part[4]->image) ? $day->day_part[4]->image : ''),
                'day_part' => array(),
            );
            //drupal_set_message($day->day_part[4]->{'temperature-data'}->avg);
            // вычисления для эквалайзера температуры
            if (isset($day->day_part[4]->{'temperature-data'}->avg) && isset($day->day_part[5]->{'temperature-data'}->avg)) {
                $pre = ((integer)$day->day_part[4]->{'temperature-data'}->avg - (integer)$day->day_part[5]->{'temperature-data'}->avg);
                $pre = ($pre == 0) ? 1 : $pre;
                $mult = 40 / $pre;
                $shift = (integer)$day->day_part[5]->{'temperature-data'}->avg;

                foreach ($day->day_part as $day_part) {
                    $result['day_part'][] = array(
                        'part' => (string)$day_part['type'],
                        'temp_from' => (string)$day_part->temperature_from,
                        'temp_to' => (string)$day_part->temperature_to,
                        'temp' => (string)$day_part->{'temperature-data'}->avg,
                        'temp_avg' => (string)$day_part->{'temperature-data'}->avg,
                        'weather_type' => (string)$day_part->weather_type,
                        'wind_speed' => (string)$day_part->wind_speed,
                        'wind_drctn' => (string)$day_part->wind_direction,
                        'wind_info' => t((string)$day_part->wind_direction),
                        'humidity' => (string)$day_part->humidity,
                        'pressure' => (string)$day_part->pressure,
                        'imagev3' => (string)$day_part->{'image-v3'},
                        'image' => (string)$day_part->image,
                        'height' => (integer)((integer)$day_part->{'temperature-data'}->avg - $shift) * $mult + 30,
                    );
                }
            }
            $weather['day'][] = $result;
        }
    } else {
        // проверяем ошибки
        foreach (libxml_get_errors() as $error) {
            // handle errors here
        }
        libxml_clear_errors();
    }

    return $weather;
}

function _juice_get_city($ip) {
    if (!filter_var($ip, FILTER_VALIDATE_IP, array('flags' => FILTER_FLAG_IPV4))) return false;
    $get = file_get_contents('http://ipgeobase.ru:7020/geo?ip=' . $ip);
    $xml = simplexml_load_string($get);
    $city = isset($xml->ip->city) ? strtolower($xml->ip->city) : '';
    return $city;
}


