<?php

include 'includes/address_book.autocomplete.inc';

/**
 * Implements hook_menu().
 */
function address_book_menu() {
//    $items['adr-book/%'] = array(
//        'title' => t('Address Book'),
//        'page callback' => 'address_book_callback',
//        'page arguments' => array(1),
//        'access arguments' => array('access content'),
//        'type' => MENU_CALLBACK,
//    );
    // %1 - default address id
    // %2 - callback module
    // %3 - target entity id
    $items['adr-book/%/%/%'] = array(
        'title' => t('Address Book'),
        'page callback' => 'address_book_callback',
        'page arguments' => array(1, 2, 3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    // автозаполнение полей
    $items['abook/autocomplete/region'] = array(
        'page callback' => 'address_book_autocomplete_region',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['abook/autocomplete/area/%'] = array(
        'page callback' => 'address_book_autocomplete_area',
        'page arguments' => array(3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['abook/autocomplete/city/%'] = array(
        'page callback' => 'address_book_autocomplete_city',
        'page arguments' => array(3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['abook/autocomplete/street/%'] = array(
        'page callback' => 'address_book_autocomplete_street',
        'page arguments' => array(3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['abook/autocomplete/house/%'] = array(
        'page callback' => 'address_book_autocomplete_house',
        'page arguments' => array(3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['abook/place-select/%/%'] = array(
        'page callback' => 'address_book_place_select',
        'page arguments' => array(2, 3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function address_book_theme( ) {
    return array(
        'address_book_radio_element' => array(
            'render element' => 'element',
        ),
    );
}

/**
 * callback вызова окна выбора Местоположения
 */
function address_book_place_select($rid, $cid, $mode = NULL) {
    if ($mode == 'ajax') {
        ctools_include('ajax'); ctools_include('modal');
        $form_state = array('ajax' => TRUE, 'title' => t('Place selection'));
        $form_state['build_info']['args'] = array('rid' => $rid, 'cid' => $cid);
        $output = ctools_modal_form_wrapper('address_place_select_form', $form_state);
        if (!empty($form_state['ajax_commands'])) $output = $form_state['ajax_commands'];
        print ajax_render($output);
        drupal_exit();
    }
    else return drupal_get_form('address_place_select_form', $rid, $cid);
}
/**
 * форма выбора Местоположения
 */
function address_place_select_form($form, &$form_state, $rid, $cid) {

    // todo сохранение выбора или переход по ссылке

    $form = array(
        '#prefix' => '<div id="place-select">',
        '#suffix' => '</div>',
    );

    $class  = $rid ? 'city' : 'region';
    $cols   = $rid ? 4 : 3;
    $select_all = $rid ? t('All over the region') : t('All over the country');
    $select_all_tids = $rid ? $rid . '/all' : 'all/0';
    $choose_area = $rid ? 'Choose city' : 'Choose region';

    // получить список регионов или городов
    $vid = taxonomy_vocabulary_machine_name_load('regions')->vid;
    $items_list = taxonomy_get_tree($vid, $rid, 1, true);

    // разбить на столбцы
    $regions_list = array();
    $col = $counter = 0;
    foreach ($items_list as $item) {
        $letter = drupal_strtoupper(drupal_substr($item->name, 0, 1));
        $regions_list[$col][$letter][$item->tid] = $item->name;
        if ($counter++ >= round(count($items_list) / $cols)) {
            $col++;
            $counter = 0;
        }
    }

    // сгенерировать разметку
    $list  = '<div class="place-select-header">';
    $list .=    '<div class="place-select-title">';
    $list .=        t($choose_area) . ($rid ? '<span> (' . l(t('change region'), 'abook/place-select/0/0/nojs', array('attributes' => array('class' => array('use-ajax')))) . ')</span>' : '');
    $list .=    '</div>';
    $list .=    '<div class="place-select-all">';
    $list .=        l(t($select_all), 'abook/place-select/' . $select_all_tids . '/nojs', array('attributes' => array('class' => array('use-ajax'))));
    $list .=    '</div>';
    $list .= '</div>';
    
    $list .= '<ul class="place-list">';
    foreach ($regions_list as $column) {
        $list .= '<li class="place-column ' . $class . '">';
        foreach ($column as $key_l => $letter_set) {
            $list .= '<ul class="place-letter">';
            $list .= '<li class="letter">' . $key_l . '</li>';
            foreach ($letter_set as $key_r => $row) {
                if ($rid) { $r = $rid; $c = $key_r; } else { $r = $key_r; $c = 0; }
                $link = l($row, 'abook/place-select/' . $r . '/' . $c . '/nojs', array('attributes' => array('class' => array('use-ajax'))));
                $list .= '<li>' . $link . '</li>';
            }
            $list .= '</ul>';
        }
        $list .= '</li>';
    }
    $list .= '</ul>';


    $form['list'] = array(
        '#markup' => $list,
    );

    return $form;
}

function get_places_list($rid) {

    $countryId = 1; // Russia
    $lang = 0;
    $headerOptions = array(
        'http' => array(
            'method' => "GET",
            'header' => "Accept-language: en\r\n" .
                "Cookie: remixlang=$lang\r\n"
        )
    );
    $methodUrl = 'http://api.vk.com/method/database.';
    if ($rid) $methodUrl .= 'getCities?v=5.5&region_id=' . $rid;
    else $methodUrl .= 'getRegions?v=5.5';
    $methodUrl .= '&country_id=' . $countryId;
    $methodUrl .= '&offset=0&need_all=0';
    $streamContext = stream_context_create($headerOptions);
    $json = file_get_contents($methodUrl, false, $streamContext);
    $arr = json_decode($json, true);

    return $arr['response'] ? $arr['response']['items'] : false;
}

/**
 * callback вызова окна адресной книги в оформлении заказа
 */
function address_book_callback($aid, $callback, $tgtid, $mode = NULL) {
    if ($mode == 'ajax') {
        ctools_include('ajax'); ctools_include('modal');
        $form_state = array('ajax' => TRUE, 'title' => t('Address Book'));
        $form_state['build_info']['args'] = array('default_aid' => $aid, 'callback' => $callback, 'tgtid' => $tgtid);
        $output = ctools_modal_form_wrapper('address_book_form', $form_state);
        if (!empty($form_state['ajax_commands'])) $output = $form_state['ajax_commands'];
        print ajax_render($output);
        drupal_exit();
    }
    else return drupal_get_form('address_book_form', $aid, $callback, $tgtid);
}
/**
 * форма адресной книги
 */
function address_book_form($form, &$form_state, $aid, $callback, $tgtid) {
    global $user;

    // вызываем функцию, возвращающую информацию о модуле, обратившемся к адресной книге
    $form_state['callback'] = $callback;
    $callback .= '_address_book_info';
    $mandatory_fields = $callback();
        // цель, куда будем сохранить адрес и её идентификатор
    $form_state['target_id'] = $tgtid;

    
    $form_state['aid'] = $aid;
    if (!$form_state['op']) $form_state['op'] = 'choose';

    // если после кнопки добавления адреса выбран другой адрес, перевести в режим выбора
    if ($form_state['op'] == 'add' && $form_state['op'] != $form_state['values']['radios']) $form_state['op'] = 'choose';

    // операции с адресной книгой обрабатываются в самой форме
    // submit только для отправки выбранного адреса
        // если нажата кнопка Редактировать
    if ($form_state['clicked_button']['#name'] == 'edit-button') {
        $form_state['op'] = 'edit';
    }

        // если нажата кнопка Сохранить
    if ($form_state['clicked_button']['#name'] == 'save-button') {
        if ($form_state['op'] == 'add') {
            // создать новую запись адреса
            $node = new stdClass();
            $node->type = 'address';
            node_object_prepare($node);
            $node->language = LANGUAGE_NONE;
            $node->title = t('Address');
        } else {
            $node = node_load($form_state['a_id']);
        }

        $node->field_ab_surname[LANGUAGE_NONE][0]['value']      = $form_state['input']['surname'];
        $node->field_ab_name[LANGUAGE_NONE][0]['value']         = $form_state['input']['name'];
        $node->field_ab_name2[LANGUAGE_NONE][0]['value']        = $form_state['input']['name2'];
        $node->field_ab_phone[LANGUAGE_NONE][0]['value']        = $form_state['input']['phone'];
        $node->field_ab_email[LANGUAGE_NONE][0]['value']        = $form_state['input']['email'];
        $node->field_ab_country[LANGUAGE_NONE][0]['value']      = $form_state['input']['country'];
        $node->field_ab_zipcode[LANGUAGE_NONE][0]['value']      = trim($form_state['input']['zipcode']);
        $node->field_ab_region[LANGUAGE_NONE][0]['value']       = trim($form_state['input']['region']);
        $node->field_ab_area[LANGUAGE_NONE][0]['value']         = trim($form_state['input']['area']);
        $node->field_ab_city[LANGUAGE_NONE][0]['value']         = trim($form_state['input']['city']);
        $node->field_ab_street[LANGUAGE_NONE][0]['value']       = trim($form_state['input']['street']);
        $node->field_ab_house[LANGUAGE_NONE][0]['value']        = trim($form_state['input']['house']);
        $node->field_ab_app[LANGUAGE_NONE][0]['value']          = trim($form_state['input']['app']);
        $node->field_ab_passport[LANGUAGE_NONE][0]['value']     = $form_state['input']['passport'];
        $node->field_ab_region_kladr[LANGUAGE_NONE][0]['value'] = $form_state['input']['region_kladr'];
        $node->field_ab_area_kladr[LANGUAGE_NONE][0]['value']   = $form_state['input']['area_kladr'];
        $node->field_ab_city_kladr[LANGUAGE_NONE][0]['value']   = $form_state['input']['city_kladr'];
        $node->field_ab_street_kladr[LANGUAGE_NONE][0]['value'] = $form_state['input']['street_kladr'];
        $node->field_ab_house_kladr[LANGUAGE_NONE][0]['value']  = $form_state['input']['house_kladr'];
        node_save($node);

        $form_state['input']['radios'] = $node->nid; // сделать новый или редактируемый адрес текущим
        $form_state['values']['radios'] = $node->nid; // сделать новый или редактируемый адрес текущим
        $form_state['op'] = 'choose';
    }

        // если нажата кнопка Удалить
    if ($form_state['clicked_button']['#name'] == 'delete-button') {
        node_delete($form_state['values']['radios']);
        unset($form_state['values']['radios']);
        unset($form_state['input']['radios']);
    }

    // предзаполнение полей
    if ($profile = profile2_load_by_user($user, 'main')) {
        $surname = $profile->field_profile_surname['ru'][0]['value'];
        $name = $profile->field_profile_name['ru'][0]['value'];
        $name2 = $profile->field_profile_name2['ru'][0]['value'];
        $phone = $profile->field_profile_phone['ru'][0]['value'];
    }
        
    $email = $user->mail;
    $country = 'Россия';
    $zipcode = $region = $area = $city = $street = $house = $app = $passport = '';
    $region_kladr = $area_kladr = $city_kladr = $street_kladr = $house_kladr = 0;

    $form['#attached']['js'][] = drupal_get_path('module', 'address_book') . '/js/address_book.js';
    $form['#attached']['css'][] = drupal_get_path('module', 'address_book') . '/css/address_book.css';
    $form['#prefix'] = '<div id="ab-form-wrapper">';
    $form['#suffix'] = '</div>';

    // проверяем, существует ли текущий адрес
    $query = db_select('node', 'n');
    $query->condition('n.nid', $aid);
    $query->condition('n.type', 'address');
    $query->fields('n', array('nid'));
    $nid = $query->execute()->fetchField();
    if (!$nid) $aid = 0;

    // считываем адресную книгу пользователя
    $query = db_select('node', 'n');
    $query->condition('n.uid', $user->uid);
    $query->condition('n.type', 'address');
    $query->fields('n', array('nid'));
    $nids = $query->execute()->fetchAll();

    // определяем текущее значение radiobutton
    $a_list_def = empty($form_state['values']['radios']) ? $aid : $form_state['values']['radios'];
    $a_list = array();
    if ($nids) {
        foreach ($nids as $nid) {
            $arr_cust = array();
            $node_wrapper = entity_metadata_wrapper('node', $nid->nid);
            // в режиме редактирования оставить только текущую запись
            if ($form_state['op'] != 'edit' || $nid->nid == $form_state['values']['radios']) {
                if ($node_wrapper->field_ab_surname->value())   $arr_cust[] = $node_wrapper->field_ab_surname->value();
                if ($node_wrapper->field_ab_name->value())      $arr_cust[] = $node_wrapper->field_ab_name->value();
                if (!$arr_cust) $arr_cust[] = 'Имя не задано';


                $addr = $node_wrapper->field_ab_city->value();
                if (!$addr) $addr = $node_wrapper->field_ab_region->value();
                if (!$addr) $addr = $node_wrapper->field_ab_country->value();

                $a_list[$nid->nid] = implode(' ', $arr_cust) . '<br />';
                $a_list[$nid->nid] .= $form_state['op'] == 'choose' ? '<span>' . $addr . '</span>' : '';
            }

            // для текущей записи выбрать значения для полей ввода
            if ($nid->nid == $a_list_def || !$a_list_def) {
                $a_list_def = $nid->nid;
                $surname        = $node_wrapper->field_ab_surname->value();
                $name           = $node_wrapper->field_ab_name->value();
                $name2          = $node_wrapper->field_ab_name2->value();
                $phone          = $node_wrapper->field_ab_phone->value();
                $email          = $node_wrapper->field_ab_email->value();
                $country        = $node_wrapper->field_ab_country->value();
                $zipcode        = $node_wrapper->field_ab_zipcode->value();
                $region         = $node_wrapper->field_ab_region->value();
                $area           = $node_wrapper->field_ab_area->value();
                $city           = $node_wrapper->field_ab_city->value();
                $street         = $node_wrapper->field_ab_street->value();
                $house          = $node_wrapper->field_ab_house->value();
                $app            = $node_wrapper->field_ab_app->value();
                $passport       = $node_wrapper->field_ab_passport->value();

                $region_kladr   = $node_wrapper->field_ab_region_kladr->value();
                $area_kladr     = $node_wrapper->field_ab_area_kladr->value();
                $city_kladr     = $node_wrapper->field_ab_city_kladr->value();
                $street_kladr   = $node_wrapper->field_ab_street_kladr->value();
                $house_kladr    = $node_wrapper->field_ab_house_kladr->value();
            }
        }
    }
    if ($form_state['op'] != 'edit') $a_list['add'] = t('Add address');

    if ($a_list_def == 'add') $form_state['op'] = 'add';

    // отключить редактирование полей в режиме выбора адреса
    $disabled = ($form_state['op'] == 'choose') ? true :false;

    $form['list'] = array(
        '#type' => 'container',
        '#attributes' => array(
            'class' => array('ab-list')
        ),
    );
    $form['list']['radios'] = array(
        '#type' => 'radios',
        '#options' => $a_list,
        '#default_value' => $a_list_def,
        '#ajax' => array(
            'callback' => 'address_book_form_refresh',
            'wrapper' => 'ab-form-wrapper',
        ),
        '#pre_render' => array('address_book_radio_prerender'),
    );
    $form['detail'] = array(
        '#type' => 'container',
        '#attributes' => array(
            'class' => array('ab-detail')
        ),
    );

    $form['detail']['surname'] = array(
        '#type' => 'textfield',
        '#size' => 17,
        '#attributes' => $disabled ? array() : array('placeholder' => t('Surname')),
        '#default_value' => $surname,
        '#disabled' => $disabled,
    );
    $form['detail']['name'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Name')),
        '#size' => 12,
        '#default_value' => $name,
        '#disabled' => $disabled,
    );
    $form['detail']['name2'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Second name')),
        '#size' => 18,
        '#default_value' => $name2,
        '#disabled' => $disabled,
    );
    $form['detail']['phone'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Phone')),
        '#size' => 15,
        '#default_value' => $phone,
        '#disabled' => $disabled,
    );
    $form['detail']['email'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('E-Mail')),
        '#size' => 20,
        '#default_value' => $email,
        '#disabled' => $disabled,
    );

    $form['detail']['country'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Country')),
        '#size' => 30,
        '#default_value' => $country,
        '#disabled' => $disabled,
    );
    $form['detail']['zipcode'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Zipcode')),
        '#size' => 8,
        '#default_value' => $zipcode,
        '#disabled' => $disabled,
    );
    $form['detail']['region'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Region')),
        '#size' => 44,
        '#default_value' => $region,
        '#disabled' => $disabled,
        '#autocomplete_path' => 'abook/autocomplete/region',
    );
    $form['detail']['area'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Area')),
        '#size' => 23,
        '#default_value' => $area,
        '#disabled' => $disabled,
    );
    if (!$disabled) $form['detail']['area']['#autocomplete_path'] = 'abook/autocomplete/area/0';
    $form['detail']['city'] = array(
        '#type' => 'textfield',
        '#attributes' =>$disabled ? array() : array('placeholder' => t('City')),
        '#size' => 29,
        '#default_value' => $city,
        '#disabled' => $disabled,
    );
    if (!$disabled) $form['detail']['city']['#autocomplete_path'] = 'abook/autocomplete/city/0';
    $form['detail']['street'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Street')),
        '#size' => 29,
        '#default_value' => $street,
        '#disabled' => $disabled,
    );
    if (!$disabled) $form['detail']['street']['#autocomplete_path'] = 'abook/autocomplete/street/0';
    $form['detail']['house'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('House')),
        '#size' => 7,
        '#default_value' => $house,
        '#disabled' => $disabled,
    );
    if (!$disabled) $form['detail']['house']['#autocomplete_path'] = 'abook/autocomplete/house/0';
    $form['detail']['app'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Appartment')),
        '#size' => 8,
        '#default_value' => $app,
        '#disabled' => $disabled,
    );

    $form['detail']['passport'] = array(
        '#type' => 'textfield',
        '#attributes' => $disabled ? array() : array('placeholder' => t('Passport')),
        '#size' => 60,
        '#default_value' => $passport,
        '#disabled' => $disabled,
    );

    // проверить поля на обязательность и изменить цвет подчёркивания
    foreach($form['detail'] as $key_f => $item_f) {
        if (in_array($key_f, $mandatory_fields))
            $form['detail'][$key_f]['#attributes']['class'] = array('mandatory');
    }

    $message = 'Обязательные для заполнения поля подчёркнуты красным.<br />Для редактирования нажмите кнопку "Изменить запись".';
    if ($form_state['op'] == 'add' || $form_state['op'] == 'edit')
        $message = 'Заполните поля, подчёркнутые красным и нажмите "Сохранить запись".<br />При заполнении полей адреса наберите 3-4 первых буквы и выберите значение из выпадающего списка.';
    $form['detail']['message'] = array(
        '#markup' => '<div class="message">' . $message . '</div>',
    );

    $form['buttons'] = array(
        '#type' => 'container',
        '#attributes' => array(
            'class' => array('ab-buttons')
        ),
    );
    if ($form_state['op'] != 'choose') {
        $form['buttons']['save'] = array(
            '#type' => 'button',
            '#name' => 'save-button',
            '#value' => t('Save record'),
            '#ajax' => array(
                'callback' => 'address_book_form_refresh',
                'wrapper' => 'ab-form-wrapper',
            ),
        );
    } else {
        // кнопки редактирования и удаления адреса
        $form['buttons']['edit'] = array(
            '#type' => 'button',
            '#name' => 'edit-button',
            '#value' => t('Edit record'),
            '#ajax' => array(
                'callback' => 'address_book_form_refresh',
                'wrapper' => 'ab-form-wrapper',
            ),
        );
        $form['buttons']['delete'] = array(
            '#type' => 'button',
            '#name' => 'delete-button',
            '#value' => t('Delete record'),
            '#ajax' => array(
                'callback' => 'address_book_form_refresh',
                'wrapper' => 'ab-form-wrapper',
            ),
        );
        // кнопка выбора записи
        $form['buttons']['submit'] = array(
            '#type' => 'submit',
            '#name' => 'choose-button',
            '#value' => t('Choose record'),
            '#ajax' => array(
                'callback' => 'address_book_form_ajax_submit',
            ),
        );
    }

    $form['region_kladr'] = array(
        '#type' => 'hidden',
        '#default_value' => $region_kladr,
    );
    $form['area_kladr'] = array(
        '#type' => 'hidden',
        '#default_value' => $area_kladr,
    );
    $form['city_kladr'] = array(
        '#type' => 'hidden',
        '#default_value' => $city_kladr,
    );
    $form['street_kladr'] = array(
        '#type' => 'hidden',
        '#default_value' => $street_kladr,
    );
    $form['house_kladr'] = array(
        '#type' => 'hidden',
        '#default_value' => $house_kladr,
    );

    $form_state['a_id'] = (integer)$a_list_def;

    return $form;
}
function address_book_form_refresh($form, $form_state) {
    return $form;
}

/**
 * submit формы адресной книги
 */
function address_book_form_validate($form, &$form_state) {
    if ($form_state['triggering_element']['#name'] == 'save-button' && !empty($form_state['callback'])) {
        $function = $form_state['callback'] . '_address_book_info';
        if (function_exists($function) && $mandatory_fields = $function()) {
            foreach ($mandatory_fields as $item_m) {
                if (empty($form_state['values'][$item_m])) {
                    form_set_error($item_m, 'Заполните обязательные поля, подчёркнутые красным цветом.');
                    return;
                }
            }
        }
    }
}

/**
 * submit формы адресной книги
 */
function address_book_form_submit($form, &$form_state) {
    // вызвать обработчик submit модуля, вызвавшего ABook и передать результаты выбора
    $function = $form_state['callback'] . '_address_book_submit';
    if (function_exists($function)) $function($form_state);
}
/**
 * ajax submit формы адресной книги
 * return $array - набор команд для вывода результата на форму
 */
function address_book_form_ajax_submit($form, &$form_state) {
    ctools_include('ajax'); ctools_include('modal');
    $commands = array();

        // вызвать обработчик submit модуля, вызвавшего ABook и передать результаты выбора
    $function = $form_state['callback'] . '_address_book_ajax_submit';
    if (function_exists($function)) $commands = $function($form_state);
    $commands[] = ctools_modal_command_dismiss();
    
    return array('#type' => 'ajax', '#commands' => $commands);
}


/**
 * callback for form radio button pre_render
 * предобработчик для добавления функции темизации для опций элемента radio
 */
function address_book_radio_prerender($element){
    foreach (element_children($element) as $id) {
        $element[$id]['#theme_wrappers'] = array('address_book_radio_element');
    }
    return $element;
}

/**
 * стандартная функция темизации theme_form_element
 * темизация опций элемента radio (добавить класс active для текущего элемента)
 */
function theme_address_book_radio_element($variables){
    $element = &$variables['element'];

    // This function is invoked as theme wrapper, but the rendered form element
    // may not necessarily have been processed by form_builder().
    $element += array(
        '#title_display' => 'before',
    );

    // Add element #id for #type 'item'.
    if (isset($element['#markup']) && !empty($element['#id'])) {
        $attributes['id'] = $element['#id'];
    }
    // Add element's #type and #name as class to aid with JS/CSS selectors.
    $attributes['class'] = array('form-item');
    if (!empty($element['#type'])) {
        $attributes['class'][] = 'form-type-' . strtr($element['#type'], '_', '-');
    }
    if (!empty($element['#name'])) {
        $attributes['class'][] = 'form-item-' . strtr($element['#name'], array(' ' => '-', '_' => '-', '[' => '-', ']' => ''));
    }
    // Add a class for disabled elements to facilitate cross-browser styling.
    if (!empty($element['#attributes']['disabled'])) {
        $attributes['class'][] = 'form-disabled';
    }
    if ($element['#return_value'] == $element['#value']) {
        $attributes['class'][] = 'active';
    }
    $output = '<div' . drupal_attributes($attributes) . '>' . "\n";

    // If #title is not set, we don't display any label or required marker.
    if (!isset($element['#title'])) {
        $element['#title_display'] = 'none';
    }

    switch ($element['#title_display']) {
        case 'before':

        case 'after':
            $output .= ' ' . $element['#children'];
            $output .= ' ' . theme('form_element_label', $variables) . "\n";
            break;

        case 'none':
        case 'attribute':
            // Output no label and no required marker, only the children.
            $output .= ' ' . $element['#children'] . "\n";
            break;
    }

    if (!empty($element['#description'])) {
        $output .= '<div class="description">' . $element['#description'] . "</div>\n";
    }

    $output .= "</div>\n";

    return $output;
}

/**
 * проверить запись книги $aid на заолнение полей $fields
 * @param $aid
 * @param $fields
 *
 * вернуть массив незаполненных
 */
function address_book_check_mandatory_fields ($address, $fields) {
    $result = false;
    
    if (is_numeric($address)) $address = node_load($address);
    $address_wrapper = entity_metadata_wrapper('node', $address);

    if (in_array('surname', $fields) && !$address_wrapper->field_ab_surname->value()) $result['surname'] = 'Фамилия';
    if (in_array('name', $fields) && !$address_wrapper->field_ab_name->value()) $result['name'] = 'Имя';
    if (in_array('name2', $fields) && !$address_wrapper->field_ab_name2->value()) $result['name2'] = 'Отчество';
    if (in_array('phone', $fields) && !$address_wrapper->field_ab_phone->value()) $result['phone'] = 'Телефон';
    if (in_array('email', $fields) && !$address_wrapper->field_ab_email->value()) $result['email'] = 'E-Mail';
    if (in_array('region', $fields) && !$address_wrapper->field_ab_region->value()) $result['region'] = 'Регион';
    if (in_array('city', $fields) && !$address_wrapper->field_ab_city->value()) $result['city'] = 'Населенный пункт';
    if (in_array('street', $fields) && !$address_wrapper->field_ab_street->value()) $result['street'] = 'Улица';
    if (in_array('house', $fields) && !$address_wrapper->field_ab_house->value()) $result['house'] = 'Дом';
    if (in_array('passport', $fields) && !$address_wrapper->field_ab_passport->value()) $result['passport'] = 'Паспортные данные';

    return $result;
}

/**
 * функция, возвращающая адрес отформатированный в строки: ФИО, адрес и паспорт
 */
function address_book_addr_to_string($address, $format = 'short') {
    if (is_numeric($address)) $address = node_load($address);

    $arr_addr = $arr_name = array();
    $passport = $phone = $email = '';
    if ($address) {
        $addr_wrapper = entity_metadata_wrapper('node', $address);

        if ($format == 'full' && $addr_wrapper->field_ab_zipcode->value()) $arr_addr[] = $addr_wrapper->field_ab_zipcode->value();
        if ($format == 'full' && $addr_wrapper->field_ab_region->value()) $arr_addr[] = $addr_wrapper->field_ab_region->value();
        if ($format == 'full' && $addr_wrapper->field_ab_area->value()) $arr_addr[] = $addr_wrapper->field_ab_area->value();
        if ($addr_wrapper->field_ab_city->value()) $arr_addr[] = $addr_wrapper->field_ab_city->value();
        $house = $addr_wrapper->field_ab_house->value() ? $addr_wrapper->field_ab_house->value() : '';
        $app = $addr_wrapper->field_ab_app->value() ? $addr_wrapper->field_ab_app->value() : '';
        if ($addr_wrapper->field_ab_street->value()) $arr_addr[] = $addr_wrapper->field_ab_street->value() . (!$house ? '' : (' ' . $house . (!$app ? '' : (' - ' . $app))));

        if ($addr_wrapper->field_ab_surname->value()) $arr_name[] = $addr_wrapper->field_ab_surname->value();
        if ($addr_wrapper->field_ab_name->value()) $arr_name[] = $addr_wrapper->field_ab_name->value();
        if ($addr_wrapper->field_ab_name2->value()) $arr_name[] = $addr_wrapper->field_ab_name2->value();

        $email = $addr_wrapper->field_ab_email->value() ? $addr_wrapper->field_ab_email->value() : '';
        $phone = $addr_wrapper->field_ab_phone->value() ? $addr_wrapper->field_ab_phone->value() : '';
        $passport = $addr_wrapper->field_ab_passport->value() ? $addr_wrapper->field_ab_passport->value() : '';
    } else return false;

    return array(
        'address' => implode(', ', $arr_addr),
        'user' => implode(' ', $arr_name),
        'passport' => $passport,
        'phone' => $phone,
        'email' => $email,
    );
}
