<?php

/**
 * Implements hook_menu()
 */
function mailer_menu()
{
    $items['admin/config/administration/mailer'] = array(
        'title' => 'Ручная рассылка писем',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('mailer_manual_form'),
        'access arguments' => array('access manager settings'),
    );

    return $items;
}


/**
 * Implements hook_cron_queue_info().
 */
function mailer_cron_queue_info()
{
    $queues['manual_mails_queue'] = array(
        'worker callback' => 'mailer_send_manual_mails',
    );

    $queues['http_queue'] = array(
        'worker callback' => 'mailer_http_mails',
    );

    return $queues;
}


/**
 * form callback.
 */
function mailer_manual_form($form, $form_state)
{
    $form['filter'] = array(
        '#type' => 'select',
        '#title' => 'Фильтр получателей',
        '#options' => [
            1 => 'Все',
            2 => 'Сотрудники',
            3 => 'Зарегистрированные пользователи',
        ],
        '#default_value' => empty($form_state['values']['filter']) ? [1 => 1, 2 => 2, 3 => 3] : $form_state['values']['filter'],
    );

    $form['subject'] = array(
        '#type' => 'textfield',
        '#title' => 'Тема письма',
        '#required' => TRUE,
        '#default_value' => empty($form_state['values']['subject']) ? '' : $form_state['values']['subject'],
    );

    $form['body'] = array(
        '#type' => 'text_format',
        '#title' => 'Тело письма',
        '#description' => 'Письмо может содержать в тексте HTML разметку со встроенными стилями',
        '#required' => TRUE,
        '#default_value' => empty($form_state['values']['body']['value']) ? '' : $form_state['values']['body']['value'],
    );

    $form['test'] = [
        '#type' => 'fieldset',
        '#title' => 'Протестировать',
    ];
    $form['test']['email'] = array(
        '#type' => 'textfield',
        '#title' => 'Email получателя',
        '#required' => TRUE,
        '#default_value' => empty($form_state['values']['subject']) ? '' : $form_state['values']['subject'],
    );
    $form['test']['send_test'] = [
        '#type' => 'submit',
        '#value' => 'Сначала тест!',
        '#description' => 'Отправить письмо на указанный ящик',
        '#validate' => ['mailer_manual_form_test_validate', 'mailer_manual_form_validate'],
        '#submit' => ['mailer_manual_form_test_submit'],
    ];

//    $form['subs'] = [
//        '#type' => 'fieldset',
//        '#title' => 'Подписка',
//    ];
//    $form['subs']['send_subs'] = [
//        '#type' => 'submit',
//        '#value' => 'Подписать!',
//        '#limit_validation_errors' => [],
//        '#submit' => ['mailer_manual_form_send_subs_submit'],
//    ];

    $form['actions'] = [
        '#type' => 'container'
    ];
    $form['actions']['send_spam'] = [
        '#type' => 'submit',
        '#value' => 'Начать спамить',
        '#description' => 'Отправить письма заданному контингенту',
        '#validate' => ['mailer_manual_form_filter_validate', 'mailer_manual_form_validate'],
        '#submit' => ['mailer_manual_form_spam_submit'],
    ];

    return $form;
}

/**
 * form validate callback.
 */
function mailer_manual_form_filter_validate($form, $form_state)
{
    if (!$form_state['input']['filter'][1] && !$form_state['input']['filter'][2]) {
        form_set_error('filter', 'Выберите одну или несколько категорий получателей.' );
    }
}

/**
 * form validate callback.
 */
function mailer_manual_form_validate($form, $form_state)
{
    if (empty($form_state['input']['subject'])) {
        form_set_error('subject', 'Тема письма обязательна к заполнению.' );
    }
    if (empty($form_state['input']['body'])) {
        form_set_error('body', 'Текст письма обязателен к заполнению.' );
    }
}

/**
 * form validate callback.
 */
function mailer_manual_form_test_validate($form, $form_state)
{
    if (empty($form_state['input']['email'])) {
        form_set_error('email', 'Кому отправляем письмо?' );
    }
}
/**
 * form submit callback.
 */
function mailer_manual_form_test_submit($form, &$form_state)
{
    $params['subject'] = $form_state['values']['subject'];
    $params['body'] = $form_state['values']['body']['value'];

    // письмо тестовому Пользователю
    drupal_mail('mailer', 'manual_mail', $form_state['values']['email'], 'RU', $params);

    // оставляем значения в форме
    $form_state['rebuild'] = true;
}



/**
 * form submit callback.
 */
function mailer_manual_form_send_subs_submit($form, &$form_state)
{
    ext_message_spam_subscribe();
}

/**
 * form submit callback.
 */
function mailer_manual_form_spam_submit($form, &$form_state)
{
    // определение пула получателей
    $mails = [];
    if ($form_state['values']['filter'][1]) {
        $query = db_select('users', 'u');
        $query->condition('u.status', 1);
        $query->condition('u.mail', '', '!=');
        if ($form_state['values']['filter'][2]) {
            // только для Сотрудников
            $query->innerJoin('user_roles', 'ur');
            $query->condition('ur.rid', STAFF);
        }
        if ($form_state['values']['filter'][3]) {
            // все кроме Сотрудников
            $query->innerJoin('user_roles', 'ur');
            $query->condition('ur.rid', STAFF, '!=');
        }
        $query->fields('u', ['mail']);
        $mails = $query->execute()->fetchCol();
    }

    // добавление в очередь отправки
    if ($mails) {
        $params['subject'] = $form_state['values']['subject'];
        $params['body'] = $form_state['values']['body']['value'];

        $queue = DrupalQueue::get('manual_mails_queue');
        foreach($mails as $mail) {
            $params['mail'] = $mail;

            $params['account'] = user_load_by_mail($mail);
            $queue->createItem($params);
        }
    }

    drupal_set_message('Письма поставлены в очередь и будут отправлены в ближайшее время');
}

function mailer_send_manual_mails($params)
{
     drupal_mail('mailer', 'manual_mail', $params['mail'], 'ru', $params, 'bot@kccc.ru');
}





/**
 * Implements hook_mail
 */
function mailer_mail($key, &$message, $params)
{
    switch($key) {

        case 'manual_mail':
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['body'];

            break;

        case 'order_creation':
            if ($params['mail_to'] == 'manager') {
                $message['subject'] = t('There is a new order from TradeHouse website visitor.');
                $message['body'][] = mailer_get_checkout_complete_email_text($params['data'], 'manager');
            }
            if ($params['mail_to'] == 'user') {
                $message['subject'] = t('You made an order at TradeHouse website.');
                $message['body'][] = mailer_get_checkout_complete_email_text($params['data'], 'user');
            }
            break;
    }
}

function mailer_get_checkout_complete_email_text($data, $recipient = 'manager')
{
  $order_wr = entity_metadata_wrapper('commerce_order', $data['order']);
  $order_info = ext_checkout_get_order_info($data['order']);

  // повторяющиеся стили
  $dt = 'width: 160px; text-align: right; color: #bbb; padding-right: 15px; vertical-align: top;';
  $dd = 'padding-bottom: 15px;';
  $td = 'border-bottom: 1px solid #ccc; border-right: 1px solid #ccc; padding: 4px 8px;';

  // список препаратов для письма
  $prep_table = t('No preparations selected');
  if ($order_wr->commerce_line_items->count()) {
      $table = array(
          'header' => array(
              array('data' => t('Product'),   'style' => $td . 'width: 150px; text-align:center;'),
              array('data' => t('Tare'),      'style' => $td . 'width: 100px; text-align:center;'),
              array('data' => t('Price'),     'style' => $td . 'width: 120px; text-align:center;'),
              array('data' => t('Qty'),       'style' => $td . 'width: 50px; text-align:center;'),
              array('data' => t('Total'),     'style' => $td . 'width: 150px; text-align:center;'),
          ),
      );
      foreach($order_info["products"]["items"] as $item) {
        $product = $item['product_info']['items'][$item['product_info']['nid']];
        $table['rows'][] = [
          ['data' => $item["product_info"]["title"], 'style' => $td],
          ['data' => $product['tare'], 'style' => $td],
          ['data' => $item['price_formatted'], 'style' => $td . ' text-align: right;'],
          ['data' => $item['qty'], 'style' => $td . ' text-align: center;'],
          ['data' => $item['total_formatted'], 'style' => $td . ' text-align: right;'],
        ];
      }
//      foreach ($order_wr->commerce_line_items as $item_wrapper) {
//          $pid = $item_wrapper->commerce_product->product_id->value();
//          $nid = _get_product_display_by_product_id($pid);
//          $tare = $item_wrapper->commerce_product->field_p_tare->name->value();
//          $prep_info = array_shift(ext_product_product_get_info($nid)['items']);
//
//          $table['rows'][] = array(
//              array('data' => $prep_info['title'], 'style' => $td),
//              array('data' => $tare, 'style' => $td),
//              array('data' => commerce_currency_format($item_wrapper->commerce_total->amount->value()/100, 'RUB', NULL, true), 'style' => $td . ' text-align: right;'),
//              array('data' => (int)$item_wrapper->quantity->value(), 'style' => $td . ' text-align: center;'),
//              array('data' => commerce_currency_format($item_wrapper->commerce_total->amount->value()/100 * $item_wrapper->quantity->value(), 'RUB', NULL, true), 'style' => $td . ' text-align: right;'),
//          );
//      }
      // добавить в таблицу вес, объём, сумму
    foreach ($order_info['total']['components'] as $component) {
      $table['rows'][] = [
        ['data' => $component['title'] , 'colspan' => 4, 'style' => $td],
        ['data' => $component["formatted"], 'style' => $td . ' text-align: right;'],
      ];
    }
    $table['rows'][] = [
      ['data' => t('Weight') . ': ' . $order_info['weight']['weight'] . ' ' . t($order_info['weight']['unit']) . '&nbsp;&nbsp;&nbsp;' . t('Volume') . ': ' . number_format($order_info['volume']['volume'], 2) . t('m') . '3' , 'colspan' => 4, 'style' => $td],
      ['data' => $order_info["total"]["formatted"] , 'style' => $td . ' text-align: right;'],
    ];

    $prep_table = theme('table', [
      'header' => $table['header'],
      'rows' => $table['rows'],
      'attributes' => array('cellspacing' => 0, 'style' => 'font-size: .8em; border-top: 1px solid #ccc; border-left: 1px solid #ccc;'),
    ]);
  }


  // содержимое письма
  $message = '<h2>' . t('Good day!') . '</h2>'
    . ($recipient == 'manager' ? '<p>' . t('There is a new order from TradeHouse website visitor.') . '</p>' : '<p>' . t('You made an order on TradeHouse website <a href="https://kccc.ru" target="_blank">https://kccc.ru</a>.<br />Our representative will contact you as soon as possible.') . '</p>')
    . '<table style="margin-bottom: 15px;">'
    . '<tr>'
    . '<td style="' . $dt . '">' . t('Order number') . '</td>'
    . '<td style="' . $dd . '">№ ' . $order_info['number'] . '</td>'
    . '</tr>'

    . '<tr>'
    . '<td style="' . $dt . '">' . t('User data') . '</td>'
    . '<td style="' . $dd . '">'
    . $order_info['user']['name'] . '<br />'
    . $order_info['user']['mail'] . '<br />'
    . $order_info['user']['phone']
    . '</td>'
    . '</tr>'

    . '<tr>'
    . '<td style="' . $dt . '">' . t('Preparations') . '</td>'
    . '<td style="' . $dd . '">'
    . $prep_table
    . '</td>'
    . '</tr>';

  if (!empty($order_info["services"])) {
    $message .= '<tr>'
      . '<td style="' . $dt . '">' . t('Services') . '</td>'
      . '<td style="' . $dd . '">' . $order_info["services"]['list'] . '</td>'
      . '</tr>';
  }
  if (!empty($order_info["shipping"])) {
    $message .= '<tr>'
    . '<td style="' . $dt . '">' . t('Delivery') . '</td>'
    . '<td style="' . $dd . '">'
    .  $order_info["shipping"]["title"]  . '<br />'
    .  $order_info["shipping"]["address"]
    . '</td>'
    . '</tr>';
  }
  if (!empty($order_info["services"]["support"])) {
    $message .= '<tr>'
      . '<td style="' . $dt . '">' . t('Support') . '</td>'
      . '<td style="' . $dd . '">' . $order_info["services"]["support"] . '</td>'
      . '</tr>';
  }
  if (!empty($order_info["payment"])) {
    $message .= '<tr>'
      . '<td style="' . $dt . '">' . t('Payment') . '</td>'
      . '<td style="' . $dd . '">' . $order_info["payment"]["title"] . '</td>'
      . '</tr>';
  }

  $message .= '</table>';

  return $message;
}


// замена http на https в справочниках
//function mailer_replace_http()
//{
//  $queue = DrupalQueue::get('http_queue');
//  for($i = 1; $i < 9999; $i++) {
//    $params['nid'] = $i;
//    $queue->createItem($params);
//  }
//}
//function mailer_http_mails($params)
//{
//  if ($node = node_load($params['nid'])) {
//    watchdog('http', 'Проверена нода ' . $params['nid'], NULL);
//    if (in_array($node->type, ['weed', 'disease', 'pest'])) {
//      $body_und = '';
//      $body_und_new = '';
//      if (!empty($node->body["und"][0]["value"])) {
//        $body_und = $node->body["und"][0]["value"];
//        $body_und_new = str_replace('http://kccc.', 'https://kccc.', $body_und);
//        $body_und_new = str_replace('http://www.kccc.', 'https://kccc.', $body_und_new);
//      }
//
//      $body_ru = '';
//      $body_ru_new = '';
//      if (!empty($node->body["ru"][0]["value"])) {
//        $body_ru = $node->body["ru"][0]["value"];
//        $body_ru_new = str_replace('http://kccc.', 'https://kccc.', $body_ru);
//        $body_ru_new = str_replace('http://www.kccc.', 'https://kccc.', $body_ru_new);
//      }
//
//      if ($body_und != $body_und_new || $body_ru != $body_ru_new) {
//        if ($body_und != $body_und_new) {
//          $node->body["und"][0]["value"] = $body_und_new;
//        }
//        if ($body_ru != $body_ru_new) {
//          $node->body["ru"][0]["value"] = $body_ru_new;
//        }
//        node_save($node);
//        watchdog('http', 'Нода ' . $params['nid'] . ' изменена', NULL);
//      }
//    }
//  }
//}
