<?php

/**
 * Implements hook_menu()
 */
function mailer_menu()
{
    $items['admin/config/administration/mailer'] = array(
        'title' => 'Ручная рассылка писем',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('mailer_manual_form'),
        'access arguments' => array('access manager settings'),
    );

    return $items;
}


/**
 * Implements hook_cron_queue_info().
 */
function mailer_cron_queue_info()
{
    $queues['manual_mails_queue'] = array(
        'worker callback' => 'mailer_send_manual_mails',
    );

    return $queues;
}


/**
 * form callback.
 */
function mailer_manual_form($form, $form_state)
{
    $form['filter'] = array(
        '#type' => 'select',
        '#title' => 'Фильтр получателей',
        '#options' => [
            1 => 'Все',
            2 => 'Сотрудники',
            3 => 'Зарегистрированные пользователи',
        ],
        '#default_value' => empty($form_state['values']['filter']) ? [1 => 1, 2 => 2, 3 => 3] : $form_state['values']['filter'],
    );

    $form['subject'] = array(
        '#type' => 'textfield',
        '#title' => 'Тема письма',
        '#required' => TRUE,
        '#default_value' => empty($form_state['values']['subject']) ? '' : $form_state['values']['subject'],
    );

    $form['body'] = array(
        '#type' => 'text_format',
        '#title' => 'Тело письма',
        '#description' => 'Письмо может содержать в тексте HTML разметку со встроенными стилями',
        '#required' => TRUE,
        '#default_value' => empty($form_state['values']['body']['value']) ? '' : $form_state['values']['body']['value'],
    );

    $form['test'] = [
        '#type' => 'fieldset',
        '#title' => 'Протестировать',
    ];
    $form['test']['email'] = array(
        '#type' => 'textfield',
        '#title' => 'Email получателя',
        '#required' => TRUE,
        '#default_value' => empty($form_state['values']['subject']) ? '' : $form_state['values']['subject'],
    );
    $form['test']['send_test'] = [
        '#type' => 'submit',
        '#value' => 'Сначала тест!',
        '#description' => 'Отправить письмо на указанный ящик',
        '#validate' => ['mailer_manual_form_test_validate', 'mailer_manual_form_validate'],
        '#submit' => ['mailer_manual_form_test_submit'],
    ];

//    $form['subs'] = [
//        '#type' => 'fieldset',
//        '#title' => 'Подписка',
//    ];
//    $form['subs']['send_subs'] = [
//        '#type' => 'submit',
//        '#value' => 'Подписать!',
//        '#limit_validation_errors' => [],
//        '#submit' => ['mailer_manual_form_send_subs_submit'],
//    ];

    $form['actions'] = [
        '#type' => 'container'
    ];
    $form['actions']['send_spam'] = [
        '#type' => 'submit',
        '#value' => 'Начать спамить',
        '#description' => 'Отправить письма заданному контингенту',
        '#validate' => ['mailer_manual_form_filter_validate', 'mailer_manual_form_validate'],
        '#submit' => ['mailer_manual_form_spam_submit'],
    ];

    return $form;
}

/**
 * form validate callback.
 */
function mailer_manual_form_filter_validate($form, $form_state)
{
    if (!$form_state['input']['filter'][1] && !$form_state['input']['filter'][2]) {
        form_set_error('filter', 'Выберите одну или несколько категорий получателей.' );
    }
}

/**
 * form validate callback.
 */
function mailer_manual_form_validate($form, $form_state)
{
    if (empty($form_state['input']['subject'])) {
        form_set_error('subject', 'Тема письма обязательна к заполнению.' );
    }
    if (empty($form_state['input']['body'])) {
        form_set_error('body', 'Текст письма обязателен к заполнению.' );
    }
}

/**
 * form validate callback.
 */
function mailer_manual_form_test_validate($form, $form_state)
{
    if (empty($form_state['input']['email'])) {
        form_set_error('email', 'Кому отправляем письмо?' );
    }
}
/**
 * form submit callback.
 */
function mailer_manual_form_test_submit($form, &$form_state)
{
    $params['subject'] = $form_state['values']['subject'];
    $params['body'] = $form_state['values']['body']['value'];

    // письмо тестовому Пользователю
    drupal_mail('mailer', 'manual_mail', $form_state['values']['email'], 'RU', $params);

    // оставляем значения в форме
    $form_state['rebuild'] = true;
}


/**
 * form submit callback.
 */
function mailer_manual_form_send_subs_submit($form, &$form_state)
{
    ext_message_spam_subscribe();
}

/**
 * form submit callback.
 */
function mailer_manual_form_spam_submit($form, &$form_state)
{
    // определение пула получателей
    $mails = [];
    if ($form_state['values']['filter'][1]) {
        $query = db_select('users', 'u');
        $query->condition('u.status', 1);
        $query->condition('u.mail', '', '!=');
        if ($form_state['values']['filter'][2]) {
            // только для Сотрудников
            $query->innerJoin('user_roles', 'ur');
            $query->condition('ur.rid', STAFF);
        }
        if ($form_state['values']['filter'][3]) {
            // все кроме Сотрудников
            $query->innerJoin('user_roles', 'ur');
            $query->condition('ur.rid', STAFF, '!=');
        }
        $query->fields('u', ['mail']);
        $mails = $query->execute()->fetchCol();
    }

    // добавление в очередь отправки
    if ($mails) {
        $params['subject'] = $form_state['values']['subject'];
        $params['body'] = $form_state['values']['body']['value'];

        $queue = DrupalQueue::get('manual_mails_queue');
        foreach($mails as $mail) {
            $params['mail'] = $mail;

            $params['account'] = user_load_by_mail($mail);
            $queue->createItem($params);
        }
    }

    drupal_set_message('Письма поставлены в очередь и будут отправлены в ближайшее время');
}

function mailer_send_manual_mails($params)
{
     drupal_mail('mailer', 'manual_mail', $params['mail'], 'ru', $params, 'bot@kccc.ru');
}


/**
 * Implements hook_mail
 */
function mailer_mail($key, &$message, $params)
{
    switch($key) {

        case 'manual_mail':
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['body'];

            break;

        case 'order_creation':
            if ($params['mail_to'] == 'manager') {
                $message['subject'] = t('There is a new request from TradeHouse website visitor.');
                $message['body'][] = mailer_get_checkout_complete_email_text($params['data'], 'manager');
            }
            if ($params['mail_to'] == 'user') {
                $message['subject'] = t('You made request at TradeHouse website.');
                $message['body'][] = mailer_get_checkout_complete_email_text($params['data'], 'user');
            }
            break;
    }
}

function mailer_get_checkout_complete_email_text($data, $recipient = 'manager')
{
    $order_wrapper = entity_metadata_wrapper('commerce_order', $data['order']);
    $weight = commerce_physical_order_weight($data['order'], 'kg');
    $volume = commerce_physical_order_volume($data['order'], 'm');

    // повторяющиеся стили
    $dt = 'width: 160px; text-align: right; color: #bbb; padding-right: 15px; vertical-align: top;';
    $dd = 'padding-bottom: 15px;';
    $td = 'border-bottom: 1px solid #ccc; border-right: 1px solid #ccc; padding: 4px 8px;';

    // список препаратов для письма
    $data['prep_table'] = t('No preparations selected');
    if ($order_wrapper->commerce_line_items->count()) {
        $table = array(
            'header' => array(
                array('data' => t('Product'),   'style' => $td . 'width: 150px; text-align:center;'),
                array('data' => t('Tare'),      'style' => $td . 'width: 100px; text-align:center;'),
                array('data' => t('Price'),     'style' => $td . 'width: 120px; text-align:center;'),
                array('data' => t('Qty'),       'style' => $td . 'width: 50px; text-align:center;'),
                array('data' => t('Total'),     'style' => $td . 'width: 150px; text-align:center;'),
            ),
        );
        $total = 0;
        foreach ($order_wrapper->commerce_line_items as $item_wrapper) {
            $pid = $item_wrapper->commerce_product->product_id->value();
            $nid = _get_product_display_by_product_id($pid);
            $tare = $item_wrapper->commerce_product->field_p_tare->name->value();
            $prep_info = array_shift(get_product_info($nid)['items']);

            $table['rows'][] = array(
                array('data' => $prep_info['title'], 'style' => $td),
                array('data' => $tare, 'style' => $td),
                array('data' => commerce_currency_format($item_wrapper->commerce_total->amount->value(), 'RUB', NULL, true), 'style' => $td . ' text-align: right;'),
                array('data' => (int)$item_wrapper->quantity->value(), 'style' => $td . ' text-align: center;'),
                array('data' => commerce_currency_format($item_wrapper->commerce_total->amount->value() * $item_wrapper->quantity->value(), 'RUB', NULL, true), 'style' => $td . ' text-align: right;'),
            );
            $total += $item_wrapper->commerce_total->amount->value() * $item_wrapper->quantity->value();
        }
        // добавить в таблицу вес, объём, сумму
        $table['rows'][] = array(
            array('data' => t('Weight') . ': ' . $weight['weight'] . ' ' . t($weight['unit']) . '&nbsp;&nbsp;&nbsp;' . t('Volume') . ': ' . number_format($volume['volume'], 2) . t('m') . '3' , 'colspan' => 4, 'style' => $td),
            array('data' => commerce_currency_format($total, 'RUB', NULL, true) , 'style' => $td . ' text-align: right;'),
        );

        $data['prep_table'] = theme('table', array(
            'header' => $table['header'],
            'rows' => $table['rows'],
            'attributes' => array('cellspacing' => 0, 'style' => 'font-size: .8em; border-top: 1px solid #ccc; border-left: 1px solid #ccc;'),
        ));
    }

    // регионы
    $regions = [];
    if ($data['rep']['regions']) {
        foreach ($data['rep']['regions'] as $item) {
            $regions[] = $item['name'];
        }
    }

    // содержимое письма
    $message = '<h2>' . t('Good day!') . '</h2>'
        . ($recipient == 'manager' ? '<p>' . t('There is a new request from TradeHouse website visitor.') . '</p>' : '<p>' . t('You made request on TradeHouse website <a href="https://kccc.ru" target="_blank">https://kccc.ru</a>.<br />Our representative will contact you as soon as possible.') . '</p>')
        . '<table style="margin-bottom: 15px;">'
        . '<tr>'
        . '<td style="' . $dt . '">' . t('Request number') . '</td>'
        . '<td style="' . $dd . '">№ ' . $data['order']->order_number . '</td>'
        . '</tr>'

        . '<tr>'
        . '<td style="' . $dt . '">' . t('User data') . '</td>'
        . '<td style="' . $dd . '">'
        . $data['user']['region'] . '<br />'
        . $data['user']['name'] . '<br />'
        . $data['user']['phone'] . '<br />'
        . $data['user']['email']
        . '</td>'
        . '</tr>'

        . '<tr>'
        . '<td style="' . $dt . '">' . t('Preparations') . '</td>'
        . '<td style="' . $dd . '">'
        . $data['prep_table']
        . '</td>'
        . '</tr>'

        . '<tr>'
        . '<td style="' . $dt . '">'
        . ($recipient == 'manager' ? t('Representative sent') : t('Representative'))
        . '</td>'
        . '<td style="' . $dd . '">'
        . $data['rep']['surname'] . ' ' . $data['rep']['name'] . ' ' . $data['rep']['name2'] . '<br />'
        . '<span style="color: #bbb; font-size: .9em;">' . $data['rep']['office']
        . (!empty($regions) ? ' ('. implode(', ', $regions) . ')' : '')
        . '</span><br />'
        . implode('<br />', $data['rep']['phones']) . '<br />'
        . implode('<br />', $data['rep']['emails']) . '<br />'
        . '</td>'
        . '</tr>'
        . '</table>';

    return $message;
}
