<?php

function sec_pesticides_menu()
{
  $items['admin/config/custom/pesticides'] = array(
    'title' => 'Пестициды МСХ',
    'description' => 'Импорт Пестицидов с сайта МСХ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_pesticides_import_form'),
    'access arguments' => array('access manager settings'),
    'weight' => 5,
  );

  return $items;
}

function sec_pesticides_node_access($node, $op, $account)
{
  // todo убрать
  // закрыть справочник от анонимов
  $type = is_string($node) ? $node : $node->type;
  if ($type == 'pesticide') {
    if (!user_has_role(MARKETING_RID, $account->roles)) {
      return NODE_ACCESS_DENY;
    }
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function sec_pesticides_cron_queue_info()
{
  $queues['mcx_processing_queue'] = array(
    'worker callback' => 'sec_pesticides_mcx_process_queue_item',
  );

  return $queues;
}

function ext_pesticides_import_form($form, $form_state)
{
  $form['version'] = [
    '#markup' => '<p>Текущая версия справочника: ' . variable_get('mcx_file_version', 'нет') . '<p>',
  ];

  $form['import'] = ['#type' => 'fieldset', '#title' => 'Импорт'];
  $form['import']['message'] = array(
    '#markup' => '<p>Будут последовательно выполнены следующие задачи:</p>' .
                  '<ul>' .
                    '<li>скачивание архива с сайта МСХ</li>' .
                    '<li>распаковка</li>' .
                    '<li>постановка задач на удаление всех предыдущих записей</li>' .
                    '<li>постановка задач на импорт по cron</li>' .
                  '</ul><p></p>',
  );
  $form['import']['force'] = [
    '#type' => 'checkbox',
    '#title' => 'перезагрузить текущую версию',
    '#defaulr_value' => false,
  ];

  $form['import']['run'] = [
    '#type' => 'submit',
    '#value' => 'Запустить импорт',
  ];

  return $form;
}
function ext_pesticides_import_form_submit($form, $form_state)
{
  sec_pesticides_mcx_import($form_state['values']['force']);
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function sec_pesticides_preprocess_page(&$vars)
{
  if (arg(0) == 'pesticides') {
    //$vars['banner_title'] = t('Pesticides');
    //$vars['is_title_on'] = false;
  }
}

/**
 * Выполнить импорт справочника с сайта Минсельхоза
 */
function sec_pesticides_mcx_import($force_import = false)
{
  if ($data_arr = sec_pesticides_mcx_get_new_info()) {
    if (variable_get('mcx_file_version') == $data_arr['filename'] && !$force_import) {
      drupal_set_message('Текущая версия справочника уже импортирована');
      return;
    }

    $queue = DrupalQueue::get('mcx_processing_queue');
    $queue->deleteQueue(); // todo удалить

    // Создать очередь на удаление записей по крону.
    // Удаление необходимо, так как в справочнике МСХ присутствуют дубли по имени
    // с разной формуляцией и даже полные дубли в разных категориях, а ID отсутствует.
    $dbr = db_select('node', 'n');
    $dbr->condition('n.type', 'pesticide');
    $dbr->addField('n', 'nid');
    if ($nids = $dbr->execute()->fetchCol()) {
      foreach ($nids as $record) {
        $queue->createItem(['op' => 'delete', 'record' => $record]);
      }
    }

    // Создать очередь на добавление записей по крону,
    // так как импорт всех в одном цикле может выйти за пределы max_execution_time
    foreach ($data_arr['items'] as $record) {
      $queue->createItem(['op' => 'import', 'record' => $record]);
    }
    drupal_set_message('Добавлено ' . count($data_arr['items']) . ' записей для обработки');

    // сохранить версию импортированного файла
    variable_set('mcx_file_version', $data_arr['filename']);
  }
}

/**
 * Выполнить удаление старой записи
 * или импорт новой записи справочника с сайта Минсельхоза
 */
function sec_pesticides_mcx_process_queue_item($data)
{
  $record = $data['record'];
  if ($data['op'] == 'delete') {
    node_delete($record);
    return;
  }

  if ($data['op'] == 'import' && $record["Naimenovanie"]["item"] && !is_array($record["Naimenovanie"]["item"])) {
    $node = entity_create('node', [
      'type' => 'pesticide',
      'title' => $record["Naimenovanie"]["item"],
    ]);
    node_save($node);

    $node_wr = entity_metadata_wrapper('node', $node);
    if (isset($record["Gruppa"]["item"]) && !is_array($record["Gruppa"]["item"]))
      $node_wr->field_hp_gruppa = $record["Gruppa"]["item"];
    if (isset($record["Deystvuyushee_veshestvo"]["item"]) && !is_array($record["Deystvuyushee_veshestvo"]["item"]))
      $node_wr->field_hp_dv = $record["Deystvuyushee_veshestvo"]["item"];
    if (isset($record["Soderzhanie_deystvuyushego_veshestva"]["item"]) && !is_array($record["Soderzhanie_deystvuyushego_veshestva"]["item"]))
      $node_wr->field_hp_sdv = $record["Soderzhanie_deystvuyushego_veshestva"]["item"];
    if (isset($record["Preparativnaya_forma"]["item"]) && !is_array($record["Preparativnaya_forma"]["item"])) {
      $pf = $record["Preparativnaya_forma"]["item"];
      // заменить сокращения с двойными обозначениями (ВГ/ВРГ)
      if ($pf == 'ВГ') $pf = 'ВРГ';
      if ($pf == 'ВГ') $pf = 'ВРГ';
      if (in_array($pf,['ВК', 'РК'])) $pf = 'ВРК';
      if ($pf == 'РКАП') $pf = 'ВРКАП';
      // попадаются латинские bp вместо вр
      if ($pf == 'TAБ') $pf = 'ТАБ';
      if (in_array($pf,['BP', 'BР'])) $pf = 'ВР';
      // вероятно ошибка в источнике
      if ($pf == 'В КЭ') $pf = 'КЭ';
      // расшифровать значение препаративной формы
      $dbr = db_select('taxonomy_term_data', 't');
      $dbr->condition('t.vid', taxonomy_vocabulary_machine_name_load('preparation_formulations')->vid);
      $dbr->addField('t', 'name');
      $dbr->innerJoin('field_data_field_acronym', 'fa', 'fa.entity_id = t.tid');
      $dbr->condition('field_acronym_value', $pf);
      if ($name = $dbr->execute()->fetchField()) {
        $pf = $name;
      }
      $node_wr->field_hp_pf = $pf;
    }

    if (isset($record["Registrant"]["item"]) && !is_array($record["Registrant"]["item"])) {
      $reg = $record["Registrant"]["item"];
      $reg = str_replace(['ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ', 'Индивидуальный Предприниматель', 'Индивидуальный предприниматель'], 'ИП', $reg);
      $reg = str_replace(['ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ', 'ОБЩЕСТВО с ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ', 'Общество с ограниченной ответственностью'], 'ООО', $reg);
      $reg = str_replace(['АКЦИОНЕРНОЕ ОБЩЕСТВО', 'Акционерное Общество'], 'АО', $reg);
      $reg = str_replace(['НАУЧНО-ПРОИЗВОДСТВЕННОЕ ОБЪЕДИНЕНИЕ', 'Научно-производственное объединение'], 'НПО', $reg);
      $reg = str_replace(['СЕЛЬСКОХОЗЯЙСТВЕННОЕ ПРЕДПРИЯТИЕ', 'Сельскохозяйственное Предприятие'], 'СП', $reg);
      $reg = str_replace(['НАУЧНО-ТЕХНОЛОГИЧЕСКОЕ ПРЕДПРИЯТИЕ', 'Научно-технологическое предприятие'], 'НТП', $reg);
      $reg = str_replace(['ФЕДЕРАЛЬНОЕ КАЗЕННОЕ ПРЕДПРИЯТИЕ', 'Федеральное казенное предприятие'], 'ФКП', $reg);
      $reg = str_replace(['ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ', 'Федеральное государственное бюджетное образовательное учреждение'], 'ФГБОУ', $reg);
      $reg = str_replace(['ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ УЧРЕЖДЕНИЕ НАУКИ', 'Федеральное государственное бюджетное учреждение науки'], 'ФГБУН', $reg);
      $reg = str_replace([' (Болгария)', ' (Республика Беларусь)', ' (Республика Сербия)', ' (Чешская Республика)', ' (Германия)', ' (Франция)', ' (Бельгия)', ' (Бельгия', ' (Аргентина)', ' (Индия)', ' (Китай)', '( Китай)', ' (Италия)', ' (Венгрия)', ' (Англия)', ' (КНР)', '(Великобритания)', ' (США)', ' (Япония)', ' (Австрия)'], '', $reg);
      $reg = str_replace(['Интер Групп', 'Интер Груп', 'ИнтерГрупп'], 'ИНТЕР ГРУПП', $reg);
      $reg = str_replace(['АГРОХИМ-ХХI', 'Агрохим-ХХI', 'Агрохим-ХХ1', 'АГРОХИМ- ХХI', 'АГРОХИМ-ХХ1', 'АГРОХИМ - XXI', 'Агрохим -ХХI', 'АГРОХИМ - ХХI', 'АГРОХИМ - ХХ1', 'Агрохим – XXI', 'АГРОХИМ ХХI', 'АГРОХИМ – XXI'], 'АГРОХИМ-XXI', $reg);
      $reg = str_replace('ООО АНПП', 'ООО «АНПП', $reg);
      $reg = str_replace(['ООО ГЭ «ЗЕМЛЯКОФФ»', 'ООО Группа Компаний «ЗемлякоФФ»'], 'ООО ГК «ЗЕМЛЯКОФФ»', $reg);
      $reg = str_replace(['Шандонг Вейфанг Рейнбоу Кемикал Ко., Лтд.', '«Шандонг Вейфанг Рейнбоу Кемикал Ко., Лтд»'], 'Шандонг Вейфанг Рейнбоу Кемикал Ко., Лтд', $reg);
      $reg = str_replace(['«Шин-Етсу Кемикал Ко., Лтд.»', '«Шандонг Вейфанг Рейнбоу Кемикал Ко., Лтд»'], 'Шин-Етсу Кемикал Ко., Лтд', $reg);
      $reg = str_replace(['СУМИТОМО КЕМИКАЛ АГРО ЕВРОПА С.А.С', 'Сумитомо-Кемикал Агро Юроп С.А.С.'], 'Сумитомо Кемикал Агро Юроп С.А.С.', $reg);
      $reg = str_replace(['ООО «ФРАНДЕСА»', 'ООО «ФРАНДЕСА», ООО «Франдеса»', 'ООО « Франдеса»', 'ООО «Франдесса»'], 'ООО «Франдеса»', $reg);
      $reg = str_replace(['ООО «Франдеса» ООО «Форвард»'], 'ООО «Франдеса», ООО «Форвард»', $reg);
      $reg = str_replace(['Ниппон Сода Ко., Лтд.', 'НИППОН СОДА КО., ЛТД.'], 'Ниппон Сода Ко., Лтд', $reg);
      $reg = str_replace(['«ПЕТЕРС&БУРГ Кфт.»', 'ПЕТЕРС&БУРГ Кфт.', 'ПЕТЕРС & БУРГ Кфт.'], 'ПЕТЕРС & БУРГ Кфт', $reg);
      $reg = str_replace(['Нуфарм ГмбХ и КО КГ', 'НУФАРМ ГмбХ&Ко.КГ', 'НУФАРМ ГмбХ&Ко КГ'], 'НУФАРМ ГмбХ & Ко КГ', $reg);
      $reg = str_replace(['ООО УК «АБТ-ГРУПП»,', 'ООО Управляющая компания «АБТ-ГРУПП»', 'ООО «Управляющая компания «АБТ-групп»'], 'ООО УК «АБТ-ГРУПП»', $reg);
      $reg = str_replace(['ДАУ АГРОСАЕНСЕС ВЕРТРИБСГЕЗЕЛЬ-ШАФТ М.Б.Х.', 'ДАУ АГРОСАЕНСЕС ВЕРТИБСГЕЗЕЛЬ-ШАФТ МБХ', 'Дау АгроСаенсес Вертрибсгезельшафт В.М.Х.', 'ДАУ АГРОСАЕНСЕС ВЕРТРИБСГЕЗЕЛЬШАФТ М.Б.Х.'], 'Дау АгроСаенсес Вертрибсгезельшафт МБХ', $reg);
      $reg = str_replace(['«Кингтай Кемикалз Ко.Лтд.»', 'Кингтай Кемикалз Ко., Лтд.'], 'Кингтай Кемикалз Ко. Лтд', $reg);
      $reg = str_replace(['«АГРОТЕХИНВЕСТ»', '«АгроТехИнвест»'], 'ООО «АГРОТЕХИНВЕСТ»', $reg);
      $reg = str_replace(['ООО «АДФ», ООО «Ярило»', 'ООО «Ярило», ООО «АФД»'], 'ООО «АФД», ООО «Ярило»', $reg);
      $reg = str_replace('«АЛЬФААГРОХИМ»', 'ООО «АЛЬФААГРОХИМ»', $reg);
      $reg = str_replace(['ИСК БИОСАЙЕНСИС Юроп Н.В.', 'ИСК Биосайнсис Юроп Н.В.'], 'ИСК Биосайенсис Юроп НВ', $reg);
      if ($reg == 'Паноксон, КЭ') $reg = 'ООО «ИНТЕР ГРУПП»';
      if ($reg == '«Байер Агрикалче БВ»') $reg = 'Байер Агрикалче БВ';
      if ($reg == '«КЕМИНОВА А/С»') $reg = 'КЕМИНОВА А/С';
      if ($reg == 'ООО «КЛЕВЕР ГРУПП»\'3/3') $reg = 'ООО «КЛЕВЕР ГРУПП»';
      if ($reg == 'ООО «КЛЕВЕР') $reg = 'ООО «КЛЕВЕР ГРУПП»';
      if ($reg == '«БАСФ СЕ»') $reg = 'БАСФ СЕ';
      if ($reg == 'Байер АГ') $reg = 'Байер КропСайенс АГ';
      if ($reg == 'ООО “СИНГЕНТА”') $reg = 'ООО «СИНГЕНТА»';
      if ($reg == 'ООО «ЭфЭмСи»”') $reg = 'ООО «ЭфЭмСи»';
      if ($reg == 'ФМСи Кемикал') $reg = 'ФМС Кемикал';
      if ($reg == 'ООО «ФАСКО+') $reg = 'ООО «ФАСКО+»';
      if ($reg == 'АЛЬБАУ ЮропСарл') $reg = 'Альбау Юроп Сарл';
      if ($reg == '«Агро-Кеми Кфт.»') $reg = 'Агро-Кеми Кфт';
      $reg = str_replace('МИКРООРГАНИЗ-МОВ', 'МИКРООРГАНИЗМОВ', $reg);
      $reg = str_replace([' ; ', '; ', ';'], ', ', $reg);
      $reg = str_replace(['&amp;'], '&', $reg);
      $reg = str_replace(['ЛТД.', 'лтд.', 'Лтд.'], 'Лтд', $reg);
      $reg = str_replace(['Кфт.', 'кфт.', 'КФТ.'], 'Кфт', $reg);
      $reg = str_replace('Лимитед', 'Лтд', $reg);
      $reg = str_replace('М.Б.Х.', 'МБХ', $reg);
      $reg = str_replace(['с.а.с.', 'с.а.с', 'С.А.С.'], 'САС', $reg);
      $reg = str_replace(['С.П.А.', 'С.П.А', 'С.п.А.'], 'СпА', $reg);
      $reg = str_replace(['Н.В.'], 'НВ', $reg);

      $node_wr->field_hp_registrant = $reg;
    }
    if (isset($record["Klass_opasnosti"]["item"]) && !is_array($record["Klass_opasnosti"]["item"]))
      $node_wr->field_hp_ko = $record["Klass_opasnosti"]["item"];
    if (isset($record["Srok_registracii_Po"]["item"]) && !is_array($record["Srok_registracii_Po"]["item"]))
      $node_wr->field_hp_srp = $record["Srok_registracii_Po"]["item"];
    if (isset($record["Nomer_gosudarstvennoy_registracii"]["item"]) && !is_array($record["Nomer_gosudarstvennoy_registracii"]["item"]))
      $node_wr->field_hp_ngr = $record["Nomer_gosudarstvennoy_registracii"]["item"];

    // задаём регламенты
    if ($record["fulldataset"]) {
      // json_encode некорректно обрабатывает одиночные подмассивы, корректируем
      if (!isset($record["fulldataset"]['item'][0])) {
        $arr = $record["fulldataset"]['item'];
        $record["fulldataset"]['item'] = [0 => $arr];
      }
      foreach ($record["fulldataset"]['item'] as $reglament) {
        $regl = entity_create('field_collection_item', ['field_name' => 'field_hp_reglamenty']);
        $regl->setHostEntity('node', $node);
        $regl_wr = entity_metadata_wrapper('field_collection_item', $regl);

        if (isset($reglament['Vrednyy_obekt_naznachenie']) && !is_array($reglament['Vrednyy_obekt_naznachenie']))
          $regl_wr->field_hpr_vo = drupal_substr($reglament['Vrednyy_obekt_naznachenie'], 0, 255);
        if (isset($reglament['Kultura_obrabatyvaemyy_obekt']) && !is_array($reglament['Kultura_obrabatyvaemyy_obekt']))
          $regl_wr->field_hpr_koo = $reglament['Kultura_obrabatyvaemyy_obekt'];
        if (isset($reglament['Sposob_i_vremya_obrabotki']) && !is_array($reglament['Sposob_i_vremya_obrabotki']))
          $regl_wr->field_hpr_svo = $reglament['Sposob_i_vremya_obrabotki'];
        if (isset($reglament['Srok_ozhidaniya_kratnost_obrabotok']) && !is_array($reglament['Srok_ozhidaniya_kratnost_obrabotok']))
          $regl_wr->field_hpr_soko = $reglament['Srok_ozhidaniya_kratnost_obrabotok'];
        if (isset($reglament['Sroki_vyhoda_dlya_ruchnyh_mehanizirovannyh_rabot']) && !is_array($reglament['Sroki_vyhoda_dlya_ruchnyh_mehanizirovannyh_rabot']))
          $regl_wr->field_hpr_svrmr = $reglament['Sroki_vyhoda_dlya_ruchnyh_mehanizirovannyh_rabot'];
        if (isset($reglament['Norma_primeneniya_preparata_lga_kgga_lt_kgt']) && !is_array($reglament['Norma_primeneniya_preparata_lga_kgga_lt_kgt']))
          $regl_wr->field_hpr_npp = $reglament['Norma_primeneniya_preparata_lga_kgga_lt_kgt'];
      }
    }
    $node_wr->save();

    watchdog('processing', 'Импортирован препарат ' . $record["Naimenovanie"]["item"]);
  } else {
    watchdog('processing', 'Препарат не импортирован.\n<pre>@var</pre>', ['@var' => print_r($record)], WATCHDOG_WARNING);
  }
}

/**
 * Получить последнюю версию данных с сайта Минсельхоза
 */
function sec_pesticides_mcx_get_new_info()
{
  $info = [];
  // получить сводку по версиям справочника
  $data = file_get_contents('http://opendata.mcx.ru/opendata/7708075454-pestitsidy/meta.xml');

  // найти ссылку на последнюю версию
  $url = '';
  $xml = new SimpleXMLElement($data);
  if ($result = $xml->xpath('/meta/data/dataversion[last()]/source')) {
    $url = $result[0]->__toString();
  }

  if ($url) {
    $filename = drupal_basename($url);
    $filepath = file_directory_temp() . '\mcx-data.zip';
    if (file_put_contents($filepath, fopen($url, 'r'))) {
      // распаковать zip
      $zip = new ZipArchive;
      if ($zip->open($filepath) === true) {
        $zip->extractTo(file_directory_temp());
        $zip->close();

        $data = file_get_contents(file_directory_temp() . '/' . $filename);
//        $data = file_get_contents('d:/' . $filename); // тесты
        // Convert xml string into an object
        $new = simplexml_load_string($data);
        $con = drupal_json_encode($new);
        $info = drupal_json_decode($con);
      }
    }
  }

  $info['filename'] = $filename;

  return $info;
}

/**
 * Implements hook_preprocess_node().
 */
function sec_pesticides_preprocess_node(&$vars)
{
  if ($vars['view_mode'] == 'full' && $vars['node']->type == 'pesticide') {

    // сформировать таблицу из регламентов
    $header = [
      'Культура (обрабатываемый объект)',
      'Вредный объект',
      'Норма применения препарата',
      'Способ и время обработки',
      'Срок ожидания (кратность обработок)',
      'Сроки выхода для ручных и механизированных работ',
    ];

    $rows = [];
    foreach($vars["field_hp_reglamenty"] as $reg) {
      $koo = $reg["field_collection"]->field_hpr_koo["und"][0]["value"] ?? '';
      $vo = $reg["field_collection"]->field_hpr_vo["und"][0]["value"] ?? '';
      $npp = $reg["field_collection"]->field_hpr_npp["und"][0]["value"] ?? '';
      $svo = $reg["field_collection"]->field_hpr_svo["und"][0]["value"] ?? '';
      $soko = $reg["field_collection"]->field_hpr_soko["und"][0]["value"] ?? '';
      $svrmr = $reg["field_collection"]->field_hpr_svrmr["und"][0]["value"] ?? '';
      $rows[] = [
        $koo,
        $vo,
        ['data' => $npp, 'align' => 'center'],
        $svo,
        ['data' => $soko, 'align' => 'center'],
        ['data' => $svrmr, 'align' => 'center'],
      ];
    }

    $vars['reglaments'] = theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No strings available.')));
  }
}


