<?php

/**
 * Implements hook_menu().
 */
function ext_product_menu()
{
    $items['source/qsearch'] = array(
        'page callback' => 'ext_product_qsearch_callback',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}


/**
 *
 */
function ext_product_form_field_collection_item_form_alter(&$form, &$form_state, $form_name) {

    // для Регламентов
    if ($form['field_name']['#value'] == 'field_pd_reglaments') {
        // ограничение списка Функций регламента
        $node = $form_state['field_collection_item']->hostEntity();
        $options = array();

        foreach($node->field_pd_category['und'] as $key => $item) {
          $tid = $item['tid'];

          switch ($tid) {
            case AGRO_CATEGORY_HERBICIDES_TID:
              $options[AGRO_CATEGORY_HERBICIDES_TID] = 'Гербицид';
              break;

            case AGRO_CATEGORY_DESICCANTS_TID:
              $options[AGRO_CATEGORY_DESICCANTS_TID] = 'Десикант';
              break;

            case AGRO_CATEGORY_FUNGICIDES_TID:
              $options[AGRO_CATEGORY_FUNGICIDES_TID] = 'Фунгицид';
              break;

            case AGRO_CATEGORY_DISINFECTANTS_TID:
              $options[AGRO_CATEGORY_DISINFECTANTS_TID] = 'Протравитель семян';
              break;

            case AGRO_CATEGORY_INSECTICIDES_TID:
              $options[AGRO_CATEGORY_INSECTICIDES_TID] = 'Инсектицид';
              break;

            case AGRO_CATEGORY_FERT_TID:
              $options[AGRO_CATEGORY_FERT_TID] = 'Удобрение';
              break;

            case AGRO_CATEGORY_MIX_TID:
              $options[AGRO_CATEGORY_HERBICIDES_TID] = 'Гербицид';
              $options[AGRO_CATEGORY_DESICCANTS_TID] = 'Десикант';
              $options[AGRO_CATEGORY_FUNGICIDES_TID] = 'Фунгицид';
              $options[AGRO_CATEGORY_DISINFECTANTS_TID] = 'Протравитель семян';
              $options[AGRO_CATEGORY_INSECTICIDES_TID] = 'Инсектицид';
              $options[AGRO_CATEGORY_FERT_TID] = 'Удобрение';
              break;
          }
        }
      $form['field_pd_r_function']['und']['#options'] = $options;
      $default_option = isset($form_state['field_collection_item']->field_pd_r_function['und'][0]) ? $form_state['field_collection_item']->field_pd_r_function['und'][0]['tid'] : array(key($options));
      $form['field_pd_r_function']['und']['#default_value'] = $default_option;

        // условные поля, зависят от Функции регламента
        $form['field_pd_a_weeds_groups']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    array('value' => '15'),
                    array('value' => '71534'),
                ),
            ),
        );
        $form['field_pd_a_pests_groups']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    array('value' => '17'),
                    array('value' => '71533'),
                ),
            ),
        );
        $form['field_pd_a_hobjects']['#states']
            = $form['field_pd_r_hobjects_comment']['#states']
            = $form['field_pd_r_wait_period']['#states']
            = $form['field_pd_r_multiplicator']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    '!value' => '93',
                ),
            ),
        );
    }
}

function ext_product_preprocess_node(&$vars)
{
    // для Крупной фасовки подключить js библиотеку для форматирования суммы и расчётов
    if ($vars['view_mode'] == 'full' && in_array($vars['node']->type, array('product_agro', 'product_mix', 'product_fert'))) {
        drupal_add_js(drupal_get_path('module', 'ext_product') . '/js/mini_calc.js');
        drupal_add_js(drupal_get_path('module', 'ext_product') . '/js/accounting.js');
    }

    // разложить title для агроминералов
    if ($vars['node']->type == 'product_fert') {
        $vars['header']['title'] = explode('|', $vars['node']->title)[0];
        $vars['header']['title_suffix'] = explode('|', $vars['node']->title)[1];
    }
}


/**
 * Вернуть полную информацию о продукте
 * @param $node
 * @return array с массивом препаратов заголовком, формуляцией и ингредиентами
 */
function get_product_info($node)
{
    $result = &drupal_static(__FUNCTION__);
    if (is_numeric($node) && isset($result[$node])) return $result[$node];
    if (isset($node->nid) && isset($result[$node->nid])) return $result[$node->nid];

    $lang = $GLOBALS['language']->language;

    $preparation_wr = entity_metadata_wrapper('node', $node)->language($lang);

    // составить массив препаратов
    // один препарат для химии, два препарата для смесей
    $preparations = [];
    if ($preparation_wr->getBundle() == 'product_mix') {
        foreach (['field_pd_mix_component1', 'field_pd_mix_component2'] as $key => $field) {
            $wrapper = $preparation_wr->{$field};
            $preparations[] = array(
                'order' => $key,
                'item' => $wrapper,
            );
        }
    } else {
        $preparations[] = array(
            'order' => 0,
            'item' => $preparation_wr,
        );
    }

    // формируем результирующий массив
    $preparation = array(
        'nid'    => $preparation_wr->getIdentifier(),
        'type'   => $preparation_wr->getBundle(),
        'status' => $preparation_wr->status->value(),
        'icon'   => isset($preparation_wr->field_icon) && $preparation_wr->field_icon->value() ? $preparation_wr->field_icon->file->url->value() : '',
        'url'    => url('node/' . $preparation_wr->getIdentifier()),
    );
    $titles_w_form = [];
    foreach($preparations as $item) {
        $preparation_wr = $item['item'];
        $id = $preparation_wr->getIdentifier();

        // препаративная форма
        $form_short = $form_full = '';
        if (isset($preparation_wr->field_pd_formulation) && $preparation_wr->field_pd_formulation->value()) {
            $form_short = $preparation_wr->field_pd_formulation->language($lang)->field_tax_short_name->value();
            $form_full = $preparation_wr->field_pd_formulation->language($lang)->name->value();
        }

        // единицы измерения препарата
        $unit_wr = $preparation_wr->field_pd_units->language($lang);

        // ДВ
        $ingredients = [];
        if (isset($preparation_wr->field_pd_active_ingredients) && $preparation_wr->field_pd_active_ingredients->value()) {
            foreach ($preparation_wr->field_pd_active_ingredients as $ingredient_wr) {
                if ($ingredient_wr->field_pd_ai_active_ingredient->value()) {
                    $ingredient_wr = $ingredient_wr->language($lang);
                    $ingr_name = ($lang == 'ru') ? $ingredient_wr->field_pd_ai_active_ingredient->name->value() : $ingredient_wr->field_pd_ai_active_ingredient->field_name_latin->value();
                    $ingr_dose = $ingredient_wr->field_pd_ai_concentration->value();
                    $cons_unit = t('l');
                    if (in_array($unit_wr->field_tax_short_name->value(), array('кг', 'г', 'kg', 'g'))) $cons_unit = t('kg');
                    if (in_array($unit_wr->field_tax_short_name->value(), array('л', 'мл', 'l', 'ml'))) $cons_unit = t('l');
                    $ingredients[] = $ingr_name . ', ' . $ingr_dose . ' ' . t('g') . '/' . $cons_unit;
                }
            }
        }

        // определить по категории ед. изм. применения препарата (га или т)
        // и занести в массив, т.к. неизвестно, какие из них будут использованы
        $unit_field = [];
        foreach ($preparation_wr->field_pd_category as $cat_wrapper) {
            $tid = $cat_wrapper->getIdentifier();
            $unit_field[$tid] = $tid == AGRO_CATEGORY_DISINFECTANTS_TID ? t(AGRO_SEED_MEASURE) : t(AGRO_FIELD_MEASURE);
        }

        // фото
        $photo_url = file_create_url($preparation_wr->field_product[0]->field_p_images[0]->value() ? $preparation_wr->field_product[0]->field_p_images[0]->value()['uri'] : '');

        // категория и цвет
        $cats = [];
        if ($preparation_wr->field_pd_category->value()) {
            foreach($preparation_wr->field_pd_category->getIterator() as $category_wr) {
                $cats[$category_wr->tid->value()] = [
                    'tid' => $category_wr->getIdentifier(),
                    'name' => $category_wr->label(),
                    'color' => $category_wr->field_color->value(),
                ];
            }
        }

        $preparation['items'][$id] = array(
            'id'            => $id,
            'title'         => $preparation_wr->language($lang)->title_field->value(),
            'description'   => strip_tags($preparation_wr->body->summary->value()),
            'url'           => url('node/' . $id),
            'form_short'    => $form_short,
            'form_full'     => $form_full,
            'ingredients'   => $ingredients,
            'price'         => $preparation_wr->field_pd_price_per_unit->amount->value()/100,
            'unit'          => $unit_wr->name->value(),
            'unit_short'    => $unit_wr->field_tax_short_name->value(),
            'unit_field'    => $unit_field,
            'photo_url'     => $photo_url,
            // порядковый номер в списке препаратов баковой смеси (БС)
            // используется для связи с нормой расхода в регламенте БС
            'order'         => $item['order'],
            'categories'    => $cats
        );
        $titles_w_form[] = $form_short ? $preparation_wr->title_field->value() . ', ' . $form_short : $preparation_wr->title_field->value();
    }
    $preparation['title'] = implode(' + ', $titles_w_form);

    $result[$preparation['nid']] = $preparation;

    return $preparation;
}


/**
 * --------------------------------- Сделать текст под заголовками h4 сворачиваемым (в поле body)-----------------------
 * Implements hook_node_view_alter().
 */
function ext_product_node_view_alter(&$build) {
    if ($build['#view_mode'] == 'full'
        && in_array($build['#bundle'], array('product_agro', 'product_fert', 'product_mix', 'product_chem'))
        && isset($build['body'][0]['#markup'])) {

        $ba = explode('<h4>', $build['body'][0]['#markup']);
        $expanded = true;
        $body = array_shift($ba);
        foreach ($ba as $b_key => $b_item) {
            if ($b_item) {
                $ba2 = explode('</h4>', $b_item);
                if (!empty($ba2[0]) && !empty($ba2[1])) {
                    $body .= '<h4 data-toggle="collapse" data-target="#collapse-' . $b_key . '" aria-expanded="' . $expanded . '" aria-controls="collapse-' . $b_key . '"' . ($expanded ? '' : ' class="collapsed"') . '>' . str_replace(':', '', $ba2[0]) . '<i class="fa fa-caret-down" aria-hidden="true"></i></h4>';
                    $body .= '<div class="collapse' . ($expanded ? ' in' : '') . '" id="collapse-' . $b_key . '">' . trim($ba2[1]) . '</div>';
                    $expanded = false;
                }
            }
        }
        if ($body) $build['body'][0]['#markup'] = $body;
    }
}


/**
 * --------------------------------- Вернуть полный список препаратов для функции быстрого поиска в Приложении ---------
 */
function ext_product_qsearch_callback($category_tid = null)
{
    $items = [];

    $query = db_select('node', 'n');
    $query->condition('n.type', ['product_agro', 'product_fert'], 'IN');
    $query->condition('n.status', 1);
    $query->addField('n', 'nid');
    $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
    $query->condition('tf.language', $GLOBALS['language']->language);
    $query->orderby('tf.title_field_value', 'ASC');

    if ($category_tid) {
        $query->innerJoin('field_data_field_pd_category', 'pc', 'n.nid = pc.entity_id');
        $query->condition('pc.field_pd_category_tid', $category_tid);
    }
    if ($result = $query->execute()->fetchAll()) {
        foreach($result as $prep) {
            $prep_arr = get_product_info($prep->nid);
            if (in_array($prep_arr['type'], ['product_agro', 'product_fert'])) {
                $prep_item = $prep_arr['items'][$prep_arr['nid']];
                $item = [
                    'nid' => $prep_item['id'],
                    'title' => $prep_item['title'] . ($prep_item['form_short'] ? ', ' . $prep_item['form_short'] : ''),
                    'description' => $prep_item['description'],
                    'ingredients' => implode(' + ', $prep_item['ingredients']),
                    'photo' => image_style_url('mobile_teaser_product', $prep_item['photo_url']),
                    'icon' => $prep_arr['icon'],
                ];
                foreach($prep_item['categories'] as $tid => $cat) {
                    if (empty($items[$tid]) && (!$category_tid || $tid == $category_tid)) {
                        $items[$tid] = [
                            'tid' => $tid,
                            'name' => $cat['name'],
                            'color' => $cat['color'],
                            'items' => []
                        ];
                    }
                    // если задана категория, список только для неё
                    if (!$category_tid || $tid == $category_tid) {
                        $items[$tid]['items'][] = $item;
                    }
                }
            }
        }
    }

    drupal_json_output(['preparations' => $items]);
    drupal_exit();
}
