<?php



/**
 * Implementation of hook_module_implements_alter().
 */
function ext_product_module_implements_alter(&$implementations, $hook)
{
  //  Если хук - hook_form_alter, то переносим нашу реализацию этого хука в конец очереди
  if ($hook == 'form_alter' && isset($implementations['ext_product'])) {
    $group = $implementations['ext_product'];
    unset($implementations['ext_product']);
    $implementations['ext_product'] = $group;
  }
}

function ext_product_form_alter(&$form, &$form_state, $form_id)
{

  switch ($form_id) {
    case 'product_agro_node_form':
    case 'product_mix_node_form':
    case 'product_fert_node_form':
    case 'product_chem_node_form':
      // из за включения мультиязычности поля body все тексты остались в UND, а на редактирование выводится RU
      // скопировать из UND в RU, если там пусто
      if (empty($form['body']['ru'][0]['#default_value']) && !empty($form['body']['ru'][0]['#entity']->body['und'][0]['value'])) {
        $form['body']['ru'][0]['#default_value'] = $form['body']['ru'][0]['#entity']->body['und'][0]['value'];
      }
      if (empty($form['body']['ru'][0]['summary']['#default_value']) && !empty($form['body']['ru'][0]['#entity']->body['und'][0]['summary'])) {
        $form['body']['ru'][0]['summary']['#default_value'] = $form['body']['ru'][0]['#entity']->body['und'][0]['summary'];
      }

      // отключить возможность ввода цены для варианта товара
      // цена расчитывается автоматически от цены за шт.
      if (isset($form['field_product']['und']['entities'])) {
        foreach ($form['field_product']['und']['entities'] as $key_e => $entity) {
          if (is_numeric($key_e) && !empty($entity['form']['commerce_price'])) {
            $form['field_product']['und']['entities'][$key_e]['form']['commerce_price']['#access'] = false;
          }
        }
      }
      if (!empty($form['field_product']['und']['form']['commerce_price'])) {
        $form['field_product']['und']['form']['commerce_price']['#access'] = false;
        $form['field_product']['und']['form']['commerce_price']['und'][0]['amount']['#type'] = 'value';
        $form['field_product']['und']['form']['commerce_price']['und'][0]['amount']['#default_value'] = '0';
        $form['field_product']['und']['form']['commerce_price']['und'][0]['currency_code']['#type'] = 'value';
        $form['field_product']['und']['form']['commerce_price']['und'][0]['currency_code']['#default_value'] = 'RUB';
      }
      // пересчитать цены вариантов товаров в админке при редактировании товара
      $form['#submit'][] = 'ext_product_product_calc_price';
      break;
  }
}

/**
 *
 */
function ext_product_form_field_collection_item_form_alter(&$form, &$form_state, $form_name)
{
    // для Регламентов
    if ($form['field_name']['#value'] == 'field_pd_reglaments') {
        // ограничение списка Функций регламента
        $node = $form_state['field_collection_item']->hostEntity();
        $options = array();

        foreach($node->field_pd_category['und'] as $key => $item) {
          $tid = $item['tid'];

          switch ($tid) {
            case AGRO_CATEGORY_HERBICIDES_TID:
              $options[AGRO_CATEGORY_HERBICIDES_TID] = 'Гербицид';
              break;

            case AGRO_CATEGORY_DESICCANTS_TID:
              $options[AGRO_CATEGORY_DESICCANTS_TID] = 'Десикант';
              break;

            case AGRO_CATEGORY_FUNGICIDES_TID:
              $options[AGRO_CATEGORY_FUNGICIDES_TID] = 'Фунгицид';
              break;

            case AGRO_CATEGORY_DISINFECTANTS_TID:
              $options[AGRO_CATEGORY_DISINFECTANTS_TID] = 'Протравитель семян';
              break;

            case AGRO_CATEGORY_INSECTICIDES_TID:
              $options[AGRO_CATEGORY_INSECTICIDES_TID] = 'Инсектицид';
              break;

            case AGRO_CATEGORY_FERT_TID:
              $options[AGRO_CATEGORY_FERT_TID] = 'Удобрение';
              break;

            case AGRO_CATEGORY_MIX_TID:
              $options[AGRO_CATEGORY_HERBICIDES_TID] = 'Гербицид';
              $options[AGRO_CATEGORY_DESICCANTS_TID] = 'Десикант';
              $options[AGRO_CATEGORY_FUNGICIDES_TID] = 'Фунгицид';
              $options[AGRO_CATEGORY_DISINFECTANTS_TID] = 'Протравитель семян';
              $options[AGRO_CATEGORY_INSECTICIDES_TID] = 'Инсектицид';
              $options[AGRO_CATEGORY_FERT_TID] = 'Удобрение';
              break;
          }
        }
      $form['field_pd_r_function']['und']['#options'] = $options;
      $default_option = isset($form_state['field_collection_item']->field_pd_r_function['und'][0]) ? $form_state['field_collection_item']->field_pd_r_function['und'][0]['tid'] : array(key($options));
      $form['field_pd_r_function']['und']['#default_value'] = $default_option;

        // условные поля, зависят от Функции регламента
        $form['field_pd_a_weeds_groups']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    array('value' => '15'),
                    array('value' => '71534'),
                ),
            ),
        );
        $form['field_pd_a_pests_groups']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    array('value' => '17'),
                    array('value' => '71533'),
                ),
            ),
        );
        $form['field_pd_a_hobjects']['#states']
            = $form['field_pd_r_hobjects_comment']['#states']
            = $form['field_pd_r_wait_period']['#states']
            = $form['field_pd_r_multiplicator']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    '!value' => '93',
                ),
            ),
        );
    }
}

function ext_product_preprocess_node(&$vars)
{
    // для Крупной фасовки подключить js библиотеку для форматирования суммы и расчётов
    if ($vars['view_mode'] == 'full' && in_array($vars['node']->type, array('product_agro', 'product_mix', 'product_fert'))) {
        drupal_add_js(drupal_get_path('module', 'ext_product') . '/js/mini_calc.js');
        drupal_add_js(drupal_get_path('module', 'ext_product') . '/js/accounting.js');
    }

    // разложить title для агроминералов
    if ($vars['node']->type == 'product_fert') {
        $vars['header']['title'] = explode('|', $vars['node']->title)[0];
        $vars['header']['title_suffix'] = explode('|', $vars['node']->title)[1];
    }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 * форма добавления в корзину
 */
function ext_product_form_commerce_cart_add_to_cart_form_alter(&$form, $form_state)
{
  $product_id = empty($form["product_id"]["#value"]) ? $form["product_id"]["#default_value"] : $form["product_id"]["#value"];
  $nid = _get_product_display_by_product_id($product_id, true);
  $product_info = ext_product_product_get_info($nid);

  // i18n не перевёл taxonomy_term_reference
  // извлекаем переведенное значение поля Упаковка вручную
  if (isset($form['attributes']['field_p_tare']['#options'])) {
    foreach ($form['attributes']['field_p_tare']['#options'] as $tid => $title) {
      $term_wr = entity_metadata_wrapper('taxonomy_term', $tid);
      $form['attributes']['field_p_tare']['#options'][$tid] = $term_wr->language($GLOBALS['language']->language)->name->value();
    }
  }

  // выводить элементы в одну строку с метками
  $form['#attributes']['class'][] = 'form-horizontal';
  $form['submit']['#prefix'] = '<div class="form-item form-action-wrapper">';
  $form['submit']['#suffix'] = '</div>';
  $form['submit']['#attributes']['onclick'][] = "yaCounter11541151.reachGoal('add_to_cart'); return true;";
  $form['submit']['#attributes']['class'][] = 'btn-primary';
  $form['submit']['#attributes']['class'][] = 'btn-wide-full';

  // если Out_of_stock, сделать Добавление в корзину неактивным
  if ($product_info["stock"]) {
    if (in_array($product_id, ext_product_get_order_product_ids($GLOBALS['user']->uid))) {
      $form['submit']['#value'] = 'Добавлено';
    } else {
      $form['submit']['#value'] = 'В корзину';
    }
  } else {
    $form['submit']['#disabled'] = true;
    $form['submit']['#value'] = t('Out of stock');
  }

  // сферу и таблетку перенаправить на страду через кнопку Купить
  if (isset($product_info["items"][$product_info["nid"]]["categories"]['72785'])) {
    $form['submit']['#value'] = t('Buy');
    array_unshift($form['#submit'], 'ext_product_cart_add_to_cart_form_submit');
    foreach($form['submit']['#attributes']['class'] as $index => $class) {
      if ($class == 'use-ajax-submit') unset($form['submit']['#attributes']['class'][$index]);
    }
  }
}

function ext_product_cart_add_to_cart_form_submit($form, $form_state)
{
  // если это сфера или таб, перейти на сайт страды
  if (isset($form_state['context']['entity_id'])) {
    if ($form_state['context']['entity_id'] == 8505) drupal_goto('https://joy-magazin.ru/catalog/ot-pozhara/avtonomnoe-ustroystvo-pozharotusheniya-finfire-sfera-1-shar/');
    if ($form_state['context']['entity_id'] == 8770) drupal_goto('https://joy-magazin.ru/catalog/ot-pozhara/avtonomnoe-ustroystvo-pozharotusheniya-finfire-tab-1-sht/');
  }
}

/**
 * Вернуть полную информацию о продукте
 * @param $node
 * @return array с массивом препаратов заголовком, формуляцией и ингредиентами
 */
function ext_product_product_get_info($node)
{
  $result = &drupal_static(__FUNCTION__);
  if (is_numeric($node) && isset($result[$node])) return $result[$node];
  if (isset($node->nid) && isset($result[$node->nid])) return $result[$node->nid];

  $lang = $GLOBALS['language']->language;

  $product_wr = entity_metadata_wrapper('node', $node)->language($lang);

  // составить массив препаратов
  // один препарат для химии, два препарата для смесей
  $preparations = [];
  if ($product_wr->getBundle() == 'product_mix') {
    foreach (['field_pd_mix_component1', 'field_pd_mix_component2'] as $key => $field) {
      $wrapper = $product_wr->{$field};
      $preparations[] = array(
        'order' => $key,
        'item' => $wrapper,
      );
    }
  } else {
    $preparations[] = array(
      'order' => 0,
      'item' => $product_wr,
    );
  }

  // формируем результирующий массив
  $preparation = array(
    'nid'    => $product_wr->getIdentifier(),
    'type'   => $product_wr->getBundle(),
    'status' => $product_wr->status->value(),
    'icon'   => isset($product_wr->field_icon) && $product_wr->field_icon->value() ? $product_wr->field_icon->file->url->value() : '',
    'url'    => url('node/' . $product_wr->getIdentifier()),
  );
  $titles_w_form = [];
  foreach($preparations as $item) {
    $prep_item_wr = $item['item'];
    $id = $prep_item_wr->getIdentifier();

    // препаративная форма
    $form_short = $form_full = '';
    if (isset($prep_item_wr->field_pd_formulation) && $prep_item_wr->field_pd_formulation->value()) {
      $form_short = $prep_item_wr->field_pd_formulation->language($lang)->field_tax_short_name->value();
      $form_full = $prep_item_wr->field_pd_formulation->language($lang)->name->value();
    }

    // единицы измерения препарата
    $unit_wr = $prep_item_wr->field_pd_units->language($lang);

    // ДВ
    $ingredients = [];
    if (isset($prep_item_wr->field_pd_active_ingredients) && $prep_item_wr->field_pd_active_ingredients->value()) {
      foreach ($prep_item_wr->field_pd_active_ingredients as $ingredient_wr) {
        if ($ingredient_wr->field_pd_ai_active_ingredient->value()) {
          $ingredient_wr = $ingredient_wr->language($lang);
          $ingr_name = ($lang == 'ru') ? $ingredient_wr->field_pd_ai_active_ingredient->label() : $ingredient_wr->field_pd_ai_active_ingredient->field_name_latin->value();
          $ingr_dose = $ingredient_wr->field_pd_ai_concentration->value();
          $cons_unit = t('l');
          if (in_array($unit_wr->field_tax_short_name->value(), array('кг', 'г', 'kg', 'g'))) $cons_unit = t('kg');
          if (in_array($unit_wr->field_tax_short_name->value(), array('л', 'мл', 'l', 'ml'))) $cons_unit = t('l');
          $text = $ingr_name . ', ' . $ingr_dose . ' ' . t('g') . '/' . $cons_unit;
          $ingredients[] = [
            'tid' => $ingredient_wr->field_pd_ai_active_ingredient->getIdentifier(),
            'name' => $ingr_name,
            'full' => $text
          ];
          $in_text[] = $text;
        }
      }
    }
    $ingredients_text = implode(' + ', $in_text);

    // определить по категории ед. изм. применения препарата (га или т)
    // и занести в массив, т.к. неизвестно, какие из них будут использованы
    $unit_field = [];
    foreach ($prep_item_wr->field_pd_category as $cat_wrapper) {
      $tid = $cat_wrapper->getIdentifier();
      $unit_field[$tid] = $tid == AGRO_CATEGORY_DISINFECTANTS_TID ? t(AGRO_SEED_MEASURE) : t(AGRO_FIELD_MEASURE);
    }

    // фото
    $photo_uri = 'public://default_images/no_image.jpg';
    if ($photo = $prep_item_wr->field_product[0]->field_p_images[0]->value()) {
      $photo_uri = $photo['uri'];
    }
    $photo_url = file_create_url($photo_uri);
    $photo_medium = image_style_url('medium', $photo_uri);

    // наличие (field_pd_out_of_stock есть не у всех типов)
    $stock = isset($prep_item_wr->value()->field_pd_out_of_stock) ? !$prep_item_wr->field_pd_out_of_stock->value() : $prep_item_wr->status->value();

    $product_0_wr = $prep_item_wr->field_product[0];
    // тара
    $tare = $product_0_wr->field_p_tare->name->value();

    // цена От
    $price_in_tare_amount = $product_0_wr->commerce_price->amount->value();
    $price_in_tare_formatted = str_replace(',00', '', commerce_currency_format($price_in_tare_amount, 'RUB'));

    // категория и цвет
    $cats = [];
    if ($prep_item_wr->field_pd_category->value()) {
      foreach($prep_item_wr->field_pd_category->getIterator() as $category_wr) {
        $cats[$category_wr->tid->value()] = [
          'tid' => $category_wr->getIdentifier(),
          'name' => $category_wr->label(),
          'color' => $category_wr->field_color->value(),
        ];
      }
    }

    $preparation['items'][$id] = array(
      'id'            => $id,
      'title'         => $prep_item_wr->language($lang)->title_field->value(),
      'description'   => strip_tags($prep_item_wr->body->summary->value()),
      'url'           => url('node/' . $id),
      'form_short'    => $form_short,
      'form_full'     => $form_full,
      'ingredients'   => $ingredients,
      'ingredients_text' => $ingredients_text,
      'price'         => $prep_item_wr->field_pd_price_per_unit->amount->value()/100,
      'unit'          => $unit_wr->name->value(),
      'unit_short'    => $unit_wr->field_tax_short_name->value(),
      'unit_field'    => $unit_field,
      'photo_uri'     => $photo_uri,
      'photo_url'     => $photo_url,
      'photo_medium'  => $photo_medium,
      // порядковый номер в списке препаратов баковой смеси (БС)
      // используется для связи с нормой расхода в регламенте БС
      'order'         => $item['order'],
      'categories'    => $cats,
      'stock'         => $stock,
      'tare'          => $tare,
      'price_in_tare_amount'  => $price_in_tare_amount,
      'price_in_tare_formatted'  => $price_in_tare_formatted,
    );
    $titles_w_form[] = $form_short ? $prep_item_wr->title_field->value() . ', ' . $form_short : $prep_item_wr->title_field->value();
  }
  $preparation['title'] = implode(' + ', $titles_w_form);
  if (in_array($preparation['type'], ['product_agro', 'product_fert'])) {
    $preparation['stock'] = $preparation['items'][$preparation['nid']]['stock'];
  }

  $result[$preparation['nid']] = $preparation;

  return $preparation;
}


/**
 * Получить id ноды или ноду по id привязанного commerce product
 */
function ext_product_get_product_display_by_product_id($product_id, $load_node = false)
{
  if ($product_id) {
    $product_display_nid = db_select('field_data_field_product', 'f')
      ->fields('f', array('entity_id'))
      ->condition('f.field_product_product_id', $product_id)
      ->range(0, 1)
      ->execute()
      ->fetchField();
    return $load_node ? node_load($product_display_nid) : $product_display_nid;
  }
  return false;
}

/**
 * --------------------------------- Сделать текст под заголовками h4 сворачиваемым (в поле body)-----------------------
 * Implements hook_node_view_alter().
 */
function ext_product_node_view_alter(&$build) {
    if ($build['#view_mode'] == 'full'
        && in_array($build['#bundle'], array('product_agro', 'product_fert', 'product_mix', 'product_chem'))
        && isset($build['body'][0]['#markup'])) {

        $ba = explode('<h4>', $build['body'][0]['#markup']);
        $expanded = true;
        $body = array_shift($ba);
        foreach ($ba as $b_key => $b_item) {
            if ($b_item) {
                $ba2 = explode('</h4>', $b_item);
                if (!empty($ba2[0]) && !empty($ba2[1])) {
                    $body .= '<h4 data-toggle="collapse" data-target="#collapse-' . $b_key . '" aria-expanded="' . $expanded . '" aria-controls="collapse-' . $b_key . '"' . ($expanded ? '' : ' class="collapsed"') . '>' . str_replace(':', '', $ba2[0]) . '<i class="fa fa-caret-down" aria-hidden="true"></i></h4>';
                    $body .= '<div class="collapse' . ($expanded ? ' in' : '') . '" id="collapse-' . $b_key . '">' . trim($ba2[1]) . '</div>';
                    $expanded = false;
                }
            }
        }
        if ($body) $build['body'][0]['#markup'] = $body;
    }
}


/**
 * Возвращает список product id помещенных в корзину пользователя
 * @param $uid
 * @return array|mixed
 */
function ext_product_get_order_product_ids($uid)
{
  $pids = &drupal_static(__FUNCTION__);

  // заполнить массив id товаров в корзине
  if (!$pids) {
    $pids = array();

    if ($order = commerce_cart_order_load($GLOBALS['user']->uid)) {
      $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
      foreach ($order_wrapper->commerce_line_items as $delta => $line_item_wrapper) {
        if (in_array($line_item_wrapper->type->value(), commerce_product_line_item_types())) {
          $pids[] = $line_item_wrapper->commerce_product->product_id->value();
        }
      }
    }
  }
  return $pids;
}

/**
 * пересчитать цены вариантов товаров в админке при редактировании дисплее товара, если цена за единицу изменилась
 */
function ext_product_product_calc_price($form, &$form_state)
{
  if (isset($form['field_pd_price_per_unit'])) {
    $price = (float) $form_state['values']['field_pd_price_per_unit']['und'][0]['amount'];

    foreach ($form_state['inline_entity_form'] as $inline_form) {
      foreach ($inline_form['entities'] as $key => &$line_item) {
        $qty = (float) $line_item['entity']->field_p_qty['und'][0]['value'];
        $line_item['entity']->commerce_price['und'][0]['amount'] = $qty * $price;

        $product_id = $line_item['entity']->product_id;
        // если товар уже сохранён и имеет ID, загрузить и внести изменения
        if ($product_id) {
          $product = commerce_product_load($product_id);
          $product->commerce_price['und'][0]['amount'] = $qty * $price;
          commerce_product_save($product);
        }
      }
    }
  }
}
