<?php

/**
 * Implements hook_menu().
 */
function ext_product_menu() {
  global $user;
    $items['product/rating/%/add'] = array(
        'page callback' => 'ext_product_rating_add_callback',
        'page arguments' => array(2),
        'access callback' => $user->uid,
//        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['product/rating/%/get-list'] = array(
        'page callback' => 'ext_product_rating_get_list_callback',
        'page arguments' => array(2, 'show'),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['product/rating/%/hide-list'] = array(
        'page callback' => 'ext_product_rating_get_list_callback',
        'page arguments' => array(2, 'hide'),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['source/qsearch'] = array(
        'page callback' => 'ext_product_qsearch_callback',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * callback вызова окна адресной книги в оформлении заказа
 */
function ext_product_rating_add_callback($pid, $mode = NULL) {
    if ($mode == 'ajax') {
        ctools_include('modal');
        $form_state = array('ajax' => TRUE, 'title' => t('Preparation rating'));
        $form_state['build_info']['args'] = array('pid' => $pid);
        $output = ctools_modal_form_wrapper('ext_product_rating_add_form', $form_state);
        if (!empty($form_state['ajax_commands'])) $output = $form_state['ajax_commands'];
        print ajax_render($output);
        drupal_exit();
    }
    else return drupal_get_form('ext_product_rating_add_form', $pid);
}
/**
 * форма адресной книги
 */
function ext_product_rating_add_form($form, &$form_state, $pid) {
    global $user;

    ctools_include('modal');

    $form_state['pid'] = $pid;

    // проверка наличия оценки текущим юзером текущего препарата
    $rid = $stars = 0; $text = '';
    $query = db_select('field_data_field_pd_review', 'fr');
    $query->condition('fr.entity_id', $pid);
    $query->innerJoin('field_data_field_pd_rv_user', 'fru', 'fru.entity_id = fr.field_pd_review_value AND fru.field_pd_rv_user_value = ' . $user->uid);
    $query->fields('fr', array('field_pd_review_value'));
    $query->innerJoin('field_data_field_pd_rv_stars', 'frs', 'frs.entity_id = fr.field_pd_review_value');
    $query->fields('frs', array('field_pd_rv_stars_value'));
    $query->innerJoin('field_data_field_pd_rv_text', 'frt', 'frt.entity_id = fr.field_pd_review_value');
    $query->fields('frt', array('field_pd_rv_text_value'));
    if ($review = $query->execute()->fetchObject()) {
        $stars = $review->field_pd_rv_stars_value;
        $text = $review->field_pd_rv_text_value;
        $rid = $review->field_pd_review_value;
    }
    $form_state['rid'] = $rid;

    $form = array(
        '#prefix' => '<div id="rating-form-wrapper">',
        '#attributes' => array('class' => array('custom-form')),
        '#suffix' => '</div>',
        'form-actions' => array('#type' => 'container', '#attributes' => array('class' => array('form-actions')), '#weight' => '100'),
    );

    $form['content'] = array(
        '#type' => 'container',
        '#attributes' => array(
            'class' => array('fields-container'),
        ),
    );

    // если открытие формы
    if (empty($form_state['triggering_element'])) {
        $form['content']['stars'] = array(
            '#markup' => '<div class="set-rating">
            <div class="label">Поставьте оценку</div>
            <input type="radio" id="star5" name="rating" value="5"' . ($stars == 5 ? ' checked="checked"' : '') . ' /><label for="star5" title="Отлично!">5 звёзд</label>
            <input type="radio" id="star4" name="rating" value="4"' . ($stars == 4 ? ' checked="checked"' : '') . ' /><label for="star4" title="Хорошо">4 звезды</label>
            <input type="radio" id="star3" name="rating" value="3"' . ($stars == 3 ? ' checked="checked"' : '') . ' /><label for="star3" title="Удовлетворительно">3 звезды</label>
            <input type="radio" id="star2" name="rating" value="2"' . ($stars == 2 ? ' checked="checked"' : '') . ' /><label for="star2" title="Плохо">2 звезды</label>
            <input type="radio" id="star1" name="rating" value="1"' . ($stars == 1 ? ' checked="checked"' : '') . ' /><label for="star1" title="Очень плохо">1 звезда</label>
        </div>
        ',
        );
        $form['content']['text'] = array(
            '#type' => 'textarea',
            '#title' => 'Напишите несколько слов',
            '#cols' => 50,
            '#rows' => 3,
            '#default_value' => $text,
        );

        $form['form-actions']['st_cancel'] = array(
            '#type' => 'button',
            '#name' => 'cancel',
            '#value' => t('Cancel'),
            '#limit_validation_errors' => array(),
            '#attributes' => array(
                'class' => array('button-link'),
            ),
            '#ajax' => array(
                'callback' => 'ext_product_rating_add_form_ajax',
                'wrapper' => 'rating-form-wrapper',
            ),
        );
        $form['form-actions']['st_submit'] = array(
            '#type' => 'submit',
            '#name' => 'submit',
            '#value' => t('Отправить'),
            '#ajax' => array(
                'callback' => 'ext_product_rating_add_form_ajax',
                'wrapper' => 'rating-form-wrapper',
            ),
        );
    }
    // если нажат submit
    else {
        if ($form_state['triggering_element']['#name'] == 'submit') {
            $form['content']['text'] = array(
                //'#markup' => ($form_state['reward_added'] ? 'Спасибо! Ваш отзыв принят.<br />Вам начислено ' . $form_state['reward_added'] . ' баллов.' : 'Спасибо! Изменения приняты.'),
                '#markup' => 'Спасибо! Ваш отзыв принят.',
            );
            $form['form-actions']['st_cancel'] = array(
                '#type' => 'button',
                '#name' => 'cancel',
                '#value' => t('Close'),
                '#limit_validation_errors' => array(),
                '#ajax' => array(
                    'callback' => 'ext_product_rating_add_form_ajax',
                    'wrapper' => 'rating-form-wrapper',
                ),
            );
        }
    }

    return $form;
}

/**
 * validate формы
 */
function ext_product_rating_add_form_validate($form, &$form_state) {
    if (empty($form_state['input']['rating'])) {
        form_set_error('rating', 'Необходимо задать оценку');
    } else {
        $form_state['values']['rating'] = $form_state['input']['rating'];
    }

}

/**
 * submit формы
 */
function ext_product_rating_add_form_submit($form, &$form_state) {
    global $user;

    // сохранить оценку
    $new_rating = false;
    $node = node_load($form_state['pid']);
    if (empty($form_state['rid'])) {
        $fc_item = entity_create('field_collection_item', array('field_name' => 'field_pd_review'));
        $fc_item_wrapper = entity_metadata_wrapper('field_collection_item', $fc_item);
        $fc_item->setHostEntity('node', $node);
        $new_rating = true;
    } else {
        $fc_item_wrapper = entity_metadata_wrapper('field_collection_item', $form_state['rid']);
    }

    $fc_item_wrapper->field_pd_rv_stars = $form_state['values']['rating'];
    $fc_item_wrapper->field_pd_rv_text = $form_state['values']['text'];
    $fc_item_wrapper->field_pd_rv_user = $user->uid;
    $fc_item_wrapper->field_date = time();
    $fc_item_wrapper->save(TRUE);

    // начислить баллы за Отзыв, если он новый
    if ($new_rating) {
        //$form_state['reward_added'] = person_activity_reward($user, PREPARATION_REVIEW, array('id' => $node->title));
    }

    $form_state['rebuild'] = TRUE;
}
/**
 * ajax submit формы
 * return $array - набор команд для вывода результата на форму
 */
function ext_product_rating_add_form_ajax($form, &$form_state) {
    // ajax команды можно вернуть только здесь, type=ajax при подготовке формы заменяется type=form
    if (!empty($form_state['triggering_element'])) {
        if ($form_state['triggering_element']['#name'] == 'cancel') {

            // посчитать рейтинг и количестко отзывов
            $rating_count = $rating_avg = $rating_sum = 0;
            $query = db_select('field_data_field_pd_review', 'fr');
            $query->condition('fr.entity_id', $form_state['pid']);
            $query->innerJoin('field_data_field_pd_rv_stars', 'frs', 'frs.entity_id = fr.field_pd_review_value');
            $query->fields('frs', array('field_pd_rv_stars_value'));
            if ($result = $query->execute()->fetchAll()) {
                foreach($result as $rating) {
                    $rating_count++;
                    $rating_sum += $rating->field_pd_rv_stars_value;
                }
                $rating_avg = $rating_sum/$rating_count;
            }
            $commands[] = ajax_command_invoke('.r-replace', 'html', array(theme('product_rating', array('rating' => $rating_avg)) . ' (' . $rating_count . ')'));

            $commands[] = ctools_modal_command_dismiss();
            $form = array('#type' => 'ajax', '#commands' => $commands);
        }
    }

    return $form;
}

function ext_product_form_field_collection_item_form_alter(&$form, &$form_state, $form_name) {

    // для Регламентов
    if ($form['field_name']['#value'] == 'field_pd_reglaments') {
        // ограничение списка Функций регламента
        $node = $form_state['field_collection_item']->hostEntity();
        $options = array();

        foreach($node->field_pd_category['und'] as $key => $item) {
          $tid = $item['tid'];

          switch ($tid) {
            case AGRO_CATEGORY_HERBICIDES_TID:
              $options[AGRO_CATEGORY_HERBICIDES_TID] = 'Гербицид';
              break;

            case AGRO_CATEGORY_DESICCANTS_TID:
              $options[AGRO_CATEGORY_DESICCANTS_TID] = 'Десикант';
              break;

            case AGRO_CATEGORY_FUNGICIDES_TID:
              $options[AGRO_CATEGORY_FUNGICIDES_TID] = 'Фунгицид';
              break;

            case AGRO_CATEGORY_DISINFECTANTS_TID:
              $options[AGRO_CATEGORY_DISINFECTANTS_TID] = 'Протравитель семян';
              break;

            case AGRO_CATEGORY_INSECTICIDES_TID:
              $options[AGRO_CATEGORY_INSECTICIDES_TID] = 'Инсектицид';
              break;

            case AGRO_CATEGORY_FERT_TID:
              $options[AGRO_CATEGORY_FERT_TID] = 'Удобрение';
              break;

            case AGRO_CATEGORY_MIX_TID:
              $options[AGRO_CATEGORY_HERBICIDES_TID] = 'Гербицид';
              $options[AGRO_CATEGORY_DESICCANTS_TID] = 'Десикант';
              $options[AGRO_CATEGORY_FUNGICIDES_TID] = 'Фунгицид';
              $options[AGRO_CATEGORY_DISINFECTANTS_TID] = 'Протравитель семян';
              $options[AGRO_CATEGORY_INSECTICIDES_TID] = 'Инсектицид';
              $options[AGRO_CATEGORY_FERT_TID] = 'Удобрение';
              break;
          }
        }
      $form['field_pd_r_function']['und']['#options'] = $options;
      $default_option = isset($form_state['field_collection_item']->field_pd_r_function['und'][0]) ? $form_state['field_collection_item']->field_pd_r_function['und'][0]['tid'] : array(key($options));
      $form['field_pd_r_function']['und']['#default_value'] = $default_option;

        // условные поля, зависят от Функции регламента
        $form['field_pd_a_weeds_groups']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    array('value' => '15'),
                    array('value' => '71534'),
                ),
            ),
        );
        $form['field_pd_a_pests_groups']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    array('value' => '17'),
                    array('value' => '71533'),
                ),
            ),
        );
        $form['field_pd_a_hobjects']['#states']
            = $form['field_pd_r_hobjects_comment']['#states']
            = $form['field_pd_r_wait_period']['#states']
            = $form['field_pd_r_multiplicator']['#states'] = array(
            'visible' => array(
                'select[name="field_pd_r_function[und]"]' => array(
                    '!value' => '93',
                ),
            ),
        );
    }
}

function ext_product_preprocess_node(&$vars)
{
    // для Крупной фасовки подключить js библиотеку для форматирования суммы и расчётов
    if ($vars['view_mode'] == 'full' && in_array($vars['node']->type, array('product_agro', 'product_mix', 'product_fert'))) {
        drupal_add_js(drupal_get_path('module', 'ext_product') . '/js/mini_calc.js');
        drupal_add_js(drupal_get_path('module', 'ext_product') . '/js/accounting.js');
    }

    // разложить title для агроминералов
    if ($vars['node']->type == 'product_fert') {
        $vars['header']['title'] = explode('|', $vars['node']->title)[0];
        $vars['header']['title_suffix'] = explode('|', $vars['node']->title)[1];
    }


    // расчёт и размека рейтинга препарата
    // todo найти причину падения страницы из-за следующего кода
//    if ((in_array($vars['view_mode'], array('full', 'teaser')) && in_array($vars['type'], array('product_agro')))
//        || $vars['view_mode'] == 'teaser_grid') {
//        // посчитать рейтинг и количестко отзывов
//        $rating_count = $rating_avg = $rating_sum = 0;
//        $query = db_select('field_data_field_pd_review', 'fr');
//        $query->condition('fr.entity_id', $vars['node']->nid);
//        $query->innerJoin('field_data_field_pd_rv_stars', 'frs', 'frs.entity_id = fr.field_pd_review_value');
//        $query->fields('frs', array('field_pd_rv_stars_value'));
//        if ($result = $query->execute()->fetchAll()) {
//            foreach ($result as $rating) {
//                $rating_count++;
//                $rating_sum += $rating->field_pd_rv_stars_value;
//            }
//            $rating_avg = $rating_sum / $rating_count;
//        }
//
//        $vars['rating'] = $rating_avg;
//        $vars['rating_count'] = $rating_count;
//
//        // ссылка на добавление отзыва
//        $rating_links = array();
//        if ($user->uid) {
//            chibs_include_modal();
//            $rating_links[] = '<a href="/product/rating/' . $vars['node']->nid . '/add/nojs' . '" class="add ctools-modal-style ctools-use-modal" title="' . t('Rate product') . '"><i class="fa fa-plus smooth" aria-hidden="true"></i><span class="hover-show smooth">' . t('Rate product') . '</span></a>';
//        } else {
//            $rating_links[] = '<a href="/user/login?destination=' . drupal_get_path_alias('node/' . $vars['node']->nid) . '" class="add" title="' . t('Rate product') . '"><i class="fa fa-plus" aria-hidden="true"></i><span class="hover-show smooth">' . t('Rate product') . '</span></a>';
//        }
//        if ($rating_count) $rating_links[] = '<a href="/product/rating/' . $vars['node']->nid . '/get-list/nojs' . '" class="get-list use-ajax" title="' . t('List ratings') . '"><i class="fa fa-list smooth" aria-hidden="true"></i><span class="hover-show smooth">' . t('List ratings') . '</span></a>';
//        $vars['rating_link'] = implode('', $rating_links);
//    }
}

/**
 * callback открытия списка отзывов (stars)
 */
function ext_product_rating_get_list_callback($pid, $op, $mode = NULL) {
    if ($mode == 'ajax') {

        if ($op == 'show') {
            $rating_list = ext_product_get_rating_list($pid);
            $hide_link = '<a href="/product/rating/' . $pid . '/hide-list/nojs' . '" class="get-list use-ajax" title="' . t('Hide list') . '"><i class="fa fa-list smooth" aria-hidden="true"></i><span class="hover-show smooth">' . t('Hide list') . '</span></a>';

            $output = array(
                ajax_command_invoke('.r-list', 'html', array(theme('product_rating_list', array('rating_list' => $rating_list)))),
                ajax_command_replace('.get-list', $hide_link),
            );
        } else {
            $show_link = '<a href="/product/rating/' . $pid . '/get-list/nojs' . '" class="get-list use-ajax" title="' . t('List ratings') . '"><i class="fa fa-list smooth" aria-hidden="true"></i><span class="hover-show smooth">' . t('List ratings') . '</span></a>';
            $output = array(
                ajax_command_invoke('.r-list', 'html', array('')),
                ajax_command_replace('.get-list', $show_link),
            );

        }
        print ajax_render($output);
        drupal_exit();
    }
    else return theme('product_rating_list', array('rating_list' => ext_product_get_rating_list($pid)));
}
/**
 * функция возвращает список отзывов (stars) о товаре
 */
function ext_product_get_rating_list($nid) {
    $rating_list = array();

    $query = db_select('field_data_field_pd_review', 'fr');
    $query->condition('fr.entity_id', $nid);
    $query->innerJoin('field_data_field_pd_rv_stars', 'frs', 'frs.entity_id = fr.field_pd_review_value');
    $query->innerJoin('field_data_field_pd_rv_text', 'frt', 'frt.entity_id = fr.field_pd_review_value');
    $query->innerJoin('field_data_field_pd_rv_user', 'fru', 'fru.entity_id = fr.field_pd_review_value');
    $query->leftJoin('field_data_field_date', 'frd', 'frd.entity_id = fr.field_pd_review_value');
    $query->fields('frs', array('field_pd_rv_stars_value'));
    $query->fields('frt', array('field_pd_rv_text_value'));
    $query->fields('fru', array('field_pd_rv_user_value'));
    $query->fields('frd', array('field_date_value'));
    if ($result = $query->execute()->fetchAll()) {
        foreach($result as $rating) {

            $person = person_get_user_array($rating->field_pd_rv_user_value);
            $rating_list[] = array(
                'stars' => $rating->field_pd_rv_stars_value,
                'text' => $rating->field_pd_rv_text_value,
                'date' => $rating->field_date_value ? format_date($rating->field_date_value,'custom','d.m.Y') : '',
                'user_name' => $person['short_name'],
            );
        }
    }

    return $rating_list;
}
/**
 * оформление списка отзывов (stars) о товаре
 */
function theme_product_rating_list($vars) {
    $html = '';
    foreach($vars['rating_list'] as $item_r) {
        $name = '<span class="name"><span>' . drupal_substr($item_r['user_name'], 0, 1) . '</span>' . drupal_substr($item_r['user_name'], 1) . '</span>';
        $html .= '<li>'
            . '<div class="r1">' . theme('product_rating', array('rating' => $item_r['stars'])) . ' ' . $name . '<span class="date">' . $item_r['date'] . '</span></div>'
            . '<div class="r2">' . $item_r['text'] . '</div>'
        . '</li>';
    }
    return '<ul>' . $html . '</ul>';
}


function ext_product_theme() {
    return array(
        // ----------  пятизвёздочный  рейтинг ----------------------------------
        'product_rating' => array(
            'variables' => array('rating' => NULL),
        ),
        // ----------  список отзывов (пятизвёздочный  рейтинг) -----------------
        'product_rating_list' => array(
            'variables' => array('rating_list' => NULL),
        ),
    );
}

function theme_product_rating($vars) {
    $stars = '';
    $rating = $vars['rating'];
    for($i=1; $i<=5; $i++) {
        if ($i - 0.2 <= $rating) $star = '<i class="fa fa-star" aria-hidden="true"></i>';
        elseif ($i - 0.9 <= $rating && ($i - 0.2) > $rating ) $star = '<i class="fa fa-star-half-o" aria-hidden="true"></i>';
        else $star = '<i class="fa fa-star-o" aria-hidden="true"></i>';
        $stars .= $star;
    }
    
    return '<span class="stars">' . $stars . '</span>';
}

/**
 * @param $nid - id product_agro
 * @return array с заголовком, формуляцией и ингредиентами
 */
function get_product_agro_title($nid) {
    $prep_wrapper = entity_metadata_wrapper('node', $nid);

    $ingredients = $form_short = $formulation_full = $price = $unit_short = '';
    if (in_array($prep_wrapper->value()->type, array('product_agro', 'product_fert', 'product_chem'))) {
        $unit = get_product_units($nid);
        $unit_short = isset($unit['short_unit']) ? $unit['short_unit'] : '';
    }

    if (in_array($prep_wrapper->value()->type, array('product_agro'))) {

        $prep_wrapper = $prep_wrapper->language($GLOBALS['language']->language);
        if ($prep_wrapper->field_pd_formulation->value()) {

            $form_short = $prep_wrapper->field_pd_formulation->language($GLOBALS['language']->language)->field_tax_short_name->value();
            $formulation_full = $prep_wrapper->field_pd_formulation->language($GLOBALS['language']->language)->name->value();
        }

        $arr_ingredients = array();
        if ($prep_wrapper->field_pd_active_ingredients->value()) {
            foreach ($prep_wrapper->field_pd_active_ingredients as $ingredient_wrapper) {
                if ($ingredient_wrapper->field_pd_ai_active_ingredient->value()) {
                    $ingredient_wrapper = $ingredient_wrapper->language($GLOBALS['language']->language);
                    $ingr_name = ($GLOBALS['language']->language == 'ru') ? $ingredient_wrapper->field_pd_ai_active_ingredient->name->value() : $ingredient_wrapper->field_pd_ai_active_ingredient->field_name_latin->value();
                    $ingr_dose = $ingredient_wrapper->field_pd_ai_concentration->value();
                    $cons_unit = 'l';
                    if (in_array($unit['short_unit'], array('кг', 'г', 'kg', 'g'))) $cons_unit = t('kg');
                    if (in_array($unit['short_unit'], array('л', 'мл', 'l', 'ml'))) $cons_unit = t('l');
                    $arr_ingredients[] = $ingr_name . ', ' . $ingr_dose . ' ' . t('g') . '/' . $cons_unit;
                }
            }
            $ingredients = implode(' + ', $arr_ingredients);
        }
    }

    if ($prep_wrapper->value()->type != 'product_mix') {
        $price = $prep_wrapper->field_pd_price_per_unit->amount->value()/100;
    }

    return array(
        'id' => $nid,
        'title' => $prep_wrapper->title_field->value(),
        'formulation' => $form_short,
        'formulation_full' => $formulation_full,
        'ingredients' => $ingredients,
        'ingredients_arr' => empty($arr_ingredients) ? array() : $arr_ingredients,
        'price' => $price,
        'unit' => empty($unit['unit']) ? '' : $unit['unit'],
        'unit_short' => $unit_short,
        'unit_field' => empty($unit['field_unit']) ? '' : $unit['field_unit'],
        'unit_cons' => empty($unit['cons_unit']) ? '' : $unit['cons_unit'],
        'status' => (bool)$prep_wrapper->status->value(),
    );
}

/**
 * Вернуть полную информацию о продукте
 * @param $node
 * @return array с массивом препаратов заголовком, формуляцией и ингредиентами
 */
function get_product_info($node)
{
    $result = &drupal_static(__FUNCTION__);
    if (is_numeric($node) && isset($result[$node])) return $result[$node];
    if (isset($node->nid) && isset($result[$node->nid])) return $result[$node->nid];

    $lang = $GLOBALS['language']->language;

    $preparation_wr = entity_metadata_wrapper('node', $node)->language($lang);

    // составить массив препаратов
    // один препарат для химии, два препарата для смесей
    $preparations = [];
    if ($preparation_wr->value()->type == 'product_mix') {
        foreach (['field_pd_mix_component1', 'field_pd_mix_component2'] as $key => $field) {
            $wrapper = $preparation_wr->{$field};
            $preparations[] = array(
                'order' => $key,
                'item' => $wrapper,
            );
        }
    } else {
        $preparations[] = array(
            'order' => 0,
            'item' => $preparation_wr,
        );
    }

    // формируем результирующий массив
    $preparation = array(
        'nid'    => $preparation_wr->nid->value(),
        'type'   => $preparation_wr->value()->type,
        'status' => $preparation_wr->status->value(),
        'icon'   => isset($preparation_wr->field_icon) && $preparation_wr->field_icon->value() ? $preparation_wr->field_icon->file->url->value() : '',
    );
    $titles_w_form = [];
    foreach($preparations as $item) {
        $preparation_wr = $item['item'];
        $id = $preparation_wr->nid->value();

        // препаративная форма
        $form_short = $form_full = '';
        if (isset($preparation_wr->field_pd_formulation) && $preparation_wr->field_pd_formulation->value()) {
            $form_short = $preparation_wr->field_pd_formulation->language($lang)->field_tax_short_name->value();
            $form_full = $preparation_wr->field_pd_formulation->language($lang)->name->value();
        }

        // единицы измерения препарата
        $unit_wr = $preparation_wr->field_pd_units->language($lang);

        // ДВ
        $ingredients = [];
        if (isset($preparation_wr->field_pd_active_ingredients) && $preparation_wr->field_pd_active_ingredients->value()) {
            foreach ($preparation_wr->field_pd_active_ingredients as $ingredient_wr) {
                if ($ingredient_wr->field_pd_ai_active_ingredient->value()) {
                    $ingredient_wr = $ingredient_wr->language($lang);
                    $ingr_name = ($lang == 'ru') ? $ingredient_wr->field_pd_ai_active_ingredient->name->value() : $ingredient_wr->field_pd_ai_active_ingredient->field_name_latin->value();
                    $ingr_dose = $ingredient_wr->field_pd_ai_concentration->value();
                    $cons_unit = t('l');
                    if (in_array($unit_wr->field_tax_short_name->value(), array('кг', 'г', 'kg', 'g'))) $cons_unit = t('kg');
                    if (in_array($unit_wr->field_tax_short_name->value(), array('л', 'мл', 'l', 'ml'))) $cons_unit = t('l');
                    $ingredients[] = $ingr_name . ', ' . $ingr_dose . ' ' . t('g') . '/' . $cons_unit;
                }
            }
        }

        // определить по категории ед. изм. применения препарата (га или т)
        // и занести в массив, т.к. неизвестно, какие из них будут использованы
        $unit_field = [];
        foreach ($preparation_wr->field_pd_category as $cat_wrapper) {
            $tid = $cat_wrapper->tid->value();
            $unit_field[$tid] = $tid == AGRO_CATEGORY_DISINFECTANTS_TID ? t(AGRO_SEED_MEASURE) : t(AGRO_FIELD_MEASURE);
        }

        // фото
        $photo_url = $preparation_wr->field_product[0]->field_p_images[0]->value() ? $preparation_wr->field_product[0]->field_p_images[0]->value()['uri'] : '';

        // категория и цвет
        $cats = [];
        if ($preparation_wr->field_pd_category->value()) {
            foreach($preparation_wr->field_pd_category->getIterator() as $category_wr) {
                $cats[$category_wr->tid->value()] = [
                    'tid' => $category_wr->tid->value(),
                    'name' => $category_wr->name->value(),
                    'color' => $category_wr->field_color->value(),
                ];
            }
        }

        $preparation['items'][$id] = array(
            'id'            => $id,
            'title'         => $preparation_wr->language($lang)->title_field->value(),
            'description'   => strip_tags($preparation_wr->body->summary->value()),
            'form_short'    => $form_short,
            'form_full'     => $form_full,
            'ingredients'   => $ingredients,
            'price'         => $preparation_wr->field_pd_price_per_unit->amount->value()/100,
            'unit'          => $unit_wr->name->value(),
            'unit_short'    => $unit_wr->field_tax_short_name->value(),
            'unit_field'    => $unit_field,
            'photo_url'     => $photo_url,
            // порядковый номер в списке препаратов баковой смеси (БС)
            // используется для связи с нормой расхода в регламенте БС
            'order'         => $item['order'],
            'categories'    => $cats
        );
        $titles_w_form[] = $form_short ? $preparation_wr->title_field->value() . ', ' . $form_short : $preparation_wr->title_field->value();
    }
    $preparation['title'] = implode(' + ', $titles_w_form);

    $result[$preparation['nid']] = $preparation;

    return $preparation;
}

/**
 * возвращает массив с единицами измерения в которых нормируется товар
 * @param $nid
 * @return array
 */
function get_product_units($nid) {
    $node_wrapper = entity_metadata_wrapper('node', $nid);
    $node_wrapper = $node_wrapper->language($GLOBALS['language']->language);
    $unit_wrapper = $node_wrapper->field_pd_units->language($GLOBALS['language']->language);
    $short_unit = $unit_wrapper->field_tax_short_name->value();

    // определить ед. изм. применения (га или т) по категории
    $field_unit = AGRO_FIELD_MEASURE;
    foreach ($node_wrapper->field_pd_category as $cat_wrapper) {
        if (in_array($cat_wrapper->tid->value(), array(AGRO_CATEGORY_DISINFECTANTS_TID))) {
            $field_unit = AGRO_SEED_MEASURE;
        }
    }
    return array(
        'unit' => $unit_wrapper->name->value(),
        'short_unit' => $short_unit,
        'field_unit' => t($field_unit),
        'cons_unit' => $short_unit . '/' . t($field_unit),
    );
}

function get_product_main_cultures($nid) {
    $main_cultures = array();
//    $node_wrapper = entity_metadata_wrapper('node', $nid);
//    if ($node_wrapper->field_pd_reglaments2->value()) {
//        foreach ($node_wrapper->field_pd_reglaments2->getIterator() as $reg_wrapper) {
//            if ($reg_wrapper->field_pd_r_cultures->count()) {
//                foreach ($reg_wrapper->field_pd_r_cultures->getIterator() as $c_wrapper) {
//                    $title = $c_wrapper->title->value();
//                    if ($title) {
//                        $title .= $reg_wrapper->field_pd_r_cultures_comment->value() ? (' (' . $reg_wrapper->field_pd_r_cultures_comment->value() . ')') : '';
//                    }
//                    $main_cultures[$c_wrapper->nid->value()] = array(
//                        'title' => $title,
//                    );
//                }
//            } else {
//                $main_cultures[$reg_wrapper->item_id->value()] = array(
//                    'title' => $reg_wrapper->field_pd_r_cultures_comment->value(),
//                );
//            }
//        }
//    }

    return $main_cultures;
}


/**
 * --------------------------------- Сделать текст под заголовками h4 сворачиваемым (в поле body)-----------------------
 * Implements hook_node_view_alter().
 */
function ext_product_node_view_alter(&$build) {
    if ($build['#view_mode'] == 'full'
        && in_array($build['#bundle'], array('product_agro', 'product_fert', 'product_mix', 'product_chem'))) {

        $ba = explode('<h4>', $build['body'][0]['#markup']);
        $expanded = true;
        $body = array_shift($ba);
        foreach ($ba as $b_key => $b_item) {
            if ($b_item) {
                $ba2 = explode('</h4>', $b_item);
                if (!empty($ba2[0]) && !empty($ba2[1])) {
                    $body .= '<h4 data-toggle="collapse" data-target="#collapse-' . $b_key . '" aria-expanded="' . $expanded . '" aria-controls="collapse-' . $b_key . '"' . ($expanded ? '' : ' class="collapsed"') . '>' . str_replace(':', '', $ba2[0]) . '<i class="fa fa-caret-down" aria-hidden="true"></i></h4>';
                    $body .= '<div class="collapse' . ($expanded ? ' in' : '') . '" id="collapse-' . $b_key . '">' . trim($ba2[1]) . '</div>';
                    $expanded = false;
                }
            }
        }
        if ($body) $build['body'][0]['#markup'] = $body;
    }
}


/**
 * --------------------------------- Вернуть полный список препаратов для функции быстрого поиска в Приложении ---------
 */
function ext_product_qsearch_callback($category_tid = null)
{
    $items = [];

    $query = db_select('node', 'n');
    $query->condition('n.type', ['product_agro', 'product_fert'], 'IN');
    $query->condition('n.status', 1);
    $query->addField('n', 'nid');
    $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
    $query->condition('tf.language', $GLOBALS['language']->language);
    $query->orderby('tf.title_field_value', 'ASC');

    if ($category_tid) {
        $query->innerJoin('field_data_field_pd_category', 'pc', 'n.nid = pc.entity_id');
        $query->condition('pc.field_pd_category_tid', $category_tid);
    }
    if ($result = $query->execute()->fetchAll()) {
        foreach($result as $prep) {
            $prep_arr = get_product_info($prep->nid);
            if (in_array($prep_arr['type'], ['product_agro', 'product_fert'])) {
                $prep_item = $prep_arr['items'][$prep_arr['nid']];
                $item = [
                    'nid' => $prep_item['id'],
                    'title' => $prep_item['title'] . ($prep_item['form_short'] ? ', ' . $prep_item['form_short'] : ''),
                    'description' => $prep_item['description'],
                    'ingredients' => implode(' + ', $prep_item['ingredients']),
                    'photo' => image_style_url('mobile_teaser_product', $prep_item['photo_url']),
                    'icon' => $prep_arr['icon'],
                ];
                foreach($prep_item['categories'] as $tid => $cat) {
                    if (empty($items[$tid]) && (!$category_tid || $tid == $category_tid)) {
                        $items[$tid] = [
                            'tid' => $tid,
                            'name' => $cat['name'],
                            'color' => $cat['color'],
                            'items' => []
                        ];
                    }
                    // если задана категория, список только для неё
                    if (!$category_tid || $tid == $category_tid) {
                        $items[$tid]['items'][] = $item;
                    }
                }
            }
        }
    }

    drupal_json_output(['preparations' => $items]);
    drupal_exit();
}