<?php

/**
 * Implements hook_menu().
 */
function ext_admin_menu()
{
  $items['admin/config/system/site-settings'] = array(
    'title' => 'Настройки сайта',
    'weight' => -100,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_settings_form'),
    'access arguments' => array('access manager settings'),
  );

  return $items;
}

function ext_admin_settings_form($form, &$form_state)
{
  $form['email_otdel_kadrov'] = [
    '#title' => 'E-Mail. Отдел кадров',
    '#type' => 'textfield',
    '#default_value' => variable_get('email_otdel_kadrov', ''),
  ];
  $form['phone_reception'] = [
    '#title' => 'Телефон администратора',
    '#type' => 'textfield',
    '#default_value' => variable_get('phone_reception', ''),
  ];

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#attributes' => ['class' => ['btn-success']],
    '#value' => 'Сохранить настройки',
  ];

  return $form;
}

function ext_admin_settings_form_submit($form, $form_state)
{
  variable_set('email_otdel_kadrov', $form_state['values']['email_otdel_kadrov']);
  variable_set('phone_reception', $form_state['values']['phone_reception']);
  drupal_set_message('Настройки сохранены');
}
