<?php
/**
* @file
* Adds new payment way - bank transfer
*/

/**
 * Implements hook_commerce_payment_method_info().
 */
function cash_on_delivery_commerce_payment_method_info() {
    return array(
        // Системное название способа оплаты.
        'cash_on_delivery' => array(
            // Название способа оплаты для отображения в админке.
            'title' => t('Cash On Delivery'),
            // Название способа оплаты для отображения в форме чекаута. Может содержать html.
            // Опционально.
            'display_title' => t('Cash On Delivery'),
            // Описание способа оплаты. Опционально.
            'description' => t('Payment on delivery'),
            // Состояние способа оплаты при включении модуля: TRUE — включён, FALSE — выключен
            // (по умолчанию). Опционально.
            'active' => TRUE,
            // Сможет ли администратор самостоятельно добавить этот способ оплаты для
            // завершённого заказа. Опционально. По умолчанию TRUE.
            'terminal' => TRUE,
            // Нужно ли покупателю покидать пределы сайта при оплате заказа этим способом.
            // Опционально. По умолчанию FALSE.
            'offsite' => FALSE,
            // Автоматический редирект на сторонний сайт при оплате заказа этим способом.
            // Опционально. По умолчанию FALSE.
            'offsite_autoredirect' => FALSE,
        ),
    );
}

/**
 * Payment method callback: settings form.
 */
function cash_on_delivery_settings_form($settings = NULL) {
    $form = array();
    $settings = (array)$settings
        + array('information' => '',
                'title' => '',
                );

    // Информация о способе оплаты
    // заголовок
    $form['title'] = array(
        '#type' => 'textarea',
        '#title' => t('Title'),
        '#description' => t('Title to be shown to users when they select this payment mthd.'),
        '#default_value' => $settings['title'],
    );
    // информация
    $form['information'] = array(
        '#type' => 'textarea',
        '#title' => t('Information'),
        '#description' => t('Information you would like to be shown to users when they select this payment mthd.'),
        '#default_value' => $settings['information'],
    );


    return $form;
}

/**
 * Payment method callback: submit form.
 */
function cash_on_delivery_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
    $form = array();
    $pane_values += array('cstm_method' => '');

    // Выводим заголовок способа оплаты
    if (!empty($payment_method['settings']['title'])) {
        $form['cash_on_delivery_title'] = array(
            '#markup' => '<div class="title">'. $payment_method['settings']['title']. '</div>'
        );
    }

    // Выводим информацию о способе оплаты
    if (!empty($payment_method['settings']['information'])) {
        $form['cash_on_delivery_information'] = array(
            '#markup' => '<div class="info">'. $payment_method['settings']['information']. '</div>'
        );
    }

    return $form;
}

/**
 * Payment method callback: submit form submission.
 */
function cash_on_delivery_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
    $order->data['cash_on_delivery'] = $pane_values;

    // Создаём транзакцию
    $transaction = commerce_payment_transaction_new('cash_on_delivery', $order->order_id);
    $transaction->instance_id = $payment_method['instance_id'];
    $transaction->amount = $charge['amount'];
    $transaction->currency_code = $charge['currency_code'];
    $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
    $transaction->message = t('The payment is pending.');
    commerce_payment_transaction_save($transaction);
}