<?
/**
 * Implements hook_node_presave()
 * @param $node
 */
function ext_node_node_presave($node)
{
  // только для заданных типов
  if (in_array($node->type, ['news', 'blog', 'review', 'weed', 'disease', 'pest'])) {
    $lang = $GLOBALS['language']->language;

    if (isset($node->body[$lang][0]['value'])) {
      // полный текст для проверки
      $text = $node->body[$lang][0]['value'];

      // убираем неподдающиеся регекспу кавычки
      $text = str_replace('«', '"', $text);
      $text = str_replace('»', '"', $text);

      $text = str_replace('&nbsp;', ' ', $text);

      $text = ext_node_remove_all_links($text);
      $text = ext_node_place_internal_links($text);

      // дополнительные обработки
      $text = str_replace('http://kccc.', 'https://kccc.', $text);
      $text = str_replace('http://www.kccc.', 'https://kccc.', $text);

      $node->body[$lang][0]['value'] = $text;
    }
  }
}

function ext_node_remove_all_links($text)
{
  return preg_replace('#<a.*?>(.*?)</a>#is', '\1', $text);
}

function ext_node_place_internal_links($text)
{
  // список искомых фраз и их ссылок
  $replacements_list = _ext_node_replacement_list();
  foreach ($replacements_list as $replacement_item) {
    $patterns = _ext_node_convert_needles_to_preg_patterns($replacement_item, $replacements_list);
    $id_attr = strpos($replacement_item['url'], 'node/') === 0 ? 'data-node-id="' . str_replace('node/', '', $replacement_item['url']) . '" ' : '';
    $replace = '\\1<a href="' . url($replacement_item['url']) . '" ' . $id_attr . 'target="_blank">\\2</a>\\3';
    foreach ($patterns as $pattern) {
      $text_old = $text;
      $text = preg_replace($pattern, $replace, $text, 1);
      if ($text != $text_old) break;
    }
  }

  return $text;
}

/**
 * Сформировать массив замен
 *
 * $arr[] = [
 *     'needles' => [], // список искомых фраз
 *     'url' => '',     // ссылка, которую необходимо прикрепить
 * ];

 * @return array
 */
function _ext_node_replacement_list()
{
    $result = [];

    $result[] = [
        'needles' => [
            'ООО ТД "Кирово-Чепецкая Химическая Компания"',
            'ООО Торговый Дом "Кирово-Чепецкая Химическая Компания"',
            'ТД "Кирово-Чепецкая Химическая Компания"',
            'Торговый Дом "Кирово-Чепецкая Химическая Компания"',
            'Торговый Дом "КЧХК"',
            'ООО ТД "КЧХК"', 'ТД "КЧХК"',
            'Кирово-Чепецкой Химической Компании',
            'KCCC Group', 'KCCC GROUP',
            'KCCC', 'КССС',
        ],
        'url' => 'https://kccc.ru',
    ];
    $result[] = [
        'needles' => [
            'представител',
            'купить', 'приобрести'
        ],
        'url' => 'https://kccc.ru/info/representatives',
    ];
    $result[] = [
        'needles' => [
            'испытани', 'опыты',
        ],
        'url' => 'https://kccc.ru/before-after',
    ];
    $result[] = [
        'needles' => [
            'специалист', 'экспертное мнение', 'эксперт'
        ],
        'url' => 'https://kccc.ru/agro-expert',
    ];
    $result[] = [
        'needles' => [
            'программы защиты', 'программа защиты', 'программ защиты', 'системы защиты', 'система защиты', 'систем защиты'
        ],
        'url' => 'https://kccc.ru/handbook/protection-programs',
    ];

    // препараты
    $query = db_select('node', 'n');
    $query->fields('n', ['nid']);
    $query->condition('n.type', ['product_agro', 'product_fert'], 'IN');
    $query->condition('n.status', 1);
    $query->leftJoin('field_data_title_field', 'tf', 'tf.entity_id = n.nid');
    $query->condition('tf.language', 'ru');
    $query->addField('tf', 'title_field_value', 'title');
    $query->leftJoin('field_data_field_pd_formulation', 'pf', 'pf.entity_id = n.nid');
    $query->leftJoin('field_data_field_tax_short_name', 'pfsn', 'pfsn.entity_id = pf.field_pd_formulation_tid');
    $query->condition('pfsn.language', 'ru');
    $query->addField('pfsn', 'field_tax_short_name_value', 'short_name');

    if ($products = $query->execute()->fetchAllAssoc('nid')) {
      // определить пересекающиеся названия и задать исключения (напр. Грандсил для Грандсил Ультра)
      foreach($products as $product_check) {
        foreach($products as $key => $product) {
          if (strpos($product_check->title, $product->title) === 0 && ($product->title != $product_check->title)) {
            $products[$key]->exclude = $product_check->nid;
            break;
          }
        }
      }

      // подготовить список вариантов для каждого препарата
      foreach($products as $product) {
        $title = str_replace(['*', '®'], '', $product->title);
        $title = trim($title);
        $result[$product->nid] = [
          'needles' => [$title . ', ' . trim($product->short_name), $title . ',' . trim($product->short_name), $title],
          'url' => 'node/' . $product->nid,
          'exclude' => isset($product->exclude) ? $product->exclude : '',
        ];
      }
    }

    return $result;
}

function _ext_node_convert_needles_to_preg_patterns($replacement, $replacements_list)
{
  $needles = $replacement['needles'];
  if (empty($needles)) return false;

  // <a.*?<\/a>(*SKIP)(*F) - всё, что внутри ссылок в расчёт не берём
  // как исключать ненужное - https://stackoverflow.com/questions/23589174/regex-pattern-to-match-excluding-when-except-between
  $patterns = [];
  foreach ($needles as $needle) {
    $excludes = ['<a.*?<\/a>'];
    if (!empty($replacement['exclude'])) {
      foreach ($replacements_list[$replacement['exclude']]['needles'] as $exclude_needle) {
        $excludes[] = '[>\s\"]' . $exclude_needle . '.*?[<\.\!\?\,\s\"\;\:]';
      }
    }
    $exclude = implode('|', $excludes);

    // кавычки могут быть любыми
    $needle = str_replace('"', '["\']', $needle);
    $patterns[] = '/(?:' . $exclude . ')(*SKIP)(*F)|([>\s\"])(' . $needle . '.*?)([<\.\!\?\,\s\"\;\:])/si';
  }

  return $patterns;
}
