<?php

/**
 * Implements hook_mail_alter
 */
function ext_mail_mail_alter(&$message)
{
  if (strpos($_SERVER['HTTP_HOST'], '.local') !== FALSE) {
    $message['send'] = false;
    watchdog('mailer', 'Эмуляция отправки E-Mail.<br />Почта: %mail<br />Тема: %subject<br />Текст: %body', ['%mail' => $message['to'], '%subject' => $message['subject'], '%body' => var_export($message['body'], true)], WATCHDOG_DEBUG);
  } else {
    watchdog('mailer', 'Отправка E-Mail.<br />Почта: %mail <br />Тема: %subject<br />Текст: %body', ['%mail' => $message['to'], '%subject' => $message['subject'], '%body' => var_export($message['body'], true)], WATCHDOG_DEBUG);
  }
}
