<?php

/**
 *  Implementation of hook_menu()
 */
function ext_message_got_menu()
{
    $items['message/%/got'] = array(
        'page callback' => 'ext_message_got_process_message_action',
        'page arguments' => array(1, 'set'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['message/%/ungot'] = array(
        'page callback' => 'ext_message_got_process_message_action',
        'page arguments' => array(1, 'unset'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_views_api().
 */
function ext_message_got_views_api()
{
    // привязка своей таблицы ко Views
    // https://habr.com/ru/sandbox/74002/
    return array(
        'api' => 3,
        'path' => drupal_get_path('module', 'ext_message_got') . '/views',
    );
}

/**
 * message actions page callback
 * @param $mid
 * @param null $action
 */
function ext_message_got_process_message_action($mid, $action = null)
{
    if ($action) {
        if ($action = 'set') ext_message_got_set_user_got_message($mid);
        if ($action = 'unset') ext_message_got_unset_user_got_message($mid);
    }

    $path = empty($_GET['back']) ? drupal_not_found() : $_GET['back'];
    drupal_goto($path);
}

/**
 * создать запись о прочтении Message by User
 *
 * @param $mid - Message ID
 * @param $uid - User ID
 */
function ext_message_got_set_user_got_message($mid, $uid = null)
{
    if (!$uid) $uid = $GLOBALS['user']->uid;
    if ($mid && $uid && !ext_message_got_check_user_got_message($mid, $uid)) {
        $id = db_insert('message_got')
            ->fields(array(
                'mid' => $mid,
                'uid' => $uid,
                'timestamp' => REQUEST_TIME,
            ))
            ->execute();
    }

    return isset($id) ? $id : false;
}

/**
 * удалить запись о прочтении Message by User
 *
 * @param $mid - Message ID
 * @param $uid - User ID
 */
function ext_message_got_unset_user_got_message($mid, $uid = null)
{
    $deleted = false;
    if (!$uid) $uid = $GLOBALS['user']->uid;
    if ($mid && $uid) {
        $deleted = db_delete('message_got')
            ->condition('mid', $mid)
            ->condition('uid', $uid)
            ->execute();
    }

    return $deleted;
}

/**
 * проверить наличие записи о прочтении Message by User
 *
 * @param $mid - Message ID
 * @param $uid - User ID
 */
function ext_message_got_check_user_got_message($mid, $uid)
{
    $count = 0;
    if ($mid && $uid) {
        $count = db_select('message_got')
            ->condition('mid', $mid)
            ->condition('uid', $uid)
            ->countQuery()
            ->execute()
            ->fetchField();
    }

    return (bool)$count;
}