<?php

define('CONTACTS_URL', 'info/contacts');

function contacts_menu()
{
    $items[CONTACTS_URL] = array(
        'title' => 'Contacts',
        'description' => 'Company contacts',
        'page callback' => 'contacts_main_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function contacts_theme()
{
    return array(
        'contacts_page' => array(
            'variables' => array('contacts' => NULL),
            'template' => 'templates/page',
        ),
    );
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function contacts_preprocess_page(&$vars)
{
    // установить для страницы параметры шапки
    if ($_GET['q'] == CONTACTS_URL) {
        $vars['header'] = array(
            'image' => url('/' . drupal_get_path('module', 'contacts') . '/images/header_image.jpg', array('absolute' => true)),
            'category_title' => '',
            'subtitle' => t('You can contact to our departments directly'),
            'print' => true,
        );
    }
}

// главная страница
function contacts_main_page()
{
    $lang = $GLOBALS['language']->language;

    $contacts = contacts_get_contacts_list();

    // отрендерить карточки контактов
    foreach($contacts as $key_t => $tabs) {
        foreach($tabs['departments'] as $key_d => $department) {
            foreach($department['contacts'] as $key_c => $contact) {
                $contact['surname']    = $lang == 'ru' ? $contact['surname'] : translit($contact['surname']);
                $contact['name']       = $lang == 'ru' ? $contact['name'] : translit($contact['name']);
                $contact['name2']      = $lang == 'ru' ? $contact['name2'] : translit($contact['name2']);
                $collapse = [];
                if (!empty($contact['regions'])) {
                    $collapse['id'] = $key_c;
                    $collapse['title'] = t('Regions list');
                    $regions = [];
                    foreach ($contact['regions'] as $region) { $regions[] = $region['name']; }
                    $collapse['content'] = implode(', ', $regions);
                }
                $contacts[$key_t]['departments'][$key_d]['contacts'][$key_c]['contact_html'] = theme('contact_card', array(
                    'contact' => $contact,
                    'collapse' => $collapse,
                    'options' => ['class' => 'col-md-6']));
            }
        }
    }

    $html = theme('contacts_page', array('contacts' => $contacts));

    return $html;
};

function contacts_get_contacts_list() {
    $module_path = drupal_get_path('module', 'contacts');
    $no_photo = '/sites/default/files/default_images/no_photo.png';

    $contacts = array(
        'td' => array(
            'title' => t('Trade House'),
            'logo_on' => '/' . $module_path . '/images/logo/td_on.png',
            'logo_off' => '/' . $module_path . '/images/logo/td_off.png',
            'departments' => array(
                'sales' => array(
                    'title' => t('Sales department'),
                    'contacts' => array(
                        array(
                            'office' => t('Commercial director'),
                            'access' => true,
                            'surname' => 'Рудяк', 'name' => 'Дмитрий', 'name2' => 'Вячеславович',
                            'phones' => array('+7 (8332) 76-15-31, доб. 1187', '+7 (912) 726-36-23'),
                            'emails' => array('dmitry.rudyak@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/rudyak.png',
                            'regions' => array(
                            ),
                        ),
                      array(
                        'office' => t('Deputy head'),
                        'surname' => 'Шуклина',
                        'name' => 'Наталья',
                        'name2' => 'Геннадьевна',
                        'phones' => array('+7 (8332) 76-15-28, доб. 1154', '+7 922 936-16-62'),
                        'emails' => array('natalia.shuklina@kccc.ru'),
                        'photo' => '/' . $module_path . '/images/photos/shuklina_n.png',
                        'regions' => array(
                          71675 => [], //Архангельская область",
                          71696 => [], //Москва и Московская область",
                          71706 => [], //Псковская область",
                          71654 => [], //Республика Калмыкия",
                          71662 => [], //Республика Татарстан,
                          71709 => [], //Самарская область',
                          71693 => [], //Санкт-Петербург и область",
                          71713 => [], //Смоленская область",
                          71715 => [], //Тверская область",
                          71664 => [], //Удмуртская Республика",
                          71722 => [], //Ярославская область",
                          ),
                      ),
                      array(
                        'office' => t('Head of region'),
                            'access' => true,
                            'surname' => 'Устюжанин', 'name' => 'Данила', 'name2' => 'Игоревич',
                            'phones' => array('+7 (912) 738-11-11'),
                            'emails' => array('td.sale1@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/ustyuzhanin.png',
                            'regions' => array(
                              71691 => [], //Курганская область",
                              71702 => [], //Оренбургская область",
                              71704 => [], //Пензенская область",
                              71648 => [], //Республика Башкортостан",
                              71659 => [], //Республика Мордовия",
                              71710 => [], //Саратовская область',
                              71712 => [], //Свердловская область",
                              71718 => [], //Тюменская область",
                              71719 => [], //Ульяновская область',
                              71720 => [], //Челябинская область",
                            ),
                        ),
                        array(
                            'office' => t('Head of region'),
                            'access' => true,
                            'surname' => 'Князев', 'name' => 'Алексей', 'name2' => 'Юрьевич',
                            'phones' => array('+7 (912) 700-12-07'),
                            'emails' => array('td.sale2@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/knyazev.png',
                            'regions' => array(
                              71680 => [], //Волгоградская область",
                              71653 => [], //Кабардино-Балкарская Республика",
                              71655 => [], //Карачаево-Черкесская Республика",
                              71685 => [], //Калининградская область",
                              71669 => [], //Краснодарский край",
                              71647 => [], //Республика Адыгея",
                              71651 => [], //Республика Дагестан",
                              71652 => [], //Республика Ингушетия",
                              71730 => [], //Республика Крым",
                              71661 => [], //Республика Северная Осетия - Алания",
                              71707 => [], //Ростовская область",
                              71731 => [], //Севастополь",
                              71672 => [], //Ставропольский край",
                              71666 => [], //Чеченская Республика",
                            ),
                        ),
                        array(
                            'office' => t('Head of region'),
                            'access' => true,
                            'surname' => 'Якимов', 'name' => 'Евгений', 'name2' => 'Леонидович',
                            'phones' => array('+7 922 925-88-84'),
                            'emails' => array('td.sale11@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/yakimov.png',
                            'regions' => array(
                              71668 => [], //Алтайский край",
                              71674 => [], //Амурская область",
                              71725 => [], //Еврейская АО",
                              71721 => [], //Забайкальский край",
                              71684 => [], //Иркутская область",
                              71688 => [], //Кемеровская область",
                              71670 => [], //Красноярский край",
                              71700 => [], //Новосибирская область",
                              71701 => [], //Омская область",
                              71671 => [], //Приморский край",
                              71650 => [], //Республика Алтай",
                              71716 => [], //Томская область",
                              71673 => [], //Хабаровский край",
                            ),
                        ),
                        array(
                          'office' => t('Head of region'),
                          'access' => true,
                          'surname' => 'Асадов', 'name' => 'Кирилл', 'name2' => 'Низамович',
                          'phones' => array('+7 (929) 209-60-40'),
                          'emails' => array('voronezh@kccc.ru'),
                          'photo' => '/' . $module_path . '/images/photos/asadov.png',
                          'regions' => array(
                            71677 => [], //Белгородская область",
                            71678 => [], //Брянская область",
                            71682 => [], //Воронежская область",
                            71692 => [], //Курская область",
                            71694 => [], //Липецкая область",
                            71703 => [], //Орловская область",
                            71714 => [], //Тамбовская область",
                          ),
                        ),
                    )
                ),
                'support' => array(
                    'title' => t('Control and support department'),
                    'contacts' => array(
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Гребнева',
                            'name' => 'Марина',
                            'name2' => 'Геннадьевна',
                            'phones' => array('+7 (8332) 76-15-31, доб. 1214', '+7 922 942-96-94'),
                            'emails' => array('td.sale@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/grebneva.png',
                        ),
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Крупина',
                            'name' => 'Оксана',
                            'name2' => 'Валерьевна',
                            'phones' => array('+7 (8332) 76-15-31, доб. 1215', '+7 922 941-17-00'),
                            'emails' => array('td.sale9@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/krupina_o.png',
                        ),
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Бородина',
                            'name' => 'Елена',
                            'name2' => 'Валерьевна',
                            'phones' => array('+7 (8332) 76-15-31, доб. 1214', '+7 922 938-65-50'),
                            'emails' => array('td.sale18@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/borodina_e.png',
                        ),
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Мясникова',
                            'name' => 'Жанна',
                            'name2' => 'Артуровна',
                            'phones' => array('+7 (8332) 76-15-31, доб. 1225', '+7 922 900-05-18'),
                            'emails' => array('td.sale23@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/myasnikova_z.png',
                        ),
                    ),
                ),
                'supply' => array(
                    'title' => t('Supply department'),
                    'contacts' => array(
                        array(
                            'office' => t('Head of department'),
                            'surname' => 'Чернавский',
                            'name' => 'Александр',
                            'name2' => 'Юрьевич',
                            'phones' => array('+7(8332) 76-15-27, доб. 1123'),
                            'emails' => array('aleksandr.chernavsky@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/chernavskiy.png',
                        ),
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Шиляева',
                            'name' => 'Надежда',
                            'name2' => 'Анатольевна',
                            'phones' => array('+7(8332) 76-15-27, доб. 1125', '+7 922 969-43-73'),
                            'emails' => array('nadechda.shilyaeva@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/shilyaeva.png',
                        ),
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Буторина',
                            'name' => 'Дарья',
                            'name2' => 'Николаевна',
                            'phones' => array('+7(8332) 76-15-27, доб. 1200', '+7 922 902-54-84'),
                            'emails' => array('snab2@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/butorina.png',
                        ),
                        array(
                            'office' => t('Manager'),
                            'surname' => 'Мальцев',
                            'name' => 'Дмитрий',
                            'name2' => 'Александрович',
                            'phones' => array('+7(8332) 76-15-27, доб. 1227', '+7 922 924-35-82'),
                            'emails' => array('snab3@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/maltsev_d.png',
                        ),
                    ),
                ),
                'marketing' => array(
                    'title' => t('Marketing and advertising department'),
                    'contacts' => array(
                        array(
                            'office' => t('Head of department'),
                            'surname' => 'Широкова',
                            'name' => 'Марина',
                            'name2' => 'Олеговна',
                            'phones' => array('+7(8332) 76-15-30, доб. 1155'),
                            'emails' => [], //array('marina.shirokova@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/shirokova.png',
                        ),
                        array(
                            'office' => t('Marketing specialist'),
                            'surname' => 'Былёва',
                            'name' => 'Вера',
                            'name2' => 'Александровна',
                            'phones' => array('+7(8332) 76-15-30, доб. 1155'),
                            'emails' => array('reklama@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/byleva.png',
                        ),
                        array(
                            'office' => t('Marketing specialist'),
                            'surname' => 'Орлова',
                            'name' => 'Дарья',
                            'name2' => 'Игоревна',
                            'phones' => array('+7 922 900-08-27'),
                            'emails' => array('reklama2@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/orlova_d.png',
                        ),
                    ),
                ),
                'personnel' => array(
                    'title' => t('Personnel department'),
                    'contacts' => array(
                        array(
                            'office' => t('Personnel manager'),
                            'surname' => 'Огородова',
                            'name' => 'Мария',
                            'name2' => 'Николаевна',
                            'phones' => array('+7(8332) 76-15-22, доб. 1186'),
                            'emails' => array('maria.ogorodova@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/ogorodova.png',
                        ),
                    ),
                ),
            ),
        ),
        'strada' => array(
            'title' => t('Home&Garden'),
            'logo_on' => '/' . $module_path . '/images/logo/strada_on.png',
            'logo_off' => '/' . $module_path . '/images/logo/strada_off.png',
            'departments' => array(
                'sales' => array(
                    'title' => t('Sales department'),
                    'contacts' => array(
                        array(
                            'office' => t('Head of department'),
                            'surname' => 'Пиков',
                            'name' => 'Артём',
                            'name2' => 'Сергеевич',
                            'phones' => array('+7 (8332) 76-15-35'),
                            'emails' => array('artem.pikov@kccc.ru', 'strada-kcc@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/pikov.png',
                        ),
                    ),
                ),
                'supply' => array(
                    'title' => t('Supply department'),
                    'contacts' => array(
                        array(
                            'office' => t('Head of department'),
                            'surname' => 'Сысольцев',
                            'name' => 'Константин',
                            'name2' => 'Викентьевич',
                            'phones' => array('+7 (8332) 76-15-36'),
                            'emails' => array('strada.snab@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/sysoltsev.png',
                        ),
                    ),
                ),
//                'marketing' => array(
//                    'title' => t('Marketing and advertising department'),
//                    'contacts' => array(
//                        array(
//                            'office' => t('Head of department'),
//                            'surname' => 'Нечаева',
//                            'name' => 'Екатерина',
//                            'name2' => 'Александровна',
//                            'phones' => array(),
//                            'emails' => array('ekaterina.nechaeva@kccc.ru'),
//                            'photo' => '/' . $module_path . '/images/photos/nechaeva.png',
//                        ),
//                    ),
//                ),
            ),
        ),
        'finfire' => array(
            'title' => t('Firefight'),
            'logo_on' => '/' . $module_path . '/images/logo/finfire_on.png',
            'logo_off' => '/' . $module_path . '/images/logo/finfire_off.png',
            'departments' => array(
                'sales' => array(
                    'title' => t('Sales department'),
                    'contacts' => array(
                        array(
                            'office' => t('Head of sales department'),
                            'surname' => 'Огородников',
                            'name' => 'Роман',
                            'name2' => 'Юрьевич',
                            'phones' => array('+7 (8332) 76-15-35', '8 (919) 529-86-85'),
                            'emails' => array('roman.ogorodnikov@kccc.ru'),
                            'photo' => $no_photo,
                        ),
                    ),
                ),
            ),
        ),
    );

    $query = db_select('taxonomy_term_data', 't');
    $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('regions')->vid);
    $query->fields('t', ['tid', 'name']);
    $regions_terms =  $query->execute()->fetchAllAssoc('tid');
    if ($regions_terms) {
        foreach ($contacts['td']['departments']['sales']['contacts'] as &$head) {
            foreach ($head['regions'] as $tid => &$region) {
                $region = ['name' => $regions_terms[$tid]->name];
            }
        }
    }


    return $contacts;
}
