<?php

define('CONTACTS_URL', 'info/contacts');

function contacts_menu()
{
    $items[CONTACTS_URL] = array(
        'title' => 'Departments contacts',
        'description' => 'Company contacts',
        'page callback' => 'contacts_main_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function contacts_theme()
{
    return array(
        'contacts_page' => array(
            'variables' => array('contacts' => NULL),
            'template' => 'templates/page',
        ),
    );
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function contacts_preprocess_page(&$vars)
{
    // установить для страницы параметры шапки
    if ($_GET['q'] == CONTACTS_URL) {
        $vars['header'] = array(
            'image' => url('/' . drupal_get_path('module', 'contacts') . '/images/header_image.jpg', array('absolute' => true)),
            'category_title' => '',
            'subtitle' => t('You can contact to our departments directly'),
            'print' => true,
        );
    }
}

// главная страница
function contacts_main_page()
{
    $contacts = contacts_get_contacts_list();

    // отрендерить карточки контактов
    foreach($contacts as $key_t => $tabs) {
        foreach($tabs['departments'] as $key_d => $department) {
            foreach($department['contacts'] as $key_c => $contact) {
                $collapse = [];
                if (!empty($contact['regions'])) {
                    $collapse['id'] = $key_c;
                    $collapse['title'] = t('Regions list');
                    $regions = [];
                    foreach ($contact['regions'] as $region) { $regions[] = $region; }
                    $collapse['content'] = implode(', ', $regions);
                }
                $contacts[$key_t]['departments'][$key_d]['contacts'][$key_c]['contact_html'] =
                  theme('contact_card', array(
                    'contact' => $contact,
                    'collapse' => $collapse,
                    'options' => ['class' => 'col-md-6'])
                  );
            }
        }
    }

    $html = theme('contacts_page', array('contacts' => $contacts));

    return $html;
};

function contacts_get_contacts_list()
{
    $module_path = drupal_get_path('module', 'contacts');
    $no_photo = '/sites/default/files/default_images/no_photo.png';

    $contacts = array(
        'td' => array(
            'title' => t('Trade House'),
            'logo_on' => '/' . $module_path . '/images/logo/td_on.png',
            'logo_off' => '/' . $module_path . '/images/logo/td_off.png',
            'departments' => array(
                'sales' => array(
                    'title' => t('Sales department'),
                ),
                'support' => array(
                    'title' => t('Control and support department'),
                ),
                'supply' => array(
                    'title' => t('Supply department'),
                ),
                'marketing' => array(
                    'title' => t('Marketing and advertising department'),
                ),
                'personnel' => array(
                    'title' => t('Personnel department'),
                ),
            ),
        ),
        'strada' => array(
            'title' => t('Home&Garden'),
            'logo_on' => '/' . $module_path . '/images/logo/strada_on.png',
            'logo_off' => '/' . $module_path . '/images/logo/strada_off.png',
            'departments' => array(
                'sales' => array(
                    'title' => t('Sales department'),
                    'contacts' => array(
                        array(
                            'subtitle' => t('Head of department'),
                            'title1' => 'Пиков',
                            'title2' => 'Артём Сергеевич',
                            'phones' => array('+7 (8332) 76-15-35'),
                            'emails' => array('artem.pikov@kccc.ru', 'strada-kcc@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/pikov.png',
                        ),
                    ),
                ),
                'supply' => array(
                    'title' => t('Supply department'),
                    'contacts' => array(
                        array(
                            'subtitle' => t('Head of department'),
                            'title1' => 'Сысольцев',
                            'title2' => 'Константин Викентьевич',
                            'phones' => array('+7 (8332) 76-15-36'),
                            'emails' => array('strada.snab@kccc.ru'),
                            'photo' => '/' . $module_path . '/images/photos/sysoltsev.png',
                        ),
                    ),
                ),
            ),
        ),
        'finfire' => array(
            'title' => t('Firefight'),
            'logo_on' => '/' . $module_path . '/images/logo/finfire_on.png',
            'logo_off' => '/' . $module_path . '/images/logo/finfire_off.png',
            'departments' => array(
                'sales' => array(
                    'title' => t('Sales department'),
                    'contacts' => array(
                        array(
                            'subtitle' => t('Head of sales department'),
                            'title1' => 'Огородников',
                            'title2' => 'Роман Юрьевич',
                            'phones' => array('+7 (8332) 76-15-35', '8 (919) 529-86-85'),
                            'emails' => array('roman.ogorodnikov@kccc.ru'),
                            'photo' => $no_photo,
                        ),
                    ),
                ),
            ),
        ),
    );

  $contacts_by_office = [];
  $users_by_office = ext_user_get_users_by_office([OFFICE_SALES_DEP_HEAD, OFFICE_SALES_DEP_HEAD_DEPUTY, OFFICE_SALES_HEAD]);
  foreach ($users_by_office as $office_tid => $office_users) {
    $counter = 1;
    foreach ($office_users as $user_uid => $user_info) {
      $weight = ext_user_get_office_weight($office_tid)*100 + $counter++;
      $contacts_by_office[$weight] = ext_user_get_user_contact($user_info['id']);
    }
  }
  ksort($contacts_by_office);
  $contacts['td']['departments']['sales']['contacts'] = array_values($contacts_by_office);

  $contacts_by_office = [];
  $users_by_office = ext_user_get_users_by_office([OFFICE_SUPPORT_MANAGER]);
  foreach ($users_by_office as $office_tid => $office_users) {
    $counter = 1;
    foreach ($office_users as $user_uid => $user_info) {
      $weight = ext_user_get_office_weight($office_tid)*100 + $counter++;
      $contacts_by_office[$weight] = ext_user_get_user_contact($user_info['id']);
    }
  }
  ksort($contacts_by_office);
  $contacts['td']['departments']['support']['contacts'] = array_values($contacts_by_office);

  $contacts_by_office = [];
  $users_by_office = ext_user_get_users_by_office([OFFICE_SUPPLY_HEAD, OFFICE_SUPPLY_MANAGER]);
  foreach ($users_by_office as $office_tid => $office_users) {
    $counter = 1;
    foreach ($office_users as $user_uid => $user_info) {
      $weight = ext_user_get_office_weight($office_tid)*100 + $counter++;
      $contacts_by_office[$weight] = ext_user_get_user_contact($user_info['id']);
    }
  }
  ksort($contacts_by_office);
  $contacts['td']['departments']['supply']['contacts'] = array_values($contacts_by_office);

  $contacts_by_office = [];
  $users_by_office = ext_user_get_users_by_office([OFFICE_MARKETING_HEAD, OFFICE_MARKETING_MANAGER]);
  foreach ($users_by_office as $office_tid => $office_users) {
    $counter = 1;
    foreach ($office_users as $user_uid => $user_info) {
      $weight = ext_user_get_office_weight($office_tid)*100 + $counter++;

      $contact = ext_user_get_user_contact($user_info['id']);
      // исключения
      if ($user_info['id'] == 6912) { // Широкова
        $contact['emails'] = null;
        $contact['phones'] = null;
      }
      $contacts_by_office[$weight] = $contact;
    }
  }
  ksort($contacts_by_office);

  $contacts['td']['departments']['marketing']['contacts'] = array_values($contacts_by_office);


  $contacts_by_office = [];
  $users_by_office = ext_user_get_users_by_office([OFFICE_ADMIN_HEAD_DEPUTY]);
  foreach ($users_by_office as $office_tid => $office_users) {
    $counter = 1;
    foreach ($office_users as $user_uid => $user_info) {
      $weight = ext_user_get_office_weight($office_tid)*100 + $counter++;
      $contacts_by_office[$weight] = ext_user_get_user_contact($user_info['id']);
    }
  }
  ksort($contacts_by_office);
  $contacts['td']['departments']['personnel']['contacts'] = array_values($contacts_by_office);

  return $contacts;
}
