<?php

/**
 * Implements of hook_views_api().
 */
function ext_views_views_api()
{
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ext_views') . '/views',
  );
}


/**
 * Implements hook_preprocess_page().
 */
function ext_views_preprocess_page(&$vars)
{
  if ($GLOBALS['theme'] == 'kccc') {
    if (in_array(arg(0), ['blog', 'video']))         { $vars['title'] = 'Публикации'; }
    if (in_array(arg(0), ['novosti', 'afisha']))     { $vars['title'] = 'События'; }
  }
}
