<?php

/**
 * Implements of hook_views_api().
 */
function ext_views_views_api()
{
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ext_views') . '/views',
  );
}

/**
 * Implements hook_theme()
 */
function ext_views_theme()
{
  return [
    'custom_view'    => [
      'variables' => ['view' => null, 'empty' => null],
      'template' => 'templates/custom-view',
    ],
    'custom_pager'    => [
      'variables' => ['query' => null, 'total' => null, 'per_page' => null],
    ],
  ];
}

function theme_custom_pager($vars)
{
  pager_default_initialize($vars['total'], $vars['per_page']);
  // пейджер формирует ссылку от текущего адреса, а он при ajax запросе = 'system/ajax'
  // поэтому меняем адрес на время формирования пейджера
  $bak = $_GET;
  $_GET = $vars['query'];
  $tags = ['«', '‹', ' ', '›', '»'];
  $pager = theme('pager', ['tags' => $tags]);
  $_GET = $bak;

  return $pager;
}

/**
 * Implements hook_preprocess_page().
 */
function ext_views_preprocess_page(&$vars)
{
  if ($GLOBALS['theme'] == 'kccc') {
    $banner_uri = '';
    if (in_array(arg(0), ['blog', 'video']))         {
      $vars['is_title_on'] = false;
      $vars['banner_title'] = t('Publications');
      $banner_uri = 'public://images/page-banners/blog.jpg';
    }
    if (in_array(arg(0), ['novosti', 'afisha']))     {
      $vars['banner_title'] = t('Events');
      $vars['is_title_on'] = false;
    }
    if (arg(0) == 'programmy-zashchity') {
      $vars['banner_title'] = t('Product portfolio for crop protection');
      $vars['is_title_on'] = false;
    }
    if (arg(0) == 'spravochniki') {
      $vars['banner_title'] = t('Handbooks');
      if (arg(1) == 'pesticidy') $vars['banner_title'] = t('Pesticides handbook');
      if (arg(1) == 'kultury') $vars['banner_title'] = t('Cultural plants handbook');
      if (arg(1) == 'sornye-rasteniya') $vars['banner_title'] = t('Weeds handbook');
      if (arg(1) == 'vrediteli') $vars['banner_title'] = t('Plants pests handbook');
      if (arg(1) == 'bolezni') $vars['banner_title'] = t('Plants diseases handbook');
    }
    if (arg(0) == 'vakansii') {
      $vars['banner_title'] = t('Careers');
    }
    if (in_array(arg(0), ['otzyvy', 'vakansii', 'preparaty-v-pole']))     {
      $vars['is_title_on'] = false;
    }

    if (in_array(arg(0), ['otzyvy', 'blog']))     {
      if (is_numeric(arg(1))) {
        if ($user_info = ext_user_get_user_info(arg(1))) {
          $vars['is_title_on'] = TRUE;
          $title = $user_info["label"] . ' ' . $user_info["main"]["name_short"];
          $vars['title'] = '';
          $vars['title_suffix'] = theme('card_contact', $user_info);
          drupal_set_title($vars['banner_title'] . '. ' . $title);
        }
      }
    }
    if ($banner_uri) {
      $vars['is_banner_on'] = true;
      $vars['banner_url'] = file_create_url($banner_uri);
      $vars['banner_mobile_url'] = image_style_url('banner_mobile', $banner_uri);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ext_views_preprocess_views_view_unformatted(&$vars)
{
  if ($vars['view']->name == 'search') {
    // скорректировать заголовок группы
//    $arr = ['Препараты в поле' => 'Примеры применения препаратов', 'Отзыв' => 'Отзывы', 'Блог' => 'Блоги', 'Справочник | Сорное растение' => 'Справочник сорных растений', 'Препарат' => 'Препараты',
//      'Программа защиты' => 'Программы защиты', 'Вакансия' => 'Вакансии', 'Справочник | Культура' => 'Справочник культур',
//      'Справочник | Болезнь культуры' => 'Справочник болезней культур', 'Справочник | Вредитель культуры' => 'Справочник вредителей культур', 'Новость' => 'Новости',
//      '' => ''];
    $arr = ['Препараты в поле' => t('Demonstration tests in the fields'), 'Отзыв' => t('Reviews'), 'Блог' => t('Blogs'),
      'Справочник | Сорное растение' => 'Справочник сорных растений', 'Препарат' => t('Products'),
      'Программа защиты' => 'Программы защиты', 'Вакансия' => 'Вакансии', 'Справочник | Культура' => 'Справочник культур',
      'Справочник | Болезнь культуры' => 'Справочник болезней культур', 'Справочник | Вредитель культуры' => 'Справочник вредителей культур', 'Новость' => 'Новости',
      '' => ''];
    $vars['title'] = $arr[$vars['title']] ?? $vars['title'];

    // размер карточек в зависимости от типа материала
    foreach ($vars['rows'] as $id => $result) {
      $class = 'col-xs-12 col-md-6';
      if (in_array($vars['view']->result[$id]->_entity_properties["type"], ['season', 'culture', 'weed', 'pest', 'disease', 'vacancy'])) {
        $class = 'col-xs-12 col-md-6 col-lg-4 col-xl-3';
      }
      if (in_array($vars['view']->result[$id]->_entity_properties["type"], ['blog', 'review', 'article', 'agenda'])) {
        $class = 'col-xs-12 col-md-6 col-xl-4';
      }
      $vars["classes_array"][$id] = $vars["classes_array"][$id] ? $vars["classes_array"][$id] . ' ' . $class : $class;
    }
  }
}

/**
 * Вернуть exposed form заданного view
 * https://pro-cosmos.blogspot.com/2011/08/exposed.html
 */
function ext_views_get_view_exposed_form($view_name, $display_id = 'page')
{
  if ($view = views_get_view($view_name)) {
    if ($view->access($display_id)) {
      $view->set_display($display_id);
      if (isset($view->display_handler)) {
        $view->init_handlers();
        if ($view->display_handler->uses_exposed()) {
          $exposed_form = $view->display_handler->get_plugin('exposed_form');
          $rendered_form = $exposed_form->render_exposed_form();
          $view->destroy();
          return $rendered_form;
        }
      }
    }
    $view->destroy();
  }

  drupal_set_message(t('Something went wrong'), 'error');
  return '';
}

/**
 * Implements hook_views_filters_selective_sort_alter().
 */
function ext_views_views_filters_selective_sort_alter(array &$oids, $handler)
{
  $items = $oids;
  // исключить из Selective фильтров значения Empty
  foreach($items as $key => $item) {
    if (strpos(drupal_strtolower($item), 'empty') !== false) unset($oids[$key]);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_views_form_views_exposed_form_alter(&$form, &$form_state, $form_id)
{
  // По умолчанию views не видит настройки фасетных фильтров на странице.
  // Если выполнить поиск в текстовой строке, то установки фасет блоков будут "забыты".
  // Проверяем наличие установленных фильтров и добавляем их к параметрам.
  // https://tech-tamer.com/drupal-7-refining-a-faceted-search-with-an-exposed-filter-solved/

  // Add facets as hidden inputs to preserve selection.
  if ( isset($_GET['k']) /* && ADD ANY OTHER VIEW-IDENTIFYING CODE DESIRED */ ) {
    // Get the parameters from the current page request.
    $params = drupal_get_query_parameters();
    // Add the facet values as hidden elements to the form.
    // The browser will turn them back into query parameters.
    foreach ( $params['k'] as $delta => $value ) {
      $form['f[' . $delta . ']'] = array(
        '#type' => 'hidden',
        '#value' => check_plain($value),
      );
    }
  }
}
