<?php

function representatives_menu()
{
  $items['info/representatives'] = array(
    'title' => 'Representatives',
    'description' => 'Company representatives',
    'page callback' => 'representatives_main_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['source/representatives'] = array(
    'page callback' => '_representatives_source_mobile',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['source/experts'] = array(
    'page callback' => '_experts_source_mobile',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}


function representatives_theme()
{
  return array(
    'representatives_page' => array(
      'variables' => array('representatives' => NULL),
      'template' => 'templates/page',
    ),
  );
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function representatives_preprocess_page(&$vars)
{
  // установить для страницы параметры шапки
  if ($_GET['q'] == 'info/representatives') {
    $image_url = '/' . drupal_get_path('module', 'representatives') . '/images/header_image.jpg';

    $vars['header'] = array(
      'image' => $image_url,
      'category_title' => '',
      'title' => t('Representatives'),
      'subtitle' => t('Our representatives will help you to select and buy products of ООО Trade House "Kirovo-Chepetsk Chemical Company"'),
      'print' => true,
    );
  }
}

// главная страница
function representatives_main_page()
{
  $module_path = drupal_get_path('module', 'representatives');
  drupal_add_js($module_path . '/js/representatives.js');
  drupal_add_css($module_path . '/css/representatives.css');

  drupal_add_js($module_path . '/js/jquery.mousewheel.min.js');
  drupal_add_js($module_path . '/js/jquery.mousewheel.min.js');
  drupal_add_js($module_path . '/js/mapsvg.js');
  drupal_add_css($module_path . '/css/mapsvg.css');
  drupal_add_css($module_path . '/css/nanoscroller.css');

  $html = '';

  $representatives_form = drupal_get_form('representatives_form');
  $html .= drupal_render($representatives_form);

  return $html;
};

function representatives_form($from, &$form_state)
{
  $form = [
    '#prefix' => '<div id="representatives-form-wrapper">',
    '#suffix' => '</div>',
    '#attributes' => ['class' => ['representatives-form']],
    'selector' => ['#type' => 'fieldset', '#title' => t('Search for area manager<i> by region</i>'), '#attributes' => ['id' => 'selector-wr']],
    'list' => ['#type' => 'fieldset', '#title' => ''],
  ];

  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', 29); // словарь 'regions'
  $query->innerJoin('taxonomy_term_hierarchy', 'h', 'h.tid = t.tid');
  $query->condition('h.parent', 0);
  $query->fields('t', array('tid', 'name'));
  $regions = $query->execute()->fetchAllKeyed();

  $options = ['' => t('Choose option')] + $regions;
  $form['selector']['region'] = [
    '#type' => 'select',
    '#title' => t('Region'),
    '#options' => $options,
    '#wrapper_attributes' => ['class' => ['col-md-6']],
    '#prefix' => '<div class="row">',
    '#ajax' => array(
      'callback' => 'representatives_form_refresh',
      'wrapper' => 'selector-wr',
    ),
  ];

  $contact_output = '';
  if (!empty($form_state['values']['region']) && $rep = representatives_get_sellers_by_office($form_state['values']['region'])) {
    // выбираем руководителя региона, если нет, то кластера
    $contact = array_pop($rep['heads']);
    $contact_output = theme('contact_card', ['contact' => $contact, 'options' => ['class' => 'col-md-6']]);
  }

  $form['selector']['contact'] = [
    '#markup' => $contact_output,
    '#suffix' => '</div>',
  ];

  $sales = representatives_get_sellers_by_office();
  drupal_add_js(['representatives' => ['sales' => $sales,]], 'setting');

  $form['list']['content'] = [
    '#markup' => theme('representatives_page', array('sales' => $sales)),
  ];

  return $form;
}

function representatives_form_refresh($form, $form_state)
{
  return $form['selector'];
}

/**
 * roles => Сотрудник
 * office (tid) => [OFFICE_SALES_DIRECTOR, OFFICE_SALES_HEAD, OFFICE_SALES_HEAD_DEPUTY, OFFICE_SALES_REPRESENTATIVE, OFFICE_SALES_EXPERT, OFFICE_SALES_SPECIALIST]
 */
//function representatives_sellers_list()
//{
//  $sellers = [];
//
//  $offices = [OFFICE_SALES_DIRECTOR, OFFICE_SALES_DEP_HEAD, OFFICE_SALES_DEP_HEAD_DEPUTY, OFFICE_SALES_HEAD, OFFICE_SALES_REPRESENTATIVE, OFFICE_SALES_EXPERT, OFFICE_SALES_SPECIALIST];
//
//  $users = ext_user_get_users_by_office($offices);
//
//  // todo можно выбрать только с конкретными должностями
//  $query = db_select('users', 'u');
//  $query->innerJoin('users_roles', 'ur', 'ur.uid = u.uid');
//  $query->condition('ur.rid', ROLE_STAFF);
//  $query->condition('u.status', 1);
//  $query->fields('u', array('uid'));
//  if ($staff = $query->execute()->fetchCol()) {
//    foreach ($staff as $staff_uid) {
//      $user_info = ext_user_get_user_info($staff_uid);
//      if (isset($user_info['staff']['offices']) && array_intersect(array_keys($user_info['staff']['offices']), $offices)) {
//      }
//    }
//  }
//
//  return $sellers;
//}

/**
 * список сотрудников Департамента продаж по должностям
 */
function representatives_get_sellers_by_office($filter_region_tid = null)
{
  // получаем список регионов
  $regions_by_tid = $regions_by_iso = [];
  if ($regions_terms = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('regions')->vid, 0 , null, true)) {
    foreach ($regions_terms as $region) {
      $iso = empty($region->field_iso_3166_2_ru['und'][0]) ? '' : $region->field_iso_3166_2_ru['und'][0]['value'];
      $regions_by_tid[$region->tid] = ['name' => $region->name, 'iso' => $iso];
      if ($iso) {
        $regions_by_iso[$iso] = ['name' => $region->name, 'tid' => $region->tid];
      }
    }
  }

  $offices = [OFFICE_SALES_DIRECTOR, OFFICE_SALES_DEP_HEAD, OFFICE_SALES_DEP_HEAD_DEPUTY, OFFICE_SALES_HEAD, OFFICE_SALES_REPRESENTATIVE, OFFICE_SALES_EXPERT, OFFICE_SALES_SPECIALIST];
  $users = ext_user_get_users_by_office($offices);
  $director = $heads = $reps = $exps = [];
  foreach ($users as $office_tid => $office_users) {
    foreach ($office_users as $user_uid => $user_info) {

      $seller = ext_user_get_user_contact($user_info['id'], 'staff');

      // формируем запись Продавца (из-за необходимости совместимости с приложением)
      $roles = [];
      if (isset($user_info['staff']['offices'][OFFICE_SALES_DIRECTOR])) $roles[] = 'director';
      if (isset($user_info['staff']['offices'][OFFICE_SALES_DEP_HEAD])) $roles[] = 'director_c';
      if (isset($user_info['staff']['offices'][OFFICE_SALES_DEP_HEAD_DEPUTY])) $roles[] = 'head';
      if (isset($user_info['staff']['offices'][OFFICE_SALES_HEAD])) $roles[] = 'manager';
      if (isset($user_info['staff']['offices'][OFFICE_SALES_REPRESENTATIVE])) $roles[] = 'representative';
      if (isset($user_info['staff']['offices'][OFFICE_SALES_EXPERT])) $roles[] = 'expert';
      if (isset($user_info['staff']['offices'][OFFICE_SALES_SPECIALIST])) $roles[] = 'specialist';

      $photo_url = image_style_url('user_photo', $user_info["photo_uri"]);

      $seller = array_merge($seller, [
        // для мобильного приложения
        'roles' =>  $roles,
        'expert' => $user_info["staff"]["ephone"] ? $user_info["staff"]["ephone"] : null,
        'surname' => $user_info["surname"],
        'name' => $user_info["name"],
        'name2' => $user_info["name2"],
        'photo' => $photo_url,
        // коллапс на десктопе
        'regions' => $user_info["staff"]["regions"],
      ]);

      if (empty($filter_region_tid) || isset($seller['regions'][$filter_region_tid])) {
        // транслит имён
        if ($GLOBALS['language']->language != 'ru') {
          if (isset($seller['surname'])) $seller['surname'] = translit($seller['surname']);
          if (isset($seller['name']))    $seller['name']    = translit($seller['name']);
          if (isset($seller['name2']))   $seller['name2']   = translit($seller['name2']);
          if (isset($seller['name2']))   $seller['name2']   = translit($seller['name2']);
          if (isset($seller['phone']))   $seller['phone']   = str_replace('доб.', 'add', $seller['phone']);
        }

        // заполнить инфо о регионе
        if (!empty($seller['regions'])) {
          foreach($seller['regions'] as $region_tid => &$region_arr) {
            $region_arr = empty($regions_by_tid[$region_tid]) ? [] : $regions_by_tid[$region_tid];
            if ($office_tid == OFFICE_SALES_REPRESENTATIVE) {
              $regions_by_iso[$regions_by_tid[$region_tid]['iso']]['reps'] = empty($regions_by_iso[$regions_by_tid[$region_tid]['iso']]['reps']) ? 1 : $regions_by_iso[$regions_by_tid[$region_tid]['iso']]['reps']+1;
            }
          }
        }

        // записать сотрудника с в массив с его должностью (у одного может быть несколько должностей)
        if ($office_tid == OFFICE_SALES_DIRECTOR) {
          $seller['emails'] = null;
          $seller['phones'] = null;
          $director = $seller;
        }
        if (in_array($office_tid, [OFFICE_SALES_DEP_HEAD, OFFICE_SALES_DEP_HEAD_DEPUTY, OFFICE_SALES_HEAD])) {
          $heads[$office_tid][] = $seller;
        }
        if ($office_tid == OFFICE_SALES_REPRESENTATIVE) {
          $reps[] = $seller;
        }
        if ($office_tid == OFFICE_SALES_EXPERT || $office_tid == OFFICE_SALES_SPECIALIST) {
          $exps[] = $seller;
        }
      }
    }
  }

  $heads_sorted = [];
  if (isset($heads[OFFICE_SALES_DEP_HEAD])) $heads_sorted += $heads[OFFICE_SALES_DEP_HEAD];
  if (isset($heads[OFFICE_SALES_DEP_HEAD_DEPUTY])) $heads_sorted += $heads[OFFICE_SALES_DEP_HEAD_DEPUTY];
  if (isset($heads[OFFICE_SALES_HEAD])) $heads_sorted += $heads[OFFICE_SALES_HEAD];

  return [
    'director' => $director,
    'heads' => $heads_sorted,
    'reps' => $reps,
    'experts' => $exps,
    'regions_by_tid' => $regions_by_tid,
    'regions_by_iso' => $regions_by_iso,
  ];
}


/**
 * callback function
 * источник данных о представителях (исп. в приложении)
 */
function _representatives_source_mobile($region_id = null)
{
  drupal_json_output(['representatives' => representatives_get_sellers_by_office($region_id)]);
  drupal_exit();
}

/**
 * callback function
 * источник данных об экспертах (исп. в приложении)
 */
function _experts_source_mobile($region_id = null)
{
  drupal_json_output(['representatives' => representatives_get_sellers_by_office($region_id)]);
  drupal_exit();
}


