<?php
function representatives_menu() {
  $items['info/representatives'] = array(
    'title' => 'Representatives',
    'description' => 'Company representatives',
    'page callback' => 'representatives_main_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['source/representatives'] = array(
    'page callback' => '_representatives_source',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['source/experts'] = array(
    'page callback' => '_experts_source',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}


function representatives_theme() {
  return array(
    'representatives_page' => array(
      'variables' => array('representatives' => NULL),
      'template' => 'templates/page',
    ),
  );
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function representatives_preprocess_page(&$vars) {
  // установить для страницы параметры шапки
  if ($_GET['q'] == 'info/representatives') {
    $image_url = '/' . drupal_get_path('module', 'representatives') . '/images/header_image.jpg';

    $vars['header'] = array(
      'image' => $image_url,
      'category_title' => '',
      'title' => t('Representatives'),
      'subtitle' => t('Our representatives will help you to select and buy products of ООО Trade House "Kirovo-Chepetsk Chemical Company"'),
      'print' => true,
    );
  }
}

// главная страница
function representatives_main_page()
{
  $module_path = drupal_get_path('module', 'representatives');
  drupal_add_js($module_path . '/js/representatives.js');
  drupal_add_css($module_path . '/css/representatives.css');

  drupal_add_js($module_path . '/js/jquery.mousewheel.min.js');
  drupal_add_js($module_path . '/js/jquery.mousewheel.min.js');
  drupal_add_js($module_path . '/js/mapsvg.js');
  drupal_add_css($module_path . '/css/mapsvg.css');
  drupal_add_css($module_path . '/css/nanoscroller.css');

  $html = '';

  $representatives_form = drupal_get_form('representatives_form');
  $html .= drupal_render($representatives_form);

  return $html;
};

function representatives_form($from, &$form_state)
{
  $form = [
    '#prefix' => '<div id="representatives-form-wrapper">',
    '#suffix' => '</div>',
    '#attributes' => ['class' => ['representatives-form']],
    'selector' => ['#type' => 'fieldset', '#title' => t('Search for area manager<i> by region</i>'), '#attributes' => ['id' => 'selector-wr']],
    'list' => ['#type' => 'fieldset', '#title' => ''],
  ];

  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', 29); // словарь 'regions'
  $query->innerJoin('taxonomy_term_hierarchy', 'h', 'h.tid = t.tid');
  $query->condition('h.parent', 0);
  $query->fields('t', array('tid', 'name'));
  $regions = $query->execute()->fetchAllKeyed();

  $options = ['' => t('Choose option')] + $regions;
  $form['selector']['region'] = [
    '#type' => 'select',
    '#title' => t('Region'),
    '#options' => $options,
    '#wrapper_attributes' => ['class' => ['col-md-6']],
    '#prefix' => '<div class="row">',
    '#ajax' => array(
      'callback' => 'representatives_form_refresh',
      'wrapper' => 'selector-wr',
    ),
  ];

  $contact = '';
  if (!empty($form_state['values']['region']) && $rep = representatives_get_sales($form_state['values']['region'])) {
    // выбираем руководителя региона, если нет, то кластера
    $contact = theme('contact_card', ['contact' => array_pop($rep['heads']), 'options' => ['class' => 'col-md-6']]);
  }

  $form['selector']['contact'] = [
    '#markup' => $contact,
    '#suffix' => '</div>',
  ];

  $sales = representatives_get_sales();
  drupal_add_js(['representatives' => ['sales' => $sales,]], 'setting');

  $form['list']['content'] = [
    '#markup' => theme('representatives_page', array('sales' => $sales)),
  ];

  return $form;
}

function representatives_form_refresh($form, $form_state)
{
  return $form['selector'];
}

/**
 * roles => c_head, r_head, rep, exp
 */
function representatives_sales_list()
{
  $module_path = drupal_get_path('module', 'representatives');
  $no_photo = '/sites/default/files/default_images/no_photo.png';

  $sales[] = array(
    'roles' =>  ['director'],
    'icon_l_path' => $module_path . '/images/icons/light/',
    'icon_d_path' => $module_path . '/images/icons/dark/',
    'region_path' => $module_path. '/images/map/',
    'surname' => 'Потапов', 'name' => 'Денис', 'name2' => 'Викторович',
    'phones' => [],
    'emails' => [],
    'photo' => '/' . $module_path . '/images/photos/potapov.png',
  );
  $sales[] = array(
    'roles' =>  ['director_c'],
    'access' => true,
    'surname' => 'Рудяк', 'name' => 'Дмитрий', 'name2' => 'Вячеславович',
    'phones' => array('+7 (8332) 76-15-31, доб. 1187', '+7 (912) 726-36-23'),
    'emails' => array('dmitry.rudyak@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/rudyak.png',
    'regions' => [],
  );
  $sales[] = array(
    'roles' =>  ['director_c'],
    'access' => true,
    'surname' => 'Камнева', 'name' => 'Юлия', 'name2' => 'Юрьевна',
    'phones' => array('+7 (8332) 76-15-32, доб. 1219', '+7 (922) 910-03-68', '+7 (912) 714-75-41'),
    'emails' => array('td.sale15@kccc.ru'),
    'photo' => $no_photo,
    'regions' => [
      71668 => [], //Алтайский край",
      71674 => [], //Амурская область",
      71681 => [], //Вологодская область",
      71725 => [], //Еврейская АО",
      71721 => [], //Забайкальский край",
      71684 => [], //Иркутская область",
      71686 => [], //Калужская область",
      71688 => [], //Кемеровская область",
      71670 => [], //Красноярский край",
      71692 => [], //Курская область",
      71700 => [], //Новосибирская область",
      71698 => [], //Нижегородская область",
      71699 => [], //Новговродская область",
      71702 => [], //Оренбургская область",
      71701 => [], //Омская область",
      71704 => [], //Пензенская область",
      71671 => [], //Приморский край",
      71706 => [], //Псковская область",
      71648 => [], //Республика Башкортостан",
      71649 => [], //Республика Бурятия",
      71658 => [], //Республика Марий Эл",
      71659 => [], //Республика Мордовия",
      71663 => [], //Республика Тыва",
      71665 => [], //Республика Хакасия",
      71708 => [], //Рязанская область",
      71712 => [], //Свердловская область",
      71713 => [], //Смоленская область",
      71718 => [], //Тюменская область",
      71715 => [], //Тверская область",
      71716 => [], //Томская область",
      71717 => [], //Тульская область",
      71719 => [], //Ульяновская область',
      71673 => [], //Хабаровский край",
      71720 => [], //Челябинская область",
      71667 => [], //Чувашская Республика",
    ],
  );
  $sales[] = array(
    'roles' =>  ['head'],
    'access' => true,
    'surname' => 'Шуклина', 'name' => 'Наталья', 'name2' => 'Геннадьевна',
    'phones' => array('+7 (8332) 76-15-28, доб. 1154', '+7 922 936-16-62'),
    'emails' => array('natalia.shuklina@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/shuklina_n.png',
    'regions' => array(
      71675 => [], //Архангельская область",
      71696 => [], //Москва и Московская область",
      71706 => [], //Псковская область",
      71654 => [], //Республика Калмыкия",
      71662 => [], //Республика Татарстан,
      71709 => [], //Самарская область',
      71693 => [], //Санкт-Петербург и область",
      71713 => [], //Смоленская область",
      71715 => [], //Тверская область",
      71664 => [], //Удмуртская Республика",
      71722 => [], //Ярославская область",
      71679 => [], //Владимирская область",
      71683 => [], //Ивановская область",
      71689 => [], //Кировская область",
      71690 => [], //Костромская область",
      71705 => [], //Пермский край",


//            71679 => [], //Владимирская область",
//            71681 => [], //Вологодская область",
//            71683 => [], //Ивановская область",
//            71689 => [], //Кировская область",
//            71653 => [], //Кабардино-Балкарская Республика",
//            71655 => [], //Карачаево-Черкесская Республика",
//            71685 => [], //Калининградская область",
//            71690 => [], //Костромская область",
//            71697 => [], //Мурманская область",
//
//            71705 => [], //Пермский край",
//
//          // чикин
//          71698 => [], //Нижегородская область",
//
//          // крупин
//          71686 => [], //Калужская область",
//          71699 => [], //Новгородская область",
//          71708 => [], //Рязанская область",
//          71717 => [], //Тульская область",

    ),
  );
  $sales[] = array(
    'roles' =>  ['manager'],
    'access' => true,
    'surname' => 'Устюжанин', 'name' => 'Данила', 'name2' => 'Игоревич',
    'phones' => array('+7 (912) 738-11-11'),
    'emails' => array('td.sale1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/ustyuzhanin.png',
    'regions' => array(
      71691 => [], //Курганская область",
      71702 => [], //Оренбургская область",
      71704 => [], //Пензенская область",
      71648 => [], //Республика Башкортостан",
      71659 => [], //Республика Мордовия",
      71710 => [], //Саратовская область',
      71712 => [], //Свердловская область",
      71718 => [], //Тюменская область",
      71719 => [], //Ульяновская область',
      71720 => [], //Челябинская область",


//            71676 => [], //Астраханская область",
//            71725 => [], //Еврейская АО",
//            71721 => [], //Забайкальский край",
//            71684 => [], //Иркутская область",
//            71687 => [], //Камчатский край",
//            71688 => [], //Кемеровская область",
//            71670 => [], //Красноярский край",
//            71695 => [], //Магаданская область",
//            71700 => [], //Новосибирская область",
//            71701 => [], //Омская область",
//            71671 => [], //Приморский край",
//            71650 => [], //Республика Алтай",
//            71649 => [], //Республика Бурятия",
//            71658 => [], //Республика Марий Эл",
//            71660 => [], //Республика Саха (Якутия)",
//            71663 => [], //Республика Тыва",
//            71665 => [], //Республика Хакасия",
//            71711 => [], //Сахалинская область",
//            71716 => [], //Томская область",
//            71673 => [], //Хабаровский край",
//            71727 => [], //Ханты-Мансийский АО - Югра",
//            71667 => [], //Чувашская Республика",
//            71728 => [], //Чукотский АО",
//            71729 => [], //Ямало-Ненецкий АО",
    ),
  );
  $sales[] = array(
    'roles' =>  ['manager'],
    'access' => true,
    'surname' => 'Князев', 'name' => 'Алексей', 'name2' => 'Юрьевич',
    'phones' => array('+7 (912) 700-12-07'),
    'emails' => array('td.sale2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/knyazev.png',
    'regions' => array(
      71680 => [], //Волгоградская область",
      71653 => [], //Кабардино-Балкарская Республика",
      71655 => [], //Карачаево-Черкесская Республика",
      71685 => [], //Калининградская область",
      71669 => [], //Краснодарский край",
      71647 => [], //Республика Адыгея",
      71651 => [], //Республика Дагестан",
      71652 => [], //Республика Ингушетия",
      71730 => [], //Республика Крым",
      71661 => [], //Республика Северная Осетия - Алания",
      71707 => [], //Ростовская область",
      71731 => [], //Севастополь",
      71672 => [], //Ставропольский край",
      71666 => [], //Чеченская Республика",
    ),
  );

  /** ------------------------ Представители --------------------------------------------------------------------- */
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Маринина', 'name' => 'Лариса', 'name2' => 'Валентиновна',
    'phones' => array('+7 (922) 927-70-60'),
    'emails' => array('altai@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/altai.png',
    'regions' => array(
      71668 => [], //Алтайский край",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Хаустов', 'name' => 'Сергей', 'name2' => 'Витальевич',
    'phones' => array('+7 (922) 927-68-80'),
    'emails' => array('altai2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/haustov.png',
    'regions' => array(
      71668 => [], //Алтайский край",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Мизюков', 'name' => 'Владимир', 'name2' => 'Александрович',
    'phones' => array('+7 (922) 903-02-57'),
    'emails' => array('amur.region2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/mizukov_v.png',
    'regions' => array(
      71674 => [], //Амурская область",
    ),
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Левшин', 'name' => 'Петр', 'name2' => 'Иванович',
//        'phones' => array('+7 (922) 927-80-90'),
//        'emails' => array('belgorod@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/belgorod.png',
//        'regions' => array(
//            71677 => [], //Белгородская область",
//        ),
//    );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Головин', 'name' => 'Александр', 'name2' => 'Николаевич',
//        'phones' => array('+7 (922) 908-44-10'),
//        'emails' => array('belgorod1@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/golovin.png',
//        'regions' => array(
//            71677 => [], //Белгородская область",
//        ),
//    );

  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => true,
    'surname' => 'Асадов', 'name' => 'Кирилл', 'name2' => 'Низамович',
    'phones' => array('+7 (929) 209-60-40'),
    'emails' => array('voronezh@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/asadov.png',
    'regions' => array(
      71682 => [], //Воронежская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Халецкий', 'name' => 'Александр', 'name2' => 'Викторович',
    'phones' => array('+7 (929) 209-92-21'),
    'emails' => array('voronezh1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/khaletskiy.png',
    'regions' => array(
      71682 => [], //Воронежская область",
    ),
  );

//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => '', 'name' => '', 'name2' => '',
//        'phones' => array('+7 (922) 936-10-14'),
//        'emails' => array('kaliningrad@kccc.ru'),
//        'photo' => $no_photo,
//        'regions' => array(
//            71685 => [], //Калининградская область",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => true,
    'surname' => 'Иосипчук', 'name' => 'Андрей', 'name2' => 'Викторович',
    'phones' => array('+7 (912) 825-47-45', '8 (8332) 75-20-55'),
    'emails' => array('kirov@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/kirov.png',
    'regions' => array(
      71679 => [], //Владимирская область",
      71683 => [], //Ивановская область",
      71689 => [], //Кировская область",
      71690 => [], //Костромская область",
      71705 => [], //Пермский край",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Бойко ', 'name' => 'Павел', 'name2' => 'Валерьевич',
    'phones' => array('+7 (922) 900-01-52'),
    'emails' => array('irkutsk@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/boiko_p.png',
    'regions' => array(
      71684 => [], //Иркутская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Савенко', 'name' => 'Алексей', 'name2' => 'Михайлович',
    'phones' => array('+7 (922) 969-47-05'),
    'emails' => array('krasnoyarsk@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/savenko.png',
    'regions' => array(
      71670 => [], //Красноярский край",
    ),
  );
  $sales[] = array(
    'roles' =>  ['specialist'],
    'access' => false,
    'surname' => 'Родченко', 'name' => 'Максим', 'name2' => 'Сергеевич',
    'phones' => array('+7 (922) 902-27-78'),
    'expert' => '+7 (922) 902-27-78',
    'emails' => array('krasnoyarsk2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/rodchenko_m.png',
    'regions' => array(
      71670 => [], //Красноярский край",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Домницкая', 'name' => 'Виктория', 'name2' => 'Николаевна',
    'phones' => array('+7 (922) 900-05-73'),
    'emails' => array('krasnodar@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/domnitskaya.png',
    'regions' => array(
      71669 => [], //Краснодарский край",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Петров', 'name' => 'Николай', 'name2' => 'Викторович',
    'phones' => array('+7 (922) 957-11-19'),
    'emails' => array('krasnodar4@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/petrov_n.png',
    'regions' => array(
      71669 => [], //Краснодарский край",
    ),
  );
//  $sales[] = array(
//    'roles' =>  ['representative'],
//    'access' => false,
//    'surname' => 'Лысенко', 'name' => 'Иван', 'name2' => 'Игоревич',
//    'phones' => array('+7 (922) 900-74-41'),
//    'emails' => array('krasnodar2@kccc.ru'),
//    'photo' => '/' . $module_path . '/images/photos/lisenko_i.png',
//    'regions' => array(
//      71669 => [], //Краснодарский край",
//    ),
//  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Постникова', 'name' => 'Наталья', 'name2' => 'Николаевна',
    'phones' => array('+7 (922) 922-76-22'),
    'emails' => array('kursk1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/postnikova_n.png',
    'regions' => array(
      71692 => [], //Курская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Курасов', 'name' => 'Сергей', 'name2' => 'Евгеньевич',
    'phones' => array('+7 (922) 922-76-10'),
    'emails' => array('kursk2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/kurasov_s.png',
    'regions' => array(
      71692 => [], //Курская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Плешков', 'name' => 'Владимир', 'name2' => 'Геннадьевич',
    'phones' => array('+7 (922) 908-41-44'),
    'emails' => array('lipetsk@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/pleshkov.png',
    'regions' => array(
      71694 => [], //Липецкая область",
    )
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Соломахин', 'name' => 'Николай', 'name2' => 'Викторович',
//        'phones' => array('+7 (922) 966-60-12'),
//        'emails' => array('lipetsk2@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/solomahin_n.png',
//        'regions' => array(
//            71694 => [], //Липецкая область",
//        )
//    );
  $sales[] =  array(
    'roles' =>  ['expert'],
    'surname' => 'Бекасова', 'name' => 'Марина', 'name2' => 'Викторовна',
    'phones' => array('+7 (922) 999-11-47'),
    'expert' => '+7 (922) 999-11-47',
    'emails' => array('novosibirsk1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/bekasova.png',
    'regions' => array(
      71674 => [], //Амурская область",
      71670 => [], //Красноярский край",
      71700 => [], //Новосибирская область",
      71701 => [], //Омская область",
      71668 => [], //Алтайский край",
    ),
  );
  $sales[] =  array(
    'roles' =>  ['representative'],
    'surname' => 'Дамоевский', 'name' => 'Алексей', 'name2' => 'Владимирович',
    'phones' => array('+7 (922) 966-64-34'),
    'emails' => array('novosibirsk2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/damoevskiy_a.png',
    'regions' => array(
      71700 => [], //Новосибирская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => true,
    'surname' => 'Якимов', 'name' => 'Евгений', 'name2' => 'Леонидович',
    'phones' => array('+7 922 925-88-84'),
    'emails' => array('td.sale11@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/yakimov.png',
    'regions' => array(
      71700 => [], //Новосибирская область",
//      71668 => [], //Алтайский край",
//      71674 => [], //Амурская область",
//      71725 => [], //Еврейская АО",
//      71721 => [], //Забайкальский край",
//      71684 => [], //Иркутская область",
//      71688 => [], //Кемеровская область",
//      71670 => [], //Красноярский край",
//      71701 => [], //Омская область",
//      71671 => [], //Приморский край",
//      71650 => [], //Республика Алтай",
//      71716 => [], //Томская область",
//      71673 => [], //Хабаровский край",
//      71649 => [], //Республика Бурятия",
//      71660 => [], //Республика Саха (Якутия)",
//      71663 => [], //Республика Тыва",
//      71665 => [], //Республика Хакасия",
//      71728 => [], //Чукотский АО",
    ),
  );

//    $sales[] =  array(
//        'roles' =>  ['representative'],
//        'surname' => '', 'name' => '', 'name2' => '',
//        'phones' => array('+7 (922) 966-60-12'),
//        'emails' => array('n.novgorod@kccc.ru'),
//        'photo' => $no_photo,
//        'regions' => array(
//            71698 => [], //Нижегородская область",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Усатов', 'name' => 'Валерий', 'name2' => 'Васильевич',
    'phones' => array('+7 (922) 900-74-73'),
    'emails' => array('omsk@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/usatov_v.png',
    'regions' => array(
      71701 => [], //Омская область",
    ),
  );
    $sales[] = array(
        'roles' =>  ['representative'],
        'access' => false,
        'surname' => 'Фукс', 'name' => 'Алексей', 'name2' => 'Павлович',
        'phones' => array('+7 (922) 900-02-01'),
        'emails' => array('omsk1@kccc.ru'),
        'photo' => '/' . $module_path . '/images/photos/fuks_a.png',
        'regions' => array(
            71701 => [], //Омская область",
        ),
    );
//  $sales[] = array(
//    'roles' =>  ['representative', 'expert'],
//    'access' => false,
//    'surname' => 'Токарев', 'name' => 'Виктор', 'name2' => 'Анатольевич',
//    'expert' => '+7 (922) 555-08-96',
//    'phones' => array('+7 (922) 966-05-52'),
//    'emails' => array('orenburg3@kccc.ru'),
//    'photo' => '/' . $module_path . '/images/photos/tokarev.png',
//    'regions' => array(
//      71702 => [], //Оренбургская область",
//    ),
//  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => true,
    'surname' => 'Попов', 'name' => 'Виктор', 'name2' => 'Михайлович',
    'phones' => array('+7 922 966-65-00'),
    'emails' => array('orenburg@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/popov.png',
    'regions' => array(
      71702 => [], //Оренбургская область",
    ),
  );

  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Бурлаков', 'name' => 'Владимир', 'name2' => 'Григорьевич',
    'phones' => array('+7 (922) 970-60-55'),
    'emails' => array('orenburg5@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/burlakov_v.png',
    'regions' => array(
      71702 => [], //Оренбургская область",
    ),
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Неретин', 'name' => 'Максим', 'name2' => 'Сергеевич',
//        'phones' => array('+7 (922) 970-65-00'),
//        'emails' => array('orenburg4@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/neretin.png',
//        'regions' => array(
//            71702 => [], //Оренбургская область",
//        ),
//    );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Боронкин', 'name' => 'Андрей', 'name2' => 'Михайлович',
//        'phones' => array('+7 (922) 970-60-55'),
//        'emails' => array('orenburg5@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/boronkin.png',
//        'regions' => array(
//            71702 => [], //Оренбургская область",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Юдин', 'name' => 'Сергей', 'name2' => 'Васильевич',
    'phones' => array('+7 (922) 900-01-22'),
    'emails' => array('penza1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/yudin.png',
    'regions' => array(
      71704 => [], //Пензенская область",
    ),
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Кобозев', 'name' => 'Сергей', 'name2' => 'Валерьевич',
//        'phones' => array('+7 (922) 900-07-73'),
//        'emails' => array('penza2@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/kobozev.png',
//        'regions' => array(
//            71704 => [], //Пензенская область",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Калинин', 'name' => 'Александр', 'name2' => 'Александрович',
    'phones' => array('+7 (929) 209-00-80'),
    'emails' => array('penza3@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/kalinin.png',
    'regions' => array(
      71704 => [], //Пензенская область",
    ),
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Агеев', 'name' => 'Дмитрий', 'name2' => 'Анатольевич',
//        'phones' => array('+7 (929) 209-00-90'),
//        'emails' => array('penza4@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/ageev_da.png',
//        'regions' => array(
//            71704 => [], //Пензенская область",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Тураев', 'name' => 'Радик', 'name2' => 'Галиевич',
    'phones' => array('+7 (922) 900-74-77'),
    'emails' => array('bashkortostan@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/bashkortostan.png',
    'regions' => array(
      71648 => [], //Республика Башкортостан",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Зарипов', 'name' => 'Эльвир', 'name2' => 'Зирякович',
    'phones' => array('+7 (922) 665-00-15'),
    'emails' => array('bashkortostan1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/zaripov.png',
    'regions' => array(
      71648 => [], //Республика Башкортостан",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Агеев', 'name' => 'Сергей', 'name2' => 'Евгеньевич',
    'phones' => array('+7 (922) 900-75-85'),
    'emails' => array('mordoviya@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/ageev_s.png',
    'regions' => array(
      71659 => [], //Республика Мордовия",
    ),
  );

//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Швец', 'name' => 'Олег', 'name2' => 'Викторович',
//        'phones' => array('+7 (922) 900-14-43', '+7 (909) 435-82-89'),
//        'emails' => array('rostov2@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/shvets.png',
//        'regions' => array(
//            71707 => [], //Ростовская область",
//        ),
//    );
//    $sales[] = array(
//        'roles' =>  ['expert'],
//        'access' => false,
//        'surname' => 'Четвертаков', 'name' => 'Максим', 'name2' => 'Викторович',
//        'phones' => array('+7 (922) 955-60-07'),
//        'expert' => '+7 (922) 955-60-07',
//        'emails' => array('rostov3@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/chetvertakov.png',
//        'regions' => array(
//          71707 => [], //Ростовская область",
//          71672 => [], //Ставропольский край",
//          71669 => [], //Краснодарский край",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Сейранов', 'name' => 'Карен', 'name2' => 'Николаевич',
    'phones' => array('+7 (922) 957-10-20'),
    'emails' => array('rostov4@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/seiranov.png',
    'regions' => array(
      71707 => [], //Ростовская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Русанов', 'name' => 'Алексей', 'name2' => 'Владимирович',
    'phones' => array('+7 (918) 742-67-28', '+7 (922) 966-59-77'),
    'emails' => array('stavropol@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/rusanov.png',
    'regions' => array(
      71672 => [], //Ставропольский край",
    ),
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Епифанов', 'name' => 'Александр', 'name2' => 'Владимирович',
//        'phones' => array('+7 (922) 970-66-46'),
//        'emails' => array('stavropol1@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/epifanov.png',
//        'regions' => array(
//            71672 => [], //Ставропольский край",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
//        'expert' => '+7 (902) 730-80-22',
    'surname' => 'Сироткин', 'name' => 'Евгений', 'name2' => 'Николаевич',
    'phones' => array('+7 (922) 966-59-88'),
    'emails' => array('tambov@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/sirotkin_e.png',
    'regions' => array(
      71714 => [], //Тамбовская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Сироткин', 'name' => 'Николай', 'name2' => 'Николаевич',
    'phones' => array('+7 (922) 967-12-55'),
    'emails' => array('tambov2@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/sirotkin_n.png',
    'regions' => array(
      71714 => [], //Тамбовская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Дёмин', 'name' => 'Андрей', 'name2' => 'Дмитриевич',
    'phones' => array('+7 (922) 665-01-07'),
    'emails' => array('tambov1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/demin.png',
    'regions' => array(
      71714 => [], //Тамбовская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Знаменщиков', 'name' => 'Василий', 'name2' => 'Александрович',
    'phones' => array('+7 (922) 966-60-04'),
    'emails' => array('tyumen@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/tyumen.png',
    'regions' => array(
      71718 => [], //Тюменская область",
    ),
  );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Пиленков', 'name' => 'Михаил', 'name2' => 'Владимирович',
//        'phones' => array('+7 (922) 900-23-43'),
//        'emails' => array('tyumen1@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/pilenkov.png',
//        'regions' => array(
//            71718 => [], //Тюменская область",
//        ),
//    );
//    $sales[] = array(
//        'roles' =>  ['representative'],
//        'access' => false,
//        'surname' => 'Основин', 'name' => 'Александр', 'name2' => 'Анатольевич',
//        'phones' => array('+7 (922) 966-60-16'),
//        'emails' => array('tyumen2@kccc.ru'),
//        'photo' => '/' . $module_path . '/images/photos/osnovin.png',
//        'regions' => array(
//            71718 => [], //Тюменская область",
//        ),
//    );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Микряшов', 'name' => 'Владислав', 'name2' => 'Вячеславович',
    'phones' => array('+7 (912) 332-99-69'),
    'emails' => array('udmurtia@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/udmurtia.png',
    'regions' => array(
      71664 => [], //Удмуртская Республика",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Гималов', 'name' => 'Радик', 'name2' => 'Ревгатович',
    'phones' => array('+7 (922) 903-02-46'),
    'emails' => array('ulyanovsk@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/gimalov_r.png',
    'regions' => array(
      71719 => [], //Ульяновская область',
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Солодовников', 'name' => 'Александр', 'name2' => 'Васильевич',
    'phones' => array('+7 (922) 747-26-41'),
    'emails' => array('chelyabinsk@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/solodovnikov_a.png',
    'regions' => array(
      71720 => [], //Челябинская область",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Подкорытов', 'name' => 'Дмитрий', 'name2' => 'Александрович',
    'phones' => array('+7 (922) 747-26-40'),
    'emails' => array('chelyabinsk1@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/podkoritov_d.png',
    'regions' => array(
      71720 => [], //Челябинская область",
    ),
  );
//  $sales[] = array(
//    'roles' =>  ['specialist'],
//    'access' => false,
//    'surname' => 'Красножон', 'name' => 'Сергей', 'name2' => 'Михайлович',
//    'phones' => array('+7 (922) 747-26-46'),
//    'expert' => '+7 (922) 747-26-46',
//    'emails' => array('chelyabinsk2@kccc.ru'),
//    'photo' => '/' . $module_path . '/images/photos/krasnozhon.png',
//    'regions' => array(
//      71720 => [], //Челябинская область",
//    ),
//  );
  $sales[] = array(
    'roles' =>  ['expert'],
    'access' => false,
    'surname' => 'Саитов', 'name' => 'Салимхан', 'name2' => 'Букумбаевич',
    'phones' => array('+7 (922) 967-12-55'),
    'expert' => '+7 (922) 967-12-55',
    'emails' => array('chelyabinsk3@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/saitov_s.png',
    'regions' => array(
      71720 => [], //Челябинская область",
      71702 => [], //Оренбургская область",
      71704 => [], //Пензенская область",
      71648 => [], //Республика Башкортостан",
      71719 => [], //Ульяновская область',
      71718 => [], //Тюменская область",
      71659 => [], //Республика Мордовия",
    ),
  );
  $sales[] = array(
    'roles' =>  ['representative'],
    'access' => false,
    'surname' => 'Шалаев', 'name' => 'Андрей', 'name2' => 'Сергеевич',
    'phones' => array('+7 (922) 905-89-84'),
    'emails' => array('chelyabinsk4@kccc.ru'),
    'photo' => '/' . $module_path . '/images/photos/shalaev_a.png',
    'regions' => array(
      71720 => [], //Челябинская область",
    ),
  );

  return $sales;
}


/**
 * callback function
 * источник данных о представителях (исп. в приложении)
 */
function _representatives_source($region_id = null)
{
  drupal_json_output(['representatives' => representatives_get_sales($region_id)]);
  drupal_exit();
}

/**
 * используется в корзине
 * @return array|mixed
 */
function representatives_get_sales($tid = null)
{
  // получаем список регионов
  $regions_by_tid = $regions_by_iso = [];
  if ($regions_terms = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('regions')->vid, 0 , null, true)) {
    foreach ($regions_terms as $region) {
      $iso = empty($region->field_iso_3166_2_ru['und'][0]) ? '' : $region->field_iso_3166_2_ru['und'][0]['value'];
      $regions_by_tid[$region->tid] = ['name' => $region->name, 'iso' => $iso];
      if ($iso) {
        $regions_by_iso[$iso] = ['name' => $region->name, 'tid' => $region->tid];
      }
    }
  }

  $sales = [];
  foreach (representatives_sales_list() as $sale) {
    // транслит имён
    if ($GLOBALS['language']->language != 'ru') {
      if (isset($sale['surname'])) $sale['surname'] = translit($sale['surname']);
      if (isset($sale['name']))    $sale['name'] = translit($sale['name']);
      if (isset($sale['name2']))   $sale['name2'] = translit($sale['name2']);
      if (isset($sale['name2']))   $sale['name2'] = translit($sale['name2']);
      if (isset($sale['phones'])) {
        foreach($sale['phones'] as $key => $phone) {
          $sale['phones'][$key] = str_replace('доб.', 'add', $phone);
        }
      }
    }

    // заполнить инфо о регионе
    if (!empty($sale['regions'])) {
      foreach($sale['regions'] as $region_tid => &$region_arr) {
        $region_arr = empty($regions_by_tid[$region_tid]) ? [] : $regions_by_tid[$region_tid];
        if (in_array('representative', $sale['roles'])) {
          $regions_by_iso[$regions_by_tid[$region_tid]['iso']]['reps'] = empty($regions_by_iso[$regions_by_tid[$region_tid]['iso']]['reps']) ? 1 : $regions_by_iso[$regions_by_tid[$region_tid]['iso']]['reps']+1;
        }
      }
    }

    // руководители
    if (in_array('director', $sale['roles']) || in_array('director_c', $sale['roles'])
      || in_array('head', $sale['roles']) || in_array('manager', $sale['roles'])) {
      if (!isset($tid) || isset($sale['regions'][$tid])) {
        $sale['office'] = representatives_get_office($sale['roles'][0]);
        $sales['heads'][] = $sale;
      }
    }

    // представители
    if (in_array('representative', $sale['roles'])) {
      if (!isset($tid) || isset($sale['regions'][$tid])) {
        $sale['office'] = representatives_get_office('representative');
        $sales['reps'][] = $sale;
      }
    }

    // эксперты
    if ((in_array('expert', $sale['roles']) || in_array('specialist', $sale['roles']))) {
      if (!empty($sale['expert'])) {
        if (in_array('expert', $sale['roles'])) {
          $sale['office'] = representatives_get_office('expert');
        }
        if (in_array('specialist', $sale['roles'])) {
          $sale['office'] = representatives_get_office('specialist');
        }
        $sales['experts'][] = $sale;
      }
    }
  }




  $sales['regions_by_tid'] = $regions_by_tid;
  $sales['regions_by_iso'] = $regions_by_iso;

  return $sales;
}


/**
 * callback function
 * источник данных об экспертах (исп. в приложении)
 */
function _experts_source($region_id = null)
{
  drupal_json_output(['representatives' => representatives_get_sales($region_id)]);
  drupal_exit();
}

function representatives_get_office($role)
{
  $office = '';

  switch($role) {
    case 'director':
      $office = t('Director');
      break;
    case 'director_c':
      $office = t('Head of department');
      break;
    case 'head':
      $office = t('Deputy head');
      break;
    case 'manager':
      $office = t('Head of sales department');
      break;
    case 'representative':
      $office = t('Representative');
      break;
    case 'expert':
      $office = t('Plant protection expert');
      break;
    case 'specialist':
      $office = t('Plant protection specialist');
      break;
  }

  return $office;
}

