<?php
include 'includes/bot.cr.inc';
include 'includes/bot.ex.inc';
include 'includes/bot.btc38.inc';

/**
 * Implements hook_menu().
 */
function bot_menu()
{
    $items['bot/cr'] = array(
        'title' => t('Bot/Cryptopia'),
        'page callback' => 'bot_page_cr',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['bot/ex'] = array(
        'title' => t('Bot/Exmo'),
        'page callback' => 'bot_page_ex',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['bot/btc38'] = array(
        'title' => t('Bot/btc38'),
        'page callback' => 'bot_page_38',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['bot/orders/%/%'] = array(
        'page callback' => 'orders_ajax_callback',
        'page arguments' => array(2, 3),
        'delivery callback' => 'ajax_deliver', // данные, возвращённые ф-ей orders_ajax_callback(), будут отданы в json формате
        'access arguments' => array('access content'),
    );
    return $items;
}

function bot_theme()
{
    return array(
        'bot_page' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/bot-page',
        ),
        'bot_table' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/table',
        ),
        'bot_open_trades_table' => array(
            'variables' => array('trades' => NULL),
            'template' => 'templates/table-open-trades',
        ),
        'bot_closed_trades_table' => array(
            'variables' => array('trades' => NULL),
            'template' => 'templates/table-closed-trades',
        ),
        'bot_table_btc38' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/table-btc38',
        ),
    );
}
