<?

/**
 * Implements hook_theme().
 */
function ext_entityform_theme() {
    return array(
        // темизация Entityform Обратная связь для темы Gard
        'contact_us_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'contact-us-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
        'agrohelp_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'agrohelp-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
        'contact_vacancy_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'vacancy-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
    );
}

function ext_entityform_form_alter(&$form, &$form_state, $form_id)
{
    switch($form_id) {
        case "contact_us_entityform_edit_form":
            $code = $GLOBALS['language']->language == 'ru' ? 'ru_RU' : 'en_US';
            $form['#attached']['js'][] = 'https://api-maps.yandex.ru/2.1/?lang=' . $code . '&apikey=c1e4b070-a5e4-4a15-bc6e-ce64711bdf52';
            $form['#attached']['js'][] = drupal_get_path('module', 'ext_entityform') . '/js/map.js';
            break;

        case "contact_vacancy_entityform_edit_form":
            $form['actions']['submit']['#attributes']['class'][] = 'btn-wide';
            break;

        case "agrohelp_entityform_edit_form":
            $form['field_image']['und']['#title'] = t("To identify");
            break;
    }
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function ext_entityform_preprocess_page(&$vars)
{
    if (!empty($vars['page']['content']['system_main']['entityform_type']) && $entityform = current($vars['page']['content']['system_main']['entityform_type'])) {
        $vars['header']['subtitle'] = $entityform['form']['intro']['#markup'];
    }
}
