<?

/**
 * Implements hook_theme().
 */
function ext_entityform_theme() {
    return array(
        // темизация Entityform Обратная связь для темы Gard
        'contact_us_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'contact-us-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
        'agrohelp_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'agrohelp-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
        'contact_vacancy_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'vacancy-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
    );
}

function ext_entityform_form_alter(&$form, &$form_state, $form_id)
{
    switch($form_id) {
        case "contact_us_entityform_edit_form":
            $code = $GLOBALS['language']->language == 'ru' ? 'ru_RU' : 'en_US';
            $form['#attached']['js'][] = 'https://api-maps.yandex.ru/2.1/?lang=' . $code . '&apikey=c1e4b070-a5e4-4a15-bc6e-ce64711bdf52';
            $form['#attached']['js'][] = drupal_get_path('module', 'ext_entityform') . '/js/map.js';
            break;

        case "contact_vacancy_entityform_edit_form":
            $form['actions']['submit']['#attributes']['class'][] = 'btn-wide';
            break;

        case "agrohelp_entityform_edit_form":
            $form['field_image']['und']['#title'] = t("To identify");
            break;
    }
}

/**
 * Implements hook_page_build().
 */
function ext_entityform_page_build()
{
  // If the current page is one we want to exclude from the cache,
  // set the page caching to false temporarily.
  //отключаем кеширование определенных страниц
  if ($_GET['q'] == 'eform/submit/contact-us') {
    drupal_page_is_cacheable(FALSE);
  }
}


/**
 * Pre-processes variables for
 */
function ext_entityform_preprocess_contact_us_entityform_edit_form(&$vars)
{
  // контакт в зависимости от гео
  $iso_code = 'RU-KIR';
  $contacts = chibs_get_representatives_address();
  if (module_exists('dadata_api')) {
    $user_ip = strpos($_SERVER['HTTP_HOST'], '.local') === false  ? $_SERVER['REMOTE_ADDR'] : '77.72.142.170';
    if ($suggestion = chibs_get_location_by_ip($user_ip)) {
      if (isset($contacts[$suggestion['location']['data']['region_iso_code']])) {
        $iso_code = $suggestion['location']['data']['region_iso_code'];
      }
    }
  }

  $address = '';
  foreach ($contacts[$iso_code] as $item) {
    $address .= $item['address'];
    $phones_arr = [];
    foreach ($item['phones'] as $phone) {
      $phones_arr[] =  '<a href="tel:' . $phone['raw'] . '">' . $phone['txt'] . '</a>';
    }
    if ($phones_arr) {
      $address .= '<br /> ' . implode($phones_arr, ', ');
    }
  }
  $vars['contact'] = $address;
  drupal_add_js(array('ext_entityform' => array('contact' => $contacts[$iso_code])), 'setting');

  $branches_html = '';
  foreach ($contacts as $iso => $contact) {
    if ($iso != $iso_code) {
      foreach ($contact as $item) {
        $branches_html .= '<div class="branch">' . $item['address'];
        $phones_arr = [];
        foreach ($item['phones'] as $phone) {
          $phones_arr[] =  '<a href="tel:' . $phone['raw'] . '">' . $phone['txt'] . '</a>';
        }
        if ($phones_arr) {
          $branches_html .= ', ' . implode($phones_arr, ', ');
        }
        $branches_html .= '</div>';
      }
    }
  }

  $vars['branches'] = $branches_html;
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function ext_entityform_preprocess_page(&$vars)
{
  if (!empty($vars['page']['content']['system_main']['entityform_type']) && $entityform = current($vars['page']['content']['system_main']['entityform_type'])) {
      if (!empty($entityform['form']['intro']['#markup'])) $vars['header']['subtitle'] = $entityform['form']['intro']['#markup'];
  }
}
