<?

/**
 * Implements hook_theme().
 */
function ext_entityform_theme() {
    return array(
        // темизация Entityform Обратная связь для темы Gard
        'contact_us_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'contact-us-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
        'agrohelp_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'agrohelp-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
        'contact_vacancy_entityform_edit_form' => array(
            'render element' => 'form',
            'template' => 'vacancy-entityform',
            'path' => drupal_get_path('module', 'ext_entityform') . '/templates',
        ),
    );
}

function ext_entityform_form_alter(&$form, &$form_state, $form_id)
{
    switch($form_id) {
        case "contact_us_entityform_edit_form":
            $form['field_contact_name']['und'][0]['value']['#attributes']['placeholder'] = $form['field_contact_name']['und']['#title'];
            $form['field_contact_name']['und'][0]['value']['#title'] = '';
            $form['field_phone']['und'][0]['value']['#attributes']['placeholder'] = $form['field_phone']['und']['#title'];
            $form['field_phone']['und'][0]['value']['#title'] = '';
            $form['field_contact_email']['und'][0]['value']['#attributes']['placeholder'] = $form['field_contact_email']['und']['#title'];
            $form['field_contact_email']['und'][0]['value']['#title'] = '';
            $form['field_contact_message']['und'][0]['value']['#attributes']['placeholder'] = $form['field_contact_message']['und']['#title'];
            $form['field_contact_message']['und'][0]['value']['#title'] = '';
            break;

        case "contact_vacancy_entityform_edit_form":
            $form['field_vacancy_surname']['und'][0]['value']['#attributes']['placeholder'] = $form['field_vacancy_surname']['und']['#title'];
            $form['field_vacancy_name_1']['und'][0]['value']['#attributes']['placeholder'] = $form['field_vacancy_name_1']['und']['#title'];
            $form['field_vacancy_name_2']['und'][0]['value']['#attributes']['placeholder'] = $form['field_vacancy_name_2']['und']['#title'];
            $form['field_vacancy_location']['und'][0]['value']['#attributes']['placeholder'] = $form['field_vacancy_location']['und']['#title'];
            $form['field_contact_email']['und'][0]['value']['#attributes']['placeholder'] = $form['field_contact_email']['und']['#title'];
            $form['actions']['submit']['#attributes']['class'][] = 'btn-wide';
            break;

        case "agrohelp_entityform_edit_form":
            $form['field_image']['und']['#title'] = t("To identify");
            break;
    }
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function ext_entityform_preprocess_page(&$vars)
{
    if (!empty($vars['page']['content']['system_main']['entityform_type']) && $entityform = current($vars['page']['content']['system_main']['entityform_type'])) {
        $vars['header']['subtitle'] = $entityform['form']['intro']['#markup'];
    }
}
