<?php

include 'simple_html_dom/simple_html_dom.php';

/**
 * Implements hook_menu().
 */
function advencer_menu() {
    $items['advencer/cron'] = array(
        'title' => t('Advencer'),
        'page callback' => 'advencer_cron_callback',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}


function advencer_cron_callback() {
    $pages = array(
        array(
            'link' => 'http://www.chepetsk.ru/do/?id=sport',
            'keywords' => array(
                array('word' => 'велосипед',    'minus' => array('куплю', 'приму')),
////                array('word' => 'жесткий',    'minus' => array('куплю', 'приму', 'системн', 'компьютер ')),
            ),
        ),
        array(
            'link' => 'http://www.chepetsk.ru/do/?page=1&id=other',
            'keywords' => array(
                //array('word' => 'карт',    'minus' => array('куплю', 'приму', 'видео', 'звук', 'сетев', 'смартфон', 'телефон', 'карти')),
            ),
        ),
    );

    foreach($pages as $page) {
        _make_request($page);
    }
}

function _make_request($page) {

    // получение данных с сайта по ссылке
    $request_options = array();
    if ($result = drupal_http_request($page['link'], $request_options)) {
        $content = iconv ('windows-1251', 'utf-8', $result->data);
        $content_object = str_get_html($content);

        $announcements = $content_object->find('#mainer table table table table');
        if ($announcements) {
            // проверяем каждое объявление на наличие искомых слов
            foreach ($announcements as $ann) {
                $ann_text = drupal_strtolower(html_entity_decode($ann->children(0)->children(1)->plaintext));
                $ann_translit = translit($ann_text);
                $ann_contact = html_entity_decode($ann->children(1)->children(0)->plaintext);
                $ann_phone = preg_replace('!\D!', '', $ann_contact);
                foreach ($page['keywords'] as $word) {
                    // если вхождение найдено и нет в кеше, отправить смс с телефоном и найденным словом
                    $cache_key = substr($ann_translit, 0, 20);
                    if (strpos($ann_text, $word['word']) !== false && !cache_get($cache_key)) {

                        // проверить на слова минусы
                        $have_minus = false;
                        foreach($word['minus'] as $minus) {
                            if (strpos($ann_text, $minus) !== false) $have_minus = true;
                        }

                        // отправить смс, если соответствует требованиям
                        if (!$have_minus) {
                            $text = 'Adv: ' . $ann_phone . ' ' . substr($ann_translit, 0, 140 - 17);
                            $url = 'http://sms.ru/sms/send?api_id=156B4DC4-854D-DCCD-AD11-96346E911717&to=79226646009&text=' . urlencode($text);
                            $send = file_get_contents($url);

                            // добавить объявление в кеш на 3 с небольшим суток, чтобы не отправлять повторно
                            cache_set($cache_key, 1, 'cache', time() + 300000);
                        }
                    }
                }
            }
        }
    }


}

