<?php

define('KCCC_COMPANY_PID', 668);

/**
 * роли
 */
define('ROLE_STAFF',            6);
define('STAFF_PERSONNEL',       4);
define('ROLE_STAFF_ADMINISTRATOR',  13);
define('STAFF_EDITOR',          5);
define('STAFF_REPRESENTATIVE',  14);
define('STAFF_SHOP',            11);
define('STAFF_CHIEF',           8);
define('STAFF_ADMIN',           3);

define('ROLE_UNCONFIRMED',      7);
define('ROLE_COMPANY',          15);

/**
 * Implements hook_menu_alter()
 */
function ext_user_menu_alter(&$items)
{
  $items['user/%user/edit']['weight'] = 100;

  // убрать закладки со страницы входа
  $items['user']['type'] = MENU_CALLBACK;
  $items['user/register']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
  $items['company/register']['type'] = MENU_CALLBACK;
  $items['company/password']['type'] = MENU_CALLBACK;
}

function ext_user_permission()
{
  return [
    'access product_reglaments actions' => [
      'title' => t('Access Product Reglaments'),
      'description' => t('Access Product Reglaments actions'),
    ]
  ];
}


/**
 * hook_module_implements_alter
 * change hook execution order, commerce_helper - last
 */
function ext_user_module_implements_alter(&$implementations, $hook)
{
  // Name of the hook.
  if (in_array($hook, ['form_alter'])) {
    // ext_user - last
    $module = 'ext_user';
    if (isset($implementations[$module])) {
      $group = $implementations[$module];
      unset($implementations[$module]);
      $implementations[$module] = $group;
    }
  }
}

// callback проверки прав на редактирование профиля
function ext_user_account_edit_access($acid, $op)
{
  global $user;

  // можно админу
  if ($user->uid == 1) return true;
  // можно владельцу
  if ($acid && $user->uid == $acid ) return true;
  // можно, если не редактирование и проч
  if (!in_array($op, ['edit', 'delete', 'view'])) return true;

  return false;
}


/**
 * Implements hook_preprocess_user_profile().
 */
function ext_user_preprocess_page(&$vars)
{
  global $user;

  // отключить заголовок на странице
  if (arg(0) == 'user' || arg(0) == 'company') {
    if (in_array(arg(1), ['login', 'register', 'password', 'reset']) || arg(2) == 'before_after') {
      $vars['header']['title_off'] = true;
    }
    $vars['header']['image'] = $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'ext_user') . '/images/header_image.jpg';

    drupal_add_js(drupal_get_path('module', 'ext_user') . '/js/ext_user.js');
    drupal_add_css(drupal_get_path('module', 'ext_user') . '/css/ext_user.css');

    if (arg(2) == 'edit') {
      if (arg(3) == 'main') drupal_set_title('Профиль пользователя');
      elseif (arg(3) == 'staff') drupal_set_title('Профиль сотрудника');
      elseif (arg(3) == 'company') drupal_set_title('Профиль компании');
      else drupal_set_title('Настройки аккаунта');
    }
  }

  // предупреждение для неподтвержденных аккаунтов
  if (isset($user->roles[7])) {
    drupal_set_message(t('You have to confirm your account, otherwise it wound be deleted soon. Check your e-mail.'), 'warning');
  }
}

/**
 * Implements hook_preprocess_user_profile().
 */
function ext_user_preprocess_user_profile(&$vars)
{
  global $user;

  // id запрашиваемого пользователем аккаунта
  $acid = arg(0) == 'user' && is_numeric(arg(1)) ? arg(1) : 0;

  if ($acid && $account = user_load($acid)) {
    $account_view_access = ($user->uid == $account->uid) || $user->uid == 1;

    // разрешаем просмотр аккаунтов представителей
    if ($account_view_access) {
      $user_info = ext_user_get_user_info($account->uid);
      $vars['user_profile']['name'] = $user_info['short_name'];

      if (user_has_role(STAFF_REPRESENTATIVE, $account)) {
        // todo должность, регион

        // todo Препараты в поле
        // todo Отзывы
        // todo активность на Форуме
      }

      // todo вывести ссылки на новые и все уведомления в виде local actions
//      $subscripted_notification_ids = ext_message_get_user_subscription_notification_ids($acid);
//
//      // определить фильтр, если установлен
//      $status = '';
//      if (!isset($_GET['status']) || strtolower($_GET['status']) == 'new') {
//        $status = 0;
//      }
//
//      // сформировать вывод
//      $output =   '<div class="notifications">' .
//        '<div class="n-controls">' .
//        '<div class="n-filter">' .
//        '<a href="/person/' . $acid . '/notifications?status=new" ' . ($status === 0 ? 'class="active" ' : '') . '>' . t('Only new') . '</a>' .
//        '<a href="/person/' . $acid . '/notifications?status=all" ' . ($status === '' ? 'class="active" ' : '') . '>' . t('All notifications') . '</a>' .
//        '</div>' .
//        '<div class="n-read-all">' .
//        '<a href="/message/all/got?back=' .$_GET['q'] . (isset($_GET['status']) ? '&status=' . $_GET['status'] : '') . '" title="' . t('Set all notification read') . '" class="n-all-got"><i class="fas fa-check-double"></i></a>' .
//        '</div>' .
//        '</div>' .
//        '</div>';
//
//      // списко Уведомлений по полученным Типам сообщений
//      $output .= views_embed_view('user_notifications', 'page', implode('+', $subscripted_notification_ids), $status);


      $vars['user_profile']['photo'] = '/sites/default/files/default_images/no_photo.png';
      $vars['user_profile']['add_photo_link'] = '';

      if (!user_has_role(ROLE_UNCONFIRMED)) {
        // фото
        $vars['user_profile']['add_photo_link'] = l(t('add photo'), '/user/' . $acid . '/main/edit');
      }

      $profile2 = profile2_load_by_user($acid);
      if (!empty($profile2['main']->pid)) {
        $main_wrapper = entity_metadata_wrapper('profile2', $profile2['main']->pid);
        $main_wrapper->language($account->language);

        // добавить фото
        if ($main_wrapper->field_profile_photo->value()) {
          $file = $main_wrapper->field_profile_photo->file->value();
          $vars['user_profile']['photo'] = image_style_url('profile_photo', $file->uri);
          $vars['user_profile']['add_photo_link'] = '';
        }
      }

      // статус
      $vars['user_profile']['is_online'] = ($user->uid == $account->uid) || (time() - $account->access) / 60 < 5;

      // роли
      $vars['user_profile']['role'] = 'Пользователь';
//      if (!empty($profile2['staff'])) {
//        $staff_wrapper = entity_metadata_wrapper('profile2', $profile2['staff']->pid);
//        if ($staff_wrapper->field_profile_company2->value()) {
//          $company_type = $staff_wrapper->field_profile_company2->field_profile_company_type->name->value();
//          $company_name = $staff_wrapper->field_profile_company2->field_profile_name->value();
//          $vars['user_profile']['role'] .= '<br>Cотрудник ' . $company_type . ' ' . $company_name;
//        }
//      }

      // счётчики
      // блоги
      $query = db_select('node');
      $query->addExpression('COUNT(*)');
      $query->condition('uid', $account->uid);
      $query->condition('type', 'blog');
      $result = $query->execute()->fetchField();
      $vars['user_profile']['counts'][] = array(
        'title' => t('Blog'),
        'amount' => $result,
        'link' => '/blogs/user/' . $account->uid,
      );
      // отзывы
      $query = db_select('node');
      $query->addExpression('COUNT(*)');
      $query->condition('uid', $account->uid);
      $query->condition('type', 'review');
      $result = $query->execute()->fetchField();
      $vars['user_profile']['counts'][] = array(
        'title' => t('Reviews'),
        'amount' => $result,
        'link' => '/reviews/' . $account->uid,
      );
      // До и После
      if (user_access('access before_after edit')) {
        $query = db_select('field_data_field_f_sowing', 's');
        $query->addExpression('COUNT(*)');
        $query->innerJoin('node', 'n', 'n.nid = s.entity_id');
        $query->condition('n.uid', $account->uid);
        $result = $query->execute()->fetchField();

        $vars['user_profile']['counts'][] = array(
          'title' => t('Before & After'),
          'amount' => $result,
          //'link' => '/before-after/user/' . $account->uid,
          'link' => '/before-after',
        );
      }


      if ($account_view_access) {
        // заказы
        $vars['user_profile']['counts'][] = array(
          'title' => t('Orders'),
          'amount' => ext_user_orders_count($acid),
          'link' => "/user/$acid/orders",
        );
        // баллы
//            $content['counts'][] = array(
//                'title' => t('Points'),
//                'amount' => ext_user_get_points($acid),
//                'link' => "",
//                'class' => '',
//            );
      }


//    $output = theme('ext_user_summary', array('content' => $content));
      drupal_set_title($user_info['short_name']);
    }
  }
}

/**
 * Implements hook_user_insert().
 */
function ext_user_user_insert( &$edit, &$account, $category = NULL )
{
  // при регистрации нового пользователя установить уникальное имя: Пользователь #uid
  $new_name = t('User ') . $account->uid;

  db_update('users')
    ->fields(array('name' => $new_name))
    ->condition('uid', $account->uid)
    ->execute();

  $edit['name'] = $new_name;
  $account->name = $new_name;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_user_form_user_login_alter(&$form, &$form_state)
{
  $form['title'] = [
    '#markup' => '<h1>Вход</h1>'
  ];
  $form['links'] = [
    '#markup' => '<a href="/user/register">Зарегистрироваться</a> или <a href="/user/password">Восстановить пароль</a>'
  ];

  $form['name']['#attributes']['placeholder'] = t('Your e-mail');
  unset($form['name']['#title']);
  unset($form['name']['#description']);

  $form['pass']['#attributes']['placeholder'] = t('Your password');
  unset($form['pass']['#title']);
  unset($form['pass']['#description']);

  $form['name']['#element_validate'][] = 'ext_user_login_name_validate';
}

/**
 * Form element validation handler for the user login form.
 *
 * Allows users to authenticate by username OR email.
 */
function ext_user_login_name_validate($form, &$form_state)
{
  $user = ext_user_user_load_by_login($form_state['values']['name']);
  if ($user->uid) {
    $form_state['values']['name'] = $user->name;
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_user_form_user_register_form_alter(&$form, &$form_state)
{
//  variable_set('user_mail_register_no_approval_required_notify', true);

  // изменение формы регистрации
  $form['account']['mail']['#attributes']['placeholder'] = 'E-Mail';
  unset($form['account']['mail']['#title']);
  unset($form['account']['mail']['#description']);

  $form["fz152_agreement"]["#weight"] = 100;

  // вместо пароля с подтверждением и рекомендациями выводим одно поле пароля
  $form['account']['pass']['#type'] = 'password';
  $form['account']['pass']['#attributes']['placeholder'] = 'Придумайте пароль';
  unset($form['account']['pass']['#title']);
  unset($form['account']['pass']['#description']);

  $form['account']['name']['#type'] = 'hidden';
  $form['account']['name']['#value'] = 'ext_user_' . user_password();

  if (isset($form["profile_main"])) {
    $form['title'] = ['#markup' => '<h1>Регистрация пользователя</h1>'];
    $form['links'] = ['#markup' => '<a href="/company/register">Регистрация юр. лица</a> или <a href="/user/login">Вход</a>'];
    $form["profile_main"]["field_profile_name"]["und"][0]['value']['#attributes']['placeholder'] = $form["profile_main"]["field_profile_name"]["und"][0]['value']["#title"];
    unset($form["profile_main"]["field_profile_name"]["und"][0]['value']["#title"]);
    $form["profile_main"]["field_profile_surname"]["und"][0]['value']['#attributes']['placeholder'] = $form["profile_main"]["field_profile_surname"]["und"][0]['value']["#title"];
    unset($form["profile_main"]["field_profile_surname"]["und"][0]['value']["#title"]);
    $form["profile_main"]["field_profile_phone"]["und"][0]['value']['#attributes']['placeholder'] = $form["profile_main"]["field_profile_phone"]["und"][0]['value']["#title"];
    unset($form["profile_main"]["field_profile_phone"]["und"][0]['value']["#title"]);
    $form["profile_main"]["field_profile_name2"]["#access"] = false;
    $form["profile_main"]["field_profile_photo"]["#access"] = false;
  }

  if (isset($form["profile_company"])) {
    $form['title'] = ['#markup' => '<h1>Регистрация юр. лица</h1>'];
    $form['links'] = ['#markup' => '<a href="/user/register">Регистрация пользователя</a> или <a href="/user/login">Вход</a>'];
    $form["profile_company"]["field_profile_name"]["und"][0]['value']['#attributes']['placeholder'] = $form["profile_company"]["field_profile_name"]["und"][0]['value']["#title"];
    unset($form["profile_company"]["field_profile_name"]["und"][0]['value']["#title"]);
    $form["profile_company"]["field_profile_company_inn"]["und"][0]['value']['#attributes']['placeholder'] = $form["profile_company"]["field_profile_company_inn"]["und"][0]['value']["#title"];
    unset($form["profile_company"]["field_profile_company_inn"]["und"][0]['value']["#title"]);
    unset($form["profile_company"]["field_profile_card"]["und"][0]["#description"]);
    $form["profile_company"]["field_profile_p_address"]["#access"] = false;
    $form["profile_company"]["field_profile_l_address"]["#access"] = false;
    $form["profile_main"]["#title"] = 'Представитель';
    $form["profile_company"]["#title"] = 'Организация';
  } else {
    $form["profile_main"]["#type"] = 'container';
  }

  // добавить проверку
  $form['#validate'][] = 'ext_user_user_register_form_validate';

  // добавить обработчик сабмита регистрации
  $form['#submit'][] = 'ext_user_user_register_form_submit';

  $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';

  // убрать капчу для DrupalGap и local сервера
  if (arg(0) == 'drupalgap' || strpos($GLOBALS['base_url'], '.local') !== false) {
    $form['#after_build'][] = 'ext_user_form_captcha_after_build';
  }
}

/**
 * дополнительная проверка при регистрации
 */
function ext_user_user_register_form_validate($form, $form_state)
{
  // отсеять нежелательные (спамерские) email
  foreach(['!.*@.*\.us!s', '!.*@.*\.link!s', '!.*@.*\.co\.uk!s', '!.*@.*\.work!s', '!.*@.*\.website!s',
            '!.*@.*\.app!s', '!.*@.*\.ltd!s', '!.*@.*\.net!s', '!.*@.*\.online!s', '!.*@.*\.store!s', '!.*@.*\.info!s',
            '!.*@.*\.site!s', '!.*@.*\.gq!s', '!.*@.*\.network!s', '!.*@.*\.xyz!s', '!.*@.*\.cf!s', '!.*@.*\.club!s', '!.*@.*\.jokeray\.com!s', '!.*@.*\.dynainbox\.com!s'
            , '!.*@.*\.mailsmail\.ru!s', '!.*@.*\.mailyaha\.ru!s', '!.*@.*\.aolmail\.fun!s', '!.*@.*\.osakass\.!s'] as $pattern) {
    if (preg_match($pattern, $form_state['values']['mail'])) {
      form_set_error('mail', t('E-mail is not valid.'));
    }
  }
}

/**
 * дополнительный сабмит при регистрации
 */
function ext_user_user_register_form_submit($form, &$form_state)
{
  global $user;

  // дать пользователям с почтой @kccc.ru роль сотрудника
  if (drupal_substr($form_state['values']['mail'], -8) == '@kccc.ru') {
    $user->roles[ROLE_STAFF] = 1;
    user_save($user);
  }

//  $form_state['redirect'] = 'user/' . $user->uid . '/edit/main';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_user_form_user_pass_alter(&$form)
{
  $form['title'] = ['#markup' => '<h1>Восстановить пароль</h1>'];
  $form['links'] = ['#markup' => '<a href="/user/register">Регистрация</a> или <a href="/user/login">Вход</a>'];

  $form['name']['#title'] = t('E-mail');
  $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';
}

// возвращает количество совершенных пользователем заказов
function ext_user_orders_count($acid)
{
  $count = 0;
  foreach (commerce_order_load_multiple(array(), array('uid' => $acid)) as $order) {
    if (!$order->status != 'cart') {
      $count++;
    }
  }
  return $count;
}

/**
 * An after build handler to remove captcha from DrupalGap forms.
 */
function ext_user_form_captcha_after_build($form, &$form_state)
{
  // ReCAPTCHA
  if (isset($form['captcha'])) { unset($form['captcha']); }
  // Mollom
  if (isset($form['mollom'])) { unset($form['mollom']); }
  return $form;
}



/**
 * Implements hook_translated_menu_link_alter
 * изменить путь ссылки Уведомления
 */
function ext_user_translated_menu_link_alter(&$item, $map)
{
  global $user;

  if ($item['link_path'] == 'user/notifications') {
    $item['link_path'] = 'user/' . $user->uid . '/notifications';
    $item['router_path'] = 'user/' . $user->uid . '/notifications';
    $item['href'] = 'user/' . $user->uid . '/notifications';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_user_form_user_profile_form_alter (&$form, $form_state)
{
  if ($GLOBALS['user']->uid != 1) {
    $form["account"]["name"]["#access"] = false;
    $form["account"]["status"]["#access"] = false;
    $form['timezone']['#access'] = false;
    $form['locale']['#access'] = false;
    $form['mimemail']['#access'] = false;
    $form['picture']['#access'] = false;

    if (isset($form["account"]["mail"])) {
      $form["account"]["mail"]["#weight"] = -10;
    }
    if (isset($form["account"]["pass"])) {
      $form["account"]["pass"]["#title"] = 'Новый пароль';
      $form["account"]["pass"]["#type"] = 'password';
    }

    // меняем тему формы всем, кроме Админа
    $form["#theme"] = ['user_profile_form_custom'];

    $form["#submit"][] = 'ext_user_user_profile_form_submit';
  }
}

function ext_user_user_profile_form_submit($form, &$form_state)
{
  // проверить галку Аккаунтт Юрлица и создать профиль, если отсутствует
  global $user;
  if (!empty($form_state["values"]["field_profile_has_company"]["und"][0]["value"])) {
    if (!user_has_role(ROLE_COMPANY, $user)) {
      $roles = user_roles();
      $user->roles[ROLE_COMPANY] = $roles[ROLE_COMPANY];
      user_save($user);
      $form_state['redirect'] = 'user/' . $user->uid . '/edit/company';
    }
  } else {
    if (user_has_role(ROLE_COMPANY, $user)) {
      unset($user->roles[ROLE_COMPANY]);
      user_save($user);
    }
  }
}

function ext_user_theme()
{
  return [
    'user_profile_form_custom' => array(
      'render element' => 'form',
      'template' => 'templates/user-profile-form',
    ),
    'user_register_form' => array(
      'render element' => 'form',
      'template' => 'templates/user-register-form',
    ),
    'user_login' => array(
      'render element' => 'form',
      'template' => 'templates/user-login-form',
    ),
    'user_pass' => array(
      'render element' => 'form',
      'template' => 'templates/user-pass-form',
    ),
  ];
}

// массив с информацией о пользователе
function ext_user_get_user_info($user)
{
  $account = is_numeric($user) ? user_load($user) : $user;

  $name_arr = array('', '', '');
  $email = $phone = '';
  $photo_url = image_style_url('user_photo', 'public://default_images/no_photo.png');
  $staff = [];
  $company = [];
  $label = t('User');

  if (!empty($account->uid)) {
    if ($main_pr2 = profile2_load_by_user($account, 'main')) {
      $main_wrapper = entity_metadata_wrapper('profile2', $main_pr2);
      $name_arr[0] = $main_wrapper->field_profile_surname->value() ? $main_wrapper->field_profile_surname->value() : '';
      $name_arr[1] = $main_wrapper->field_profile_name->value() ? $main_wrapper->field_profile_name->value() : '';
      $name_arr[2] = $main_wrapper->field_profile_name2->value() ? $main_wrapper->field_profile_name2->value() : '';
      $email = $account->mail;
      $phone = $main_wrapper->field_profile_phone->value() ? $main_wrapper->field_profile_phone->value() : '';
      if ($main_wrapper->field_profile_photo->value()) {
        $file = $main_wrapper->field_profile_photo->file->value();
        $photo_url = image_style_url('user_photo', $file->uri);
      }
    }

    // если утвержденный сотрудник вывести регалии
    if (user_has_role(ROLE_STAFF, $account) && $staff_pr2 = profile2_load_by_user($account, 'staff')) {
      $staff_wrapper = entity_metadata_wrapper('profile2', $staff_pr2);

      $company = 'Торговый Дом Кирово-Чепецкая Химическая Компания';
      $post = $staff_wrapper->field_profile_post->value();
      $role = $post . ' ' . $company;
      $staff = [
        'post' => $post,
        'role' => $role,
        'company' => $company,
      ];
    }

    if (user_has_role(ROLE_COMPANY, $account) && $company_pr2 = profile2_load_by_user($account, 'company')) {
      $label = t('Representative'); // представитель организации
      $company_wr = entity_metadata_wrapper('profile2', $company_pr2);

      $card_url = '';
      if ($company_wr->field_profile_card->value()) {
        $file = $company_wr->field_profile_card->file->value();
        $card_url = file_create_url($file->uri);
      }

      $company = [
        'inn' => $company_wr->field_profile_company_inn->value(),
        'name' => $company_wr->field_profile_name->value(),
        'card_url' => $card_url,
      ];
    }
  }

  return [
    'surname' => $name_arr[0],
    'name' => $name_arr[1],
    'name2' => $name_arr[2],
    'full_name' => implode(' ', $name_arr),
    'short_name' => $name_arr[1] . ' ' . $name_arr[0],
    'label' => $label,
    'email' => $email,
    'phone' => $phone,
    'photo' => $photo_url,
    'staff' => $staff,
    'company' => $company,
  ];
}


/**
 * возвращает имя пользователя аккаунта в разных форматах
 * @param $user
 * @param string $format
 * @return bool|string
 */
function ext_user_get_user_name($user, $format = 'short_ns')
{
  if (is_numeric($user)) $account = user_load($user);
  else $account = $user;

  $user_name = false;
  if (!empty($account->uid) && $main = profile2_load_by_user($account, 'main')) {
    $main_wrapper = entity_metadata_wrapper('profile2', $main);
    $name       = $main_wrapper->field_profile_name->value()    ? $main_wrapper->field_profile_name->value()    : '';
    $surname    = $main_wrapper->field_profile_surname->value() ? $main_wrapper->field_profile_surname->value() : '';
    $name2      = $main_wrapper->field_profile_name2->value()   ? $main_wrapper->field_profile_name2->value()   : '';
    switch($format) {
      case 'short_sn':
        $user_name = $surname . ' ' . $name;
        break;
      case 'short_ns':
        $user_name = $name . ' ' . $surname;
        break;
      case 'full':
        $user_name = $surname . ' ' . $name . ' ' . $name2;
        break;
    }
  }
  if (!trim($user_name)) $user_name = $account->name;

  return $user_name;
}


// проверка заданного или текущего пользователя на наличие роли
function _user_has_role($role, $acc = NULL)
{
  if (!$acc)
    $acc = $GLOBALS['user'];

  if (is_numeric($role) && isset($acc->roles[$role])) return true;
  if (is_array($acc->roles) && in_array($role, array_values($acc->roles))) return TRUE;

  return FALSE;
}

/**
 * Normalize phone to standart view
 * @param $phone
 *
 * @return string|string[]|null
 */
function ext_user_normalize_phone($phone)
{
  // убираем всё лишнее кроме цифр
  $phone = preg_replace('/[^\d]/', '', trim($phone));
  // заменить первую 8 на 7
  $phone = preg_replace('/8(\d{10})/', '7$1', $phone);
  return $phone;
}

/**
 * Format phone to user view
 */
function ext_user_format_phone($phone)
{
  // форматируем - +7-xxx-xxx-xx-xx
  $phone = preg_replace('/(\d)(\d\d\d)(\d\d\d)(\d\d)(\d\d)/', '+$1 $2 $3-$4-$5', trim($phone));

  return $phone;
}

function ext_user_valid_phone($phone)
{
  // номер правильный, если имеет минимум 11 цифр
  preg_match('/\d+(\d{10})$/', ext_user_normalize_phone($phone), $match);

  return !empty($match[1]);
}

function ext_user_user_load_by_phone($phone)
{
  $phone = ext_user_normalize_phone($phone);
  $uid = 0;
  if (ext_user_valid_phone($phone)) {
    $query = db_select('users', 'u');
    $query->innerJoin('field_data_field_phone', 'fp', 'fp.entity_id = u.uid');
    $query->condition('fp.field_phone_value', $phone);
    $query->addField('u', 'uid');
    if ($result = $query->execute()->fetchField()) {
      $uid = $result;
    }
  }
  return user_load($uid);
}

/**
 * Загрузить пользователя по указанному логину
 * @param $login
 *
 * @return object
 */
function ext_user_user_load_by_login($login)
{
  // Try loading by email.
  if ($user = user_load_by_mail($login)) {
    return $user;
  }

  // Try loading by phone.
  if ($user = ext_user_user_load_by_phone($login)) {
    return $user;
  }

  // Try loading by username.
  if ($user = user_load_by_name($login)) {
    return $user;
  }
  return user_load(0);
}

/**
 * на базе user_authenticate

 * Try to validate the user's login credentials locally.
 *
 * @param $name
 *   User name, phone or email to authenticate.
 * @param $password
 *   A plain-text password, such as trimmed text from form values.
 * @return
 *   The user's uid on success, or FALSE on failure to authenticate.
 */
function ext_user_user_authenticate($name, $password)
{
  $uid = FALSE;
  if (!empty($name) && strlen(trim($password)) > 0) {
    $account = ext_user_user_load_by_login($name);
    if ($account->uid) {
      // Allow alternate password hashing schemes.
      require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
      if (user_check_password($password, $account)) {
        // Successful authentication.
        $uid = $account->uid;

        // Update user to new password scheme if needed.
        if (user_needs_new_hash($account)) {
          user_save($account, array('pass' => $password));
        }
      }
    }
  }
  return $uid;
}


/**
 * hook_after_metatag_metatags_view_alter()
 *
 * свой метатег Description для форума
 */
function ext_user_metatag_metatags_view_alter(&$output, $instance, $options)
{
  if (arg(1) == 'user' && is_numeric(arg(2))) {
    $user_info = ext_user_get_user_info(arg(2));
    if (arg(0) == 'reviews') {
        $output["title"]["#attached"]["metatag_set_preprocess_variable"][0][2] = 'Отзывы пользователя '. $user_info['short_name'] . ' - ООО ТД Кирово-Чепецкая Химическая Компания';
        $output['description']['#attached']['drupal_add_html_head'][0][0]['#value'] = 'Отзывы пользователя '. $user_info['short_name'] . ' о работе средств защиты растений ООО ТД Кирово-Чепецкая Химическая Компания';
    }
    if (arg(0) == 'blogs') {
        $output["title"]["#attached"]["metatag_set_preprocess_variable"][0][2] = 'Блог пользователя '. $user_info['short_name'] . ' - ООО ТД Кирово-Чепецкая Химическая Компания';
        $output['description']['#attached']['drupal_add_html_head'][0][0]['#value'] = 'Блог пользователя '. $user_info['short_name'] . ' о работе средств защиты растений ООО ТД Кирово-Чепецкая Химическая Компания';
    }
  }
}
