<?php


/**
 * Implementation of hook_module_implements_alter().
 */
function entityform_mobile_module_implements_alter(&$implementations, $hook) {
  // Если хук - hook_services_request_postprocess_alter,
  // то переносим нашу реализацию этого хука в конец очереди
  // необходимо по причине того, что drupalgap затирает ранее полученные данные
  if ($hook == 'services_request_postprocess_alter') {
    $group = $implementations['entityform_mobile'];
    unset($implementations['entityform_mobile']);
    $implementations['entityform_mobile'] = $group;
  }
}

/**
* ----------------------------------------------- Мобильное приложение ------------------------------------------------
*/

/**
 * Implements hook_services_request_postprocess_alter()
 */
function entityform_mobile_services_request_postprocess_alter($data, &$context1, &$context2, &$context3) {

  // при запуске приложения и выполнении system/connect.json
  if ($data['callback'] == '_system_resource_connect') {
    // наряду с информацией о стандартных сущностях
    // передать информацию о сущности entityform
    $context2->field_info_instances['entityform'] = field_info_instances('entityform');

    // наряду с информацией о типах контента node
    // передать инфо о типах контента entityform вместе с правами
    if ($content_types = _entityform_mobile_resource_entityform_types_list()) {
      $context2->content_types_list = array_merge($context2->content_types_list, $content_types);
    }
    if ($content_types_permissions = _entityform_mobile_resource_entityform_types_user_permissions()) {
      $context2->content_types_user_permissions = array_merge($context2->content_types_user_permissions, $content_types_permissions);
    }
  }
}

/**
 * Returns a collection of entityform types from the {entityform_type} table.
 *
 * It also bundles other available information about each entityform type
 * with the return results.
 *
 * @param array $options
 *   An array of options.
 *
 * @return object
 *   MySQL object results from the {entityform_type} table
 */
function _entityform_mobile_resource_entityform_types_list($options = array()) {
  // Grab content types.
  $sql = "SELECT * FROM {entityform_type} ORDER BY label ASC";
  $content_types_result = db_query($sql);

  if ($content_types_result) {
    if ($content_types_result) {
      if ($content_types = $content_types_result->fetchAll()) {
        foreach($content_types as $i => $ct) {
          $content_types[$i]->name = $ct->label;
        }
      }
      return $content_types;
    }
  }
}

/**
 * Returns a collection of permissions from entityform types for the current user.
 *
 * @return array
 *   Array of entityform types with permissions for each.
 */
function _entityform_mobile_resource_entityform_types_user_permissions() {
  $content_types = _entityform_mobile_resource_entityform_types_list();
  $content_type_permissions = array();
  foreach ($content_types as $content_type) {
    $content_type_permissions[$content_type->type] = array(
      'create' => true,
      'delete any' => false,
      'delete own' => true,
      'edit any' => false,
      'edit own' => true,
    );
  }
  return $content_type_permissions;
}