<?php

function sec_contacts_menu()
{
  $items['kontakty'] = array(
    'title' => 'Main office',
    'description' => t('Main office contacts'),
    'page callback' => 'sec_contacts_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function sec_contacts_preprocess_page(&$vars)
{
  if (arg(0) == 'kontakty') {
    // вывод Заголовка в виде баннера
    $vars['is_banner_on'] = true;
    $vars['is_title_on'] = false;
    $img_uri = 'public://images/page-banners/contacts.jpg';
    $vars['banner_url'] = file_create_url($img_uri);
    $vars['banner_mobile_url'] = image_style_url('banner_mobile', $img_uri);
    $vars['banner_title'] = t('Contacts');
  }
}

// главная страница
function sec_contacts_page()
{
  $content = '';

  // список Представителей
  if ($contacts = sec_contacts_get_contacts_list()) {

    $content .= '<div class="row">';

    $sorted = [];
    foreach ($contacts as $uid) {
      $contact = ext_user_get_user_info($uid);
      $key = ($contact['staff']['office']['weight'] ?? 1)*1000000+$uid;
      $sorted[$key] = $contact;
    }
    ksort($sorted);

    foreach ($sorted as $contact) {
      $contact['active'] = true;
      $content .= '<div class="col-xs-12 col-md-6">';
      $content .=   theme('card_contact', $contact);
      $content .= '</div>';
    }
    $content .= '</div>';

  } else {
    $content .= 'Контактов не найдено.';
  }

  return  '<div id="contacts" class="company-contacts view">' .
            '<div class="contacts-content">' .
              $content .
            '</div>' .
          '</div>';
}

/**
 * Вернуть id пользователей с меткой центрального офисв
 *
 * @return array|false
 */
function sec_contacts_get_contacts_list()
{
  $dbr = db_select('profile', 'p');
  $dbr->innerJoin('field_data_field_staff_is_in_contacts', 'fsc', 'fsc.entity_id = p.pid');
  $dbr->condition('fsc.field_staff_is_in_contacts_value', 1);
  $dbr->innerJoin('users', 'u', 'u.uid = p.uid');
  $dbr->condition('u.status', 1);
  $dbr->addField('p', 'uid');
  $users = $dbr->execute()->fetchCol();

  return $users ?? false;
}




