<?php

/**
 * Implements hook_commerce_shipping_method_info().
 */
function transport_commerce_shipping_method_info() {
    $shipping_methods = array();

    $shipping_methods['transport_shipping_method'] = array(
        'title' => t('Transport company shipping'),
        'description' => t('Defines shipping method by transport company.'),
    );

    return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function transport_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['transport_shipping_service'] = array(
    'title' => t('Transport shipping service'),
    'description' => t(''),
    'display_title' => t('Transport company'),
    'shipping_method' => 'transport_shipping_method',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'transport_service_rate',
      'details_form' => 'transport_service_details_form',
      'details_form_validate' => 'transport_service_details_form_validate',
      'details_form_submit' => 'transport_service_details_form_submit',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function transport_service_rate($shipping_service, $order) {
    $address_id = 0;
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order->order_id);
    if ($order_wrapper->commerce_customer_shipping) {
        $shipping_wrapper = $order_wrapper->commerce_customer_shipping;
        $address_id = $shipping_wrapper->field_ship_address->value();
    }

    if ($address_id && $cache = cache_get('transport_service_rate_' . $order->order_id . '_' . $address_id)) {
        return $cache->data;
    } else {
        $set_cache = false;

        // в $order после ajax submit старые данные, загружаем заново
        $order = commerce_order_load($order->order_id);

        $error = $message = $time = $terminals = '';
        $shipping_cost = 0;
        if ($address_id && $address = node_load($address_id)) {

            // проверить заполнение Обязательных полей
            $mandatory_fields = transport_address_book_info();
            $absent_fields = address_book_check_mandatory_fields($address, $mandatory_fields);

            if (!$absent_fields) {
                $address_wrapper = entity_metadata_wrapper('node', $address);

                // физические  данные
                $weight = commerce_physical_order_weight($order, 'kg');
                $volume = commerce_physical_order_volume($order, 'm');
                // сумма заказа
                $order_amount = $order_wrapper->commerce_order_total->value();
                $order_total = $order_amount['amount'] / 100;
                // опции
                $to_door = $shipping_wrapper->field_ship_to_door->value();
                $insurance = $shipping_wrapper->field_ship_insurance->value();
                // КЛАДР терминала убытия
                $derival_kladr = '4300000100000000000000000';  // Киров

                // определить КЛАДР терминала прибытия
                $city_kladr = $address_wrapper->field_ab_city_kladr->value();
                $street_kladr = $address_wrapper->field_ab_street_kladr->value();
                $house_kladr = $address_wrapper->field_ab_house_kladr->value();

                $arrival_kladr = '';
                if ($house_kladr) $arrival_kladr = $house_kladr;
                elseif ($street_kladr) $arrival_kladr = $street_kladr;
                elseif ($city_kladr) {
                    $arrival_kladr = $city_kladr;
                } else {
                    // попробовать вычислить кладр по адресу, сделав запрос к kladr-api.ru
                    $api = new Kladr\Api('570f4f570a69deff1f8b4584', '');
                    $query = new Kladr\Query();

                    // сначала пробуем по индексу

                    $zipcode = $address_wrapper->field_ab_zipcode->value();
                    $zipcode = trim($zipcode);
                    if ($zipcode && strlen($zipcode) == 6 && is_numeric($zipcode)) {
                        $query->Zip = $zipcode;
                        $query->ContentType = Kladr\ObjectType::Building;
                        $query->WithParent = TRUE;
                        $message = 'Стоимость доставки рассчитана по указанному индексу.';
                    } else {
                        // иначе по строке адреса
                        $arr_addr = array();
                        $region = $address_wrapper->field_ab_region->value();
                        $area = $address_wrapper->field_ab_area->value();
                        $city = $address_wrapper->field_ab_city->value();
                        $street = $address_wrapper->field_ab_street->value();
                        $house = $address_wrapper->field_ab_house->value();

                        if ($region) $arr_addr[] = $region;
                        if ($area) $arr_addr[] = $area;
                        if ($city) $arr_addr[] = $city;
                        if ($street) $arr_addr[] = $street;
                        if ($house) $arr_addr[] = $house;

                        $query->ContentName = check_plain(implode(', ', $arr_addr));
                        $query->OneString = TRUE;
                    }

                    $query->Limit = 1;
                    $result = $api->QueryToArray($query);

                    if ($result) $arrival_kladr = $result[0]['id'];
                }

                $arrival_kladr = str_pad($arrival_kladr, 25, '0');

                $request = array(
                    'appKey' => '3405D910-082A-11E5-AD49-00505683A6D3',// ключ для вашего приложения
                    'derivalPoint' => $derival_kladr, // код КЛАДР пункта отправки  (обязательное поле)
                    'arrivalPoint' => $arrival_kladr, // код КЛАДР пункта прибытия (обязательный параметр)
                    'sizedVolume' => $volume['volume'],  // общий объём груза в кубических метрах (обязательный параметр)
                    'sizedWeight' => $weight['weight'],  // общий вес груза в килограммах (обязательный параметр)
                    'arrivalDoor' => (bool)$to_door, // необходима доставка груза до адреса    (необязательный параметр), true/false
                );
                if ($insurance) $request['statedValue'] = $order_total; // заявленная стоимость груза в рублях. необходимо      передать этот параметр, если требуется страхование груза с заявленной стоимостью         (необязательный параметр)

                if ((int)$arrival_kladr && $volume['volume'] && $weight['weight']) {
                    if ($sheet = transport_api_calc(json_encode($request))) {

                        if (empty($sheet['errors'])) {
                            if (!empty($sheet['time']['genitive'])) {
                                $time = $sheet['time']['genitive'];
                            }
                            if (!empty($sheet['arrival']['terminals'])) {
                                $terminals = $sheet['arrival']['terminals'];
                            }

                            $overcost = 1.04; // наценка платежной системы
                            $shipping_cost = $sheet['price'] * $overcost;

                            $set_cache = true;
                        } else {
                            $error = 2;
                            if (is_array($sheet['errors'])) {
                                $message = current($sheet['errors']);
                            }
                            if (is_string($sheet)) $message = $sheet;
                            if ($message == 'transport server error') $message = 'Возникла ошибка при обращении к серверу транспотрной компании. Попробуйте позже.';
                        }
                    } else {
                        $error = 3;
                        $message = t('Calculation service on transport company website is not available now. You can try later or confirm order now and our manager will contact you.');
                    }
                } else {
                    $error = 1;
                    $message = 'Не удалось определить код КЛАДР для адреса доставки из-за неверного Индекса или неточного адреса. Попробуйте изменить Индекс или заполнить адрес в адресной книге выбирая значения полей из выпадающего списка.';
                }
            } else {
                $error = 1;
                $message = 'Заполните в выбранной записи Адресной книги следующие обязательные поля: ' . implode(', ' , array_values($absent_fields));
            }
        } else {
            $error = 1;
            $message = 'Для расчёта стоимости доставки выберите запись из Адресной книги';
        }
        $calculation = array(
            'amount' => $shipping_cost * 100,
            'currency_code' => $order_wrapper->commerce_order_total->currency_code->value(),
            'data' => array(
                'error' => $error,
                'message' => $message,
                'time' => $time,
                'terminals' => $terminals,

            ),
        );

        // устанавливаем кеш на 12 часов
        if ($address_id && $set_cache)
            cache_set('transport_service_rate_' . $order->order_id . '_' . $address_id, $calculation, 'cache', time() + 43200);

        return $calculation;
    }
}

function transport_api_calc($request) {
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, "https://api.dellin.ru/v1/public/calculator.json");
    curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $request);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $data = curl_exec($curl);

    curl_close($curl);
    if($data === false) {
        return "transport server error";
    }

    $js = json_decode($data, true);

    return $js;
}

/**
 * Allows modules to alter the options array generated to select a shipping
 * service on the checkout form.
 */
function transport_commerce_shipping_service_rate_options_alter(&$options, $order){
    if (isset( $order->shipping_rates['transport_shipping_service'] )) {
        $line_item = $order->shipping_rates['transport_shipping_service'];
        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

        $amount = $line_item_wrapper->commerce_unit_price->amount->value();
        $data = $line_item_wrapper->commerce_unit_price->data->value();
        $txt_price = '';
        if (empty($data['error'])) {
            $txt_price = $amount ? commerce_currency_format($amount, $line_item_wrapper->commerce_unit_price->currency_code->value()) : t('free');
            $txt_price = '<div>Стоимость: <span class="amount">' . $txt_price . '</span></div>';
        }

        $message = '';
        if (!empty($data['error']) && $data['error'] == 1) $message = 'уточните адрес';
        if (!empty($data['error']) && $data['error'] == 2) $message = 'расчёт не выполнен';
        if (!empty($data['error']) && $data['error'] == 3) $message = 'сервис недоступен';


        $options['transport_shipping_service'] = t('!shipping_service!price', array(
            '!shipping_service' => $message ? commerce_shipping_line_item_title($line_item) . '<br /><span class="error">' . $message .  '</span>' : commerce_shipping_line_item_title($line_item) . '<br />',
            '!price' => $txt_price,
        ));
    }
}

/**
 * Shipping service callback: returns the example shipping service details form.
 */
function transport_service_details_form($pane_form, $pane_values, $checkout_pane, $order, &$shipping_service) {
    // в $order после ajax submit старые данные, загружаем заново
    $order_new = commerce_order_load($order->order_id);
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order_new);

    // заполнить поля адреса и фио
    $address_id = 0;
    $address = array();
    if (!empty($order->commerce_customer_shipping)) {
        // загрузить профиль доставки и сформировать в строки
        $shipping_wrapper = $order_wrapper->commerce_customer_shipping;
        if ($shipping_wrapper->field_ship_address->value()) {
            $address_id = $shipping_wrapper->field_ship_address->value();
            $address = address_book_addr_to_string($address_id);
        } 
        $to_door = $shipping_wrapper->field_ship_to_door->value();
        $insurance = $shipping_wrapper->field_ship_insurance->value();
    }

    $form = array();

    $form['title'] = array(
        '#markup' => '<div class="fieldset-title">'. t('Transport company delivery') .'</div>'
    );

    // если есть сообщения или ошибки - вывести
    if(isset($order->shipping_rates)) {
        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $order->shipping_rates['transport_shipping_service']);
        if(isset($line_item_wrapper)) {
            $data = $line_item_wrapper->commerce_unit_price->data->value();
        }
    }

    $message = empty($data['message']) ? '' : $data['message'];
    if (!empty($data['error'])) $message = '<span class="error">' . $message . '</span>';

    $form['message'] = array(
        '#markup' => '<div class="item">' . $message . '</div>',
        '#prefix' => '<div class="fieldset">',
        '#suffix' => '</div>'
    );

    $form['customer'] = array(
        '#markup' => $address ? ('<div class="item"><div>ФИО:</div><div id="customer">' . $address['user'] . '</div></div>') : '',
        '#prefix' => '<div class="fieldset">'
            .'  <div class="head">' .t('Customer information').'</div>',
    );
    $form['address'] = array(
        '#markup' => $address ? ('<div class="item"><div>' . t('Address') . ':</div><div id="address">'. $address['address'] . '</div></div>') : '',
    );
    $form['passport'] = array(
        '#markup' => $address ? ('<div class="item"><div>' . t('Passport') . ':</div><div id="passport">' . $address['passport'] . '</div></div>') : '',
    );

    $link_adr_message = ($address_id) ? t('Address book') : t('Choose from Address Book');
    $link_adr = l($link_adr_message, 'adr-book/' . $address_id . '/transport/' . $order->order_id . '/nojs', array('attributes' => array('class' => array('ctools-modal-style', 'ctools-use-modal'))));
    $form['button'] = array(
        '#markup' => '<div class="info">' . $link_adr . '</div>',
        '#suffix' => '</div>'
    );


    $options = array(
        0 => t('terminal'),
        1 => t('door'),
    );
    $form['to_door'] = array(
        '#title'            => t('Deliver order to '),
        '#type'             => 'radios',
        '#options'          => $options,
        '#default_value'    => (integer)$to_door,
        '#ajax' => array(
            'callback' => 'transport_ajax_to_door_refresh',
        ),
        '#prefix' => '<div class="fieldset">'
            .'  <div class="head">' .t('Options').'</div>'
    );
    $form['insurance'] = array(
        '#type' => 'checkbox',
        '#title' => t('Add insurance'),
        '#default_value' => (integer)$insurance,
        '#checked' => false,
        '#ajax' => array(
            'callback' => 'transport_ajax_insurance_refresh',
        ),
        '#suffix' => '</div>'
    );


    if (isset($data['terminals'])) {
        $terminals = '';
        foreach($data['terminals'] as $item) {
            $terminals .= $item['address'] . '<br />';
        }
        $time = empty($data['time']) ? '' : $data['time'];
        $form['terminals'] = array(
            '#markup' => '  <div class="item"><div>' .t('Delivery time') . ':</div>' . $time . '</div>'
                        .'  <div class="item"><div>' .t('Terminal adresses'). ':</div>' . $terminals .'</div>',
            '#prefix' => '<div class="fieldset">'
                        .'  <div class="head">' .t('Shipping information').'</div>',
            '#suffix' => '</div>'

        );
    }

    $form['information'] = array(
        '#markup' => '<div class="info">'. t('Shipping is provided by "DELOVIE LINII" company. Services cost is accounted automatically basing on transport company web-site rater. Fill all fields above to get correct amount.') .'</div>',
        '#prefix' => '<div class="fieldset">'
                    .'  <div class="head">' .t('Description').'</div>',
        '#suffix' => '</div>'
    );

    return $form;
}

/*
 * callback пересчёт тарифа после изменения значения поля Доставка до двери
 */
function transport_ajax_to_door_refresh ($form, $form_state){
    $to_door = $form_state['values']['commerce_shipping']['service_details']['to_door'];

    // изменить опцию доставки в заказе
    if ($order = commerce_order_load($form_state['order']->order_id)) {
        $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
        $shipping_wrapper = $order_wrapper->commerce_customer_shipping;
        $shipping_wrapper->field_ship_to_door->set($to_door);
        $shipping_wrapper->save();
        $address_id = $shipping_wrapper->field_ship_address->value();

        // чистим кеш сохраненных расчётов в заказе
        cache_clear_all('transport_service_rate_' . $form_state['order']->order_id . '_' . $address_id, 'cache', TRUE);
    }

    return array(
        '#type' => 'ajax',
        '#commands' => array(
            ajax_command_invoke('input[name="customer_profile_shipping[field_ship_to_door][und][0][value]"]', 'val', array($to_door)),
            ajax_command_invoke(null, 'commerceCheckShippingRecalculation'),
        ),
    );
}

/*
 * callback пересчёт тарифа после изменения значения поля Страховка
 */
function transport_ajax_insurance_refresh ($form, $form_state){
    $insurance = $form_state['values']['commerce_shipping']['service_details']['insurance'];

    // изменить опцию доставки в заказе
    if ($order = commerce_order_load($form_state['order']->order_id)) {
        $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
        $shipping_wrapper = $order_wrapper->commerce_customer_shipping;
        $shipping_wrapper->field_ship_insurance->set($insurance);
        $shipping_wrapper->save();
        $address_id = $shipping_wrapper->field_ship_address->value();

        // чистим кеш сохраненных расчётов в заказе
        cache_clear_all('transport_service_rate_' . $form_state['order']->order_id . '_' . $address_id, 'cache', TRUE);
    }

    return array(
        '#type' => 'ajax',
        '#commands' => array(
            ajax_command_invoke('input[name="customer_profile_shipping[field_ship_insurance][und][0][value]"]', 'val', array($insurance)),
            ajax_command_invoke(null, 'commerceCheckShippingRecalculation'),
        ),
    );
}

/**
 * Shipping service callback: validates the example shipping service details.
 */
function transport_service_details_form_validate($details_form, $details_values, $shipping_service, $order, $form_parents){
    // проверить наналичие ошибок в форме
    if (strpos($details_form['message']['#markup'], 'error') !== false) {
        $error = strip_tags($details_form['message']['#markup']);
        form_set_error(implode('][', array_merge($form_parents, array('name'))), $error);
        return false;
    }
}

/**
 * Shipping service callback: increases the shipping line item's unit price if
 * express delivery was selected.
 */
function transport_service_details_form_submit($details_form, $details_values, $line_item) {
//        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
//
//        // Build a price array for the express delivery fee.
//        $express_price = array(
//            'amount' => 1500,
//            'currency_code' => $line_item_wrapper->commerce_unit_price->currency_code->value(),
//            'data' => array(),
//        );
//
//        // Add the express upcharge to the line item unit price.
//        $line_item_wrapper->commerce_unit_price->amount = $line_item_wrapper->commerce_unit_price->amount->value() + 1500;
//
//        // Add the express delivery fee component to the unit price.
//        $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
//            $line_item_wrapper->commerce_unit_price->value(),
//            'example_shipping_service_express',
//            $express_price,
//            TRUE,
//            FALSE
//        );

}

/**
 * функция возвращающая информацию о вызывающем модуле для модуля Address Book
 * @return array
 */
function transport_address_book_info() {
    return array('surname', 'name', 'name2', 'email', 'phone', 'region', 'city', 'passport');
}
/**
 * функция, вызываемая при ajax submit в модуле Address Book
 * вставка выбранного адреса в форму
 */
function transport_address_book_ajax_submit($form_state) {
    return order_address_book_ajax_submit($form_state);
}

/**
 * hook_node_presave
 * функция очищает кеш расчётов при сохранении нового или измененного адреса в модуле Address Book
 */
function transport_node_presave($node) {
    if ($node->type =='address') {
        if ($order_id = commerce_cart_order_id($GLOBALS['user']->uid)) {
            cache_clear_all('transport_service_rate_' . $order_id . '_', 'cache', TRUE);
        }
    }
}
/**
 * hook_node_delete
 * функция очищает кеш расчётов при удалении адреса в модуле Address Book
 */
function transport_node_delete($node) {
    if ($node->type =='address') {
        if ($order_id = commerce_cart_order_id($GLOBALS['user']->uid)) {
            cache_clear_all('transport_service_rate_' . $order_id . '_', 'cache', TRUE);
        }
    }
}
