<?php

define('YANDEX_API_KEY', 'c1e4b070-a5e4-4a15-bc6e-ce64711bdf52');

/**
 * Implements hook_menu().
 */
function sec_branches_menu()
{
  $items['filialy'] = [
    'title' => 'Regional warehouses',
    'page callback' => 'sec_branches_page',
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

function sec_branches_preprocess_page(&$vars)
{
  if (arg(0) == 'filialy') {
    $vars['banner_title'] = t('Contacts');
    $vars['is_title_on'] = false;

    drupal_add_js('https://api-maps.yandex.ru/2.1/?apikey=' . YANDEX_API_KEY . '&lang=ru_RU');
    drupal_add_js(drupal_get_path('module', 'sec_branches') . '/js/sec_branches.js');
  }
}

function sec_branches_page()
{
  // контакт в зависимости от гео
  $contacts = sec_branches_get_branches();
  $iso_code = key($contacts);
  if (module_exists('dadata_api')) {
    $user_ip = strpos($_SERVER['HTTP_HOST'], '.local') === false  ? $_SERVER['REMOTE_ADDR'] : '77.72.142.170';
    if ($suggestion = sec_branches_get_location_by_ip($user_ip)) {
      if (isset($contacts[$suggestion['location']['data']['region_iso_code']])) {
        $iso_code = $suggestion['location']['data']['region_iso_code'];
      }
    }
  }


  // -- URL карточки организации
  if ($file = file_load(variable_get('company_card', 0))) {
    $company_card_url = file_create_url($file->uri);
  }

  drupal_add_js(['sec_branches' => ['regions' => $contacts, 'iso_start' => $iso_code]], 'setting');

  $branches_html = '';
  foreach ($contacts as $iso => $contact) {
    if ($iso != 'RU-KIR') {
      foreach ($contact as $index => $item) {
        $branches_html .= '<div class="branch"><div class="title"><a href="#branches" id="' . $iso . $index . '">' . $item['address'] . '</a></div>';
//        $phones_arr = [];
//        foreach ($item['phones'] as $phone) {
//          $phones_arr[] =  '<a href="tel:' . $phone['raw'] . '" class="c0py">' . $phone['txt'] . '</a>';
//        }
//        if ($phones_arr) {
//          $branches_html .= '<div class="phones">' . implode($phones_arr, ', ') . '</div>';
//        }
        $branches_html .= '</div>';
      }
    }
  }

  return  '<div id="branches" class="branches">' .
    '<div class="h4">' . t('Trading House «Kirovo-Chepetsk Chemical Company» LLC') . '</div>' .
    '<div class="branch">' .
    '<div class="title"><a href="#" id="RU-KIR0">' . t('613048, Kirov region, Kirovo-Chepetsk, Proizvodstvennaya str., 6') . '</a></div>' .
    '<div class="phone"><a href="tel:+' . ext_user_normalize_phone(variable_get('phone_reception', '')) . '" class="c0py">' . ext_user_format_phone(variable_get('phone_reception', '')) . '</a></div>' .
    '<div class="email"><a href="mailto:' . variable_get('email_reception', '') . '" class="c0py">' . variable_get('email_reception', '') . '</a></div>' .
    '<div class=""><p>' . t('OGRN') . ' 1084312000750&nbsp;&nbsp;' . t('INN') . ' 4312138026</p></div>' .
    (empty($company_card_url) ? '' : '<div class="links"><a href="' . $company_card_url . '" download>' . t('Download details') . '</a></div>') .
    '</div>' .
    '<div id="map" class="map"></div>' .
    '<div class="h4">' . t('Warehouses in regions') . '</div><div class="notice">' . t('Click on the address to open it on the map') . '</div>' .
    '<div id="list" class="list">' . $branches_html . '</div>' .
    '</div>';
}

function sec_branches_get_branches()
{
  $branches = [];
  $voc = taxonomy_vocabulary_machine_name_load('warehouses');
  if ($voc && $terms = taxonomy_get_tree($voc->vid)) {
      foreach ($terms as $term) {
        $term_wr = entity_metadata_wrapper('taxonomy_term', $term->tid);
        $phones = $phones_arr = [];
        if ($phones_arr = explode(',', $term_wr->field_text_phone->value())) {
          foreach ($phones_arr as $phone) {
            $phones[] = [
              'raw' => str_replace(['(', ')', '-', ' '], '', $phone),
              'txt' => $phone,
            ];
          }
        }
        $branches[$term_wr->field_region_iso->value()][] = [
          'name' => $term_wr->label(),
          'target' => $term_wr->field_text->value(),
          'address' => $term_wr->field_text_address->value(),
          'phones' => $phones,
          'schedule' => $term_wr->field_text_schedule->value(),
          'coords' => ['x' => explode(',', $term_wr->field_text_coords->value())[0], 'y' => explode(',', $term_wr->field_text_coords->value())[1]],
        ];
      }
  } else
    $branches = [
      'RU-KIR' => [[
        'target' => 'Главный офис',
        'address' => '613048, Кировская область, г. Кирово-Чепецк, ул.Производственная, 6',
        'phones' => [
          ['raw' => str_replace(['(', ')', '-', ' '], '', variable_get('phone_reception', '8 (8332) 76-15-30')), 'txt' => variable_get('phone_reception', '8 (8332) 76-15-30')],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 58.540577, 'y' => 49.976613],
      ]],
      'RU-ALT' => [[
        'target' => 'Филиал',
        'address' => 'Алтайский край, г. Барнаул, ул. Власихинская, 151',
        'phones' => [
          ['raw' => '+79229277060', 'txt' => '+7 (922) 927-70-60'],
          ['raw' => '+79229276880', 'txt' => '+7 (922) 927-68-80'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 53.339113, 'y' => 83.639073],
      ]],
      'RU-AMU' => [[
        'target' => 'Филиал',
        'address' => 'Амурская область, с. Тамбовка',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 50.099146, 'y' => 128.060889],
      ]],
      'RU-BRY'  => [
        [
          'target' => 'Филиал',
          'address' => 'Брянская область, г. Брянск, проезд Московский, д. 10А',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 53.221991, 'y' => 34.431374],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Брянская область, с. Меленск, ул. Северная, д. 1Д',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 52.638079, 'y' => 32.925384],
        ],
      ],
      'RU-VGG' => [[
        'target' => 'Филиал',
        'address' => 'Волгоградская область, г. Волгоград, пр-д. Нефтяников, владение 14',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 48.763024, 'y' => 44.464316],
      ]],
      'RU-VOR' => [[
        'target' => 'Филиал',
        'address' => 'Воронежская область,  Новоусманский р-н, с. Бабяково, ул. Индустриальная, 46',
        'phones' => [
          ['raw' => '+79292096040', 'txt' => '+7 (929) 209-60-40'],
          ['raw' => '+79292099221', 'txt' => '+7 (929) 209-92-21'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 51.708595, 'y' => 39.465569],
      ]],
      'RU-IRK' => [[
        'target' => 'Филиал',
        'address' => 'Иркутская область, г. Иркутск, ул. Тухачевского, д. 25',
        'phones' => [
          ['raw' => '+79229000152', 'txt' => '+7 (922) 900-01-52'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 52.363346, 'y' => 104.163996],
      ]],
      'RU-KDA' => [
        [
          'target' => 'Филиал',
          'address' => 'Краснодарский край, с. Белая Глина, ул. Привокзальная, 21',
          'phones' => [
            ['raw' => '+79229000573', 'txt' => '+7 (922) 900-05-73'],
            ['raw' => '+79229571119', 'txt' => '+7 (922) 957-11-19'],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 46.092999, 'y' => 40.840126],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Краснодарский край, г. Тимашевск, ул. Промышленная, д. 3',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 45.648163, 'y' => 38.968441],
        ],
      ],
      'RU-KYA' => [[
        'target' => 'Филиал',
        'address' => 'Красноярский край, пос. Солонцы, квартал Центральная промзона, стр. 18А',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 56.074428, 'y' => 92.838324],
      ]],
      'RU-KGN' => [[
        'target' => 'Филиал',
        'address' => 'Курганская область, г. Курган, ул. Омская, д. 134, стр. 3',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 55.468790, 'y' => 65.375613],
      ]],
      'RU-KRS' => [[
        'target' => 'Филиал',
        'address' => 'Курская область, г.Курск, ул. Магистральная, д. 1',
        'phones' => [
          ['raw' => '+79229227622', 'txt' => '+7 (922) 922-76-22'],
          ['raw' => '+79229227610', 'txt' => '+7 (922) 922-76-10'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 51.652578, 'y' => 36.129944],
      ]],
      'RU-LIP' => [[
        'target' => 'Филиал',
        'address' => 'г. Липецк, пос. Сырский Рудник, ул. Ново-Весовая, 24',
        'phones' => [
          ['raw' => '+79229084144', 'txt' => '+7 (922) 908-41-44'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 52.569615, 'y' => 39.481864],
      ]],
      'RU-NGR' => [[
        'target' => 'Филиал',
        'address' => 'Новгородская область, рп. Панковка, ул. Промышленная, д. 13',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 58.505291, 'y' => 31.208991],
      ]],
      'RU-NVS' => [[
        'target' => 'Филиал',
        'address' => 'Новосибирск, Толмачевская ул, 43/4',
        'phones' => [
          ['raw' => '+79229666434', 'txt' => '+7 (922) 966-64-34'],
          ['raw' => '+79229258884', 'txt' => '+7 (922) 925-88-84'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 54.969114, 'y' => 82.801061],
      ]],
      'RU-OMS' => [[
        'target' => 'Филиал',
        'address' => 'г. Омск, Карбышево 2-я ст.',
        'phones' => [
          ['raw' => '+79229007473', 'txt' => '+7 (922) 900-74-73'],
          ['raw' => '+79229000201', 'txt' => '+7 (922) 900-02-01'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 54.909313, 'y' => 73.259183],
      ]],
      'RU-ORE' => [
        [
          'target' => 'Филиал',
          'address' => 'г. Оренбург, Шарлыкское шоссе, 4',
          'phones' => [
            ['raw' => '+79229666500', 'txt' => '+7 (922) 966-65-00'],
            ['raw' => '+79229706055', 'txt' => '+7 (922) 970-60-55'],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 51.854567, 'y' => 55.126447],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Оренбургская область, с. Грачевка, ул. Зеленая, д. 44',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 52.919119, 'y' => 52.850772],
        ],
      ],
      'RU-ORL' => [[
        'target' => 'Филиал',
        'address' => 'г. Орёл, ул. Северная, зд. 9в',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 53.004035, 'y' => 36.098422],
      ]],
      'RU-PNZ' => [[
        'target' => 'Филиал',
        'address' => 'г. Пенза, ул. Байдукова, 94',
        'phones' => [
          ['raw' => '+79229000122', 'txt' => '+7 (922) 900-01-22'],
          ['raw' => '+79292090080', 'txt' => '+7 (929) 209-00-80'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 53.236572, 'y' => 45.005524],
      ]],
      'RU-PRI' => [
        [
          'target' => 'Филиал',
          'address' => 'Приморский край, с.Михайловка, ул.Вокзальная, д. 72',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 43.936497, 'y' => 132.025990],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Приморский край, пгт.Сибирцево, ул.Брюсова, д. 49',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 44.205336, 'y' => 132.471537],
        ],
      ],
      'RU-BA'  => [
        [
          'target' => 'Филиал',
          'address' => 'Республика Башкортостан, г. Уфа, ул. Ульяновых, д. 65',
          'phones' => [
            ['raw' => '+79229007477', 'txt' => '+7 (922) 900-74-77'],
            ['raw' => '+79226650015', 'txt' => '+7 (922) 665-00-15'],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 54.829959, 'y' => 56.086117],
        ],
      ],
      'RU-KRM' => [[
        'target' => 'Филиал',
        'address' => 'Республика Крым, г. Симферополь, пер. С.Ф.Бокуна, д. 32',
        'phones' => [
          ['raw' => '', 'txt' => ''],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 44.972563, 'y' => 34.116128],
      ]],
      'RU-ROS' => [
        [
          'target' => 'Филиал',
          'address' => 'Ростовская область, ст-ца Егорлыкская, ул. Буденного, д. 2',
          'phones' => [
            ['raw' => '+79229571020', 'txt' => '+7 (922) 957-10-20'],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 46.570117, 'y' => 40.673830],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Ростовская область, г. Батайск, Сальское ш., зд. 1Г',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 47.088635, 'y' => 39.763657],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Ростовская область, сп. Ленинское, ул. Тенистая, д. 2',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 47.096016, 'y' => 39.835387],
        ],
      ],
      'RU-SAM' => [
        [
          'target' => 'Филиал',
          'address' => 'Самарская область, г. Самара, Гаражный проезд, д. 4',
          'phones' => [['raw' => '', 'txt' => '']],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 53.122123, 'y' => 50.098244],
        ],
      ],
      'RU-STA' => [
        [
          'target' => 'Филиал',
          'address' => 'Ставропольский край, г. Михайловск, ул. Никонова, д. 60',
          'phones' => [['raw' => '', 'txt' => '']],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 45.139878, 'y' => 42.067566],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Ставропольский край, г. Новоалександровск, ул. Толстого, 15',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 45.485696, 'y' => 41.238052],
        ],
        [
          'target' => 'Филиал',
          'address' => 'Ставропольский край, г. Ставрополь, ул. 8 Промышленная, д. 20, пом. 2',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 45.079664, 'y' => 41.928462],
        ],
      ],
      'RU-TAM' => [
        [
          'target' => 'Филиал',
          'address' => 'Тамбовская область, р.п Новая Ляда, ул. Совхозная, 2Ж',
          'phones' => [
            ['raw' => '', 'txt' => ''],
          ],
          'schedule' => 'Пн-Пт  8:00-17:00',
          'coords' => ['x' => 52.713086,'y' =>  41.639510],
        ]
      ],
      'RU-TYU' => [[
        'target' => 'Филиал',
        'address' => 'г. Тюмень, ул. Камчатская д. 194 строение 4',
        'phones' => [
          ['raw' => '+79229666004', 'txt' => '+7 (922) 966-60-04'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 57.153187, 'y' => 65.677150],
      ]],
      'RU-CHE' => [[
        'target' => 'Филиал',
        'address' => 'Челябинская область, г. Копейск, ул. Старопоселковая, д. 32',
        'phones' => [
          ['raw' => '+79227472641', 'txt' => '+7 (922) 747-26-41'],
          ['raw' => '+79227472640', 'txt' => '+7 (922) 747-26-40'],
          ['raw' => '+79229058984', 'txt' => '+7 (922) 905-89-84'],
        ],
        'schedule' => 'Пн-Пт  8:00-17:00',
        'coords' => ['x' => 55.060879, 'y' => 61.535971],
      ]],
    ];

  return $branches;
}

/**
 * Вернуть геолокацию по IP адресу
 */
function sec_branches_get_location_by_ip($ip)
{
  $suggestion = &drupal_static(__FUNCTION__, NULL);
  if (!isset($suggestion)) {
    $dadata = new DaDataApiSuggestions;
    if ($suggestion = $dadata->ipLocate($ip)) {
      return $suggestion;
    }
  }
  return $suggestion;
}
