<?php


/**
 * Implements hook_menu().
 */
function profiter_menu() {
    $items['profiter/main'] = array(
        'title' => 'Profiter',
        'page callback' => 'profiter_main_page_callback',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['profiter/update/%'] = array(
        'title' => 'Profiter',
        'page callback' => 'profiter_update_callback',
        'page arguments' => array(2),
        'delivery callback' => 'ajax_deliver',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['profiter/algo/%/edit'] = array(
        'title' => 'Profiter',
        'page callback' => 'profiter_algo_edit_callback',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['profiter/coin/%/edit'] = array(
        'title' => 'Profiter',
        'page callback' => 'profiter_coin_edit_callback',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * основная страница с подключением библиотек и скриптов
 * @return string
 */
function profiter_main_page_callback() {
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_js('misc/ajax.js');

    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();

    $example_style = array(
        'modal-style' => array(
            'modalSize' => array(
                'type' => 'fixed', // Тип модального окна. фиксированный или резиновый.
                'width' => 420, // Ширина модального окна.
                'height' => 'auto', // Высота модального окна.
            ),
            'modalOptions' => array(
                'opacity' => (float) 0.8, // Прозрачность фона.
                'background-color' => '#000000', // Цвет фона.
            ),
            'closeText' => '', // Текст для закрытия модального окна.
            'loadingText' => '', // Текст, отображаемый в момент загрузки модального окна.
            'animation' => 'fadeIn', // Эффект появления модального окна.
            'animationSpeed' => 'fast', // Скорость анимации.
        ),
    );

    // Подключаем настройки для модального окна.
    drupal_add_js($example_style, 'setting');


    $output = profiter_get_table_html();

    return $output;
}

/**
 * обновление страницы
 * @return string
 */
function profiter_update_callback($cid, $mode = NULL) {
    if ($mode != 'ajax') {
        drupal_goto('profiter/main');
    }

    if ($cid) {
        profiter_wtm_update_one($cid);
    } else {
        // обновляем данные с WTM
        profiter_wtm_update();
    }

    // возвращаем таблицу
    $output = profiter_get_table_html();
    $commands[] = ajax_command_replace('#table', $output);

    return array(
        '#type' => 'ajax',
        '#commands' => $commands,
    );
}

/**
 * ------------------------------- редактирование алгоритма ------------------------------------------------------------
 * @return string
 */
function profiter_algo_edit_callback($algo_name, $mode = NULL) {
    if ($mode != 'ajax') {
        drupal_goto('profiter/main');
    }

    if ($mode == 'ajax') {
        ctools_include('modal');

        $form_state = array('ajax' => TRUE, 'title' => t('Edit algorithm'));
        $form_state['build_info']['args'] = array('algo' => $algo_name);
        $output = ctools_modal_form_wrapper('profiter_algo_form', $form_state);
        if (!empty($form_state['ajax_commands'])) { $output = $form_state['ajax_commands']; }
        print ajax_render($output); drupal_exit();
    } else {
        return drupal_get_form('profiter_algo_form', $algo_name);
    }

}

/**
 * форма редактирования алгоритма
 */
function profiter_algo_form($form, &$form_state, $algo_name) {
    global $user;

    if ($entities = entity_load('algo', false, array('name' => $algo_name))) {
        $algo = current($entities);
        $form_state['algo'] = $algo;
    }

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Алгоритм',
        '#default_value' => isset($algo->name) ? $algo->name : $algo_name,
    );
    $form['hash'] = array(
        '#type' => 'textfield',
        '#title' => t('Rig hashrate'),
        '#default_value' => $algo->hash,
    );

    $form['actions'] = array('#type' => 'container', '#attributes' => array('class' => array('form-actions')));
    $form['actions']['algo-submit'] = array(
        '#type' => 'submit',
        '#value' => 'Сохранить',
        '#ajax' => array(
            'callback' => 'profiter_algo_form_ajax_handler'
        ),
    );


    return $form;
}
function profiter_algo_form_submit($form, $form_state) {

    if (empty($form_state['algo'])) {
        $algo = entity_create('algo', array('name' =>  $form_state['values']['algo']));
    } else $algo = $form_state['algo'];

    $algo->name = $form_state['values']['name'];
    $algo->hash = $form_state['values']['hash'];
    $algo->save();
}
function profiter_algo_form_ajax_handler($form, $form_state) {
    ctools_include('modal');

    // обновить список полей
    $output = profiter_get_table_html();
    $commands[] = ajax_command_replace('#table', $output);
    $commands[] = ctools_modal_command_dismiss();

    return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * ------------------------------- редактирование монеты ---------------------------------------------------------------
 * @return string
 */
function profiter_coin_edit_callback($coin_id, $mode = NULL) {
    if ($mode == 'ajax') {
        ctools_include('modal');

        $form_state = array('ajax' => TRUE, 'title' => t('Edit coin'));
        $form_state['build_info']['args'] = array('coin_id' => $coin_id);
        $output = ctools_modal_form_wrapper('profiter_coin_form', $form_state);
        if (!empty($form_state['ajax_commands'])) { $output = $form_state['ajax_commands']; }
        print ajax_render($output); drupal_exit();
    } else {
        return drupal_get_form('profiter_coin_form', $coin_id);
    }
}

/**
 * форма редактирования алгоритма
 */
function profiter_coin_form($form, &$form_state, $coin_id) {

    if ($entities = entity_load('coin', array($coin_id))) {
        $coin = current($entities);

        $form_state['coin'] = $coin;
    }
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Монета',
        '#default_value' => $coin->name,
    );
    $form['tag'] = array(
        '#type' => 'textfield',
        '#title' => 'Символ',
        '#default_value' => $coin->tag,
    );

    $options= array();
    if ($entities = entity_load('algo', false)) {
        foreach($entities as $algo) {
            $options[$algo->name] = $algo->name;
        }
    }
    $form['algo'] = array(
        '#type' => 'select',
        '#title' => 'Алгоритм',
        '#options' => $options,
        '#default_value' => $coin->algo,
    );

    $form['block_reward'] = array(
        '#type' => 'textfield',
        '#title' => 'Награда за блок',
        '#default_value' => $coin->block_reward,
    );
    $form['diff'] = array(
        '#type' => 'textfield',
        '#title' => 'Сложность',
        '#default_value' => $coin->diff,
    );
    $form['diff_24'] = array(
        '#type' => 'textfield',
        '#title' => 'Сложность',
        '#default_value' => $coin->diff_24,
    );
    $form['pow'] = array(
        '#type' => 'textfield',
        '#title' => 'Модификатор',
        '#default_value' => $coin->pow,
    );

    $form['actions'] = array('#type' => 'container', '#attributes' => array('class' => array('form-actions')));
    $form['actions']['coin-submit'] = array(
        '#type' => 'submit',
        '#value' => 'Сохранить',
        '#ajax' => array(
            'callback' => 'profiter_coin_form_ajax_handler'
        ),
    );


    return $form;
}
function profiter_coin_form_submit($form, $form_state) {
    global $user;

    if (empty($form_state['coin'])) {
        $coin = entity_create('coin', array());
    } else $coin = $form_state['coin'];

    $coin->tag = $form_state['values']['tag'];
    $coin->name = $form_state['values']['name'];
    $coin->block_reward = $form_state['values']['block_reward'];
    $coin->difficulty = $form_state['values']['diff'];
    $coin->difficulty = $form_state['values']['diff_24'];
    $coin->algo = $form_state['values']['algo'];
    $coin->pow = $form_state['values']['pow'];

    if ($entity = entity_load('algo', false, array('name' => $form_state['values']['algo']))) {
        $algo = current($entity);
        $coin->reward   = (($algo->hash * $coin->block_reward) / ($coin->diff * $coin->pow)) * 3600 * 24;
        $coin->reward_24 = (($algo->hash * $coin->block_reward) / ($coin->diff_24 * $coin->pow)) * 3600 * 24;
    }

    $coin->save();
}
function profiter_coin_form_ajax_handler($form, $form_state) {
    ctools_include('modal');

    // обновить список полей
    $output = profiter_get_table_html();
    $commands[] = ajax_command_replace('#table', $output);
    $commands[] = ctools_modal_command_dismiss();

    return array('#type' => 'ajax', '#commands' => $commands);
}




/**
 * обновить данные с WTM
 * @return string
 */
function profiter_wtm_update() {
    global $user;

    $id = 1;
    while($id < 250) {
        profiter_wtm_update_one($id);

        sleep(1);
        $id++;
    };
}

function profiter_wtm_update_one($cid) {

    $coin = null;
    $algo = null;

    // если данных нет в бд, сделать запрос
    if ($entities = entity_load('coin', false, array('wtm_id' => $cid))) {
        $coin = current($entities);
    } else {
        $url = 'http://whattomine.com/coins/' . $cid . '.json';
        $responce = drupal_http_request($url);
        if (empty($responce->error) && $data = json_decode($responce->data)) {
            $data = json_decode($responce->data);

            $coin = entity_create('coin', array('wtm_id' => $data->id, 'name' => $data->name, 'tag' => $data->tag, 'algo' => $data->algorithm, 'pow' => '4294967296'));
        }
        sleep(1);
    }

    if ($coin) {
        if ($entity = entity_load('algo', false, array('name' => $coin->algo))) {
            $algo = current($entity);
        }

        $url = 'http://whattomine.com/coins/' . $cid . '.json' . (empty($algo->hash) ? '' : '?hr=' . $algo->hash);
        $responce = drupal_http_request($url);
        if (empty($responce->error) && $data = json_decode($responce->data)) {
            $coin->diff           = $data->difficulty;
            $coin->diff_24        = $data->difficulty24;
            $coin->ex_rate        = $data->exchange_rate;
            $coin->block_reward   = $data->block_reward;
            $coin->btc_revenue    = empty($algo->hash) ? 0 : $data->btc_revenue;
            $coin->revenue        = empty($algo->hash) ? 0 : $data->revenue;
            $coin->updated        = REQUEST_TIME;
        }
        $coin->save();
    }
}

/**
 * вернуть разметку таблицы монет с данными из БД
 * @return string
 */
function profiter_get_table_html() {

    $algo_add_link  = '<a href="/profiter/algo/0/edit/nojs" class="btn btn-warning use-ajax ctools-modal-modal-style" title="добавить хэшрейт">Добавить Алго</a>';
    $coin_add_link  = ' <a href="/profiter/coin/0/edit/nojs" class="btn btn-warning use-ajax ctools-modal-modal-style" title="добавить монету">Добавить Монету</a>';

    $output = '<table id="table" class="table table-striped">';
    $output .= '<tr>';
    $output .= '<td colspan="11" align="right">' . $algo_add_link . $coin_add_link . ' <a href="/profiter/update/0/nojs" class="use-ajax btn btn-success">Обновить все</a></td>';
    $output .= '</tr>';
    $output .= '<tr>';
    $output .= '<th></th><th>Символ</th><th>Алго</th><th style="text-align: right;">Хэшрейт</th>'
             . '<th></th><th style="text-align: center;">Профит, BTC</th><th style="text-align: center;">Профит, $</th><th style="text-align: center;" width="110">Изменение сложности</th><th width="90"></th>';
    $output .= '</tr>';

    if ($entities = entity_load('coin', false)) {
        // все монеты с не 0 профитом
        foreach ($entities as $coin) {
            if ($coin->btc_revenue) $coins_sort[$coin->btc_revenue] = $coin->id;
        }

        if (!empty($coins_sort)) krsort($coins_sort);

        // монеты с 0 профитом
        foreach ($entities as $coin) {
            if (!$coin->btc_revenue) $coins_sort[] = $coin->id;
        }

        $n = 1;
        foreach ($coins_sort as $wtm_id) {
            $algo = null;
            $coin = $entities[$wtm_id];
            if ($entity = entity_load('algo', false, array('name' => $coin->algo))) {
                $algo = current($entity);
            }

            $hash = empty($algo) ? '' : $algo->hash;
            $algo_edit_link = '<a href="/profiter/algo/' . $coin->algo . '/edit/nojs" class="btn btn-info btn-xs use-ajax ctools-modal-modal-style" title="изменить хэшрейт"><span class="glyphicon glyphicon-edit"></span></a>';
            $coin_edit_link = '<a href="/profiter/coin/' . $coin->id . '/edit/nojs" class="btn btn-info btn-xs use-ajax ctools-modal-modal-style" title="изменить монету"><span class="glyphicon glyphicon-edit"></span></a>';
            $coin_upd_link =  $coin->wtm_id ? ('<a href="/profiter/update/' . $coin->wtm_id . '/nojs" class="btn btn-info btn-xs use-ajax ctools-modal-modal-style" title="обновить монету"><span class="glyphicon glyphicon-refresh"></span></a>') : '';

            // формула
            $reward = $reward_24 = '';
            if (!empty($coin->pow) && !empty($algo->hash)) {
                $reward   = number_format((($algo->hash * $coin->block_reward) / ($coin->diff * $coin->pow)) * 3600 * 24 * $coin->ex_rate, 4);
                $reward_24 = number_format((($algo->hash * $coin->block_reward) / ($coin->diff_24 * $coin->pow)) * 3600 * 24 * $coin->ex_rate, 4);
            }
            // сложность в % соотношении
            $diff = -100 + ($coin->diff/$coin->diff_24)*100;

            $output .= '<tr>';
            $output .= '<td>' . $n++ . '</td><td>' . $coin->tag . '</td><td>' . $coin->algo . '</td><td align="right">' . $hash . '</td>'
                     . '<td>' . $algo_edit_link . '</td>'
                      .'<td align="center">' . $coin->btc_revenue . '</td><td align="center">' . $coin->revenue . '</td>'
                      .'<td align="center">' . (int)$diff . '%</td>'
//                      . '<td>' . $reward . ' / ' . $reward_24 . '</td>'
//                      .'<td>' . number_format($coin->diff, 2) . '</td><td>' . number_format($coin->diff_24, 2) . '</td>'
                      .'<td>' . $coin_upd_link . ' ' . $coin_edit_link . '</td>';
            $output .= '</tr>';
        }
    }

    $output .= '</table>';


    return $output;
}


/**
 *
 *
 */
function profiter_callback1() {

    // формула

}

/**
 * Реализация hook_entity_info()
 */
function profiter_entity_info() {
    return array(
        'coin' => array(                                      // Системное имя сущности
            'label' => t('Coin'),                              // Человеко-понятное имя сущности
            'entity class' => 'Entity',                         // Класс сущности
            'controller class' => 'EntityAPIController',        // Контроллер сущности
            'base table' => 'coins',                          // Таблица, в которой хранится информация об альбомах
            'entity keys' => array(
                'id' => 'id',                                  // Название поля, в котором располагаются идентификаторы альбомов
            ),
            'module' => 'profiter',
        ),
        'algo' => array(                                      // Системное имя сущности
            'label' => t('Algorithm'),                              // Человеко-понятное имя сущности
            'entity class' => 'Entity',                         // Класс сущности
            'controller class' => 'EntityAPIController',        // Контроллер сущности
            'base table' => 'algorithms',                          // Таблица, в которой хранится информация об альбомах
            'entity keys' => array(
                'id' => 'id',                                  // Название поля, в котором располагаются идентификаторы альбомов
            ),
            'module' => 'profiter',
        ),
    );
}

/**
 * hook_custom_theme
 *
 * сменить тему для заданных страниц
 */
function profiter_custom_theme() {
    if ($_GET['q'] == 'profiter/main' || $_GET['q'] == 'profiter/wtm') {
        return 'gard';
    }
}

