<?php

/**
 * Implements hook_cron().
 */
function checkout_cron() {
//    if (module_exists('commerce_order')) {
//        $order_ids = db_select('commerce_order', 'o')
//            ->fields('o', array('order_id'))
//            ->condition('o.uid', 0)
//            ->condition('o.status', array('cart', 'checkout_checkout'))
//            ->condition('o.changed', REQUEST_TIME - max(ini_get('session.gc_maxlifetime'), 15000000), '<') // ~полгода
//            ->range(0, 100)
//            ->execute()
//            ->fetchCol();
//
//        if ($order_ids) {
//            commerce_order_delete_multiple($order_ids);
//            watchdog('commerce_cart', 'Удалено ' . count($order_ids) . ' анонимных корзин', NULL);
//        }
//    }
}

/**
 * Implements hook_commerce_checkout_pane_info()
 */
function checkout_commerce_checkout_pane_info() {
    return array(
        'checkout_cart' => array(
            'title' => t('Checkout cart'),
            'page' => 'checkout',
            'weight' => 0,
            'file' => 'includes/checkout_cart.checkout_pane.inc',
            'base' => 'checkout_cart_pane',
        ),
        'checkout_contact' => array(
            'title' => t('Checkout contact'),
            'page' => 'checkout',
            'weight' => 0,
            'file' => 'includes/checkout_contact.checkout_pane.inc',
            'base' => 'checkout_contact_pane',
        ),
    );
}

/**
 * Implementation of hook_module_implements_alter().
 */
function checkout_module_implements_alter(&$implementations, $hook)
{
    //  Если хук - hook_form_alter, то переносим нашу реализацию этого хука в конец очереди
    if ($hook == 'form_alter' && isset($implementations['checkout'])) {
        $group = $implementations['checkout'];
        unset($implementations['checkout']);
        $implementations['checkout'] = $group;
    }
    //  Если хук - hook_theme, то переносим нашу реализацию этого хука в конец очереди
    if ($hook == 'theme' && isset($implementations['checkout'])) {
        $group = $implementations['checkout'];
        unset($implementations['checkout']);
        $implementations['checkout'] = $group;
    }
}

function checkout_theme( ) {
    return array(
        'checkout_radio_element' => array(
            'render element' => 'element',
        ),
        'commerce_checkout_form_complete' => array(
            'render element' => 'form',
            'template' => 'templates/commerce-checkout-form-complete',
        ),
        'commerce_checkout_errors_message' => array(
            'variables' => array('label' => NULL, 'message' => NULL),
            'template' => 'templates/commerce-checkout-errors-message',
        ),
    );
}

function checkout_preprocess_page(&$vars)
{
    if (arg(0) == 'checkout') {
        $vars['header']['image'] = url('/' . drupal_get_path('module', 'checkout') . '/images/header_image.jpg', array('absolute' => true));
        $vars['header']['subtitle'] = t('You can keep here products you are interested in and send this list to our representative');
        if (arg(2) == 'complete') {
            $vars['header']['title'] = t('Request accepted');
            $vars['header']['subtitle'] = t('Our representative will contact you soon');
        }
        $vars['header']['print'] = true;
    }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 * форма Оформления заказа
 */
function checkout_form_commerce_checkout_form_checkout_alter(&$form, &$form_state, $form_id)
{
    $form['#attributes']['class'][] = 'commerce-checkout-form-checkout';

    // отключить отмену, переименовать оформление
    unset($form['buttons']['cancel']);
    $form['buttons']['continue']['#value'] = t('Send request');
    $form['buttons']['continue']['#attributes']['class'][] = 'pull-right btn-wide';
    $form['buttons']['continue']['#attributes']['onclick'][] = "yaCounter11541151.reachGoal('send_request'); return true;";
    $form['buttons']['continue']['#submit'][] = 'checkout_commerce_checkout_form_submit';
    // подавить общее сообщение о наличии ошибок в форме
    // выводить ошибки на соотв. панели
    // unset($form['error_message']);  // при длинном списке не видно ошибки после обновления страницы
}

/**
 * commerce_checkout_form submit callback
 */
function checkout_commerce_checkout_form_submit($form, $form_state)
{
    $region_tid = $form_state['values']['checkout_contact']['request']['forma']['region'];
    $rep_mail = $form_state['values']['checkout_contact']['request']['forma']['rep'];

    $sales = representatives_get_representatives($region_tid);
    // если выбран Представитель, найти его по email
    // todo Представителей связать с пользователем сайта
    $rep = [];
    foreach($sales['reps'] as $rep) {
        if (in_array($rep_mail, $rep['emails'])) {
            break;
        }
    }

    // отправить письма
    $params = [];
    $params['data'] = [
        'order' => $form_state['order'],
        'user' => [
            'region' => taxonomy_term_load($region_tid)->name,
            'email' => $form_state['values']['checkout_contact']['request']['forma']['email'],
            'name' => $form_state['values']['checkout_contact']['request']['forma']['name'],
            'phone' => $form_state['values']['checkout_contact']['request']['forma']['phone'],
        ],
        'rep' => $rep
    ];
    $params['mail_to'] = 'manager';

    if (strpos($_SERVER['HTTP_HOST'], '.local') === false) {
        // отправить письмо Представителю, дублировать Руководителю и Рудяк попросил отправлять ещё на td.sale3@kccc.ru
        if ($rep) {
            drupal_mail('mailer', 'order_creation', $rep_mail, $GLOBALS['language'], $params);
        }
        if (!empty($sales['heads'])) {
            $head = array_pop($sales['heads']);
            drupal_mail('mailer', 'order_creation', $head['emails'][0], $GLOBALS['language'], $params);
        }

        drupal_mail('mailer', 'order_creation', 'td.sale3@kccc.ru', $GLOBALS['language'], $params);

        // отправить письмо пользователю
        $params['mail_to'] = 'user';
        $user_mail = $form_state['values']['checkout_contact']['request']['forma']['email'];
        drupal_mail('mailer', 'order_creation', $user_mail, $GLOBALS['language']->language, $params);

    } else {
        drupal_mail('mailer', 'order_creation', 'mega_comp@mail.ru', 'ru', $params);
    }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 * форма добавления в корзину
 */
function checkout_form_commerce_cart_add_to_cart_form_alter(&$form, $form_state)
{
    // i18n не перевёл taxonomy_term_reference
    // извлекаем переведенное значение поля Упаковка вручную
    if (isset($form['attributes']['field_p_tare']['#options'])) {
        foreach ($form['attributes']['field_p_tare']['#options'] as $tid => $title) {
            $term_wr = entity_metadata_wrapper('taxonomy_term', $tid);
            $form['attributes']['field_p_tare']['#options'][$tid] = $term_wr->language($GLOBALS['language']->language)->name->value();
        }
    }

    // выводить элементы в одну строку с метками
    $form['#attributes']['class'][] = 'form-horizontal';
    $form['submit']['#prefix'] = '<div class="form-item form-action-wrapper">';
    $form['submit']['#suffix'] = '</div>';
    $form['submit']['#attributes']['onclick'][] = "yaCounter11541151.reachGoal('add_to_cart'); return true;";
    $form['submit']['#attributes']['class'][] = "btn-info";

    // если установлен в товаре флаг Out_of_stock, сделать Добавление в корзину неактивным
    $product_display = _get_product_display_by_product_id($form['product_id']['#value'], false);
    if (strpos($form_state['default_product']->type, 'product_') === 0) {
        if (isset($form['product_id']['#value']))
            $product_display = _get_product_display_by_product_id($form['product_id']['#value'], false);
        elseif (isset($form['product_id']['#default_value']))
            $product_display = _get_product_display_by_product_id($form['product_id']['#default_value'], false);

        $form['submit']['#value'] = t('Add to list');
    }

    // сферу и таблетку перенаправить на страду через кнопку Купить
    if ($product_display->field_pd_category['und'][0]['tid'] == '72785') {
        $form['submit']['#value'] = t('Buy');
        array_unshift($form['#submit'], 'checkout_cart_add_to_cart_form_submit');
        foreach($form['submit']['#attributes']['class'] as $index => $class) {
            if ($class == 'use-ajax-submit') unset($form['submit']['#attributes']['class'][$index]);
        }
    }

    if ((isset($product_display->out_of_stock) && $product_display->out_of_stock == 1)
        || (isset($product_display->field_pd_price_per_unit['und']) && (($product_display->field_pd_price_per_unit['und'][0]['amount'] == 0)))
    ) {
        $form['submit']['#disabled'] = true;
        $form['submit']['#value'] = t('Out of stock');
    }
}

function checkout_cart_add_to_cart_form_submit($form, $form_state)
{
    // если это сфера или таб, перейти на сайт страды
    if (isset($form_state['context']['entity_id'])) {
        if ($form_state['context']['entity_id'] == 8505) drupal_goto('https://joy-magazin.ru/product/finfire-sfera');
        if ($form_state['context']['entity_id'] == 8770) drupal_goto('https://joy-magazin.ru/product/finfire-tab');
    }
}

/**
 * ------------- При добавлении в корзину обновить блок корзины -------------------
 */
function checkout_commerce_fast_ajax_atc_commands_alter(&$commands, $form_state)
{
    foreach($commands as $key => $command) {
        // найти команду замены блока и скорректировать
        if ($command['selector'] == '#block-commerce-cart-cart') {
                $commands[$key]['selector'] = '#block-cart';
                $commands[$key]['data'] = checkout_get_cart_block();
        }
    }
    // добавить класс тряски для корзины
    $commands[] = ajax_command_invoke('#block-cart', 'addClass', array('shake-on'));
}

/**
 * возвращает html с количеством препаратов в корзине
 */
function checkout_get_cart_block()
{
    $product_quantity_count = 0;
    if ($order = commerce_cart_order_load($GLOBALS['user']->uid)) {
        $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

        foreach ($order_wrapper->commerce_line_items as $delta => $line_item_wrapper) {
            // If line item is a commerce product type
            if (in_array($line_item_wrapper->type->value(), commerce_product_line_item_types())) {
                $product_quantity_count += $line_item_wrapper->quantity->value();
            }
        }
    }

    return '<div id="block-cart" class="shake">' . ($product_quantity_count ? $product_quantity_count : '') . '</div>';
}

/**
 * ------------- страница завершения заказа (checkout/%/complete) ------------------------------------------------------
 */
function checkout_form_commerce_checkout_form_complete_alter(&$form, &$form_state)
{
    // передаём в template_preprocess номер заказа
    $form['order'] = array(
        '#markup' => $form_state['order']->order_number,
    );
}

function checkout_preprocess_commerce_checkout_form_complete(&$vars)
{
    $order = commerce_order_load_by_number($vars['form']['order']['#markup']);
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

    $data['order'] = $order;
    $data['number'] = $order->order_number;

    // пользователь
    $data['user_region'] = $order_wrapper->field_f_region->name->value();
    $data['user_region_tid'] = $order_wrapper->field_f_region->tid->value();
    $data['user_name'] = $order_wrapper->field_username->value();
    $data['user_phone'] = $order_wrapper->field_phone->value();
    $data['user_email'] = $order_wrapper->field_email->value();
    $data['rep_email'] = $order_wrapper->field_representative_mail->value();

    // физические данные
    $data['weight'] = commerce_physical_order_weight($order, 'kg');
    $data['volume'] = commerce_physical_order_volume($order, 'm');

    // кол-во наименований
    $data['items_count'] = format_plural($order_wrapper->commerce_line_items->count(), '@count item', '@count items', array(), array('context' => 'Checkout'));

    // представитель
    $sales = representatives_get_representatives($data['user_region_tid']);
    // если выбран Представитель, найти его по email
    // todo Представителей связать с пользователем сайта
    foreach($sales['reps'] as $rep) {
        if (in_array($data['rep_email'], $rep['emails'])) {
            $data['rep'] = $rep;
            $data['contact_card'] = theme('contact_card', array('contact' => $rep, 'options' => ['class' => 'col-md-6']));
            break;
        }
    }

    $vars['data'] = $data;
}

