<?php
/**
* @file
* Adds new payment way - bank transfer
*/

/**
 * Implements hook_commerce_payment_method_info().
 */
function other_method_commerce_payment_method_info() {
    return array(
        // Системное название способа оплаты.
        'other_method' => array(
            // Название способа оплаты для отображения в админке.
            'title' => t('Other Method'),
            // Название способа оплаты для отображения в форме чекаута. Может содержать html.
            // Опционально.
            'display_title' => t('Other method'),
            // Описание способа оплаты. Опционально.
            'description' => t('Choose other payment method with manager'),
            // Состояние способа оплаты при включении модуля: TRUE — включён, FALSE — выключен
            // (по умолчанию). Опционально.
            'active' => TRUE,
            // Сможет ли администратор самостоятельно добавить этот способ оплаты для
            // завершённого заказа. Опционально. По умолчанию TRUE.
            'terminal' => TRUE,
            // Нужно ли покупателю покидать пределы сайта при оплате заказа этим способом.
            // Опционально. По умолчанию FALSE.
            'offsite' => FALSE,
            // Автоматический редирект на сторонний сайт при оплате заказа этим способом.
            // Опционально. По умолчанию FALSE.
            'offsite_autoredirect' => FALSE,
        ),
    );
}

/**
 * Payment method callback: settings form.
 */
function other_method_settings_form($settings = NULL) {
    $form = array();
    $settings = (array)$settings
        + array('information' => '',
                );

    // Пример настройки — информация о способе оплаты
    $form['information'] = array(
        '#type' => 'textarea',
        '#title' => t('Information'),
        '#description' => t('Information you would like to be shown to users when they select this payment mthd.'),
        '#default_value' => $settings['information'],
    );


    return $form;
}

/**
 * Payment method callback: submit form.
 */
function other_method_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
    $form = array();
    $pane_values += array('cstm_method' => '');

    // Выводим информацию о способе оплаты
    if (!empty($payment_method['settings']['information'])) {
        $form['other_method_information'] = array(
            '#markup' => $payment_method['settings']['information']
        );
    }

    // Дополнительные данные — поле для ввода имени
    $form['cstm_method'] = array(
        '#type' => 'textfield',
        '#title' => t('Preferred method'),
        '#description' => t('Write here the payment method you prefer'),
        '#default_value' => $pane_values['cstm_method'],
        '#required' => TRUE,
    );

    return $form;
}

/**
 * Payment method callback: submit form submission.
 */
function other_method_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
    $order->data['other_method'] = $pane_values;

    // Создаём транзакцию
    $transaction = commerce_payment_transaction_new('other_method', $order->order_id);
    $transaction->instance_id = $payment_method['instance_id'];
    $transaction->amount = $charge['amount'];
    $transaction->currency_code = $charge['currency_code'];
    $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
    $transaction->message = t('The payment is pending.');
    commerce_payment_transaction_save($transaction);
}