<?php

/**
 * @file
 * Defines an example shipping method for testing and development.
 */


/**
 * Implements hook_commerce_shipping_method_info().
 */
function courier_commerce_shipping_method_info() {
    $shipping_methods = array();

    $shipping_methods['courier_shipping_method'] = array(
        'title' => t('Courier shipping method'),
        'description' => t('Defines shipping method by courier.'),
    );

    return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function courier_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['courier_shipping_service'] = array(
    'title' => t('Courier shipping service'),
    'display_title' => t('Courier'),
    'shipping_method' => 'courier_shipping_method',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'courier_service_rate',
      'details_form' => 'courier_service_details_form',
      'details_form_validate' => 'courier_service_details_form_validate',
      'details_form_submit' => 'courier_service_details_form_submit',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function courier_service_rate($shipping_service, $order) {
    // в $order после ajax submit старые данные, загружаем заново
    $order = commerce_order_load($order->order_id);
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order->order_id);

    $error = $message = '';
    $shipping_cost = 0;
    if ($order->commerce_customer_shipping) {
        $shipping_wrapper = $order_wrapper->commerce_customer_shipping;
        $address_id = $shipping_wrapper->field_ship_address->value();
        if ($address_id && $address = node_load($address_id)) {
            // проверить заполнение Обязательных полей
            $mandatory_fields = courier_address_book_info();
            $absent_fields = address_book_check_mandatory_fields($address, $mandatory_fields);

            if (!$absent_fields) {
                $address_wrapper = entity_metadata_wrapper('node', $address);
                $city = mb_strtolower(trim($address_wrapper->field_ab_city->value()));

                if (strpos($city, 'киров') !== false || strpos($city, 'кирово-чепецк') !== false) {
                    $order_amount = $order_wrapper->commerce_order_total->value();
                    $order_total = $order_amount['amount'] / 100;

                    $shipping_cost = 300;
                    if (strpos($city, 'киров') !== false && $order_total >= 3000) $shipping_cost = 0;
                    if (strpos($city, 'кирово-чепецк') !== false && $order_total >= 1000) $shipping_cost = 0;
                } else {
                    $error = 3;
                    $message = t('This shipping method is not available for your city.');
                }
            } else {
                $error = 1;
                $message = 'Заполните в выбранной записи Адресной книги следующие обязательные поля: ' . implode(', ' , array_values($absent_fields));
            }
        } else {
            $error = 1;
            $message = 'Для расчёта стоимости доставки выберите запись из Адресной книги';
        }
    } else {
        $error = 1;
        $message = 'Для расчёта стоимости доставки выберите запись из Адресной книги';
    }

    return array(
        'amount' => $shipping_cost*100,
        'currency_code' => $order_wrapper->commerce_order_total->currency_code->value(),
        'data' => array(
            'error' => $error,
            'message' => $message,
        ),
    );
}


/**
 * Allows modules to alter the options array generated to select a shipping
 * service on the checkout form.
 */
function courier_commerce_shipping_service_rate_options_alter(&$options, $order){
    if (isset( $order->shipping_rates['courier_shipping_service'] )) {
        $line_item = $order->shipping_rates['courier_shipping_service'];
        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

        $amount = $line_item_wrapper->commerce_unit_price->amount->value();
        $data = $line_item_wrapper->commerce_unit_price->data->value();
        $txt_price = '';
        if (empty($data['error'])) {
            $txt_price = $amount ? commerce_currency_format($amount, $line_item_wrapper->commerce_unit_price->currency_code->value()) : t('free');
            $txt_price = '<div>Стоимость:  <span class="amount">' . $txt_price . '</span></div>';
        }

        $message = '';
        if (!empty($data['error']) && $data['error'] == 1) $message = 'уточните адрес';
        if (!empty($data['error']) && $data['error'] == 2) $message = 'расчёт не выполнен';
        if (!empty($data['error']) && $data['error'] == 3) $message = 'сервис недоступен';

        $options['courier_shipping_service'] = t('!shipping_service!price', array(
            '!shipping_service' => $message ? commerce_shipping_line_item_title($line_item) . '<br /><span class="error">' . $message .  '</span>' : commerce_shipping_line_item_title($line_item) . '<br />',
            '!price' => $txt_price,
        ));
    }
}

/**
 * Shipping service callback: returns the shipping service details form.
 */
function courier_service_details_form($pane_form, $pane_values, $checkout_pane, $order, $shipping_service){
    // в $order после ajax submit старые данные, загружаем заново
    $order_new = commerce_order_load($order->order_id);
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order_new);

    // заполнить поля адреса и фио
    $address_id = 0;
    $address = array();
    if (!empty($order->commerce_customer_shipping)) {
        // загрузить профиль доставки и сформировать в строки
        if ($order_wrapper->commerce_customer_shipping->field_ship_address->value()) {
            $address_id = $order_wrapper->commerce_customer_shipping->field_ship_address->value();
            $address = address_book_addr_to_string($address_id);
        }
    }

    $form = array();

    $form['title'] = array(
        '#markup' => '<div class="fieldset-title">'. t('Courier delivery') .'</div>'
    );

    // если есть сообщения об ошибках - вывести
    if(isset($order->shipping_rates)) {
        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $order->shipping_rates['courier_shipping_service']);
        if(isset($line_item_wrapper)) {
            $data = $line_item_wrapper->commerce_unit_price->data->value();
        }
    }

    $message = empty($data['message']) ? '' : $data['message'];
    if (!empty($data['error'])) $message = '<span class="error">' . $message . '</span>';

    $form['message'] = array(
        '#markup' => '<div class="info">' . $message . '</div>',
        '#prefix' => '<div class="fieldset">',
        '#suffix' => '</div>'
    );

    $form['customer'] = array(
        '#markup' => $address ? ('<div class="item"><div>ФИО:</div><div id="customer">' . $address['user'] . '</div></div>') : '',
        '#prefix' => '<div class="fieldset">'
            .'  <div class="head">' .t('Customer information').'</div>',
    );
    $form['address'] = array(
        '#markup' => $address ? ('<div class="item"><div>' . t('Address') . ':</div><div id="address">'. $address['address'] . '</div></div>') : '',
    );


    $link_adr_message = ($address_id) ? t('Address book') : t('Choose from Address book');
    $link_adr = l($link_adr_message, 'adr-book/' . $address_id . '/courier/' . $order->order_id . '/nojs', array('attributes' => array('class' => array('ctools-modal-style', 'ctools-use-modal'))));
    $form['button'] = array(
        '#markup' => '<div class="info">' . $link_adr . '</div>',
        '#suffix' => '</div>'
    );

    $form['information'] = array(
        '#markup' => '<div class="info">'. 'Доставка курьером доступна только для двух городов: Киров и Кирово-Чепецк.<br />Стоимость доставки считается автоматически.' .'</div>',
        '#prefix' => '<div class="fieldset">'
            .'  <div class="head">' .t('Description').'</div>',
        '#suffix' => '</div>'
    );

    return $form;
}

/**
 * Shipping service callback: validates the example shipping service details.
 */
function courier_service_details_form_validate($details_form, $details_values, $shipping_service, $order, $form_parents){
    // проверить наналичие ошибок в форме
    if (strpos($details_form['message']['#markup'], 'error') !== false) {
        $error = strip_tags($details_form['message']['#markup']);
        form_set_error(implode('][', array_merge($form_parents, array('name'))), $error);
        return false;
    }
}

/**
 * Shipping service callback: increases the shipping line item's unit price if
 * express delivery was selected.
 */
function courier_service_details_form_submit($details_form, $details_values, $line_item) {
}

/**
 * Implements hook_commerce_price_component_type_info().
 */
function courier_commerce_price_component_type_info() {
//    return array(
//        'example_shipping_service_express' => array(
//            'title' => t('Express delivery'),
//            'weight' => 20,
//        ),
//    );
}

/**
 * функция возвращающая обязательные поля для модуля Address Book
 * @return array
 */
function courier_address_book_info() {
    return array('surname', 'name', 'name2', 'email', 'phone', 'city');
}
/**
 * функция, вызываемая при ajax submit в модуле Address Book
 * вставка выбранного адреса в форму
 */
function courier_address_book_ajax_submit($form_state) {
    return order_address_book_ajax_submit($form_state);
}