<?


/**
 * Implements hook_menu().
 */
function sec_structure_menu()
{
    $items['structure'] = array(
        'title' => 'Организационная структура',
        'page callback' => 'sec_structure_page',
        'page arguments' => array(1),
        'access callback' => true,
//        'access callback' => '_user_has_role',
//        'access arguments' => array('6'),       // только для роли Сотрудник
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_theme().
 */
function sec_structure_theme()
{
  return array(
    'structure_page' => array(
      'render element' => 'element',
    ),
    'structure_level' => array(
      'render element' => 'element',
      'template' => 'templates/structure-level',
    ),
    'structure_box' => array(
      'render element' => 'element',
      'template' => 'templates/structure-box',
    ),
  );
}

/**
 * menu callback
 */
function sec_structure_page()
{
  $structure = sec_structure_get_structure();

  drupal_add_css(drupal_get_path('module', 'sec_structure') . '/css/sec_structure.css');
  drupal_add_js(drupal_get_path('module', 'sec_structure') . '/js/sec_structure.js');

  return $structure;
}

/**
 * вернуть массив со структурой организации
 */
function sec_structure_get_structure()
{
  return [
    '#theme' => 'structure_page',
    'content' => [
      'level' => [
        '#theme' => 'structure_level',
        'child' => [
          [
            'shell' => 'Директор<br>КЧЗ "Агрохимикат"',
            'card' => 'АЛЕКСАНДРОВ<br>Валерий Николаевич',
            'photo' => drupal_get_path('module', 'sec_structure') . '/images/aleksandrov.png',
            'class' => 'deepblue open',
            '#theme' => 'structure_box',
            'level' => [
              '#theme' => 'structure_level',
              'child' => [
                [
                  'shell' => 'Административный корпус',
                  'card' => '',
                  'class' => 'deepblue',
                  '#theme' => 'structure_box',
                  'level' => [
                    '#theme' => 'structure_level',
                    'child' => [
                      [
                        'shell' => 'Финансовый директор',
                        'card' => 'ПЛАТУНОВ<br>Александр Борисович',
                        'photo' => drupal_get_path('module', 'sec_structure') . '/images/platunov.png',
                        'class' => 'orange',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Финансово-экономический отдел',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Экономист',
                                    'card' => 'Блохина Светлана Ивановна<a href="mailto:svetlana.blokhina@kccc.ru">svetlana.blokhina@kccc.ru</a>т. 76-15-21 (11-15)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Экономист<span style="font-size: .8em">по нормированию труда</span>',
                                    'card' => 'Овсейчик Елена Владимировна<br>т. 76-15-21 (11-19)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Зам. директора по правовым вопросам',
                        'card' => 'САБРЕКОВ<br>Эдуард Тахирович',
                        'photo' => drupal_get_path('module', 'sec_structure') . '/images/dumb.png',
                        'class' => 'orange',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Юридический отдел',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Заместитель руководителя',
                                    'card' => 'Изергин Константин Владимирович<a href="mailto:konstantin.izergin@kccc.ru">konstantin.izergin@kccc.ru</a>т. 76-15-22 (11-28)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Главный бухгалтер',
                        'card' => 'РАЗНАРЕВИЧ<br>Ольга Викторовна',
                        'photo' => drupal_get_path('module', 'sec_structure') . '/images/dumb.png',
                        'class' => 'orange',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Бухгалтерия',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Заместитель главного бухгалтера',
                                    'card' => 'Бобков Михаил Юрьевич<a href="mailto:michael.bobkov@kccc.ru">michael.bobkov@kccc.ru</a>т. 76-15-25 (11-36)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Ведущий бухгалтер<span style="font-size: .8em">по расчету с персоналом</span>',
                                    'card' => 'Койсина Алевтина Михайловна<a href="mailto:alevtina.koysina@kccc.ru">alevtina.koysina@kccc.ru</a>т. 76-15-25 (11-34)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                            [
                              'shell' => 'Отдел информационных технологий',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Ведущий специалист<span style="font-size: .8em">по защите информации</span>',
                                    'card' => 'Лучников Александр Альфредович<a href="mailto:aluch@kccc.ru">aluch@kccc.ru</a>т. 76-15-21 (11-13)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Инженер-системный программист',
                                    'card' => 'Асхадуллин Ильшат Ильдусович<a href="mailto:ilshat.askhadullin@kccc.ru">ilshat.askhadullin@kccc.ru</a>т. 76-15-21 (11-82)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Административный директор',
                        'card' => 'САВЕНКО<br>Ольга Васильевна',
                        'photo' => drupal_get_path('module', 'sec_structure') . '/images/dumb.png',
                        'class' => 'orange',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Служба управления персоналом',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Зам. административного директора',
                                    'card' => 'Огородова Мария Николаевна<a href="mailto:maria.ogorodova@kccc.ru">maria.ogorodova@kccc.ru</a>т. 76-15-22 (11-86)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Администратор офиса',
                                    'card' => 'Гвоздкова Елена Александровна<a href="mailto:td@kccc.ru">td@kccc.ru</a>т. 76-15-21 (11-07)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                            [
                              'shell' => 'Отдел логистики',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Начальник отдела логистики',
                                    'card' => 'Комлева Владилена Валериевна<a href="mailto:vlada.komleva@kccc.ru">vlada.komleva@kccc.ru</a>т. 76-15-23 (11-68)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                            [
                              'shell' => 'Отдел снабжения',
                              'card' => '',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Начальник отдела снабжения',
                                    'card' => 'Чернавский Александр Юрьевич<a href="mailto:aleksandr.chernavsky@kccc.ru">aleksandr.chernavsky@kccc.ru</a>т. 76-15-27 (11-23)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                    ],
                  ],
                ],
                [
                  'shell' => 'Производственный корпус',
                  'card' => '',
                  'class' => 'deepblue',
                  '#theme' => 'structure_box',
                  'level' => [
                    '#theme' => 'structure_level',
                    'child' => [
                      [
                        'shell' => 'Главный инженер',
                        'card' => 'НАУМОВ<br>Александр Владимирович',
                        'photo' => drupal_get_path('module', 'sec_structure') . '/images/dumb.png',
                        'class' => 'orange',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Участок производства смол',
                              'card' => '',
                              'class' => 'purple',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Начальник производства',
                                    'card' => 'ИСТАМОВ Вахид Кахарович<a href="mailto:vakhid.istamov@kccc.ru">vakhid.istamov@kccc.ru</a>т. 76-15-24 (11-38)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Зам. начальника производства',
                                    'card' => 'ШИБАНОВ Дмитрий Сергеевич<br>т. 76-15-24 (11-38)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                            [
                              'shell' => 'Участок производства ХСЗР',
                              'card' => '',
                              'class' => 'purple',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Начальник производства',
                                    'card' => 'ШУМИЛОВ Алексей Владимирович<a href="mailto:aleksey.shumilov@kccc.ru">aleksey.shumilov@kccc.ru</a>т. 76-15-24 (11-97)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Зам. начальника производства',
                                    'card' => 'ПЕХОТИН Александр Викторович<a href="mailto:aleksandr.pehotin@kccc.ru">aleksandr.pehotin@kccc.ru</a>т. 76-15-24 (11-97)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                            [
                              'shell' => 'Служба главного технолога',
                              'card' => '',
                              'class' => 'purple',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Начальник производства',
                                    'card' => 'ДЮПИН Вячеслав Викторович<a href="mailto:vyacheslav.dyupin@kccc.ru">vyacheslav.dyupin@kccc.ru</a>т. 76-15-24 (11-39)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],

                            ],
                            [
                              'shell' => 'Складское хозяйство',
                              'card' => '',
                              'class' => 'purple',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Начальник складского хозяйства',
                                    'card' => 'ЛЯЛИНА Ольга Владимировна<a href="mailto:olga.cepaeva@kccc.ru">olga.cepaeva@kccc.ru</a>т. 76-15-26 (11-31)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                  [
                                    'shell' => 'Зам. начальника складского хозяйства',
                                    'card' => 'ДЮНЯШЕВА Лариса Викторовна<a href="mailto:larisa.dyunyasheva@kccc.ru">larisa.dyunyasheva@kccc.ru</a>т. 76-15-26 (11-31)',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                  ],
                                ],
                              ],
                            ],
                            [
                              'shell' => 'Сервисные службы',
                              'card' => '',
                              'class' => 'purple',
                              '#theme' => 'structure_box',
                              'level' => [
                                '#theme' => 'structure_level',
                                'child' => [
                                  [
                                    'shell' => 'Механическая служба',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Главный механик',
                                          'card' => 'ЧЕРЕПАНОВ Дмитрий Владимирович<a href="mailto:dmitry.cherepanov@kccc.ru">dmitry.cherepanov@kccc.ru</a>т. 76-15-27 (11-42)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],
                                  ],
                                  [
                                    'shell' => 'Электрослужба',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Главный энергетик',
                                          'card' => 'ОБУХОВ Михаил Сергеевич<a href="mailto:mikhail.obukhov@kccc.ru">mikhail.obukhov@kccc.ru</a>т. 76-15-26 (11-31)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                        [
                                          'shell' => 'Зам. главного энергетика',
                                          'card' => 'ЮФЕРЕВ Андрей Александрович<a href="mailto:andrey.yuferev@kccc.ru">andrey.yuferev@kccc.ru</a>т. 76-15-26 (11-31)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],
                                  ],
                                  [
                                    'shell' => 'Служба КИПиА',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Начальник службы',
                                          'card' => 'БАБОКИН Андрей Александрович<a href="mailto:andrey.babokin@kccc.ru">andrey.babokin@kccc.ru</a>т. +7 912 737 29 82',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],

                                  ],
                                  [
                                    'shell' => 'Технический отдел',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Начальник технического отдела',
                                          'card' => 'БЕЛОЗЕРОВ Алексей Федорович<a href="mailto:alexey.belozerov@kccc.ru">alexey.belozerov@kccc.ru</a>т. 76-15-22 (11-20)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],

                                  ],
                                  [
                                    'shell' => 'Отдел промышленной безопасности',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Начальник отдела',
                                          'card' => 'ОЛЮНИН Дмитрий Витальевич<a href="mailto:dmitriy.olyunin@kccc.ru">dmitriy.olyunin@kccc.ru</a>т. 76-15-22 (12-34)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                        [
                                          'shell' => 'Специалист по охране труда',
                                          'card' => 'БУЛАНОВ Андрей Николаевич<a href="mailto:andrei.bulanov@kccc.ru">andrei.bulanov@kccc.ru</a>т. 76-15-22 (11-18)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                        [
                                          'shell' => 'Инженер по охране окружающей среды',
                                          'card' => 'КАРГАПОЛЬЦЕВА Анастасия Аркадьевна<a href="mailto:anastasia.kargapoltseva@kccc.ru">anastasia.kargapoltseva@kccc.ru</a>т. 76-15-22 (11-17)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                        [
                                          'shell' => 'Медработник',
                                          'card' => 'ШУМИХИНА Светлана Петровна',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],

                                  ],
                                  [
                                    'shell' => 'Хозяйственная служба',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Начальник хозяйственной службы',
                                          'card' => 'ШУКЛИН Алексей Александрович<br>т. +7 953 139 47 89',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                        [
                                          'shell' => 'Зам. начальника хозяйственной службы',
                                          'card' => 'МИХАЙЛОВ Эдуард Викторович<br>т. +7 909 131 66 09',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],
                                  ],
                                  [
                                    'shell' => 'Автотранспортная служба',
                                    'card' => '',
                                    'class' => 'blue',
                                    '#theme' => 'structure_box',
                                    'level' => [
                                      '#theme' => 'structure_level',
                                      'child' => [
                                        [
                                          'shell' => 'Специалист по автранспорту',
                                          'card' => 'ШУКЛИН Алексей Александрович<a href="mailto:td.sale7@kccc.ru">td.sale7@kccc.ru</a>т. 76-15-21 (11-19)',
                                          'class' => 'blue',
                                          '#theme' => 'structure_box',
                                        ],
                                      ],
                                    ],
                                  ],
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Отдел реализации проектов',
                        'card' => '',
                        'class' => 'red',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Руководитель проектов',
                              'card' => 'СМИРНОВ Яков Эдуардович<a href="mailto:yakov.smirnov@kccc.ru">yakov.smirnov@kccc.ru</a>т. +7 912 820 11 11',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                            ],
                            [
                              'shell' => 'Руководитель проекта',
                              'card' => 'ГУТОВСКИЙ Дмитрий Владимирович<a href="mailto:dmitry.gutovsky@kccc.ru">dmitry.gutovsky@kccc.ru</a>т. +7 953 689 01 31',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Испытательная лаборатория',
                        'card' => '',
                        'class' => 'purple',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Начальник лаборатории',
                              'card' => 'ВОРОНЧИХИНА Екатерина Аркадьевна<a href="mailto:ekaterina.voronchihina@kccc.ru">ekaterina.voronchihina@kccc.ru</a>т. 76-15-26 (11-92)',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                            ],
                            [
                              'shell' => 'Зам.начальника лаборатории',
                              'card' => 'АНДРЕЕВА Наталия Игоревна<br>т. 76-15-26 (11-92)',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Отдел развития новых продуктов и технологий',
                        'card' => '',
                        'class' => 'purple',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Руководитель исследовательской группы',
                              'card' => 'ЦЕЛИЩЕВ Дмитрий Владимирович<a href="mailto:dmitry.tselishev@kccc.ru">dmitry.tselishev@kccc.ru</a>т. 76-15-24 (11-40)',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                            ],
                          ],
                        ],
                      ],
                      [
                        'shell' => 'Отдел технического контроля',
                        'card' => '',
                        'class' => 'blue',
                        '#theme' => 'structure_box',
                        'level' => [
                          '#theme' => 'structure_level',
                          'child' => [
                            [
                              'shell' => 'Начальник отдела',
                              'card' => 'ЕВТУШЕНКО Диана Юрьевна<a href="mailto:diana.evtushenko@kccc.ru">diana.evtushenko@kccc.ru</a>т. 76-15-26 (11-92)',
                              'class' => 'blue',
                              '#theme' => 'structure_box',
                            ],
                          ],
                        ],

                      ],

                    ],
                  ],
                ],
              ],
            ],
          ]
        ]
      ]
    ]
  ];
}

/**
 * A #theme function.
 */
function theme_structure_page($vars)
{
  return  '<div class="structure">' .
            '<h1 class="text-center">Организационная структура</h1>' .
            render($vars['element']['content']) .
          '</div>';
}

/**
 * Implements hook_preprocess_page().
 */
function sec_structure_preprocess_page(&$vars)
{
    // сменить шаблон страницы на пустой,
    // чтобы иметь возможность развернуться на весь экран
    if (arg(0) == 'structure' && !arg(1)) {
      $vars['header'] = array(
        'image' => '/' . drupal_get_path('module', 'sec_structure') . '/images/header_image.jpg',
        'category_title' => '',
      );
      $vars['theme_hook_suggestions'][] = 'page__empty';
    }
}
