<?

/**
 *  Implementation of hook_menu()
 */
function agroexpert_menu()
{
    $items['agro-expert'] = array(
        'title' => 'Agro Expert',
        'description' => 'You can get free help of our experts',
        'page callback' => 'agroexpert_router_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['agro-expert/online'] = array(
        'title' => 'Experts Online',
        'description' => 'Contact our expert directly by phone, email or WhatsApp',
        'page callback' => 'agroexpert_online_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
     return $items;
}

/**
 *  Страница маршрутизатор
 */
function agroexpert_router_page()
{
    $list = '';
    foreach(_get_agroexpert_router_items() as $item) {
        $list .= theme('router_card', ['item' => $item]);
    }

    $output = '' .
            '<div class="agro-expert-router">' .
                '<div class="row">' .
                    $list .
                '</div>' .
            '</div>';

    return $output;
}

/**
 *  Страница "Эксперты онлайн"
 */
function agroexpert_online_page()
{
    $list = '<div></div>';
    foreach(representatives_get_representatives_list() as $region) {
        foreach($region as $item) {
            if (!empty($item['expert'])) {
                $list .= theme('contact_card', array(
                    'contact' => $item,
                    'options' => ['class' => 'col-md-6']));
            }
        }
    }

    $output = '' .
            '<div class="agro-expert-online">' .
                '<div class="row">' .
                    $list .
                '</div>' .
            '</div>';

    return $output;
}

function _get_agroexpert_router_items()
{
    return [
        0 => [
            'title' => t('Consultation online'),
            'description' => t('Experts will help you online'),
            'url' => '/agro-expert/online',
            'image_url' => drupal_get_path('module', 'agroexpert') . '/images/expert_online.jpg',
            'button_text' => t('Go!'),
        ],
        1 => [
            'title' => t('Forum'),
            'description' => t('Dozens of experts and hundreds of different opinions'),
            'url' => '/forum',
            'image_url' => drupal_get_path('module', 'agroexpert') . '/images/expert_forum.jpg',
            'button_text' => t('Go!'),
        ],
        2 => [
            'title' => t('Request with photo'),
            'description' => t('Detailed answer for a specific pest'),
            'url' => '/agro-expert/form',
            'image_url' => drupal_get_path('module', 'agroexpert') . '/images/expert_photo.jpg',
            'button_text' => t('Go!'),
        ],
    ];
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function agroexpert_preprocess_page(&$vars)
{
    // установить для страницы параметры шапки
    if (arg(0) == 'agro-expert') {
        $category_title = '';
        $image = '/' . drupal_get_path('module', 'agroexpert') . '/images/header_image.jpg';
        if (arg(1) != '') {
            $category_title = '<a href="/agro-expert">' . t('Agro Expert') . '</a>';
        }

        $vars['header'] = array(
            'image' => $image,
            'category_title' => $category_title,
            'print' => false,
        );
    }

    if (drupal_get_path_alias($_GET['q']) == 'agro-expert/form') {
        $vars['header'] = array(
            'image' => '/' . drupal_get_path('module', 'agroexpert') . '/images/header_image.jpg',
            'category_title' => '<a href="/agro-expert">' . t('Agro Expert') . '</a>',
            'print' => false,
        );
    }
}