<?
define('AGROEXPERT_URL', 'agro-expert');

/**
 *  Implementation of hook_menu()
 */
function agroexpert_menu()
{
    $items[AGROEXPERT_URL] = array(
        'title' => 'Agro Expert',
        'description' => 'You can get free help of our experts',
        'page callback' => 'agroexpert_router_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items[AGROEXPERT_URL . '/online'] = array(
        'title' => 'Experts Online',
        'description' => 'Contact our expert directly by phone, email or WhatsApp',
        'page callback' => 'agroexpert_online_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
     return $items;
}

/**
 *  Страница маршрутизатор
 */
function agroexpert_router_page()
{
    $list = '';
    foreach(_get_agroexpert_router_items() as $item) {
        $list .= '<div class="col-md-4">' . theme('router_card', ['item' => $item]) . '</div>';
    }

    $output = '' .
            '<div class="agro-expert-router">' .
                '<div class="row">' .
                    $list .
                '</div>' .
            '</div>';

    return $output;
}

/**
 *  Страница "Эксперты онлайн"
 */
function agroexpert_online_page()
{
    $list = '';
    foreach(representatives_get_experts()['experts'] as $key => $exp) {
      $collapse = [];
      if (!empty($exp['regions'])) {
        $regions = [];
        foreach ($exp['regions'] as $region) {
          $regions[] = $region['name'];
        }
        $collapse = [
          'id' => 'exp_' . $key,
          'title' => t('Regions list'),
          'content' => implode(', ', $regions)
        ];
      }

        $list .= '<div class="col-md-4">' . theme('contact_card', ['contact' => $exp,'collapse' => $collapse]) . '</div>';
        if (($key) % 3) $list .= '<div class="clearfix"></div>';
    }

    $output =
            '<div class="agro-expert-online">' .
                '<div class="row">' .
                    $list .
                '</div>' .
            '</div>';

    return $output;
}

function _get_agroexpert_router_items()
{
    return [
        0 => [
          'title' => t('Consultation online'),
          'description' => t('Experts will help you online'),
          'url' => '/' . AGROEXPERT_URL . '/online',
          'image_url' => drupal_get_path('module', 'agroexpert') . '/images/expert_online.svg',
          'card_attributes' => ['class' => ['router-card', 'agro-expert']],
        ],
        1 => [
          'title' => t('Forum'),
          'description' => t('Dozens of experts and hundreds of different opinions'),
          'url' => '/forum',
          'image_url' => drupal_get_path('module', 'agroexpert') . '/images/expert_forum.svg',
          'card_attributes' => ['class' => ['router-card', 'agro-expert']],
        ],
        2 => [
          'title' => t('Request with photo'),
          'description' => t('Detailed answer for a specific pest'),
          'url' => '/' . AGROEXPERT_URL . '/form',
          'image_url' => drupal_get_path('module', 'agroexpert') . '/images/expert_photo.svg',
          'card_attributes' => ['class' => ['router-card', 'agro-expert']],
        ],
    ];
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function agroexpert_preprocess_page(&$vars)
{
    // установить для страницы параметры шапки
    if (arg(0) == 'agro-expert') {
        $category_title = '';
        $image = '/' . drupal_get_path('module', 'agroexpert') . '/images/header_image.jpg';
        if (arg(1) != '') {
            $category_title = '<a href="/' . AGROEXPERT_URL . '">' . t('Agro Expert') . '</a>';
        }

        $vars['header']['image'] = $image;
        $vars['header']['category_title'] = $category_title;
        $vars['header']['print'] = false;
    }

    if (drupal_get_path_alias($_GET['q']) == AGROEXPERT_URL . '/form') {
      $vars['header']['image'] = '/' . drupal_get_path('module', 'agroexpert') . '/images/header_image.jpg';
      $vars['header']['category_title'] = '<a href="/' . AGROEXPERT_URL . '">' . t('Agro Expert') . '</a>';
      $vars['header']['print'] = false;
    }
}
