<?php

/**
 * Implements hook_init().
 */
function ext_redirect_init()
{
  $old_path = $_GET['q'];


//  $request_headers = getallheaders();
//  if ((!empty($request_headers['origin']) && $request_headers['origin'] == 'https://app.kccc.ru')
//    || (!empty($request_headers['Origin']) && $request_headers['Origin'] == 'https://app.kccc.ru')) {
//    drupal_add_http_header('Access-Control-Allow-Origin', 'https://app.kccc.ru', true);
//    drupal_add_http_header('Access-Control-Allow-Headers', 'x-csrf-token, Authorization, Origin, X-Requested-With, Accept, Content-Type', true);
//  }
  watchdog('debug', 'Запрос: <pre>@v</pre>', array('@v' => print_r( $_SERVER, TRUE)), WATCHDOG_INFO);

  if (strpos($old_path, 'services/session/token') !== false || strpos($old_path, 'drupalgap/system/connect.json') !== false) {
    $headers = [];
    $request_headers = getallheaders();
    foreach ($request_headers as $t => $v) {
      if (!in_array($t, ['Host'])) {
        $headers[] = $t . ': ' . $v;
      }
    }

    watchdog('debug', '$request_headers: <pre>@v</pre>', array('@v' => print_r( $request_headers, TRUE)), WATCHDOG_INFO);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,'https://old.kccc.ru' . $_SERVER["REQUEST_URI"]);
    if ($_SERVER["REQUEST_METHOD"] == 'POST')  {
      curl_setopt($ch, CURLOPT_POST, 1);
      $data = $_REQUEST;
      watchdog('debug', '$data: <pre>@v</pre>', array('@v' => print_r( $headers, TRUE)), WATCHDOG_INFO);
      unset($data['q']);
      curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
    }
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $response = curl_exec($ch);
    curl_close($ch);
    watchdog('debug', '$response: "<pre>@v</pre>"', array('@v' => print_r( $response, TRUE)), WATCHDOG_INFO);

    drupal_add_http_header('Access-Control-Allow-Origin', $request_headers['Origin'], true);
    drupal_add_http_header('Access-Control-Allow-Headers', 'x-csrf-token, Authorization, Origin, X-Requested-With, Accept, Content-Type', true);
    print $response;
    drupal_exit();
  }


  // todo переадресация Разделов с изменившимися адресами
  //  301 Moved Permanently
  //  Препараты, Новости, Блоги, Афиша, Представители, Контакты и тд.
  if (drupal_valid_path($old_path) || drupal_lookup_path('source', $old_path)) return;

  $new_path = '';
  switch($old_path) {
    case 'info/contacts'                              : $new_path = 'kontakty'; break;
    case 'info/representatives'                       : $new_path = 'predstaviteli'; break;
    case 'info/contact-us'                            : $new_path = 'filialy'; break;
    case 'news/events'                                : $new_path = 'novosti'; break;
    case 'agenda'                                     : $new_path = 'afisha'; break;
    case 'handbook/protection-programs'               : $new_path = 'programmy-zashchity'; break;
    case 'handbook/protection-programs/programma-zashchity-soi'             : $new_path = 'programmy-zashchity/soya'; break;
    case 'handbook/protection-programs/programma-zashchity-svyokly'         : $new_path = 'programmy-zashchity/svyokla'; break;
    case 'handbook/protection-programs/programma-zashchity-rapsa'           : $new_path = 'programmy-zashchity/raps'; break;
    case 'handbook/protection-programs/programma-zashchity-podsolnechnika'  : $new_path = 'programmy-zashchity/podsolnechnik'; break;
    case 'handbook/protection-programs/programma-zashchity-lna'             : $new_path = 'programmy-zashchity/lyon'; break;
    case 'handbook/protection-programs/programma-zashchity-kukuruzy'        : $new_path = 'programmy-zashchity/kukuruza'; break;
    case 'handbook/protection-programs/programma-zashchity-goroha'          : $new_path = 'programmy-zashchity/goroh'; break;
    case 'handbook/protection-programs/programma-zashchity-kartofelya'      : $new_path = 'programmy-zashchity/kartofel'; break;
    case 'handbook/protection-programs/programma-zashchity-zernovyh'        : $new_path = 'programmy-zashchity/zernovye'; break;
    case 'handbook'                                   : $new_path = 'spravochniki'; break;
    case 'handbook/cultures'                          : $new_path = 'spravochniki/kultury'; break;
    case 'handbook/weeds'                             : $new_path = 'spravochniki/sornye-rasteniya'; break;
    case 'handbook/diseases'                          : $new_path = 'spravochniki/bolezni'; break;
    case 'handbook/pests'                             : $new_path = 'spravochniki/vrediteli'; break;
    case 'agro-expert/online'                         : $new_path = 'eksperty'; break;
    case 'info/about'                                 : $new_path = 'o-kompanii'; break;
    case 'reviews'                                    : $new_path = 'otzyvy'; break;
    case 'complaints'                                 : $new_path = 'predlozheniya'; break;
    case 'idea'                                       : $new_path = 'ideya'; break;
    case 'info/job'                                   : $new_path = 'vakansii'; break;
    case 'catalog/agrochemicals/disinfectants'        : $new_path = 'katalog/protraviteli'; break;
    case 'catalog/agrochemicals/herbicides'           : $new_path = 'katalog/gerbicidy'; break;
    case 'catalog/agrochemicals/fungicides'           : $new_path = 'katalog/fungicidy'; break;
    case 'catalog/agrochemicals/insecticides'         : $new_path = 'katalog/insekticidy'; break;
    case 'catalog/agrochemicals/desiccants'           : $new_path = 'katalog/desikanty'; break;
    case 'catalog/agrochemicals/mineral-fertilizers'  : $new_path = 'katalog/udobreniya'; break;
    case 'catalog/agrochemicals/surfactants'          : $new_path = 'katalog/drugie'; break;
  }
  // wildcard
  if (!$new_path) {
    $path = str_replace(
      [
        'news/events',
        'blogs',
        'catalog/agrochemicals/disinfectants',
        'catalog/agrochemicals/herbicides',
        'catalog/agrochemicals/fungicides',
        'catalog/agrochemicals/insecticides',
        'catalog/agrochemicals/desiccants',
        'catalog/agrochemicals/mineral-fertilizers',
        'catalog/agrochemicals/surfactants',
      ],
      [
        'novosti',
        'blog',
        'katalog/protraviteli',
        'katalog/gerbicidy',
        'katalog/fungicidy',
        'katalog/insekticidy',
        'katalog/desikanty',
        'katalog/udobreniya',
        'katalog/drugie',
      ], $old_path);
    if (drupal_valid_path($path) || drupal_lookup_path('source', $path)) {
      $new_path = $path;
    }
  }
  if ($new_path) {
    header('Location: ' . 'https://kccc.ru/' .$new_path, true, 301);
    drupal_exit();
  }

//   если путь на сайте не существует, переадресовать на старый сайт
//   302 Moved Temporarily
//   todo kccc.ru -> old.kccc.ru
//   todo не забыть про запросы от Приложения и Расписания
//   todo в теории,всё подряд переадресовать нельзя (что-то 404, но оно и на старом 404)
  if (!drupal_valid_path($old_path)) { // Not a system URL.
    if (!drupal_lookup_path('source', $old_path))  { // Not a path alias.

      // переадресация ещё нереализованного функционала на старый сайт
      // например: Препараты в поле
      switch($old_path) {
        case 'preparaty-v-pole' : $new_path = 'before-after'; break;
        default:                  $new_path = 'https://old.kccc.ru' . $_SERVER["REQUEST_URI"];
      }

      header('Location: ' . $new_path, true, 302);
      drupal_exit();
    }
  }
}
