<?php

/**
 * Implements hook_block_info().
 */
function ext_block_block_info()
{
  return [
    'custom-block-front-banner'  => [                     // по какой-то причине, если индекс содержит _ вместо - блок виден в базовой теме, но НЕ виден в подтеме.
      'info' => t('CB | Front Banner'),
    ],
    'custom-block-front-counters' => [
      'info' => t('CB | Счётчики на главной'),
    ],
    'custom-block-new-products' => [
      'info' => t('CB | New products'),
    ],
    'custom-block-recommended' => [
      'info' => 'CB | Рекомендуемые продукты',
    ],
    'custom-block-catalog'      => [
      'info' => t('CB | Catalog'),
    ],
    'custom-block-video-about'  => [
      'info' => 'CB | Видео О компании',
    ],
    'custom-block-contacts'     => [
      'info' => t('CB | Contacts'),
    ],
    'custom-block-agro-services' => [
      'info' => 'CB | Агросервисы',
    ],
    'custom-block-information'  => [
      'info' => t('CB | Information'),
    ],
    'custom-block-video-can'    => [
      'info' => t('CB | Video Can'),
    ],
    'custom-block-app'          => [
      'info' => 'CB | Приложение',
    ],
    'custom-block-video-manufacture' => [
      'info' => 'CB | Видео Производство',
    ],
    'custom-block-counters'     => [
      'info' => 'CB | Счётчики',
    ],
    'custom-block-about'        => [
      'info' => 'CB | О компании',
    ],
    'custom-block-advantages'   => [
      'info' => 'CB | Преимущества',
    ],
    'custom-block-trade-net'    => [
      'info' => 'CB | Торговая сеть',
    ],
    'custom-block-services'     => [
      'info' => 'CB | Сервисы',
    ],
    'custom-block-reviews'      => [
      'info' => 'CB | О нас говорят',
    ],
    'custom-block-socials'      => [
      'info' => 'CB | Социальные сети',
    ],
    'custom-block-more-info'    => [
      'info' => 'CB | Дополнительная информация',
    ],
    'custom-block-history'    => [
      'info' => 'CB | История компании',
    ],
    'custom-block-features'    => [
      'info' => 'CB | Особенности производства',
    ],
    'custom-block-agro-calculator' => [
      'info' => 'CB | Агро Калькулятор',
    ],
    'custom-block-contact-us' => [
      'info' => 'CB | Связаться с нами',
    ],
    'custom-block-dumb' => [
      'info' => 'CB | Пустая заглушка для сайдборда',
    ],
    'custom-block-news' => [
      'info' => 'CB | Новости',
    ],
    'custom-block-prep-pvp' => [
      'info' => 'CB | Препарат | Опыт применения',
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function ext_block_block_view($delta = '')
{
  $block = [];

  // блоки с динамически формируемым содержимым
  if ($delta == 'custom-block-front-banner') {
    $block['content'] = theme($delta, ['slides' => ext_block_get_front_banner_slides()]);
  }

  elseif ($delta == 'custom-block-new-products') {
    if ($novelties = sec_catalog_get_new_products()) {
      $cards = [];
      foreach ($novelties as $product) {
        $cards[] = theme('card_product_v', $product);
      }
      $block['content'] = theme($delta, ['cards' => $cards, 'title' => 'Новинки']);
    } else $block['content'] = null;
  }

  elseif ($delta == 'custom-block-recommended') {
    $cards = [];
    foreach (sec_catalog_get_recommended_products() as $product) {
      $cards[] = theme('card_product_v', $product);
    }
    $block['content'] = theme($delta, ['cards' => $cards, 'title' => 'С этим препаратом покупают']);
  }

  elseif ($delta == 'custom-block-catalog') {
    $categories = sec_catalog_get_categories();
    unset($categories[406]);
    $block['content'] = theme($delta, ['categories' => $categories]);
  }

  elseif ($delta == 'custom-block-news') {
    $block['content'] = theme($delta, ['cards' => ext_block_get_front_news()]);
  }

  elseif ($delta == 'custom-block-prep-pvp') {
    $block['subject'] = null;
    $filters = sec_pvp_get_filters_default();
    // получаем контекст
    $nid = str_replace('node/', '', $_GET['q']);
    if (is_numeric($nid)) {
      $filters['preparations']['current_id'] = $nid;
      $content = sec_pvp_get_content_filtered($filters, 4);
      if ($content['output']) {
        $content = $content['output'];
      } else {
        $content = '<div class="view-empty col-xs-12">По данному препарату нет записей об опыте применения, но есть по <a href="/preparaty-v-pole">другим</a>.</div>';
      }
      $block['content'] = theme($delta, ['content' => $content]);
    }
  }

  // блоки со статичной разметкой
  elseif (strpos($delta, 'custom-block-') === 0) {
    $block['content'] = theme($delta);
  }

  // общее для программных блоков
  if (strpos($delta, 'custom-block-') === 0) {
    $block['subject'] = null;
    drupal_add_css(drupal_get_path('module', 'ext_block') . '/css/ext_block.css');
    drupal_add_js(drupal_get_path('module', 'ext_block') . '/js/ext_block.js');
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function ext_block_theme()
{
  return [
    'custom-block-front-banner'    => [
      'variables' => [],
      'template' => 'templates/block-front-banner',
    ],
    'custom-block-front-counters'    => [
      'variables' => [],
      'template' => 'templates/block-front-counters',
    ],
    'custom-block-new-products'   => [
      'variables' => [],
      'template' => 'templates/block-products-carousel',
    ],
    'custom-block-recommended'   => [
      'variables' => [],
      'template' => 'templates/block-products-carousel',
    ],
    'custom-block-catalog'        => [
      'variables' => [],
      'template' => 'templates/block-catalog',
    ],
    'custom-block-video-about'    => [
      'variables' => [],
      'template' => 'templates/block-video-about',
    ],
    'custom-block-contacts'       => [
      'variables' => [],
      'template' => 'templates/block-contacts',
    ],
    'custom-block-agro-services'   => [
      'variables' => [],
      'template' => 'templates/block-agro-services',
    ],
    'custom-block-information'    => [
      'variables' => [],
      'template' => 'templates/block-information',
    ],
    'custom-block-video-can'      => [
      'variables' => [],
      'template' => 'templates/block-video-can',
    ],
    'custom-block-app'            => [
      'variables' => [],
      'template' => 'templates/block-app',
    ],
    'custom-block-video-manufacture' => [
      'variables' => [],
      'template' => 'templates/block-video-manufacture',
    ],
    'custom-block-counters'       => [
      'variables' => [],
      'template' => 'templates/block-counters',
    ],
    'custom-block-about'          => [
      'variables' => [],
      'template' => 'templates/block-about',
    ],
    'custom-block-advantages'     => [
      'variables' => [],
      'template' => 'templates/block-advantages',
    ],
    'custom-block-trade-net'      => [
      'variables' => [],
      'template' => 'templates/block-trade-net',
    ],
    'custom-block-services'       => [
      'variables' => [],
      'template' => 'templates/block-services',
    ],
    'custom-block-reviews'        => [
      'variables' => [],
      'template' => 'templates/block-reviews',
    ],
    'custom-block-socials'        => [
      'variables' => [],
      'template' => 'templates/block-socials',
    ],
    'custom-block-more-info'      => [
      'variables' => [],
      'template' => 'templates/block-more-info',
    ],
    'custom-block-history'      => [
      'variables' => [],
      'template' => 'templates/block-history',
    ],
    'custom-block-features'      => [
      'variables' => [],
      'template' => 'templates/block-features',
    ],
    'custom-block-agro-calculator'      => [
      'variables' => [],
      'template' => 'templates/block-agro-calculator',
    ],
    'custom-block-contact-us'      => [
      'variables' => [],
      'template' => 'templates/block-contact-us',
    ],
    'custom-block-dumb'      => [
      'variables' => [],
      'template' => 'templates/block-dumb',
    ],
    'custom-block-news' => [
      'variables' => [],
      'template' => 'templates/block-news',
    ],
    'custom-block-prep-pvp' => [
      'variables' => [],
      'template' => 'templates/block-prep-pvp',
    ],
  ];
}

function ext_block_get_front_banner_slides()
{
  $banners = [];
  if ($terms = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('slider_front_banners')->vid, 0, null, true)) {
    foreach($terms as $term) {
      if (module_exists('i18n_taxonomy')) {
        $term = i18n_taxonomy_localize_terms($term);
      }
      $banners[] = [
        'title' => $term->name,
        'description' => $term->description,
        'img' => file_create_url($term->field_image["und"][0]["uri"]),
        'path' => $term->field_text["und"][0]["value"],
      ];
    }
  }

  return $banners;
}

function ext_block_get_front_news()
{
  $news = [];

  $dbr = db_select('node', 'n');
  $dbr->condition('n.type', 'article');
  $dbr->addField('n', 'nid');
  $dbr->orderBy('n.created', 'DESC');
  $dbr->range(0, 8);
  if ($nodes = $dbr->execute()->fetchCol()) {

    foreach($nodes as $nid) {
      $node_wr = entity_metadata_wrapper('node', $nid);
      $text = $node_wr->body->summary->value() ?: text_summary(strip_tags($node_wr->body->value->value()), '', 240);
      $news[] = [
        'title' => $node_wr->label(),
        'text' => $text,
        'img' => image_style_url('teaser', $node_wr->field_images[0]->value()['uri']),
        'path' => drupal_get_path_alias('node/' . $node_wr->getIdentifier()),
      ];
    }
  }

  return $news;
}
