<?

/**
 * Implements hook_menu().
 */
function ext_mobile_app_menu()
{
  // источник данных для мобильного приложения <= 2.4.1
  $items['source/qsearch'] = [
    'page callback' => 'ext_mobile_app_qsearch_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  // источник данных для мобильного приложения >= 3
  $items['source/qsearch.json'] = [
    'page callback' => 'ext_mobile_app_qsearch_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/terms.json'] = [
    'page callback' => 'ext_mobile_terms_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/dv.json'] = [
    'page callback' => 'ext_mobile_dv_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/programs.json'] = [
    'page callback' => 'ext_mobile_programs_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/front-news.json'] = [
    'page callback' => 'ext_mobile_front_news_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/front-products.json'] = [
    'page callback' => 'ext_mobile_front_products_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  $items['admin/config/mobile'] = array(
    'title' => 'Mobile application',
    'description' => 'App administration tools.',
    'position' => 'right',
    'weight' => -99,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/mobile/settings'] = array(
    'title' => 'App Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_mobile_app_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/ext_mobile_app.settings.inc',
  );

  return $items;
}

/**
 * ------------------ Каталог ------------------------------------------------------------------------------------------
 */

/**
 * Вернуть полный список препаратов для функции быстрого поиска в Приложении
 */
function ext_mobile_app_qsearch_callback($category_tid = null)
{
  // является ли запрос Предзагрузкой
  $is_preload = !empty($_GET['init']);

  $items = [];

  $query = db_select('node', 'n');
  $query->condition('n.type', ['product_agro', 'product_fert'], 'IN');
  $query->condition('n.status', 1);
  $query->addField('n', 'nid');
  $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
  $query->condition('tf.language', $GLOBALS['language']->language);
  $query->orderby('tf.title_field_value', 'ASC');

  if ($category_tid) {
    $query->innerJoin('field_data_field_pd_category', 'pc', 'n.nid = pc.entity_id');
    $query->condition('pc.field_pd_category_tid', $category_tid);
  }
  if ($result = $query->execute()->fetchAll()) {
    foreach($result as $prep) {
      $prep_arr = ext_product_product_get_info($prep->nid);
      if (in_array($prep_arr['type'], ['product_agro', 'product_fert'])) {
        $prep_item = $prep_arr['items'][$prep_arr['nid']];
        $dv = [];
        foreach ($prep_item['ingredients'] as $ingredient) {
          $dv[] = $ingredient['full'];
        }
        $photo_t_base64 = $photo_f_base64 = '';
        if ($is_preload) {
          $path_t = image_style_url('thumbnail', $prep_item['photo_uri']);
          $path_f = $prep_item['photo_uri'];
          $type = pathinfo($path_t, PATHINFO_EXTENSION);
          $data_t = file_get_contents($path_t);
          $data_f = file_get_contents($path_f);
          $photo_t_base64 = 'data:image/' . $type . ';base64,' . base64_encode($data_t);
          $photo_f_base64 = 'data:image/' . $type . ';base64,' . base64_encode($data_f);
        }
        $item = [
          'nid' => $prep_item['id'],
          'title' => $prep_item['title'] . ($prep_item['form_short'] ? ', ' . $prep_item['form_short'] : ''),
          'description' => $prep_item['description'],
          'ingredients' => implode(' + ', $dv),
          'photo' => image_style_url('thumbnail', $prep_item['photo_uri']),
          'photo_base64' => $photo_t_base64,
          'photo_full' => file_create_url($prep_item['photo_uri']),
          'photo_full_base64' => $photo_f_base64,
          'icon' => $prep_arr['icon'],    // поддержка приложения версии <= 2.4.1
           // todo для Предзагрузки можно добавить изображения сертификатов
        ];
        foreach($prep_item['categories'] as $tid => $cat) {
          if (empty($items[$tid]) && (!$category_tid || $tid == $category_tid)) {
            $items[$tid] = [
              'tid' => $tid,
              'name' => $cat['name'],
              'color' => $cat['color'],
              'items' => []
            ];
          }
          // если задана категория, список только для неё
          if (!$category_tid || $tid == $category_tid) {
            $items[$tid]['items'][] = $item;
          }
        }
      }
    }
  }

  drupal_json_output(['preparations' => $items]);
  drupal_exit();
}

/**
 * ------------------ Справочники --------------------------------------------------------------------------------------
 */

/**
 * callback function
 * источник данных о Терминах
 */
function ext_mobile_terms_source()
{
  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('terms')->vid);
  $query->fields('t', array('tid', 'name', 'description'));
  $query->innerJoin('field_data_field_name_latin', 'fnl', 'fnl.entity_id = t.tid');
  $query->addField('fnl', 'field_name_latin_value', 'subtitle');
  $query->orderBy('name');
  $terms = $query->execute()->fetchAll();

  foreach($terms as &$term) {
    $term->description = strip_tags($term->description);
  }
  drupal_json_output(['terms' => $terms]);
  drupal_exit();
}

/**
 * callback function
 * источник данных о Действующих веществах
 */
function ext_mobile_dv_source()
{
  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('active_substances')->vid);
  $query->fields('t', array('tid', 'name', 'description'));
  $query->innerJoin('field_data_field_name_latin', 'fnl', 'fnl.entity_id = t.tid');
  $query->addField('fnl', 'field_name_latin_value', 'subtitle');
  $query->innerJoin('field_data_field_textfield_1', 'ff', 'ff.entity_id = t.tid');
  $query->addField('ff', 'field_textfield_1_value', 'subtitle2');
  $query->orderBy('name');
  $terms = $query->execute()->fetchAll();

  foreach($terms as &$term) {
    $term->description = strip_tags($term->description);
  }
  drupal_json_output(['dv' => $terms]);
  drupal_exit();
}

/**
 * ------------------ Программы защиты ---------------------------------------------------------------------------------
 */

/**
 * callback function
 * источник данных по Программам защиты
 */
function ext_mobile_programs_source()
{
  $programs = [];

  $query = db_select('node', 'n');
  $query->condition('n.type', 'protection_program');
  $query->condition('n.status', 1);
  $query->addField('n', 'nid');
  $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
  $query->condition('tf.language', 'ru');
  $query->orderby('tf.title_field_value', 'ASC');

  if ($result = $query->execute()->fetchCol()) {
    foreach ($result as $nid) {
      $programs[$nid] = _reglaments_get_protection_system2(['program_id' => $nid]);
    }
  }

  drupal_json_output([
    'programs' => $programs,
    'sorted' => $result,
  ]);
  drupal_exit();
}

/**
 * ------------------ Слайдеры на главной ------------------------------------------------------------------------------
 */

function ext_mobile_front_news_source()
{
  $items = [
    [
      'path' => $GLOBALS['base_url'] . '/sites/default/files/images/tmp_front/slide_1.jpg',
      'link' => [
        'external' => true,
        'url' => 'https://kccc.ru/news/interesting-facts/pamyatka-rosselhozcentra-ob-osennem-vnesenii-glifosatov'
      ],
    ],
    ['path' => $GLOBALS['base_url'] . '/sites/default/files/images/tmp_front/slide_2.jpg', 'link' => ['url' => 'catalog']],
  ];

  sleep(2);

  drupal_json_output(['news' => [
    'items' => $items
  ]]);
  drupal_exit();
}

function ext_mobile_front_products_source()
{
  $items = [];
  foreach (variable_get('ema_ap_list', []) as $nid) {
    $product_info = ext_product_product_get_info($nid);
    $items[] = [
      'nid' => $product_info['nid'],
      'title' => $product_info['title'],
      'description' => $product_info['items'][$product_info['nid']]['description'],
      'ingredients' => $product_info['items'][$product_info['nid']]['ingredients_text'],
      'img' => $product_info['items'][$product_info['nid']]['photo_medium'],
    ];
  }

  drupal_json_output(['products' => [
    'status' => true,
    'title' => variable_get('ema_ap_title', ''),
    'intro' => variable_get('ema_ap_intro', ''),
    'items' => $items,
  ]]);
  drupal_exit();

  return ;
}

/**
 * Implementation of hook_module_implements_alter().
 */
function ext_mobile_app_module_implements_alter(&$implementations, $hook)
{
  // переносим нашу реализацию хука в конец очереди
  // необходимо по причине того, что drupalgap затирает ранее полученные данные
  if ($hook == 'services_request_postprocess_alter') {
    $group = $implementations['ext_mobile_app'];
    unset($implementations['ext_mobile_app']);
    $implementations['ext_mobile_app'] = $group;
  }
}

/**
 * Implementation of hook_services_request_postprocess_alter().
 */
function ext_mobile_app_services_request_postprocess_alter($controller, $args, &$result)
{
  // при запуске приложения и выполнении system/connect.json
  if ($controller['callback'] == '_system_resource_connect') {
    // наряду с информацией о стандартных сущностях
    // передать информацию о сущности entityform
    $result->field_info_instances['entityform'] = field_info_instances('entityform');

    // наряду с информацией о типах контента node
    // передать инфо о типах контента entityform вместе с правами
    if ($content_types = _ext_mobile_app_resource_entityform_types_list()) {
      $result->content_types_list = array_merge($result->content_types_list, $content_types);
    }
    if ($content_types_permissions = _ext_mobile_app_resource_entityform_types_user_permissions()) {
      $result->content_types_user_permissions = array_merge($result->content_types_user_permissions, $content_types_permissions);
    }
  }

  // для продукции по аналогии с модулем Commerce Services
  // упрощаем и расширяем массив отдаваемых данных
  if ($controller['callback'] == '_node_resource_retrieve' && in_array($result->type, ['product_agro', 'product_fert'])) {
    // добавить свойства для части данных
    commerce_services_decorate_entity('node', $result);

    // добавить информацию о вложенных сущностях и упростить массив
    commerce_services_expand_entities('node', $result, 3, true);

    // упростить массив с данными. This must be the last operation
    // performed as it breaks the standard field data model. An entity whose
    // fields have thus been flattened is no longer wrappable.
    commerce_services_flatten_fields('node', $result);
  }
}

/**
 * Returns a collection of entityform types from the {entityform_type} table.
 *
 * It also bundles other available information about each entityform type
 * with the return results.
 */
function _ext_mobile_app_resource_entityform_types_list($options = array())
{
  // Grab content types.
  $sql = "SELECT * FROM {entityform_type} ORDER BY label ASC";
  $content_types_result = db_query($sql);

  if ($content_types_result) {
    if ($content_types_result) {
      if ($content_types = $content_types_result->fetchAll()) {
        foreach($content_types as $i => $ct) {
          $content_types[$i]->name = $ct->label;
        }
      }
      return $content_types;
    }
  }
}

/**
 * Returns a collection of permissions from entityform types for the current user.
 */
function _ext_mobile_app_resource_entityform_types_user_permissions()
{
  $content_types = _ext_mobile_app_resource_entityform_types_list();
  $content_type_permissions = array();
  foreach ($content_types as $content_type) {
    $content_type_permissions[$content_type->type] = array(
      'create' => true,
      'delete any' => false,
      'delete own' => true,
      'edit any' => false,
      'edit own' => true,
    );
  }
  return $content_type_permissions;
}

/**
 * Implements hook_init().
 */
function ext_mobile_app_init()
{
  // для запросов от приложения (оно должно отправлять origin: https://app.kccc.ru)
  // разрешить CORS запросы
  $request_headers = getallheaders();
//  watchdog('init', 'Массив <pre>@v</pre>', array('@v' => print_r( $request_headers, TRUE)), WATCHDOG_INFO);
  if ((!empty($request_headers['origin']) && $request_headers['origin'] == 'https://app.kccc.ru')
      || (!empty($request_headers['Origin']) && $request_headers['Origin'] == 'https://app.kccc.ru')) {
//    watchdog('init', 'Ориджин <pre>@v</pre>', array('@v' =>  $request_headers['origin']), WATCHDOG_INFO);
    drupal_add_http_header('Access-Control-Allow-Origin', 'https://app.kccc.ru', true);
    drupal_add_http_header('Access-Control-Allow-Headers', 'x-csrf-token, Authorization, Origin, X-Requested-With, Accept, Content-Type', true);
  }
}


/**
 * If running nginx, implement getallheaders ourself.
 *
 * Code is taken from http://php.net/manual/en/function.getallheaders.php
 */
if (!function_exists('getallheaders'))
{
  function getallheaders()
  {
    foreach ($_SERVER as $name => $value) {
      if (substr($name, 0, 5) == 'HTTP_') {
        $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
      }
    }
    return $headers;
  }
}
