<?

/**
 * Implements hook_menu().
 */
function ext_mobile_app_menu()
{
  // источник данных для мобильного приложения <= 2.4.1
  $items['source/qsearch'] = [
    'page callback' => 'ext_mobile_app_qsearch_source',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  // источник данных для мобильного приложения >= 3
  $items['source/front-news.json'] = [
    'page callback' => 'ext_mobile_front_news_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/front-products.json'] = [
    'page callback' => 'ext_mobile_front_products_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  $items['source/qsearch.json'] = [
    'page callback' => 'ext_mobile_app_qsearch_source',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  $items['source/representatives.json'] = array(
    'page callback' => 'ext_mobile_app_sellers_source',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['source/terms.json'] = [
    'page callback' => 'ext_mobile_terms_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/dv.json'] = [
    'page callback' => 'ext_mobile_dv_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/programs.json'] = [
    'page callback' => 'ext_mobile_programs_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  $items['source/pvp.json'] = array(
    'page callback' => 'ext_mobile_app_pvp_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['source/preloader/images'] = array(
    'page callback' => 'ext_mobile_app_preloader_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['admin/config/mobile'] = array(
    'title' => 'Mobile application',
    'description' => 'App administration tools.',
    'position' => 'right',
    'weight' => -99,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/mobile/settings'] = array(
    'title' => 'App Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_mobile_app_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/ext_mobile_app.settings.inc',
  );

  return $items;
}

/**
 * ------------------ Каталог ------------------------------------------------------------------------------------------
 */

/**
 * Вернуть полный список препаратов для функции быстрого поиска в Приложении
 */
function ext_mobile_app_qsearch_source($category_tid = null)
{
  // является ли запрос Предзагрузкой
  $is_preload = !empty($_GET['init']);

  $items = [];

  $query = db_select('node', 'n');
  $query->condition('n.type', ['product_agro', 'product_fert'], 'IN');
  $query->condition('n.status', 1);
  $query->addField('n', 'nid');
  $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
  $query->condition('tf.language', $GLOBALS['language']->language);
  $query->orderby('tf.title_field_value', 'ASC');

  if ($category_tid) {
    $query->innerJoin('field_data_field_pd_category', 'pc', 'n.nid = pc.entity_id');
    $query->condition('pc.field_pd_category_tid', $category_tid);
  }
  if ($result = $query->execute()->fetchAll()) {
    foreach($result as $prep) {
      $prep_arr = ext_product_product_get_info($prep->nid);
      if (in_array($prep_arr['type'], ['product_agro', 'product_fert'])) {
        $prep_item = $prep_arr['items'][$prep_arr['nid']];
        $dv = [];
        foreach ($prep_item['ingredients'] as $ingredient) {
          $dv[] = $ingredient['full'];
        }
        $item = [
          'nid' => $prep_item['id'],
          'title' => $prep_item['title'] . ($prep_item['form_short'] ? ', ' . $prep_item['form_short'] : ''),
          'description' => $prep_item['description'],
          'ingredients' => implode(' + ', $dv),
          'photo' => image_style_url('medium', $prep_item['photo_uri']),
          'photo_full' => file_create_url($prep_item['photo_uri']),
          'certs' => $prep_item['certs'],
          'icon' => $prep_arr['icon'],    // поддержка приложения версии <= 2.4.1
           // todo для Предзагрузки можно добавить изображения сертификатов
        ];
        foreach($prep_item['categories'] as $tid => $cat) {
          if (empty($items[$tid]) && (!$category_tid || $tid == $category_tid)) {
            $items[$tid] = [
              'tid' => $tid,
              'name' => $cat['name'],
              'color' => $cat['color'],
              'items' => []
            ];
          }
          // если задана категория, список только для неё
          if (!$category_tid || $tid == $category_tid) {
            $items[$tid]['items'][] = $item;
          }
        }
      }
    }
  }

  drupal_json_output(['preparations' => $items]);
  drupal_exit();
}


/**
 * ------------------ Справочники --------------------------------------------------------------------------------------
 */

/**
 * callback function
 * источник данных о Терминах
 */
function ext_mobile_terms_source()
{
  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('terms')->vid);
  $query->fields('t', array('tid', 'name', 'description'));
  $query->innerJoin('field_data_field_name_latin', 'fnl', 'fnl.entity_id = t.tid');
  $query->addField('fnl', 'field_name_latin_value', 'subtitle');
  $query->orderBy('name');
  $terms = $query->execute()->fetchAll();

  foreach($terms as &$term) {
    $term->description = strip_tags($term->description);
  }
  drupal_json_output(['terms' => $terms]);
  drupal_exit();
}

/**
 * callback function
 * источник данных о Действующих веществах
 */
function ext_mobile_dv_source()
{
  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('active_substances')->vid);
  $query->fields('t', array('tid', 'name', 'description'));
  $query->innerJoin('field_data_field_name_latin', 'fnl', 'fnl.entity_id = t.tid');
  $query->addField('fnl', 'field_name_latin_value', 'subtitle');
  $query->innerJoin('field_data_field_textfield_1', 'ff', 'ff.entity_id = t.tid');
  $query->addField('ff', 'field_textfield_1_value', 'subtitle2');
  $query->orderBy('name');
  $terms = $query->execute()->fetchAll();

  foreach($terms as &$term) {
    $term->description = strip_tags($term->description);
  }
  drupal_json_output(['dv' => $terms]);
  drupal_exit();
}

/**
 * ------------------ Программы защиты ---------------------------------------------------------------------------------
 */

/**
 * callback function
 * источник данных по Программам защиты
 */
function ext_mobile_programs_source()
{
  $programs = [];

  $query = db_select('node', 'n');
  $query->condition('n.type', 'protection_program');
  $query->condition('n.status', 1);
  $query->addField('n', 'nid');
  $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
  $query->condition('tf.language', 'ru');
  $query->orderby('tf.title_field_value', 'ASC');

  if ($result = $query->execute()->fetchCol()) {
    foreach ($result as $nid) {
      $programs[$nid] = _reglaments_get_protection_system2(['program_id' => $nid]);
    }
  }

  drupal_json_output([
    'programs' => $programs,
    'sorted' => $result,
  ]);
  drupal_exit();
}

/**
 * ------------------ Слайдеры на главной ------------------------------------------------------------------------------
 */

function ext_mobile_front_news_source()
{
  $items = [];
  if ($banners = variable_get('ema_front_banners', [])) {
    foreach($banners as $fid => $banner) {
      $file = file_load($fid);
      $file_full = $banner['bann_full_fid'] ? file_load($banner['bann_full_fid']) : null;

      $items[] = [
        'image' => file_create_url($file->uri),
        'image_full' => $file_full ? file_create_url($file_full->uri) : '',
        'type' => $banner['type'],
        'link' => [
          'external' => $banner['type'] == 'external',
          'url' => $banner['url']
        ],
      ];
    }
  }

  drupal_json_output(['news' => [
    'items' => $items
  ]]);
  drupal_exit();
}

function ext_mobile_front_products_source()
{
  $items = [];
  foreach (variable_get('ema_ap_list', []) as $nid) {
    $product_info = ext_product_product_get_info($nid);
    $items[] = [
      'nid' => $product_info['nid'],
      'title' => $product_info['title'],
      'description' => $product_info['items'][$product_info['nid']]['description'],
      'ingredients' => $product_info['items'][$product_info['nid']]['ingredients_text'],
      'img' => $product_info['items'][$product_info['nid']]['photo_medium'],
    ];
  }

  drupal_json_output(['products' => [
    'status' => true,
    'title' => variable_get('ema_ap_title', ''),
    'intro' => variable_get('ema_ap_intro', ''),
    'items' => $items,
  ]]);
  drupal_exit();

  return ;
}

/**
 * Implementation of hook_module_implements_alter().
 */
function ext_mobile_app_module_implements_alter(&$implementations, $hook)
{
  // переносим нашу реализацию хука в конец очереди
  // необходимо по причине того, что drupalgap затирает ранее полученные данные
  if ($hook == 'services_request_postprocess_alter') {
    $group = $implementations['ext_mobile_app'];
    unset($implementations['ext_mobile_app']);
    $implementations['ext_mobile_app'] = $group;
  }
}

/**
 * Implementation of hook_services_request_postprocess_alter().
 */
function ext_mobile_app_services_request_postprocess_alter($controller, $args, &$result)
{
  // при запуске приложения и выполнении system/connect.json
  if ($controller['callback'] == '_system_resource_connect') {
    // наряду с информацией о стандартных сущностях
    // передать информацию о сущности entityform
    $result->field_info_instances['entityform'] = field_info_instances('entityform');

    // наряду с информацией о типах контента node
    // передать инфо о типах контента entityform вместе с правами
    if ($content_types = _ext_mobile_app_resource_entityform_types_list()) {
      $result->content_types_list = array_merge($result->content_types_list, $content_types);
    }
    if ($content_types_permissions = _ext_mobile_app_resource_entityform_types_user_permissions()) {
      $result->content_types_user_permissions = array_merge($result->content_types_user_permissions, $content_types_permissions);
    }
  }

  // для продукции по аналогии с модулем Commerce Services
  // упрощаем и расширяем массив отдаваемых данных
  if ($controller['callback'] == '_node_resource_retrieve' && in_array($result->type, ['product_agro', 'product_fert'])) {
    // добавить свойства для части данных
    commerce_services_decorate_entity('node', $result);

    // добавить информацию о вложенных сущностях и упростить массив
    ext_mobile_app_expand_some_entities('node', $result, 3, true);

    // упростить массив с данными. This must be the last operation
    // performed as it breaks the standard field data model. An entity whose
    // fields have thus been flattened is no longer wrappable.
    commerce_services_flatten_fields('node', $result);
  }
}

/**
 * на базе commerce_services_expand_entities,
 * для уменьшения отдаваемого трафика удалить поле body для вложенных уровней
 *
 * Expands entity reference field values into full entities in a corresponding
 * property on the given entity to a specified depth of child entities.
 *
 * @param $entity_type
 *   The machine-name entity type of the given entity.
 * @param $entity
 *   The entity whose reference field values should be expanded.
 * @param $depth
 *   The depth to which referenced entities should be expanded; a depth of 1
 *   means only the reference field values on the entity passed to the function
 *   should be expanded, 2 means those and the entities they reference, etc.
 * @param $flatten_fields
 *   Boolean indicating whether or not field value arrays should be flattened.
 */
function ext_mobile_app_expand_some_entities($entity_type, $entity, $depth, $flatten_fields)
{
  // Extract the bundle name.
  list(, , $bundle) = entity_extract_ids($entity_type, $entity);

  // Look for each type of Commerce reference field on the given entity.
  foreach (array('entityreference', 'field_collection', 'commerce_product_reference', 'commerce_line_item_reference', 'commerce_customer_profile_reference', 'taxonomy_term_reference') as $field_type) {
    // Look for reference field instances of each type on the entity.
    foreach (field_info_instances($entity_type, $bundle) as $field_name => $instance) {
      $entities_field_name = $field_name . '_entities';
      $field_info = field_info_field($field_name);

      if ($field_info['type'] == $field_type) {
        // Extract the type of referenced entity from the property info.
        $property_info = entity_get_property_info($entity_type);

        if (!empty($property_info['bundles'][$bundle]['properties'][$field_name]['type'])) {
          $referenced_entity_type = $property_info['bundles'][$bundle]['properties'][$field_name]['type'];
          $entity_wrapper = entity_metadata_wrapper($entity_type, $entity);


          // If the field is multi-value, extract the entity type from within
          // the list markup and expand the whole list.
          if (substr($referenced_entity_type, 0, 5) == 'list<') {
            $referenced_entity_type = substr($referenced_entity_type, 5, strlen($referenced_entity_type) - 6);

            foreach ($entity_wrapper->{$field_name} as $delta => $referenced_entity_wrapper) {
              // Extract the entity from the wrapper.
              $referenced_entity_id = $referenced_entity_wrapper->raw();

              // трафикоёмкий body удаляем
              if (isset($referenced_entity_wrapper->value()->body['ru'])) {
                $referenced_entity_wrapper->value()->body['ru'] = [];
              }
              if (isset($referenced_entity_wrapper->value()->body['und'])) {
                $referenced_entity_wrapper->value()->body['und'] = [];
              }

              if (!empty($referenced_entity_id) && $referenced_entity_wrapper->value()) {
                $referenced_entity = clone($referenced_entity_wrapper->value());

                // Decorate the entity.
                commerce_services_decorate_entity($referenced_entity_type, $referenced_entity);

                // If our entity traversal depth has not reduced to 1, then we
                // need to recurse to expand any entity reference fields present
                // on the referenced entity.
                if ($depth > 1) {
                  ext_mobile_app_expand_some_entities($referenced_entity_type, $referenced_entity, $depth - 1, $flatten_fields);
                }

                // Flatten field value arrays on the referenced entity if directed.
                if ($flatten_fields) {
                  commerce_services_flatten_fields($referenced_entity_type, $referenced_entity);
                }

                // And finally set the referenced entity to be the new value at
                // the current delta in the reference field value array.
                $entity->{$entities_field_name}[$referenced_entity_id] = $referenced_entity;
              }
            }
          }
          else {
            // Extract the entity and its ID from the wrapper.
            $referenced_entity_id = $entity_wrapper->{$field_name}->raw();

            if (!empty($referenced_entity_id) && $entity_wrapper->{$field_name}->value()) {
              $referenced_entity = clone($entity_wrapper->{$field_name}->value());

              // трафикоёмкий body удаляем
              $referenced_entity->body = [];

              // Decorate the entity.
              commerce_services_decorate_entity($referenced_entity_type, $referenced_entity);

              // If our entity traversal depth has not reduced to 1, then we
              // need to recurse to expand any entity reference fields present
              // on the referenced entity.
              if ($depth > 1) {
                ext_mobile_app_expand_some_entities($referenced_entity_type, $referenced_entity, $depth - 1, $flatten_fields);
              }

              // Flatten field value arrays on the referenced entity if directed.
              if ($flatten_fields) {
                commerce_services_flatten_fields($referenced_entity_type, $referenced_entity);
              }

              // And finally set the referenced entity to be the new value at the
              // current delta in the reference field value array.
              $entity->{$entities_field_name}[$referenced_entity_id] = $referenced_entity;
            }
          }
        }
      }
    }
  }
}


/**
 * Returns a collection of entityform types from the {entityform_type} table.
 *
 * It also bundles other available information about each entityform type
 * with the return results.
 */
function _ext_mobile_app_resource_entityform_types_list($options = [])
{
  // Grab content types.
  $sql = "SELECT * FROM {entityform_type} ORDER BY label ASC";
  $content_types_result = db_query($sql);

  if ($content_types_result) {
    if ($content_types_result) {
      if ($content_types = $content_types_result->fetchAll()) {
        foreach($content_types as $i => $ct) {
          $content_types[$i]->name = $ct->label;
        }
      }
      return $content_types;
    }
  }
}

/**
 * Returns a collection of permissions from entityform types for the current user.
 */
function _ext_mobile_app_resource_entityform_types_user_permissions()
{
  $content_types = _ext_mobile_app_resource_entityform_types_list();
  $content_type_permissions = array();
  foreach ($content_types as $content_type) {
    $content_type_permissions[$content_type->type] = array(
      'create' => true,
      'delete any' => false,
      'delete own' => true,
      'edit any' => false,
      'edit own' => true,
    );
  }
  return $content_type_permissions;
}

/**
 * Implements hook_init().
 */
function ext_mobile_app_init()
{
  // нужно настроить nginx на отправку Access-Control-Allow-Origin 'https://app.kccc.ru'
  // так как nginx может отправлять изображения и некоторые json без обращения к серверу,
  // то настраиваем удаление существующего Access-Control-Allow-Origin (отправленного отсюда для запросов переданных серверу)
  // и добавляем снова
  //  location / {
  //    proxy_hide_header Access-Control-Allow-Origin;
  //    add_header Access-Control-Allow-Origin "https://app.kccc.ru";
  //  }
  // для изображений добавляем отдельно
  // ...

  // для запросов от приложения (оно должно отправлять origin: https://app.kccc.ru)
  // разрешить CORS запросы
  $request_headers = getallheaders();
  if ((!empty($request_headers['origin']) && $request_headers['origin'] == 'https://app.kccc.ru')
      || (!empty($request_headers['Origin']) && $request_headers['Origin'] == 'https://app.kccc.ru')) {
    drupal_add_http_header('Access-Control-Allow-Origin', 'https://app.kccc.ru', true);
    drupal_add_http_header('Access-Control-Allow-Headers', 'x-csrf-token, Authorization, Origin, X-Requested-With, Accept, Content-Type', true);
  }
}


/**
 * If running nginx, implement getallheaders ourself.
 *
 * Code is taken from http://php.net/manual/en/function.getallheaders.php
 */
if (!function_exists('getallheaders'))
{
  function getallheaders()
  {
    foreach ($_SERVER as $name => $value) {
      if (substr($name, 0, 5) == 'HTTP_') {
        $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
      }
    }
    return $headers;
  }
}

/**
 * callback function
 * источник данных о представителях
 */
function ext_mobile_app_sellers_source($region_id = null)
{
  $sellers = representatives_get_sellers_by_office($region_id);

  drupal_json_output(['sellers' => $sellers]);
  drupal_exit();
}

/**
 * callback function
 * источник данных о сезонах для Мобильного приложения
 */
function ext_mobile_app_pvp_source()
{
  // все записи ПвП
  $atf_ids = before_after_get_atfield_ids();
  $seasons_all = before_after_get_atfield_list($atf_ids);

  // наполнение для фильтров, чтобы фильтровать по месту
  // плюс сортировка (в МП проблематично)
  $filters = [
    'regions' => [],
    'cultures' => [],
    'dv' => ['list' => [], 'sorted' => []],
    'years' => []
  ];
  foreach ($seasons_all as &$season) {
    $filters['regions']['list'][$season['region']['tid']] = $season['region'];
    $filters['regions']['sorted'][$season['region']['tid']] = $season['region']['name'];
    $filters['cultures']['list'][$season['culture']['nid']] = $season['culture'];
    $filters['cultures']['sorted'][$season['culture']['nid']] = $season['culture']['title'];
    $filters['dv']['list'] = $filters['dv']['list'] + $season['dv'];
    $filters['years'][$season['year']] = $season['year'];
  }
  asort($filters['regions']['sorted']);
  $filters['regions']['sorted'] = array_keys($filters['regions']['sorted']);

  asort($filters['cultures']['sorted']);
  $filters['cultures']['sorted'] = array_keys($filters['cultures']['sorted']);

  foreach ($filters['dv']['list'] as $tid => $value) {
    $filters['dv']['sorted'][$tid] = $value['name'];
  }
  asort($filters['dv']['sorted']);
  $filters['dv']['sorted'] = array_keys($filters['dv']['sorted']);

  asort($filters['years']);

  $result = [
    'seasons' => $seasons_all,
    'filters' => $filters,
  ];

  drupal_json_output(['pvp' => $result]);
  drupal_exit();
}

function ext_mobile_app_preloader_source()
{
  // получаем запрос
  $image_urls = json_decode(file_get_contents('php://input'), true);

  // запрошенные изображения переводим в base64
  $images_base64 = [];
  foreach ($image_urls as $url) {
    $base64 = chibs_image_style_base64('', $url);
    if (strlen($base64) > 100) {
      $images_base64[] = ['u' => $url, 'b' => $base64];
    }
  }

  // отправляем ответ
  $size = strlen(drupal_json_encode($images_base64));
  header("Content-length: $size");
  drupal_json_output($images_base64);
  drupal_exit();
}
