<?

/**
 * Implements hook_menu().
 */
function ext_mobile_app_menu()
{
  $items['source/qsearch'] = [
    'page callback' => 'ext_mobile_app_qsearch_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/terms'] = [
    'page callback' => 'ext_mobile_terms_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];
  $items['source/dv'] = [
    'page callback' => 'ext_mobile_dv_source',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ext_mobile_app_ctools_plugin_api($owner, $api)
{
  if ($owner == 'services' && $api == 'services') {
    return [
      'version' => 3,
      'file' => 'ext_mobile_app.services.inc'
    ];
  }
}

/**
 * Вернуть полный список препаратов для функции быстрого поиска в Приложении
 */
function ext_mobile_app_qsearch_callback($category_tid = null)
{
  $items = [];

  $query = db_select('node', 'n');
  $query->condition('n.type', ['product_agro', 'product_fert'], 'IN');
  $query->condition('n.status', 1);
  $query->addField('n', 'nid');
  $query->leftJoin('field_data_title_field', 'tf', 'n.nid = tf.entity_id');
  $query->condition('tf.language', $GLOBALS['language']->language);
  $query->orderby('tf.title_field_value', 'ASC');

  if ($category_tid) {
    $query->innerJoin('field_data_field_pd_category', 'pc', 'n.nid = pc.entity_id');
    $query->condition('pc.field_pd_category_tid', $category_tid);
  }
  if ($result = $query->execute()->fetchAll()) {
    foreach($result as $prep) {
      $prep_arr = ext_product_product_get_info($prep->nid);
      if (in_array($prep_arr['type'], ['product_agro', 'product_fert'])) {
        $prep_item = $prep_arr['items'][$prep_arr['nid']];
        $dv = [];
        foreach ($prep_item['ingredients'] as $ingredient) {
          $dv[] = $ingredient['full'];
        }
        $item = [
          'nid' => $prep_item['id'],
          'title' => $prep_item['title'] . ($prep_item['form_short'] ? ', ' . $prep_item['form_short'] : ''),
          'description' => $prep_item['description'],
          'ingredients' => implode(' + ', $dv),
          'photo' => image_style_url('mobile_teaser_product', $prep_item['photo_uri']),
          'icon' => $prep_arr['icon'],
        ];
        foreach($prep_item['categories'] as $tid => $cat) {
          if (empty($items[$tid]) && (!$category_tid || $tid == $category_tid)) {
            $items[$tid] = [
              'tid' => $tid,
              'name' => $cat['name'],
              'color' => $cat['color'],
              'items' => []
            ];
          }
          // если задана категория, список только для неё
          if (!$category_tid || $tid == $category_tid) {
            $items[$tid]['items'][] = $item;
          }
        }
      }
    }
  }

  drupal_json_output(['preparations' => $items]);
  drupal_exit();
}


/**
 * callback function
 * источник данных о Терминах
 */
function ext_mobile_terms_source()
{
  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('terms')->vid);
  $query->fields('t', array('tid', 'name', 'description'));
  $query->innerJoin('field_data_field_name_latin', 'fnl', 'fnl.entity_id = t.tid');
  $query->addField('fnl', 'field_name_latin_value', 'subtitle');
  $query->orderBy('name');
  $terms = $query->execute()->fetchAll();

  foreach($terms as &$term) {
    $term->description = strip_tags($term->description);
  }
  drupal_json_output(['terms' => $terms]);
  drupal_exit();
}

/**
 * callback function
 * источник данных о Действующих веществах
 */
function ext_mobile_dv_source()
{
  $query = db_select('taxonomy_term_data', 't');
  $query->condition('t.vid', taxonomy_vocabulary_machine_name_load('active_substances')->vid);
  $query->fields('t', array('tid', 'name', 'description'));
  $query->innerJoin('field_data_field_name_latin', 'fnl', 'fnl.entity_id = t.tid');
  $query->addField('fnl', 'field_name_latin_value', 'subtitle');
  $query->innerJoin('field_data_field_textfield_1', 'ff', 'ff.entity_id = t.tid');
  $query->addField('ff', 'field_textfield_1_value', 'subtitle2');
  $query->orderBy('name');
  $terms = $query->execute()->fetchAll();

  foreach($terms as &$term) {
    $term->description = strip_tags($term->description);
  }
  drupal_json_output(['dv' => $terms]);
  drupal_exit();
}
