<?php

// константы терминов в словаре Подписки пользователей
foreach(_ext_message_get_vars() as $index => $var) {
    define($var['const'], 'ext_message_var_' . $index);
}

function _ext_message_get_vars()
{
    return [
        0 => ['const' => 'EM_ADD_AGENDA',   'title' => 'Добавление мероприятия'],
        1 => ['const' => 'EM_ADD_NEWS',     'title' => 'Добавление новости'],
    ];
}

/**
 * Implements hook_views_api().
 */
function ext_message_views_api($module = NULL, $api = NULL)
{
    return array("api" => "3.0");
}

/**
 * Implements hook_entity_info_alter().
 *
 * Add a the notification view modes.
 */
function ext_message_entity_info_alter(&$entity_info)
{
    $entity_info['message']['view modes']['notification'] = array(
        'label' => t('Notification'),
        'custom settings' => TRUE,
    );
}

/**
 * Implements hook_entity_insert().
 *
 *  универсальный метод создания сообщений
 *  проверяет наличие типа сообщения для создаваемой сущности
 */
function ext_message_entity_insert($entity, $type)
{
    $info = entity_get_info($type);

    // для Препаратов создан один Тип сообщений
    $entity_bundle = $entity->{$info['entity keys']['bundle']};
    if (in_array($entity_bundle, ['product_agro', 'product_chem', 'product_fert'])) $entity_bundle = 'product';

    // если тип Сообщения существует
    if (isset($entity->{$info['entity keys']['bundle']})) {
        $message_type_name = $type . '__' . $entity_bundle . '__create';
        if ($message_type = message_type_load($message_type_name)) {

            $uid = empty($entity->uid) ? 0 : $entity->uid;
            $status = empty($entity->status) ? 1 : $entity->status;

            // для новостей Уведомления только для материалов из раздела События
            if ($message_type_name == 'node__news__create') {
                $entity_wr = entity_metadata_wrapper('node', $entity);
                if ($entity_wr->field_news_category->target_id->value() != 5) {
                    return;
                }
            }

            // создать Сообщение
            $message = message_create($message_type_name, ['uid' => $uid]);
            $wrapper = entity_metadata_wrapper('message', $message);
            $wrapper->field_entity_ref->set($entity);
            $wrapper->field_published->set($status);

            if (module_exists('message_subscribe')) {
                // If Message-subscribe exists, let this example module use it.
                // извлечь термин словаря Подписки, чтобы определить кто подписан на Уведомления этого типа
                $subscription_tid = ext_message_get_message_type_subscription_tid($message_type_name);
                message_subscribe_send_message($type, $entity, $message, array('email_with_realname' => []), [], ['taxonomy_term' => [$subscription_tid]]);
            }
        }
    }
}


/**
 * Implements hook_node_update().
 */
function ext_message_node_update($node)
{
    ext_message_update_message_status('node', $node);
}

/**
 * Update the "published" field in the message entity, when it changes in the
 * related entity.
 *
 * @param $entity_type
 *   The entity type (node or comment).
 * @param $entity
 *   The entity object.
 */
function ext_message_update_message_status($entity_type, $entity)
{
    if (in_array($entity_type, ['node'])) {
        if ($entity->status == $entity->original->status) {
            // status didn't change.
            return;
        }
        list($id) = entity_extract_ids($entity_type, $entity);
        $field_name = 'field_entity_ref';

        $query = new EntityFieldQuery();
        $result = $query
            ->entityCondition('entity_type', 'message')
            ->fieldCondition($field_name, 'target_id', $id, '=')
            ->execute();

        if (empty($result['message'])) {
            return;
        }

        foreach (array_keys($result['message']) as $mid) {
            $wrapper = entity_metadata_wrapper('message', $mid);
            // If comment status changed, we still need to check the node as-well.
            $status = $entity->status;
            if ($wrapper->field_published->value() != $status) {
                // Status changed, so update the message entity.
                $wrapper->field_published->set($status);
                $wrapper->save();
            }
        }
    }
}


/**
 * Implements hook_ctools_plugin_directory().
 */
function ext_message_ctools_plugin_directory($module, $plugin)
{
    if ($module == 'message_notify') {
        return 'plugins/' . $plugin;
    }
}

/**
 * Implements hook_flag_default_flags().
 */
function ext_message_flag_default_flags()
{
    $flags = array();

    // Exported flag: "Подписки пользователей".
    $flags['subscribe_subscribes'] = array(
        'entity_type' => 'taxonomy_term',
        'title' => 'Подписки пользователей',
        'global' => 0,
        'types' => array(
            0 => 'subscribes',
        ),
        'flag_short' => t('Subscribe'),
        'flag_long' => '',
        'flag_message' => '',
        'unflag_short' => t('Unsubscribe'),
        'unflag_long' => '',
        'unflag_message' => '',
        'unflag_denied_text' => '',
        'link_type' => 'toggle',
        'weight' => 0,
        'show_in_links' => array(
            'full' => 0,
            'term_teaser' => 0,
            'token' => 0,
        ),
        'show_as_field' => 0,
        'show_on_form' => 0,
        'access_author' => '',
        'show_contextual_link' => 0,
        'api_version' => 3,
        'status' => TRUE,
        'module' => 'ext_message',
    );

    return $flags;
}

/**
 * Вернуть tid подписки на указанный тип события
 * @param $type
 * @return mixed
 */
function ext_message_get_message_type_subscription_tid($type)
{
    $query = db_select('taxonomy_term_data', 't');
    $query->innerJoin('field_data_field_message_type_ref', 'mtr', 't.tid = mtr.entity_id');
    $query->innerJoin('message_type', 'mt', 'mtr.field_message_type_ref_target_id = mt.id');
    $query->condition('mt.name', $type);
    $query->addField('t', 'tid');
    return $query->execute()->fetchField();
}

/**
 * Implements hook_preprocess_page().
 */
function ext_message_preprocess_page(&$vars)
{
    drupal_add_css(drupal_get_path('module', 'ext_message') . '/css/messages.css');
}

/**
 * Implements hook_preprocess_messag().
 */
function ext_message_preprocess_message(&$vars)
{
    /**
     * ----- возможность создания отдельных шаблонов для разных view mode
     *  ----- http://xandeadx.ru/blog/drupal/576 -----
     */
    $message_type_suggestion_key = array_search('message', $vars['theme_hook_suggestions']);
    if ($message_type_suggestion_key !== FALSE) {
        $message_view_mode_suggestion = 'message__' . $vars['view_mode'];
        array_splice($vars['theme_hook_suggestions'], $message_type_suggestion_key + 1, 0, array($message_view_mode_suggestion));

        $message_class = 'message-' . $vars['view_mode'];
        $vars['classes_array'][] = $message_class;
    }

    if (isset($vars['message']->view) && $vars['message']->view->name == 'user_notifications') {
        $row_index = $vars['message']->view->row_index;
        $vars['is_message_got'] = empty($vars['message']->view->result[$row_index]->timestamp) ? false : true;
    }
}

/**
 * получить id Типов сообщений, на которые подписан пользователь
 *
 * @param $uid
 * @return array
 */
function ext_message_get_user_subscription_notification_ids($uid)
{
    $subscripted_notification_ids = [];

    // получаем список Флагов, относящихся к модулю Подписок на Сообщения (message_notify)
    $fids = array();
    $flags = message_subscribe_flag_get_flags('taxonomy_term');
    foreach ($flags as $flag) {
        $fids[$flag->fid] = $flag->name;
    }

    // получаем tids Подписок пользователя
    $query = db_select('flagging', 'fc');
    $query->condition('entity_type', 'taxonomy_term');
    $query->condition('fid', array_keys($fids), 'IN');
    $query->condition('fc.uid', $uid);
    $query->addField('fc', 'entity_id');

    // получаем Типы сообщений, на которые подписан пользователь
    if ($subscription_tids = $query->execute()->fetchCol()) {
        $query = db_select('field_data_field_message_type_ref', 'mtr');
        $query->condition('mtr.entity_id', $subscription_tids, 'IN');
        $query->addField('mtr', 'field_message_type_ref_target_id');
        $subscripted_notification_ids = $query->execute()->fetchCol();
    }

    return $subscripted_notification_ids;
}

/** -------------------------------- Токены для уведомлений --------------------------------------------------------- */
/**
 * Implements hook_tokens().
 */
function ext_message_tokens($type, $tokens, array $data = array(), array $options = array())
{
    $replacements = array();

    // Only handling message
    if (!in_array($type, array('message'))) {
        return;
    }

    $entity_wr = entity_metadata_wrapper($type, $data['message']);
    foreach ($tokens as $name => $original) {

        switch($name) {
            case 'field_entity_ref:item_id':
                $eid = $entity_wr->value()->field_entity_ref['und'][0]['target_id'];
                $replacements[$original] = $eid;
                break;

            case 'field_entity_ref:field_f_s_culture:title':
                $eid = $entity_wr->value()->field_entity_ref['und'][0]['target_id'];
                $entity_ref = entity_metadata_wrapper('field_collection_item', $eid);

                $replacements[$original] = $entity_ref->field_f_s_culture->title->value();
                break;
        }
    }

    return $replacements;
}


/** -------------------------------- Создание уведомлений на Custom события ----------------------------------------- */

/**
 * Уведомления при создании и обновлении Препаратов в поле
 * @param $data[op] - create, update
 * @param $data[sid] - season ID
 */
function ext_message_before_after_measurement_save_alter($data)
{
    // загружаем сезон, нужен для привязки
    // todo и разрешения Токенов в письме (через custom токены или Field Collections Tokens)
    $season = field_collection_item_load($data['sid']);

    $type = 'custom__before_after__' . $data['op'];
    if ($message_type = message_type_load($type)) {

        // создать Сообщение
        $message = message_create('custom__before_after__create', ['uid' => $GLOBALS['user']->uid]);
        $wrapper = entity_metadata_wrapper('message', $message);
        $wrapper->field_entity_ref->set($season);
        $wrapper->field_published->set(1);

        if (module_exists('message_subscribe')) {
            // If Message-subscribe exists, let this example module use it.
            // извлечь термин словаря Подписки, чтобы определить кто подписан на Уведомления этого типа
            $subscription_tid = ext_message_get_message_type_subscription_tid($type);
            message_subscribe_send_message('message', $message, $message, array('email_with_realname' => []), [], ['taxonomy_term' => [$subscription_tid]]);
        }
    }
}