<?php

/**
 *  Implementation of hook_menu()
 */
function ext_message_menu()
{
    // отписаться от всех писем
    $items['unsubscribe'] = array(
        'title' => t('Unsubscribe'),
        'page callback' => 'ext_message_unsubscribe_callback',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_views_api().
 */
function ext_message_views_api($module = NULL, $api = NULL)
{
    return array("api" => "3.0");
}

/**
 * Implements hook_entity_info_alter().
 *
 * Add a the notification view modes.
 */
function ext_message_entity_info_alter(&$entity_info)
{
    $entity_info['message']['view modes']['notification'] = array(
        'label' => t('Notification'),
        'custom settings' => TRUE,
    );
}

/**
 * Implements hook_entity_insert().
 *
 *  универсальный метод создания сообщений
 *  проверяет наличие типа сообщения для создаваемой сущности
 */
function ext_message_entity_insert($entity, $type)
{
    $info = entity_get_info($type);

    // если тип Сообщения существует
    if (isset($entity->{$info['entity keys']['bundle']})) {
        // для Препаратов создан один Тип сообщений
        $entity_bundle = $entity->{$info['entity keys']['bundle']};
        if (in_array($entity_bundle, ['product_agro', 'product_chem', 'product_fert'])) $entity_bundle = 'product';

        $message_type_name = $type . '__' . $entity_bundle . '__create';
        if ($message_type = message_type_load($message_type_name)) {

            $uid = empty($entity->uid) ? 0 : $entity->uid;
            $status = empty($entity->status) ? 1 : $entity->status;

            // для новостей Уведомления только для материалов из раздела События
            if ($message_type_name == 'node__news__create') {
                $entity_wr = entity_metadata_wrapper('node', $entity);
                if ($entity_wr->field_news_category->tid->value() != 5) {
                    return;
                }
            }

            // создать Сообщение
            $message = message_create($message_type_name, ['uid' => $uid]);
            $wrapper = entity_metadata_wrapper('message', $message);
            $wrapper->field_entity_ref->set($entity);
            $wrapper->field_published->set($status);

            if (module_exists('message_subscribe')) {
                // If Message-subscribe exists, let this example module use it.
                // извлечь термин словаря Подписки, чтобы определить далее определить, кто подписан на Уведомления привязанные к термину
                $subscription_tid = ext_message_get_message_type_subscription_tid($message_type_name);
                message_subscribe_send_message($type, $entity, $message, array('email_with_realname' => []), [], ['taxonomy_term' => [$subscription_tid]]);
            }
        }
    }
}


/**
 * hook_message_subscribe_get_subscribers_alter()
 *
 * проверить наличие установленного флага подписки на email (subscribe_subscribes_email) Уведомления
 * второй флаг subscribe_subscribes - это подписка на сайте, его не учитываем при отправке письма
 * так как message_subscribe_send_message принимает только сущность, на которую нужно проверять подписку
 */
function ext_message_message_subscribe_get_subscribers_alter(&$uids, $values)
{
    if ($uids) {
        foreach ($uids as $uid => $item) {
            if (!in_array('subscribe_subscribes_email', array_values($item['flags']))) {
                unset($uids[$uid]);
            }
        }
    }
}

/**
 * Implements hook_node_update().
 */
function ext_message_node_update($node)
{
    ext_message_update_message_status('node', $node);
}

/**
 * Update the "published" field in the message entity, when it changes in the
 * related entity.
 *
 * @param $entity_type
 *   The entity type (node or comment).
 * @param $entity
 *   The entity object.
 */
function ext_message_update_message_status($entity_type, $entity)
{
    if (in_array($entity_type, ['node'])) {
        if ($entity->status == $entity->original->status) {
            // status didn't change.
            return;
        }
        list($id) = entity_extract_ids($entity_type, $entity);
        $field_name = 'field_entity_ref';

        $query = new EntityFieldQuery();
        $result = $query
            ->entityCondition('entity_type', 'message')
            ->fieldCondition($field_name, 'target_id', $id, '=')
            ->execute();

        if (empty($result['message'])) {
            return;
        }

        foreach (array_keys($result['message']) as $mid) {
            $wrapper = entity_metadata_wrapper('message', $mid);
            // If comment status changed, we still need to check the node as-well.
            $status = $entity->status;
            if ($wrapper->field_published->value() != $status) {
                // Status changed, so update the message entity.
                $wrapper->field_published->set($status);
                $wrapper->save();
            }
        }
    }
}


/**
 * Implements hook_ctools_plugin_directory().
 */
function ext_message_ctools_plugin_directory($module, $plugin)
{
    if ($module == 'message_notify') {
        return 'plugins/' . $plugin;
    }
}

/**
 * Implements hook_flag_default_flags().
 */
function ext_message_flag_default_flags()
{
    $flags = array();

    // Exported flag: "Подписки пользователей".
    $flags['subscribe_subscribes'] = array(
        'entity_type' => 'taxonomy_term',
        'title' => 'Подписки пользователей',
        'global' => 0,
        'types' => array(
            0 => 'subscribes',
        ),
        'flag_short' => t('Subscribe'),
        'flag_long' => '',
        'flag_message' => '',
        'unflag_short' => t('Unsubscribe'),
        'unflag_long' => '',
        'unflag_message' => '',
        'unflag_denied_text' => '',
        'link_type' => 'toggle',
        'weight' => 0,
        'show_in_links' => array(
            'full' => 0,
            'term_teaser' => 0,
            'token' => 0,
        ),
        'show_as_field' => 0,
        'show_on_form' => 0,
        'access_author' => '',
        'show_contextual_link' => 0,
        'api_version' => 3,
        'status' => TRUE,
        'module' => 'ext_message',
    );

    return $flags;
}

/**
 * Вернуть tid подписки на указанный тип события
 * @param $type
 * @return mixed
 */
function ext_message_get_message_type_subscription_tid($type)
{
    $query = db_select('taxonomy_term_data', 't');
    $query->innerJoin('field_data_field_message_type_ref', 'mtr', 't.tid = mtr.entity_id');
    $query->innerJoin('message_type', 'mt', 'mtr.field_message_type_ref_target_id = mt.id');
    $query->condition('mt.name', $type);
    $query->addField('t', 'tid');
    return $query->execute()->fetchField();
}

/**
 * Implements hook_preprocess_page().
 */
function ext_message_preprocess_page(&$vars)
{
    drupal_add_css(drupal_get_path('module', 'ext_message') . '/css/messages.css');

    // отключить заголовок на странице
    if (arg(0) == 'unsubscribe') {
        $vars['header']['title_off'] = true;
        $vars['header']['image'] = $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'ext_message') . '/images/header_image.jpg';
    }
}

/**
 * Implements hook_preprocess_messag().
 */
function ext_message_preprocess_message(&$vars)
{
    /**
     * ----- возможность создания отдельных шаблонов для разных view mode
     *  ----- http://xandeadx.ru/blog/drupal/576 -----
     */
    $message_type_suggestion_key = array_search('message', $vars['theme_hook_suggestions']);
    if ($message_type_suggestion_key !== FALSE) {
        $message_view_mode_suggestion = 'message__' . $vars['view_mode'];
        array_splice($vars['theme_hook_suggestions'], $message_type_suggestion_key + 1, 0, array($message_view_mode_suggestion));

        $message_class = 'message-' . $vars['view_mode'];
        $vars['classes_array'][] = $message_class;
    }

    if (isset($vars['message']->view) && $vars['message']->view->name == 'user_notifications') {
        $row_index = $vars['message']->view->row_index;
        $vars['is_message_got'] = empty($vars['message']->view->result[$row_index]->timestamp) ? false : true;
    }
}

/**
 * получить id Типов сообщений, на которые подписан пользователь
 *
 * @param $uid
 * @return array
 */
function ext_message_get_user_subscription_notification_ids($uid)
{
    $subscripted_notification_ids = [];

    // получаем Типы сообщений, на которые подписан пользователь
    if ($uid && $subscription_tids = ext_message_get_user_subscriptions($uid)) {
        $query = db_select('field_data_field_message_type_ref', 'mtr');
        $query->condition('mtr.entity_id', $subscription_tids, 'IN');
        $query->addField('mtr', 'field_message_type_ref_target_id');
        $subscripted_notification_ids = $query->execute()->fetchCol();
    }

    return $subscripted_notification_ids;
}

/**
 * Определить tids подписок пользователя на Уведомления
 * @param $uid
 * @return mixed
 */
function ext_message_get_user_subscriptions($uid)
{
    $subscription_tids = [];
    if ($uid) {

        // получаем список Флагов, относящихся к модулю Подписок на Сообщения (message_notify)
        $fids = array();
        $flags = message_subscribe_flag_get_flags('taxonomy_term', 'subscribes');
        foreach ($flags as $flag) {
            $fids[$flag->fid] = $flag->name;
        }

        // получаем tids Подписок пользователя
        $query = db_select('flagging', 'fc');
        $query->condition('entity_type', 'taxonomy_term');
        $query->condition('fid', array_keys($fids), 'IN');
        $query->condition('fc.uid', $uid);
        $query->addField('fc', 'entity_id');

        // получаем термины словаря Подписки, на которые подписан пользователь
        if ($result = $query->execute()) {
            $subscription_tids = $result->fetchCol();
        }
    }

    return $subscription_tids;
}

/**
 * Отписка пользователя от всех Уведомлений
 * @param $uid
 */
function ext_message_unsubscribe_all($uid)
{
    if ($account = user_load($uid)) {
        // найти все подписки пользователя
        if ($subscription_tids = ext_message_get_user_subscriptions($uid)) {
            // отключить все
            foreach($subscription_tids as $stid) {
                flag('unflag', 'subscribe_subscribes_email', $stid, $account);
            }
        }
    }
}


/** -------------------------------- Токены для уведомлений --------------------------------------------------------- */
/**
 * Implements hook_tokens().
 */
function ext_message_tokens($type, $tokens, array $data = array(), array $options = array())
{
    $replacements = array();

    // Only handling message
    if (!in_array($type, array('message'))) {
        return;
    }

    $entity_wr = entity_metadata_wrapper($type, $data['message']);
    foreach ($tokens as $name => $original) {

        switch($name) {
            case 'field_entity_ref:item_id':
                $eid = $entity_wr->value()->field_entity_ref['und'][0]['target_id'];
                $replacements[$original] = $eid;
                break;

            case 'field_entity_ref:field_f_s_culture:title':
                $eid = $entity_wr->value()->field_entity_ref['und'][0]['target_id'];
                $entity_ref = entity_metadata_wrapper('field_collection_item', $eid);

                $replacements[$original] = $entity_ref->field_f_s_culture->title->value();
                break;
        }
    }

    return $replacements;
}


/** -------------------------------- Создание уведомлений на Custom события ----------------------------------------- */

/**
 * Уведомления при создании и обновлении Препаратов в поле
 * @param $data[op] - create, update
 * @param $data[sid] - season ID
 */
function ext_message_before_after_measurement_save_alter($data)
{
    // загружаем сезон, нужен для привязки
    $season = field_collection_item_load($data['sid']);

    $type = 'custom__before_after__' . $data['op'];
    if ($message_type = message_type_load($type)) {

        // создать Сообщение
        $message = message_create('custom__before_after__create', ['uid' => $GLOBALS['user']->uid]);
        $wrapper = entity_metadata_wrapper('message', $message);
        $wrapper->field_entity_ref->set($season);
        $wrapper->field_published->set(1);

        if (module_exists('message_subscribe')) {
            // If Message-subscribe exists, let this example module use it.
            // извлечь термин словаря Подписки, чтобы определить кто подписан на Уведомления этого типа
            $subscription_tid = ext_message_get_message_type_subscription_tid($type);
            message_subscribe_send_message('message', $message, $message, array('email_with_realname' => []), [], ['taxonomy_term' => [$subscription_tid]]);
        }
    }
}

/**
 * --------------------------------- Добавить в письмо Отписку ---------------------------------------------------------
 *
 * Implement hook_mail_alter().
 */
function ext_message_mail_alter(&$message)
{
    if ($message['module'] == 'message_notify') {
        if (!empty($message['to']) && $message['to']->mail && $uid = $message['to']->uid) {
            $mail = $message['to']->mail;

            // добавить подпись об отписке
            $message['params']['context']['auto'] = t('You got this mail, because you subscribed to notifications.<br />You can !set_up or !unsubscribe.',
                [
                    '!set_up' => l(t('set up subscriptions'), "person/$uid/subscriptions", ['absolute' => true]),
                    '!unsubscribe' => l(t('unsubscribe all'), "unsubscribe", ['absolute' => true, 'query' => ['mail' => $mail]])
                ]
            );
        }
    }
}



/**
 * --------------------------------- Форма полной отписки от Уведомлений -----------------------------------------------
 *
 * menu callback
 */
function ext_message_unsubscribe_callback()
{
    $mail = empty($_GET['mail']) ? '' : $_GET['mail'];
    if ($mail && $user = user_load_by_mail($mail)) {
        $form = drupal_get_form('ext_message_unsubscribe_form', $user->uid);
        return drupal_render($form);
    } else {
        drupal_goto('<front>');
    }
}

/**
 * форма подтверждения отписки
 */
function ext_message_unsubscribe_form($form, $form_state, $uid)
{
    $form['#attributes'] = ['class' => ['unsubscribe-form']];
    $form['uid'] = ['#type' => 'hidden', '#value' => $uid];
    $form['text'] = ['#markup' => '<h3 class="text-center">' . t('You going to unsubscribe from our E-Mails') . '</h3>'];
    $form['actions'] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['text-center']]
    ];
    $form['actions']['unsubscribe'] = [
        '#type' => 'submit',
        '#value' => t('Unsubscribe'),
        '#attributes' => ['class' => ['btn-primary', 'btn-wide']]
    ];
    $form['actions']['setup'] = ['#markup' => '<div class="setup-link">' . l(t('Set up subscribes'), "/person/$uid/subscriptions") . '</div>'];

    return $form;
}

function ext_message_unsubscribe_form_submit($form, &$form_state)
{
    ext_message_unsubscribe_all($form_state['values']['uid']);

    $form_state['redirect'] = '<front>';
}

/**
 * --------------------------------- Всех подписать и отправить письма -------------------------------------------------
 * --------------------------------- единоразово -------------------------------------------------
 */
function ext_message_spam_subscribe()
{
    // список всех пользователей
    $query = db_select('users', 'u');
    $query->condition('mail', '', '<>');
    $query->fields('u', ['uid', 'mail']);

    // получаем термины словаря Подписки, на которые подписан пользователь
    if ($users = $query->execute()->fetchAll()) {

        // подписать пользователя на все подписки
        foreach ($users as $user) {
            ext_message_subscribe_all($user->uid);

            // отправить письмо (через очередь)
            $params['subject'] = 'Обновление функционала на сайте kccc.ru';
            $params['body'] = '<p>На нашем сайте <a href="https://kccc.ru">kccc.ru</a> появилась возможность получать уведомления о публикации новых материалов в разделах <a href="https://kccc.ru/catalog/agrochemicals">Препараты</a>, <a href="https://kccc.ru/agenda">Афиша</a>, <a href="https://kccc.ru/info/job">Вакансии</a>, <a href="https://kccc.ru/reviews">Отзывы</a>, <a href="https://kccc.ru/blogs">Блоги</a>, <a href="https://kccc.ru/news/events">Новости</a>, <a href="https://kccc.ru/survey">Опросы</a> и <a href="https://kccc.ru/before-after">Препараты в поле</a>.</p>' .
                '<p>Уведомления будут приходить в <a href="https://kccc.ru/person/' . $user->uid . '/notifications">Личный кабинет</a> и на электронную почту.</p>' .
                '<p>Мы подписали Вас на все уведомления, но если Вам интересны только часть из них, настройки можно найти в Личном кабинете в разделе <a href="https://kccc.ru/person/' . $user->uid . '/subscriptions">Подписки</a>.</p>';

            $queue = DrupalQueue::get('manual_mails_queue');
            $params['mail'] = $user->mail;

            $params['account'] = $user;
            $queue->createItem($params);
        }
    }
}

/**
 * Подписать пользователя на все Уведомления
 */
function ext_message_subscribe_all($uid)
{
    if ($account = user_load($uid)) {
        // пройтись по всем подпискам
        if ($subscription_terms = taxonomy_get_tree(taxonomy_vocabulary_machine_name_load('subscribes')->vid)) {
            foreach($subscription_terms as $sterm) {
                flag('flag', 'subscribe_subscribes', $sterm->tid, $account);
                flag('flag', 'subscribe_subscribes_email', $sterm->tid, $account);
            }
        }
    }
}