<?php

function sec_experts_menu()
{
  $items['eksperty'] = array(
    'title' => 'Agronomic service',
    'description' => t('Agronomic service contacts'),
    'page callback' => 'sec_experts_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Pre-processes variables for the "page" theme hook.
 */
function sec_experts_preprocess_page(&$vars)
{
  if (arg(0) == 'eksperty') {
    $vars['banner_title'] = t('Contacts');
    $vars['is_title_on'] = false;
  }
}

// главная страница
function sec_experts_page()
{
  $content = '';

  // список Представителей
  if ($experts = sec_experts_get_experts()) {

    $content .= '<div class="row">';

    foreach ($experts as $expert) {
      $expert['active'] = true;
      $content .= '<div class="col-xs-12 col-md-6">';
      $content .=   theme('card_contact', $expert);
      $content .= '</div>';
    }
    $content .= '</div>';

  } else {
    $content .= 'Контактов не найдено.';
  }

  return  '<div id="experts" class="company-experts view">' .
            '<div class="experts-content">' .
              $content .
            '</div>' .
          '</div>';
}

/**
 * Вернуть id пользователей с должностью эксперта
 *
 * @return array|false
 */
function sec_experts_get_experts_ids()
{
  $dbr = db_select('profile', 'p');
  $dbr->innerJoin('field_data_field_staff_office', 'fso', 'fso.entity_id = p.pid');
  $dbr->condition('fso.field_staff_office_tid', [OFFICE_SALES_EXPERT, OFFICE_SALES_SPECIALIST], 'IN');
  $dbr->innerJoin('users', 'u', 'u.uid = p.uid');
  $dbr->condition('u.status', 1);
  $dbr->addField('p', 'uid');
  $users = $dbr->execute()->fetchCol();

  return $users ?? false;
}

/**
 * Вернуть список пользователей с должностью эксперта
 *
 * @return array
 */
function sec_experts_get_experts()
{
  $experts = [];
  if ($experts_ids = sec_experts_get_experts_ids()) {
    $sorted = [];
    foreach ($experts_ids as $eid) {
      $expert = ext_user_get_user_info($eid);
      $key = ($expert['staff']['office']['weight'] ?? 1) * 1000000 + $eid;
      $sorted[$key] = $expert;
    }
    ksort($sorted);

    foreach ($sorted as $expert) {
      $experts[$expert['id']] = $expert;
    }
  }

  return $experts;
}



