<?

define('ROOM1', 73063);
define('ROOM2', 73064);
define('ROOM3', 73067);
define('ROOM4', 73065);
define('ROOM5', 73066);
define('ROOM6', 73068);

// время в минутах до начала и после начала
// в течение которых выводить События в серую зону
define('TIME_TO_FOOTER', 15);

/**
 * Implements hook_menu().
 */
function shedule_menu()
{
    $items['shedule'] = array(
        'page callback' => 'shedule_page',
        'page arguments' => array(1),
        'access callback' => true,
//        'access callback' => '_user_has_role',
//        'access arguments' => array('6'),       // только для роли Сотрудник
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_theme().
 */
function shedule_theme()
{
    return array(
        'shedule_page' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-page',
        ),
        'shedule_block_1' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-1',
        ),
        'shedule_block_2' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-2',
        ),
        'shedule_block_3' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-3',
        ),
        'shedule_block_4' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-4',
        ),
        'shedule_block_5' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-5',
        ),
        'shedule_block_6' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-6',
        ),
    );
}

/**
 * menu callback
 */
function shedule_page($ajax)
{
    if ($ajax == 'ajax') {

        $content = [
            'admin' => _user_has_role(6),
        ];

        // допустимые значения для поля Этаж
        $field_floor_allowed_values = list_allowed_values(field_info_field('field_floor'));

        // выбрать все текущие или идущие события на сегодняшний день
        if ($rooms = taxonomy_get_tree(47, 0 ,null, true)) {
            foreach ($rooms as $room) {
                $content[$room->tid] = [
                    'title' => $room->name,
                    'floor' => $room->field_floor['und'][0]['value'],
                    'floor_text' => trim($field_floor_allowed_values[$room->field_floor['und'][0]['value']]),
                ];
            }
        }

        // выбрать все текущие или идущие события на сегодняшний день
        if ($events = shedule_get_events_by_date(time(), false)) {
            foreach ($events as $eid => $event) {
                $room_id = $event->field_room_tid;
                if (!isset($content[$room_id]['events']) || count($content[$room_id]['events']) < 3) {
                    $content[$room_id]['events'][$eid] = [
                        'title' => $event->title,
                        'description' => $event->body_value,
                        'start' => date('H:i', $event->field_period_value),
                        'started' => (time() > $event->field_period_value) ? ' started' : '',
                    ];
                }

                // события, до начала которых или с начала которых 15 минут в нижний блок
                $now = time();
    //            if (($event->field_period_value - TIME_TO_FOOTER*60 < $now && $event->field_period_value > $now)
    //                || ($event->field_period_value < $now && $event->field_period_value + TIME_TO_FOOTER*60 > $now)) {
                if (($event->field_period_value - TIME_TO_FOOTER*60 < $now && $event->field_period_value + TIME_TO_FOOTER*60 > $now)) {
                    $content['footer']['events'][$eid] = [
                        'title' => $event->title,
                        'start' => date('H:i', $event->field_period_value),
                        'floor' => $content[$room_id]['floor'],
                        'started' => $content[$room_id]['events'][$eid]['started'],
                        'hurry' => $event->field_period_value - 2*60 < $now ? true : false,
                    ];

                }

            }
        }

        $result = array(
            '#type' => 'ajax',
            '#commands' => [
                ajax_command_invoke('.block-1', 'replaceWith', [theme('shedule_block_1', ['content' => $content])]),
                ajax_command_invoke('.block-2', 'replaceWith', [theme('shedule_block_2', ['content' => $content])]),
                ajax_command_invoke('.block-3', 'replaceWith', [theme('shedule_block_3', ['content' => $content])]),
                ajax_command_invoke('.block-4', 'replaceWith', [theme('shedule_block_4', ['content' => $content])]),
                ajax_command_invoke('.block-5', 'replaceWith', [theme('shedule_block_5', ['content' => $content])]),
                ajax_command_invoke('.block-6', 'replaceWith', [theme('shedule_block_6', ['content' => $content])]),
            ],
        );
        ajax_deliver($result);
        drupal_exit();
    } else {
        drupal_add_library('system', 'drupal.ajax');
        drupal_add_css(drupal_get_path('module', 'shedule') . '/css/shedule.css');
        drupal_add_js(drupal_get_path('module', 'shedule') . '/js/shedule.autorefresh.js');
        return theme('shedule_page');
    }
}

/**
 * hook_form_FORM_ID_alter
 */
function shedule_form_room_event_node_form_alter(&$form, $form_state)
{
    // дополнить названия Комнат значением Этажа
        // допустимые значения для поля Этаж
    $field_floor_allowed_values = list_allowed_values(field_info_field('field_floor'));
        // перебор опций
    foreach ($form['field_room']['und']['#options'] as $tid => $option) {
        if (is_numeric($tid)) {
            $query = db_select('field_data_field_floor', 'fr');
            $query->condition('fr.entity_id', $tid);
            $query->addField('fr', 'field_floor_value');
            if ($floor = $query->execute()->fetchField()) {
                $form['field_room']['und']['#options'][$tid] .= ', ' .  $field_floor_allowed_values[$floor];
            }
        }
    }

    $form['actions']['submit']['#submit'][] = 'shedule_form_room_event_node_form_submit';

    // подключаем к форме редактирования и создания элемента расписания виджета выбора даты-времени
    // https://xdan.ru/samij-udobnij-datetimepicker.html
    // версия js из статьи выдавала ошибку,
    // поэтому взят файл из https://github.com/xdan/datetimepicker/issues/471
    $form['#attached']['css'][] = drupal_get_path('module', 'shedule') . '/css/jquery.datetimepicker.css';
    $form['#attached']['js'][] = drupal_get_path('module', 'shedule') . '/js/jquery.datetimepicker.js';
    $form['#attached']['js'][] = drupal_get_path('module', 'shedule') . '/js/shedule.forms.js';
}

/**
 * submit callback
 */
function shedule_form_room_event_node_form_submit($form, &$form_state)
{
    $form_state['redirect'] = '/shedule';
}

/**
 * вернуть события от заданной даты до конца дня
 * @param $date - дата unix
 * @param bool $all - все или за исключением прошедших
 * @return array
 */
function shedule_get_events_by_date($date, $all = true)
{
    $query = db_select('node', 'n');
    $query->condition('n.type', 'room_event');
    $query->condition('n.status', 1);
    $query->leftJoin('field_data_field_period', 'fp', 'fp.entity_id = n.nid');
    $query->condition('fp.field_period_value2', $date, '>');
    $query->condition('fp.field_period_value', strtotime('tomorrow 1am'), '<'); //
    $query->leftJoin('field_data_body', 'fb', 'fb.entity_id = n.nid');
    $query->leftJoin('field_data_field_room', 'fr', 'fr.entity_id = n.nid');
    $query->fields('n', ['nid', 'title']);
    $query->fields('fp', ['field_period_value', 'field_period_value2']);
    $query->fields('fb', ['body_value']);
    $query->fields('fr', ['field_room_tid']);
    $query->orderBy('field_period_value');
    return $query->execute()->fetchAllAssoc('nid');
}

/**
 * Implements hook_preprocess_page().
 */
function shedule_preprocess_page(&$vars)
{
    // сменить шаблон страницы на пустой,
    // чтобы иметь возможность развернуться на весь экран
    if (arg(0) == 'shedule' && !arg(1)) {
        $vars['theme_hook_suggestions'][] = 'page__empty';
    }
}