<?

define('ROOM1', 73063);
define('ROOM2', 73064);
define('ROOM3', 73067);
define('ROOM4', 73065);
define('ROOM5', 73066);
define('ROOM6', 73068);

// время в минутах до начала и после начала
// в течение которых выводить События в серую зону
define('TIME_TO_FOOTER', 15);

function shedule_init()
{
  if (!$_GET['q']) drupal_init_path();

  // отключаем кеширование определенных страниц
  // и разрешаем доступ только с корп ip
  if (arg(0) == 'shedule') {
    $GLOBALS['conf']['cache'] = 0;
    if (!in_array($GLOBALS["user"]->hostname, ['127.0.0.1', '77.72.142.170'])) {
      watchdog('ip block', 'IP <pre>@v</pre>', array('@v' => $GLOBALS["user"]->hostname), WATCHDOG_INFO);
      drupal_not_found();
    }
  }
}

/**
 * Implements hook_menu().
 */
function shedule_menu()
{
    $items['shedule'] = array(
        'page callback' => 'shedule_page',
        'page arguments' => array(1),
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );
    $items['shedule/room/%'] = array(
        'page callback' => 'shedule_room_page',
        'page arguments' => array(2,3),
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_theme().
 */
function shedule_theme()
{
    return array(
        'shedule_room_page' => array(
            'variables' => array('room' => NULL),
            'template' => 'templates/shedule-room-page',
        ),
        'shedule_room_content' => array(
            'variables' => array('room' => NULL),
            'template' => 'templates/shedule-room-content',
        ),

        'shedule_page' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-page',
        ),
        'shedule_block_1' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-1',
        ),
        'shedule_block_2' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-2',
        ),
        'shedule_block_3' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-3',
        ),
        'shedule_block_4' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-4',
        ),
        'shedule_block_5' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-5',
        ),
        'shedule_block_6' => array(
            'variables' => array('content' => NULL),
            'template' => 'templates/shedule-block-6',
        ),
    );
}

/**
 * menu callback
 */
function shedule_room_page($room_num, $ajax)
{
  $shedule = shedule_get_events_by_date(24 * 60);

  if (isset($shedule[constant('ROOM' . $room_num)])) {
    $room = $shedule[constant('ROOM' . $room_num)];
  }

  if ($ajax == 'ajax') {

    $result = array(
      '#type' => 'ajax',
      '#commands' => [
        ajax_command_invoke('.room-content', 'replaceWith', [theme('shedule_room_content', ['room' => $room])]),
      ],
    );
    ajax_deliver($result);
    drupal_exit();
  } else {
    return theme('shedule_room_page', ['room' => $room]);
  }
}

/**
 * menu callback
 */
function shedule_page($ajax)
{
    if ($ajax == 'ajax') {

        $content = shedule_get_events_by_date(TIME_TO_FOOTER);

        $result = array(
            '#type' => 'ajax',
            '#commands' => [
                ajax_command_invoke('.block-1', 'replaceWith', [theme('shedule_block_1', ['content' => $content])]),
                ajax_command_invoke('.block-2', 'replaceWith', [theme('shedule_block_2', ['content' => $content])]),
                ajax_command_invoke('.block-3', 'replaceWith', [theme('shedule_block_3', ['content' => $content])]),
                ajax_command_invoke('.block-4', 'replaceWith', [theme('shedule_block_4', ['content' => $content])]),
                ajax_command_invoke('.block-5', 'replaceWith', [theme('shedule_block_5', ['content' => $content])]),
                ajax_command_invoke('.block-6', 'replaceWith', [theme('shedule_block_6', ['content' => $content])]),
            ],
        );
        ajax_deliver($result);
        drupal_exit();
    } else {
        return theme('shedule_page');
    }
}

function shedule_get_events_by_date($closest_event_remain_time)
{
  $content = [
    'admin' => user_has_role(ROLE_STAFF_ADMINISTRATOR),
  ];

  // допустимые значения для поля Этаж
  $field_floor_allowed_values = list_allowed_values(field_info_field('field_floor'));

  // массив комнат
  if ($rooms = taxonomy_get_tree(47, 0 ,null, true)) {
    foreach ($rooms as $room) {
      $content[$room->tid] = [
        'title' => $room->name,
        'floor' => $room->field_floor['und'][0]['value'],
        'floor_text' => trim($field_floor_allowed_values[$room->field_floor['und'][0]['value']]),
      ];
    }
  }

  // выбрать все текущие или идущие события на сегодняшний день
  $now = time();
  if ($events = _get_events_by_date($now, false)) {
    foreach ($events as $eid => $event) {
      $room_id = $event->field_room_tid;
      if (!isset($content[$room_id]['events']) || count($content[$room_id]['events']) < 3) {
        $content[$room_id]['events'][$event->field_period_value] = [
          'eid' => $eid,
          'title' => $event->title,
          'description' => $event->body_value,
          'start_unix' => $event->field_period_value,
          'start' => date('H:i', $event->field_period_value),
          'finish_unix' => $event->field_period_value2,
          'finish' => date('H:i', $event->field_period_value2),
          'started' => ($now > $event->field_period_value) ? ' started' : '',
          'participants' => $event->field_participants,
        ];
      }
    }

    ksort($content[$room_id]['events']);
  }

  return $content;
}

/**
 * hook_form_FORM_ID_alter
 */
function shedule_form_room_event_node_form_alter(&$form, $form_state)
{
    // дополнить названия Комнат значением Этажа
        // допустимые значения для поля Этаж
    $field_floor_allowed_values = list_allowed_values(field_info_field('field_floor'));
        // перебор опций
    foreach ($form['field_room']['und']['#options'] as $tid => $option) {
        if (is_numeric($tid)) {
            $query = db_select('field_data_field_floor', 'fr');
            $query->condition('fr.entity_id', $tid);
            $query->addField('fr', 'field_floor_value');
            if ($floor = $query->execute()->fetchField()) {
                $form['field_room']['und']['#options'][$tid] .= ', ' .  $field_floor_allowed_values[$floor];
            }
        }
    }

    $form['actions']['submit']['#submit'][] = 'shedule_form_room_event_node_form_submit';

    // подключаем к форме редактирования и создания элемента расписания виджета выбора даты-времени
    // https://xdan.ru/samij-udobnij-datetimepicker.html
    // версия js из статьи выдавала ошибку,
    // поэтому взят файл из https://github.com/xdan/datetimepicker/issues/471
    $form['#attached']['css'][] = drupal_get_path('module', 'shedule') . '/css/jquery.datetimepicker.css';
    $form['#attached']['js'][] = drupal_get_path('module', 'shedule') . '/js/jquery.datetimepicker.js';
    $form['#attached']['js'][] = drupal_get_path('module', 'shedule') . '/js/shedule.forms.js';
}

/**
 * submit callback
 */
function shedule_form_room_event_node_form_submit($form, &$form_state)
{
    $form_state['redirect'] = '/shedule';
}

/**
 * вернуть события от заданной даты до конца дня
 * @param $date - дата unix
 * @param bool $all - все или за исключением прошедших
 * @return array
 */
function _get_events_by_date($date, $all = true)
{
    $query = db_select('node', 'n');
    $query->condition('n.type', 'room_event');
    $query->condition('n.status', 1);
    $query->leftJoin('field_data_field_period', 'fp', 'fp.entity_id = n.nid');
    $query->condition('fp.field_period_value2', $date, '>');
    $query->condition('fp.field_period_value', strtotime('tomorrow 1am'), '<'); //
    $query->leftJoin('field_data_body', 'fb', 'fb.entity_id = n.nid');
    $query->leftJoin('field_data_field_room', 'fr', 'fr.entity_id = n.nid');
    $query->fields('n', ['nid', 'title']);
    $query->fields('fp', ['field_period_value', 'field_period_value2']);
    $query->fields('fb', ['body_value']);
    $query->fields('fr', ['field_room_tid']);
    $query->orderBy('field_period_value');
    if ($results = $query->execute()->fetchAllAssoc('nid')) {
      foreach ($results as $eid => &$result) {
        $query = db_select('field_data_field_participants', 'fp');
        $query->condition('fp.entity_id', $result->nid);
        $query->fields('fp', ['field_participants_value']);
        $query->leftJoin('field_data_field_company', 'fc', 'fc.entity_id = fp.field_participants_value');
        $query->fields('fc', ['field_company_value']);
        $query->leftJoin('field_data_field_participants_list', 'fpl', 'fpl.entity_id = fp.field_participants_value');
        $query->fields('fpl', ['field_participants_list_value']);
        $result->field_participants = $query->execute()->fetchAllAssoc('field_participants_value');
      }
    }
    return $results;
}

/**
 * Implements hook_preprocess_page().
 */
function shedule_preprocess_page(&$vars)
{
    // сменить шаблон страницы на пустой,
    // чтобы иметь возможность развернуться на весь экран
    if (arg(0) == 'shedule') {
        $vars['theme_hook_suggestions'][] = 'page__empty';
      drupal_add_css(drupal_get_path('module', 'shedule') . '/css/shedule.css');
      drupal_add_library('system', 'drupal.ajax');
      drupal_add_js(drupal_get_path('module', 'shedule') . '/js/shedule.autorefresh.js');
    }
}

/**
 * ---------------------------------- ИМПОРТ --------------------------------------------------------------------------
 */

/**
 * Implements hook_cron()
 */
function shedule_cron()
{
  // выполнить импорт мероприятий
  shedule_process_incoming_files();
}

function shedule_process_incoming_files()
{
  $directory = 'private://exchange/';

  // получить список файлов по шаблону
  $mask = '/event_import.*\.json/';
  $files = file_scan_directory($directory, $mask, ['recurse' => false], 0);

//  watchdog('import', 'Крон запущен <pre>@v</pre>', array('@v' => print_r( $files, TRUE)), WATCHDOG_INFO);

  // импортировать
  if ($files) {
    foreach ($files as $file) {
      $c = file_get_contents($file->uri);
      $array = drupal_json_decode(file_get_contents($file->uri));
      if (shedule_event_import($array)) {
        $path = $directory . 'success/' . date('Y') . '/' . date('m') . '/' . date('d');
      } else {
        $path = $directory . 'fail/' . date('Y') . '/' . date('m') . '/' . date('d');
      }
      file_prepare_directory($path, FILE_CREATE_DIRECTORY);
      file_unmanaged_move($file->uri, $path . '/' . $file->filename);
    }
  }
}

function shedule_event_import($array)
{
  if (is_array($array) && isset($array['room_id'])) {

    $query = new EntityFieldQuery();
    $events = $query
      ->entityCondition('entity_type', 'node')
      ->propertyCondition('type', 'room_event')
      ->fieldCondition('field_id_1c', 'value', trim($array['id_1c']))
      ->execute();

    if (!$events) {
      $event = (object)array(
        'title' => $array['title'],
        'type' => 'room_event',
        'status' => 1,
      );
      node_save($event);
    } else {
      $event = current($events['node']);
    }

    $node_wr = entity_metadata_wrapper('node', $event->nid);
    $node_wr->title->set($array['title']);
    $node_wr->status->set($array['status']);
    $node_wr->body->value->set($array['description']);
    $node_wr->field_id_1c = $array['id_1c'];
    $node_wr->field_room = $array['room_id'];
    $node_wr->field_period->value->set(strtotime($array['start']));
    $node_wr->field_period->value2->set(strtotime($array['finish']));
    foreach ($node_wr->field_participants->getIterator() as $pp_wr) {
      $pp_wr->delete();
    }
    $node_wr->field_participants->set(null);
    $node_wr->save();

    foreach($array['participants'] as $item_pp) {
      $participant = entity_create('field_collection_item', array('field_name' => 'field_participants'));
      $participant->setHostEntity('node', $node_wr->value());
      $participant_wr = entity_metadata_wrapper('field_collection_item', $participant);
      $participant_wr->field_company = $item_pp['company'];
      $participant_wr->field_participants_list = implode('<br>', $item_pp['list']);
      $participant_wr->save();
    }

    drupal_set_message('Мероприятие импортировано.');
    watchdog('import', 'Мероприятие импортировано.', [], WATCHDOG_INFO);
    return true;
  } else {
    drupal_set_message('Импорт мероприятия не выполнен.', 'warning');
    watchdog('import', 'Импорт мероприятия не выполнен.', [], WATCHDOG_ERROR);
    return false;
  }
}
